### ISSUE TITLE
Question: Is .Net Core written ALL from scratch?

### ISSUE THREAD

**Issue by sherry-ummen** [dotnet/core#1055]
Hi,

Sorry if this place and question is inappropriate then please close the issue and my apologies.

But, if I am allowed to ask then could some one actually let me understand the history and the development of .Net core which I have been wondering
- Is the .Net Core written all from scratch?
- If not then are there still some legacy code? 
- How was the legacy code refactored to be made open source?
- How is the testing done for legacy code here? I see C# code is using NUnit so how about the legacy code?

**Comment by Petermarcu** [comment]
This is probably as good a place as any. I'll try to answer some of the questions but will likely close this issues pretty quickly because its not really an issue with the product.

A lot of the code is either exactly from or an evolution of .NET Framework code. I wouldn't say there is legacy code. There is code that was written a long time ago though. We did a lot of things on a case by case basis using ifdef's in the code, or refactoring into separate source files. We migrated most of our tests to XUnit for our C# code. For native code, that is just a thin wrapper that runs our native test runners. 

Is there something in particular you need or are trying to get to?

**Comment by sherry-ummen** [comment]
Thanks @Petermarcu .

I was particularly interested on the Native code
1) How do you test the native code? What framework is being used?
2) So then there must some some .Net framework code still shared with .Net core? Was it written in C++? Could you actually point me to an example .Net core code which is actually calling the Native old code?

Sorry I am just starting to learn about this whole new era of .Net and how it evolved. If you have pointers or articles to it. Then please post it here. Thanks once again.

**Comment by Petermarcu** [comment]
This repo is where most of the native code is: https://github.com/dotnet/coreclr

There is a tests folder where the tests live. Its a custom built test framework that is basically just a console application that returns various values depending on the result of test execution. That can then be wrapped in various higher level frameworks to provide reporting, etc.

Most of the code in that repo copied or evolved from the code in .NET Framework. We recompile all of the code for .NET Core. The .NET Core code doesn't call "old code". Its all .NET Core code in that repo.

**Comment by sherry-ummen** [comment]
Thank you very much. This was very helpful. I will close this issue now.
