### ISSUE TITLE
No place on dot.net to provide feedback and issues

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/core#107]
After running into an issue trying to follow the directions setting up Debian I was unsure where I could file an issue.  I had to walk down the hall and find a coworker who told me to file the issues here.  We should have somewhere on the page a link that will allow the user to file issues or provide some form of feedback on how their experience went.

**Comment by blackdwarf** [comment]
@Chrisboh there are at least several ways to provide feedback:

1. CLI repo
2. Community channel
3. Gitter CLI channel
4. ASP.NET Core repos
5. This repo

All of these are known to people who are interacting with our product. I'm not sure that providing more info would be super useful, but I will let @shanselman comment, since he owns that page.

**Comment by AlexChesser** [comment]
@blackdwarf what about two new CLI commands for feedback?

     dotnet :)        -- send positive feedback
     dotnet :(        -- send negative feedback (includes system and diagnostic profile)

The user experience could plug into whatever internal systems you've got set up for feedback around VS Code and the like (that little smiley face button)

![image](https://cloud.githubusercontent.com/assets/355561/15511526/eeb51af2-21a9-11e6-8a79-23093c6f5a3e.png)

Command line & remote shell users could send their smiles and frownies directly from the affected  system. I'm only joking here, because I think an emoticon for a command line option is funny... but the use case isn't actually *terrible*

**Comment by Chrisboh** [comment]
When you say they are known are you meaning they can go click on the community tab and maybe find the right place to ask their question?  My first instinct was to click on a support or feedback link.  I don't think it would hurt if we had an extra call out that says something like the following.

Need help?  Click here! <- and have the link take you to the specific place we want the user to go to get help.  If I look on the community tab I am not sure if I should go to the CLI github repo link or the forums.  

I like @AlexChesser idea for sending feedback.  In my case though I ran into issues getting CLI installed so I wouldn't have been able use this.

**Comment by blackdwarf** [comment]
@Chrisboh yes, and that information is available. If you are having trouble with installing the CLI tools, I would imagine you would go to the dotnet/cli gitter channel/repo to file that issue. It is a potential product issue after all. 😃 However, I have filed an issue on the respective repo to fix the community page to add the information. 

With this, will close this issue.
