### ISSUE TITLE
Problem about sockets in multi threads

### ISSUE THREAD

**Issue by eaglexiang** [dotnet/core#1105]
Below is part of my code (pseudocode):

```csharp
class Session
{
    public Socket socketB;
    public string msgB;
}

private static void Listen()
{
// *** create and bind socketA
    socketA.Listen();
    List<Session> sessions = new List<Session>();
    while(true)
    {
        Session s = new Session();
        s.socketB = socketA.Accept();

// ***s.msgB = s.socketB.Receive()**
        sessions.Add(s);
        Thread t = new Thread(HandleMsg);
        t.IsBackground = true;
        t.start(s);
    }
}

private static void HandleMsg(Session s)
{
//***more (string)msgC transfered with the s.socketB***
}
```

I found new (string)`msgC` got in thread HandleMsg would appear in (Session)s.msgB sometimes, I mean string of old socketB from socketA.Accept() will appear in new socketB. That should be impossible, is it?

Who can tell me why?

**Comment by stephentoub** [comment]
> sometimes, I mean string of old socketB from socketA.Accept() will appear in new socketB

Is there a loop you're leaving out of your example?

**Comment by eaglexiang** [comment]
@stephentoub yes I do have loop, sorry and I've fixed my code on 1F.

**Comment by stephentoub** [comment]
> I've fixed my code on 1F

And this is exactly how the code looks?  For example, the `Session s` is defined inside the loop rather than outside of it?  The behavior you describe is almost certainly not a bug in .NET, but rather a bug of some kind in your program, likely do to changing an object that ends up being shared across multiple threads.

Rather than sharing a small snippet, it'd be helpful if you could share a small but complete runnable repro that demonstrates the issue.

**Comment by richlander** [comment]
Any more thoughts / feedback @eaglexiang ?

**Comment by eaglexiang** [comment]
@richlander Thank you for reply! I'm still trying to recurrent and find true reason for that bug. Please close this issue for now. Thank you two very much!
