### ISSUE TITLE
Package name / versioning for CentOS packages

### ISSUE THREAD

**Issue by CRCinAU** [dotnet/core#1248]
The package names for RPM distributions seem to be a bit whack. As things stand, you can't do point release upgrades on the system without manual intervention - which seems to be somewhat limiting.

For example, the latest runtime package is: dotnet-runtime-2.0.5-2.0.5-1.x86_64

This breaks down to:
* package name = dotnet-runtime-2.0.5
* version = 2.0.5
* revision = 1
* arch = x86_64

This means when you release 2.0.6 for example, it will be a manual upgrade to 2.0.6 as the actual package name will be dotnet-runtime-2.0.6 with version 2.0.6

Unless there is some abuse going on with the Obsoletes / Provides tags in the .spec file used to generate the RPM, I can't see how this fits in with proper practice for packaging on *nix based systems.

Generally, the package name would be set as 'dotnet-runtime', with a *version* of 2.0.5 - or even if it is a dotnet limitation, have 'dotnet-runtime-2.0' - which can then have a version of 2.0.5, 2.0.6, 2.0.7 etc etc delivered seamlessly as a package upgrade via the distro package manager.

**Comment by crozone** [comment]
Definitely noticed this. The CentOS package name is `dotnet-host-2.0.5-1.x86_64` which corresponds to this build:

```
Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

From what I understand, different versions of dotnet can be installed simultaneously, and are automatically selected by the sdk and host when it is used to compile a project or run an executable.

AFAIK patch versions only include non-breaking security and bug fixes, so it doesn't make sense to me why the actual package name includes the patch version, since it seems to imply that every patch version will get its own separate side-by-side package. This should be entirely unnecessary since patches are meant to be non-breaking anyway, and makes updating to the latest patch version a manual process which makes deploying critical security updates difficult.

**Comment by Petermarcu** [comment]
@leecow 

I believe we have an issue tracking this somewhere and it is on the list of things @leecow was going to drive getting fixed.

**Comment by CRCinAU** [comment]
Just wanted to poke this for comment... The more we deploy this, the more difficult it will be as time goes by to shift things to whatever method is chosen in the long run....

**Comment by Petermarcu** [comment]
@leecow you said you had made some progress here on a spec. Is there a link?

**Comment by CRCinAU** [comment]
Plus, I've been packaging stuff targeting RHEL/CentOS environments for 10+ years - so happy to provide input - or even contribute - but that assumes knowing what the plan is :)

**Comment by leecow** [comment]
Ideas are coming together at https://gist.github.com/leecow/afc1cda5262a702c05978f5a149e2fdc. Will be moving to the designs repo soon. Feel free to comment @CRCinAU !

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/core-setup #3850](https://github.com/dotnet/core-setup/issues/3850) via [**ZenHub**](https://www.zenhub.com/)
