### ISSUE TITLE
Question: PDB vs. SourceMap

### ISSUE THREAD

**Issue by kasper3** [dotnet/core#1262]
https://github.com/dotnet/core/blob/c9862ad13/Documentation/diagnostics/portable_pdb.md

says:

> .NET Core introduces a new symbol file (PDB) format - portable PDBs. Unlike traditional PDBs which are Windows-only, portable PDBs can be created and read on all platforms.

Was inventing the new PDB format for cross platform necessary when there is another well defined format that all browsers (and their debuggers), many editors and debuggers of various language platforms (beyond JavaScript and CSS) support these days:

https://sourcemaps.info/spec.html

Or am I missing the point and SourceMap and PDB are not comparable (or perhaps PDB offsets SourceMap functionality-wise)? If you have knowledge, can you please explain a bit what is not possible with SourceMap compared to [portable-]PDB?

**Comment by Petermarcu** [comment]
@tmat perhaps you can give insight here?

**Comment by tmat** [comment]
SourceMap encodes similar information to PDB. Since it's just JSON format it can presumably be extended and store any additional information that managed compilers need to store in PDB beyond what's specified by https://sourcemaps.info/spec.html. We could have used SourceMap. That said, the Portable PDB format is more compact and it's based on the managed metadata format that managed compilers already produce. It's optimized for both size and speed of access to various information based on what the common needs of managed debuggers are.

You can find the specification here: https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PortablePdb-Metadata.md for comparison with SourceMap.

**Comment by kasper3** [comment]
Thanks that answers the question.
