### ISSUE TITLE
Visual Studio 15.6.3 Installs .NET Core SDK 2.1.102

### ISSUE THREAD

**Issue by arushe0805** [dotnet/core#1364]
Visual Studio 15.6.3 Installs .NET Core SDK 2.1.102

I do not see the installer or release notes for this anywhere.

Is this an official release?

**Comment by cgountanis** [comment]
I agree this is confusing. Is it safe to use the 2.1.102 version as I see nothing about it in release notes.

**Comment by nickkarpuk** [comment]
@cgountanis , I just had to uninstall this 2.1.102 version of the SDK because of the issue with deploying .NET Core 2.0 app. I found a similar problem on Stackoverflow: https://stackoverflow.com/questions/49397793/error-publishing-net-core-2-0-web-applicaiton-to-azure-app-service . And 2.1.101 seems to be working fine in this regard.

**Comment by cgountanis** [comment]
Good call, deploy would be an issue if there is no IISHosting package for us. Might as well be safe and not use the 102 for now, waiting for the review build anyway.

Thanks

**Comment by arushe0805** [comment]
I just found this.
This was made 19 hours ago:
https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.102-sdk-download.md

Still no notes.

**Comment by arushe0805** [comment]
@leecow is there any notes for this sdk patch?

**Comment by leecow** [comment]
For updates which take tooling updates for VS, we haven't be doing notes beyond the CLI repo release tag - https://github.com/dotnet/cli/releases/tag/v2.1.2 is the last example. Waiting on @livarcocc for the 2.1.102 tag so that repo release info can be published.

Let me know if the 2.1.2 example is sufficient or if notes similar to the larger updates would be helpful.

**Comment by bonsailimited** [comment]
@leecow Overall the 2.1.2 example should be sufficient - however; when these "silent releases" occur - it would be helpful to know which runtime they sit over. Having just come off the 2.0.5->2.0.6 push during the SDK 100/101 releases, with days going by with no word or indication from MS, it can be frustrating, to say the least, when servers and deployments are involved, even if only in dev environments.

**Comment by cgountanis** [comment]
Rule of thumb use global.json for SDK specification and never use/upgrade anything for at least two weeks. Unless it is a major security update, no reason to work the weekend fixing something that broke.

**Comment by leecow** [comment]
Thanks all for the feedback. We're fixing things so that everyone has sufficient information on release day to make appropriate choices for their situation.

**Comment by dasMulli** [comment]
@leecow could you/someone update releases.json for the 103 SDK? would like to update the homebrew cask accordingly.

**Comment by leecow** [comment]
@dasMulli - will do as soon as a few other tasks related to the release are complete. Hopefully this morning. 

cc @livarcocc @preetikr

**Comment by leecow** [comment]
2.1.103 release docs are published.

**Comment by Petermarcu** [comment]
I think everything in this issue is done. I'm closing. Let us know if thats not the case.
