### ISSUE TITLE
Download page broken for linux

### ISSUE THREAD

**Issue by kasper3** [dotnet/core#1379]
Tested on Firefox and Edge https://www.microsoft.com/net/learn/get-started/linux

Change the value in dropdown menu from RHEL to Ubuntu and the page content is not changing (keeps showing `yum install ..`.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/dotnet-core-website #551](https://github.com/dotnet/dotnet-core-website/issues/551) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kasper3** [comment]
@Petermarcu https://github.com/dotnet/dotnet-core-website repo is not publicly accessible (try in in-private browsing) :(

**Comment by Petermarcu** [comment]
Ok, we can leave it open here and close it when its fixed.

**Comment by kasper3** [comment]
Does changing the dropdown value to Ubuntu shows `apt-get`? I am keep seeing `yum install` both on FF and Edge on Windows 10.. something is wrong with my system.

**Comment by Petermarcu** [comment]
Yeah, I get apt-get when I switch to Ubuntu.

**Comment by kasper3** [comment]
F12 tool in firefox is showing an error in console:

>ReferenceError: initOs is not defined[Learn More]
>get-started.min.js:1:1055

**Comment by rowanmiller** [comment]
@kasper3 that info is super helpful thanks! I'll see if I can work out what is happening based on that.

**Comment by rowanmiller** [comment]
Hmmm, so it appears that an outdated version of the js has been cached for you, but this shouldn't happen, because we use a cache breaker on the file, so the URL changes whenever the contents change. Code using the initOs variable was removed from the file about a month ago.

Just to be 100% certain, could you load https://www.microsoft.com/net/bundles/js/get-started.min.js?v=UJfiUJKa4gKy09VBnU4dEw3svrcR1E5r3fMWXvR0FfM and confirm that the string `initOs` appears in the result.

**Comment by kasper3** [comment]
I can see `;$(window).on("popstate","",this,this.navHandler);this.updateNav(initOs)}n.prototype.navHandler=function(n)`.

**Comment by rowanmiller** [comment]
I forced a hash change on that file, so you should get the current version now. Can you confirm the page works? 

I'm not sure what happened here, somehow you got an old version of the file cached on the URL for the updated version

**Comment by kasper3** [comment]
Thanks @rowanmiller, it works! 🍹
