### ISSUE TITLE
Cloud native features

### ISSUE THREAD

**Issue by patelmiral81** [dotnet/core#1494]
#Missing cloud native features

I am Java developers for 15+ years. Right now I am looking at some code in .net core where microservices based design Attempted. I believe .net core and .net in general need to add features for cloud native functions - something like spring boot. Problem is with microservices we need rapid development , and we want lot of defaults (opinionated) built into frameworks so developers can continue coding on minimum business functions only.
Few examples:
Cloud connector - if I am deploying in CF, and I informed my service I need to use rabbitmq, it should able to find out service and do necessary binding.
Property reading - should be simplified for clouds when it needs to read from environments. e.g. CF VCAP..I dont want to do parsing. I want framework to take care.

Like this it needs to enhanced more to empower developers.

**Comment by Petermarcu** [comment]
@glennc where is the best place for @patelmiral81 to follow all the work we're doing for microservices?

**Comment by glennc** [comment]
@patelmiral81 Specifically for CF stuff checkout out Steeltoe (https://github.com/SteelToeOSS). It's sponsored by Pivotal with the goal of bringing all the CF stuff you are used to into .NET. They are .NET Foundation members and we've talked a bunch of times about making .NET better for them to extend in this direction.

For the env vars, we support retrieving and overriding config values from env vars by default. Do you mean support for understanding the CF VCAP JSON?

I have the charter for trying to bring more of the things that projects like Spring Boot have for Microservices to .NET Core, so I am interested in as many details and examples you want to give. glennc is my MS alias if you want to email me @ microsoft.com rather than here. But I am hapy with either.

To answer Peters actual question, the announcements repo of the aspnet org are where you will see most things related to this announced. In general this sort of work layers on-top of the work done in the dotnet org so it appears in orgs like aspnet.

**Comment by GearsAD** [comment]
+1
In .Net core automatic vcap binding would be really neat. For cloudfoundry we wrote our own and it has led to a herd of issues.

**Comment by glennc** [comment]
Looks like the Steeltoe config provider binds VCAP variables to config data: http://steeltoe.io/docs/steeltoe-configuration/#1-0-cloud-foundry-provider

That seems like the right place for it, a package built by a team closest to CF supporting the CF features like VCAP. Did you expect something more than just getting the data or was there something stopping you from using Steeltoe that we should talk about? Are they missing a type to expose the data in more than just KeyValue pairs for example?

I don't know if it's discoverability of Steeltoe that's the problem or something else.

**Comment by GearsAD** [comment]
At least for my comment, its more about discoverability. I have a todo to take a look at it, much appreciated for the reference.

**Comment by patelmiral81** [comment]
Thank you Glenn and Petermarcu. Yes steeltoe is there but I was little concern about roadmap and support of that project as I was not seeing much activities in past. But now since you (MS) are advocating it I believe its safe to use that for production applications.
Idea here was to bring awareness and I think we all agree that .net core need to bridge some gaps. Steeltoe is perfect framework to make .net core cloud native ready and for rapid app dev.

**Comment by Eilon** [comment]
Hi all, I'm closing this issue because I think answers were provided to the question. If people have additional ASP.NET Core specific questions, please log them at https://github.com/aspnet/Home. Thanks!
