### ISSUE TITLE
System.IO.Ports

### ISSUE THREAD

**Issue by WangAngIOT** [dotnet/core#1513]
I have a program is running on the .NET Compact Framework. There is no VPU driver on the WinCE System, so I need to change the operating System to an embedded Linux System (arm architecture), but there is no System.IO.Ports API in NETCore. Will you add the API in the future?

**Comment by pjanotti** [comment]
@wfurt is working on a PR to get this started (see #29033).

While that is not ready yet some people had success with https://github.com/jcurl/SerialPortStream (see [here](https://github.com/dotnet/core/issues/740#issuecomment-314506664) for example), but that may not be an option to you since it seems you already have code using the Fx API.

**Comment by WangAngIOT** [comment]
@pjanotti @wfurt Thanks. 
On the embedded Linux system, I did a simple test and ran the program successfully.
I may need to transplant my program that is running on the .NET Compact Framework to make sure it works perfectly.
