### ISSUE TITLE
Is there a way for building asp.net core project as an executable using the FDD approach

### ISSUE THREAD

**Issue by yashwanthreddyg** [dotnet/core#1540]
I would like to have the project run on both windows and nix systems. It is expected for the hosts to have runtimes already installed. I know running dotnet ABC.dll would work but I really world like to have executable output without having the coreclr and other dlls in the output (hence FDD).

**Comment by Petermarcu** [comment]
you will need different executables for Windows and for Linux. @steveharter didn't we enable this in 2.1?

**Comment by dasMulli** [comment]
@yashwanthreddyg while for linux and windows the files would differ in extension (`.exe` vs no extension), you can't really have a fully portable application that would work on all systems since the no-extension executable would need be either an ELF or MACH-O assembly for linux/mac and also match the architecture (x64, arm, arm64,..) to be able to run and boot the runtime.
