### ISSUE TITLE
Cannot install .NET Core 2.0 on CentOS 6.4

### ISSUE THREAD

**Issue by syeerzy** [dotnet/core#1603]
step 1:
`sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm `
done

step 2:
`sudo yum update`
done

step 3:
`sudo yum install libunwind libicu`
done

step 4:
`sudo yum install dotnet-sdk-2.1.200`
Error: Package: dotnet-runtime-2.0.7-2.0.7-1.x86_64 (packages-microsoft-com-prod)
           Requires: openssl-libs
Error: Package: dotnet-runtime-deps-2.1.0-rc1-2.1.0_rc1-1.x86_64 (packages-microsoft-com-prod)
           Requires: openssl-libs

step 5:
`sudo yum install openssl openssl-devel` 
Package openssl-1.0.1e-57.el6.x86_64 already installed and latest version
Package openssl-devel-1.0.1e-57.el6.x86_64 already installed and latest version
Nothing to do

 i already had openssl-devel, but It still saying that  requires "openssl-libs" .

how can i fixed this?

**Comment by leecow** [comment]
The minimum version supported by .NET Core 2.0 is CentOS 7. Couple of things to try - use the [tar.gz package](https://download.microsoft.com/download/3/7/1/37189942-C91D-46E9-907B-CF2B2DE584C7/dotnet-sdk-2.1.200-linux-x64.tar.gz) rather than the installers and if that does not run correctly, try the [2.1 tar.gz for RHEL6](https://download.microsoft.com/download/8/8/5/88544F33-836A-49A5-8B67-451C24709A8F/dotnet-sdk-2.1.300-rhel.6-x64.tar.gz).
