### ISSUE TITLE
sqlconnection is not available in .net core 2.1

### ISSUE THREAD

**Issue by DoubleCouponDay** [dotnet/core#1699]
![image](https://user-images.githubusercontent.com/7555725/41513984-78cd40ae-72e6-11e8-962f-b7f612fc0a17.png)

![image](https://user-images.githubusercontent.com/7555725/41513987-807a22b8-72e6-11e8-980f-77c56a6fcc5c.png)

It is also missing when using the `system.data.sqlclient` namespace from nuget.
why is this?

**Comment by svick** [comment]
When I add a reference to the System.Data.SqlClient package, `SqlConnection` compiles for me on both .Net Core 2.0 and 2.1. Do you have an example (including .csproj) where it doesn't?

If the issue is only in the documentation, the it should be reported at [the dotnet/docs repo](https://github.com/dotnet/docs).

**Comment by leecow** [comment]
Issue moved to [dotnet/docs #6069](https://github.com/dotnet/docs/issues/6069) via [**ZenHub**](https://www.zenhub.com/)
