### ISSUE TITLE
can not install dotnet-sdk-2.1 on centos7.2

### ISSUE THREAD

**Issue by dinjonya** [dotnet/core#1770]
on centos7.2 
sudo yum install dotnet-sdk-2.1 
install need compat-openssl10 
who can help me

**Comment by leecow** [comment]
Strange, we had not seen that issue on CentOS before. There are a couple options - 1) update the CentOS to the latest (7.4 I think) which should remove the dependency or 2) since I don't see the package on the default centos feeds, download the compat-openssl10 rpm (possibly from https://pkgs.org/download/compat-openssl10) and install.

/cc @omajid for other ideas.

**Comment by omajid** [comment]
`compat-openssl10`? That almost sounds like a Fedora package. Are you sure this is CentOS? Where did you get the package from? What does `yum info dotnet-sdk-2.1` say?

**Comment by joshfree** [comment]
Closing this old issue which needs more info.  Please feel free to reactivate with more details.  Thanks
