### ISSUE TITLE
Missing support of T4 Template in ASP NET CORE MVC project

### ISSUE THREAD

**Issue by VitaliiNikitchyn** [dotnet/core#1793]
# Missing support of T4 Template in ASP NET CORE MVC project

There is no possibility to add "Text Template" from Add -> New Item -> ...  In ASP NET CORE MVS project

Does T4 Templating supports by .NET Core ?

**Comment by leecow** [comment]
@natemcmaster / @Eilon

**Comment by Eilon** [comment]
Hi @VitaliiNikitchyn , there is no direct T4 support in runtime in ASP.NET Core MVC. If you're looking for T4 support in Visual Studio, please use the [Report a Problem](https://developercommunity.visualstudio.com/) tool in VS.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.

Thanks!

**Comment by VitaliiNikitchyn** [comment]
Thanks for your response, Eilon

One more question:
You told that "There is no direct T4 support in runtime in ASP.NET Core MVC"
Is there another way to include T4 in this kind of ptoject ?

The probleme is that I have a code generation module written in T4. The module was created as a part of .NET Framework MVC project. Now I would like to port my project from .NET Framework to .Net Core and I want to use my old T4 module in my ASP.NET Core MVC app.

**Comment by Eilon** [comment]
@VitaliiNikitchyn sorry not that I'm aware of. All I meant was that in theory someone could write support for it, but there isn't anything built-in.
