### ISSUE TITLE
PDB files not matching DLLs

### ISSUE THREAD

**Issue by JoshClose** [dotnet/core#185]
If this is the wrong repository to put this in, please let me know which I should use instead.

The pdb files that are being generated seem to not match the dlls they were built for.

I'm using this command to build.

`dotnet pack src\CsvHelper --configuration release --output NuGet`

Users are reporting this

> Using symchk, I checked the DLL and the PDB to see if they matched and I get:
SYMCHK: CsvHelper.dll FAILED - CsvHelper.pdb mismatched or not found

They are having issues checking the files into TFS. There is more information about that here. https://github.com/JoshClose/CsvHelper/issues/535

Is this something I'm doing wrong or is there a bug building the pdb files?

**Comment by akoeplinger** [comment]
Your problem is likely this: https://github.com/JoshClose/CsvHelper/blob/316f62dce451dd428eb95d4997a8f29245920d5e/src/CsvHelper/project.json#L17

This means that the PDBs will be created in the new Portable PDB format which works cross platform. It seems TFS doesn't understand this format yet.

You could try switching to `"debugType": "full"` but this only works on Windows.

**Comment by blackdwarf** [comment]
@JoshClose does @akoeplinger response solve the problem?

**Comment by JoshClose** [comment]
Yes! At least for the non-portable builds. Not sure about the portable ones, but it sounds like TFS needs to be updated for those.

**Comment by JoshClose** [comment]
What is the case with `"degutType": "portable"`? Will TFS support this soon?
