### ISSUE TITLE
OperationContractAttribute not available in netcore2.1 ?

### ISSUE THREAD

**Issue by CalvinPangch** [dotnet/core#1966]
refer to the document , the system.servicemodel.operationcontractattribute are available in dotnet core 2.0 but not 2.1. why its is dropped from 2.1 and does it had any other way to do code the same as the operationContractAttribute ?
https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.operationcontractattribute?view=netcore-2.0

**Comment by MarcoRossignoli** [comment]
I'm not sure but maybe is a doc issue...if you reference https://www.nuget.org/packages/System.ServiceModel.Primitives/ `OperationContractAttribute` is present on `netcoreapp2.1` target framework.
You could move issue to https://github.com/dotnet/wcf/issues or https://github.com/dotnet/docs/issues
Also the guide refers to it https://docs.microsoft.com/en-us/dotnet/framework/wcf/designing-service-contracts

/cc @StephenBonikowsky

**Comment by karelz** [comment]
@CalvinPangch it's a bug in docs - can you please file it via Feedback button on that page? Thanks!
cc @mairaw (I think this is a known problem)

**Comment by mairaw** [comment]
I think this is due to the fact that we added Platform extensions assemblies for earlier releases and we stopped doing that for 2.1. The ones for .NET Core will be removed and we'll add a new moniker for platform extensions until our build process is smart enough to identify different packages and their targets. 
We're working on adding the extensions now with https://github.com/dotnet/dotnet-api-docs/pull/590 and we'll have to try to remove extensions from .NET Core next. We ran into some issues last time we tried to do this.
