### ISSUE TITLE
WPF for .NET Core 3.0 has no COMPOSITEFONT files

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/core#2009]
.NET Core 3.0.100-alpha1-009689

It doesn't come with the `*.COMPOSITEFONT` files so any WPF application that tries to call Fonts.SystemFontFamilies crashes (unless they have a try/catch)

It's very similar to [this bug](https://github.com/dotnet/announcements/issues/53).

**Comment by diverdan92** [comment]
@ericstj - can you help triage?

**Comment by ericstj** [comment]
This is a WPF issue.  I think @rladuca is looking at this.

**Comment by rladuca** [comment]
@0xd4d There is a fix coming down the pipe for this soon.  We weren't getting the CompositeFont files including in the installer for the SDK.  

For now, you can copy the desktop versions from either:
- "%SYSTEMROOT%\Microsoft.NET\Framework\v4.0.30319\WPF"
- "%SYSTEMROOT%\Microsoft.NET\Framework\v4.0.30319\WPF\Fonts" 

Put them into the shared Microsoft.DesktopUI.App SDK folder that .NET Core is loading from.  The file contents themselves haven't changed so that will fix any crashes temporarily.

**Comment by rladuca** [comment]
@diverdan92 I just checked the latest installer and this fix is available.

**Comment by karelz** [comment]
Closing as solved.
