### ISSUE TITLE
Segmentation fault on Ubuntu 18.04 after a couple of hours running console application

### ISSUE THREAD

**Issue by lokisisland** [dotnet/core#2012]
I am having a problem with an application which has been running on Windows for months with no issue which I'm now running on Linux. I run the application via the command line (it is a console app) and after a couple of hours (the time varies, up to around four hours), the app dies. 

In the system logs I have the following:

`dotnet[26179]: segfault at 7f4b5ee8cc80 ip 00007f4bf55147b6 sp 00007f4b79569c60 error 4 in libcoreclr.so[7f4bf53e8000+352000]`

The application is quite complex and I have absolutely no idea where to start working out what the issue is; the application connects to SQL Server, uses HttpClient for web access and uses Quartz scheduler to orchestrate everything. 

The error does not appear to be related to any activity that it obvious (i.e. Quartz starting a new job etc.). 

My dotnet environment is as below:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
Unfortunately, I am unable to post the code for my application, although if I can narrow down where the issue is happening, I may be able to create a repro project. 

Any help would be greatly appreciated!

**Comment by karelz** [comment]
Analhyzing crash dump on Linux is similar to analyzis on Windows - except that you need to use different tools: https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md#debugging-coreclr-on-linux

Collect the dump, get the callstack (ideally from multiple segfaults), then try to guess where the problem is.

FYI: Just the fact that an app worked in one environment (WIndows) does not mean it doesn't have a bug which reproduces on other environments (Linux), although it may be less likely. Once you post the callstack (make sure you have symbols right), hopefully it will be enough to say where the problem is in your app or in .NET Core.

**Comment by lokisisland** [comment]
Thank you for the debugging advice. I have narrowed the error I'm seeing down to a hardware fault; it is happening at random times throughout the life of the program. I have confirmed this by running MemTest which has shown many memory errors. 

Thank you again!
