### ISSUE TITLE
Dapper seems incompatible with .Net core SDK 2.2

### ISSUE THREAD

**Issue by saurabhnachankar** [dotnet/core#2018]
Dapper is not able to map SQL Query columns to class properties.

`I hereby wrote the problem on dapper source code for reference :` 

[Not able to map to properties in dotnet core 2.2](https://github.com/StackExchange/Dapper/issues/1147#issue-372837414)

Dapper version : 1.50.5
.Net core SDK version : 2.2
Visual studio code version : 1.28.2

**Comment by karelz** [comment]
Let's wait for analysis on Dapper repo first - if it is a regression caused by .NET Core, we will need information which API regressed, then ideally filed in CoreFX repo.
Given that nearly nothing changed in .NET Core 2.2 against 2.1.x in lower-layers of .NET Core (most changes were in ASP.NET Core layer above), I am curious if this is indeed a regression caused by .NET Core.
