### ISSUE TITLE
Deserialize binary[] to  ISet<T> wrong Internal HashCode has been stored

### ISSUE THREAD

**Issue by gokhanabatay** [dotnet/core#2027]
[InternalHashCodeIssue.zip](https://github.com/dotnet/core/files/2527021/InternalHashCodeIssue.zip)

Hi, 
I have an issue that demonstrates above sample, I try to explain as I can.

When I serialized ISet<T> to binary[], than Deserialize to ISet<T>, before T's Dictionary property has been setted T.GetHashCode is called and stored which is returned wrong(missing) hash code. 

If I can override hash code; after Deserialize I need to have same hash code for same object in the same process.

FilterKey class GetHashCode and Equals methods is overrided for checking equality of to different instance of ISet<FilterKey>.

**Comment by karelz** [comment]
Please post the code demonstrating the problem you're hitting directly here (the ZIP file is corrupted).

Note: AFAIK hash codes are randomized intentionally to NOT be stable across processes (to avoid security issues). If you need to persist hash codes, you need to create your own mechanism.

**Comment by svick** [comment]
@karelz The attached ZIP file can't be opened in Windows Explorer, because it actually seems to be a mislabeled RAR file. I could open it fine in 7-Zip.

I think there is indeed an issue here: the deserialized `HashSet<T>` is no longer consistent, in that `set.Contains(set.Single())` returns `false`, even though `GetHashCode` and `Equals` of the contained value are implemented correctly.

As far as I can tell, this happens because on deserialization, `HashSet<T>.OnDeserialization`, which calls `GetHashCode` of the contained object, is called before the `Parameters` collection is filled. This means the `HashSet<T>` stores the incorrect hash code in its internal structure.

Here is my minimal repro, created by removing unnecessary parts from the attached code:

```c#
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;

[Serializable]
class FilterKey
{
    public Dictionary<int, int> Parameters { get; } = new Dictionary<int, int>();

    public override int GetHashCode() => Parameters.Count.GetHashCode();

    public override bool Equals(object other) =>
        other is FilterKey that && Parameters.Count == that.Parameters.Count;
}

class Program
{
    static byte[] Serialize(object obj)
    {
        using (var stream = new MemoryStream())
        {
            new BinaryFormatter().Serialize(stream, obj);
            return stream.ToArray();
        }
    }

    static object Deserialize(byte[] data)
    {
        using (var stream = new MemoryStream(data))
        {
            return new BinaryFormatter().Deserialize(stream);
        }
    }

    static void Main()
    {
        var set = new HashSet<FilterKey> { new FilterKey { Parameters = { { 1, 2 } } } };

        // correctly prints True
        Console.WriteLine(set.Contains(set.Single()));

        var deserializedSet = (HashSet<FilterKey>)Deserialize(Serialize(set));

        // this prints False, which is the issue
        Console.WriteLine(deserializedSet.Contains(deserializedSet.Single()));
    }
}
```

**Comment by gokhanabatay** [comment]
Sorry for the wrong file format, I edited the project file you can download it again.

Also @svick sample is the short(very good) story of what i really try.

**Comment by fredericDelaporte** [comment]
@gokhanabatay has initially reported this on NHibernate side (nhibernate/nhibernate-core#1888, ongoing PR nhibernate/nhibernate-core#1891), since this issue affects NHibernate second level cache. (When the kind of classes shown in @svick cleaned-up code example are used with a cache provider using binary serialization on them.)

The trouble also occurs with dictionaries (`Dictionary<TKey, TValue>`), when using as `TKey` a class like the `FIlterKey` of the above example.

On NHibernate side, we consider dodging the trouble by serializing the sets and dictionaries content as arrays, and use them instead of the sets and dictionaries for `GetHashCode` and `Equals` implementation, when the call to these methods occurs during deserialization.

**Comment by karelz** [comment]
@ViktorHofer can you please help me route it? Is it something we want to move to CoreFX and fix?

**Comment by ViktorHofer** [comment]
Thanks @svick. Took a quick look. The cause is that OnDeserialization is called before OnDeserialization is called on the Parameters Dictionary<,>. 

A more general issue description: The hash code computation of stored (n-deep) childs is wrong it the child defers its deserialization logic, i.e. with IDeserializationCallback.OnDeserialization.

For a possible solution I would need to dig deeper. For now I'll move the issue to corefx.

**Comment by ViktorHofer** [comment]
@karelz I'm not an admin here, can you please move it? Thanks.

**Comment by karelz** [comment]
Issue moved to [dotnet/corefx #33470](https://github.com/dotnet/corefx/issues/33470) via [**ZenHub**](https://www.zenhub.com/)
