### ISSUE TITLE
XAML on .net core

### ISSUE THREAD

**Issue by reader-man** [dotnet/core#208]
Hi,
Thanks a lot on the huge work done in .Net Core 1.0, and its features.

It would be great to have a XAML to rule them all (to rule the desktop of all OSs), that benefits from any GPU/CPU on that system, and to be a the defecto desktop UI development, that is more powerful than both old .Net XAML, and Xamarin XAML, and that draws its own shapes, not a layer above current UI frameworks in each platform.

**Comment by aleks-sidorenko** [comment]
It would be good to have really xplat XAML based UI for .NET Core, but Xamarin is definitely the way to go in xplat UI development for .NET.
However, all MS's UI xplat products for now are Javascript based: Visual Studio Code, Skype for Linux etc.
Maybe they don't believe in XAML?

**Comment by richlander** [comment]
There are a couple projects to look at:

- [Xamarin.Forms](https://www.xamarin.com/forms), also raised above.
- [AvaloniaUI](https://github.com/AvaloniaUI)

> Maybe they don't believe in XAML?

I don't think that this is quite right. There is no xplat Xaml UI stack for those teams to use. As one of the projects above supports both mobile and desktop, then that may change.

Closing, since the .NET Core team doesn't have any plans for a x-plat XAML UI stack. Best to look at those other projects.
