### ISSUE TITLE
Can I Porting .NET project to .NET Core and use dll dependency from .NET 4

### ISSUE THREAD

**Issue by SerhiiS-in6k** [dotnet/core#221]
Hi. I was looking for possibilities for porting small project from Windows .NET framework to Ubuntu(linux) using  .NET Core. But the project has dependency from other much bigger .NET 4 project. Can I just add reference to the .NET 4 dll dependency. Thanks.

**Comment by mellinoe** [comment]
No, that is not supported. You will need to port the dependency as well, and that will involve working around types and methods that the dependency uses that are not available in .NET Core.

**Comment by SerhiiS-in6k** [comment]
@mellinoe Thank you for your quick reply. I have analyzed dependency in .NET 4 projects. And I found that project uses native C method. Can I Do something like:
```
[DllImport(ServiceDll, CallingConvention = CallingConvention.Cdecl)]
public static extern Consumer Consumer();
```
in the .NET Core

**Comment by swgillespie** [comment]
@SerhiiS-in6k yes, platform invoking like that is supported on .NET Core.

**Comment by mellinoe** [comment]
Yep, PInvokes work fine. Keep in mind that any native dependency you have needs to be available on all of the platforms you intend to run on. If you only intend on running on Windows, there's no problem, but do keep in mind that any native code used will limit your flexibility.

**Comment by SerhiiS-in6k** [comment]
Thanks, guys. Today I tried use Pinvokes and it works fine. I also tried to use Pinvokes in Ubuntu it also works and it's very cool because my project uses a lot native call. But I can't find 'System.Security.Permissions' in NET Core
`
PermissionSetAttribute(SecurityAction.LinkDemand, Name = "FullTrust")] or 
 [EnvironmentPermission(SecurityAction.LinkDemand, Unrestricted = true)], ''
`
Do you know any packages which I Can use instead;

**Comment by mjrousos** [comment]
Those permission attributes are related to CAS, which is gone in .NET Core, so you shouldn't need them. .NET Core doesn't enforce security restrictions the way the old .NET Framework (sort of) did. Instead, if resources need to be protected, it's expected to be done at the OS level via ACLs or some similar mechanism.

So, it should be fine to just remove those attributes.

**Comment by SerhiiS-in6k** [comment]
Hi. Thanks all, your answer is very helpful for me. I almost port project to Net Core. But have some error:
1) Can I remove Clonable interface;
2) How can I replace these lines: 
```
Attribute.IsDefined(property, typeof(ServiceSerializableAttribute))
    
new JsonFormatter().Print(respObj)

ConfigurationManager.AppSettings["ServiceName"];

```
Thanks.

**Comment by mjrousos** [comment]
* Yes, the ICloneable interface can be removed - it's not used by the .NET Core Framework. If you need cloning functionality, you can still keep the methods you've implemented (or provide your own ICloneable interface if it's useful to your apps).
* ManualResetEvent.Close can be replaced with ManualResetEvent.Dispose.
* For Attribute.IsDefined, use the System.Reflection.CustomAttributeExtensions.IsDefined() extension method the in System.Reflection.Extensions contract.
* I'm not very familiar with JsonFormatter, but it's probably possible to get similar functionality with the Newtonsoft.Json package or with the DataContractSerializer type.
* Configuration has changed in .NET Core since different targets will have different underling config systems. If this is for ASP.NET, you can use the new [ASP.NET configuration system](https://docs.asp.net/en/latest/fundamentals/configuration.html).

**Comment by blackdwarf** [comment]
I believe that with the above comments all of the questions in this issue have been addressed, so I'm going to close it. If you believe it was in error, please reopen.
