### ISSUE TITLE
NuGet does not select the latest .NET Core version

### ISSUE THREAD

**Issue by martore** [dotnet/core#2259]
# NuGet does not select the latest .NET Core version

Take a look at https://stackoverflow.com/questions/54414482/what-am-i-missing-to-upgrade-asp-net-mvc-net-core-2-2-0-apps-to-net-core-2-2-1

# General
1. Uninstall all .NET Core SDKs and runtimes.
2. Install latest .NET Core SDK (2.2.103) and runtime (2.2.1.27207)
3. In VS 2019 create new .NET Core Web App project.

NuGet references `Microsoft.NETCore.App` version 2.2.0 rather than 2.2.1.

Explicitly specifying `Microsoft.NETCore.App` version to target 2.2.1 in .csproj works, however, during a build it will show a warning stating that specifying version is not recommended.

**Comment by karelz** [comment]
@nguerrera @livarcocc is it part of VS or where would you suggest to route it?

**Comment by nguerrera** [comment]
This is the expected behavior. For framework-dependent apps, you usually do not want to specify a patch version. The reason is that if you upgrade to a patch before a hoster (web app)/customer (client app) then your app will not launch on their machines. Nevertheless, framework-dependent apps will use the latest patch available automatically at runtime via roll-forward. So you get the security benefit without having to rebuild your app for every patch.

Generally speaking, just specify the TargetFramework and let the system pick the right packages.

There are a few scenarios where you need to twiddle with the defaults and they are covered in this doc: https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-patch-selection
