### ISSUE TITLE
How does inbox vs nuget System.Net.Http work?

### ISSUE THREAD

**Issue by omajid** [dotnet/core#2291]
This is an attempt to understand how `System.Net.Http` which exists both as a nuget package and as an inbox dll in .NET Core is used by (ASP).NET Core. This is *not* to understand how the network code works.

The original motivation is trying to understand how `System.Net.Http` version `4.3.0`, which is supposed to be vulnerable to CVE-2018-8292 is a false positive for (ASP).NET Core applications.

If I do a simple `dotnet new web`, it turns out .NET Core download the "vulnerable" version of `System.Net.Http`, 4.3.0.

1. I was told at https://github.com/dotnet/corefx/issues/32730 that `System.Net.Http` being version 4.3.0 in .NET Core is a false positive. I have verified locally that this is indeed the case - the `System.Net.Http.dll` from the .NET Core installation is used. How does .NET Core decide to both download `4.3.0` from nuget, but decide to use the version inbox in .NET Core?

2. Where is this version 4.3.0 defined in (ASP).NET Core? Can we bump it to 4.3.4 or something similar to remove a false positive for anything that tries to check for CVE-2018-8292.

3. Is there a list of other packages that exist on nuget.org but are also available inbox where the inbox version is always preferred?

cc @tmds @karelz

**Comment by bartonjs** [comment]
@terrajobst Do we have a simple or technical explanation anywhere of "inbox + nuget" assemblies?

**Comment by omajid** [comment]
Anyone have any pointers or answers? I can try and do a writeup for number 1, but I dont know about 2 and 3 at all.

**Comment by leecow** [comment]
Adding a few folks to try and tease out some information - @danmosemsft @davidsh @rmkerr @mconnew

**Comment by davidsh** [comment]
>I have verified locally that this is indeed the case - the `System.Net.Http.dll` from the .NET Core installation is used. How does .NET Core decide to both download `4.3.0` from nuget, but decide to use the version inbox in .NET Core?

@ericstj @joperezr Can you help explain how this works?  It is "binding" magic that makes sure that the "inbox" System.Net.Http.dll is used instead of NuGet version.  Note that in this case, "inbox" refers to a version of System.Net.Http.dll from Microsoft.NETCore.App instead of using the one from System.Net.Http NuGet package.  Note also that in the .NET Framework case, this is "binding" magic as well to prefer the GAC version of System.Net.Http.dll instead of any System.Net.Http.dll from a Nuget package.

**Comment by tmds** [comment]
> I was told at dotnet/corefx#32730 that System.Net.Http being version 4.3.0 in .NET Core is a false positive. I have verified locally that this is indeed the case - the System.Net.Http.dll from the .NET Core installation is used. How does .NET Core decide to both download 4.3.0 from nuget, but decide to use the version inbox in .NET Core?

The sdk ends up with a number of possible assemblies and then picks what it considers the best.
Each assembly is turned into a:
```c#
    internal enum ConflictItemType
    {
        Reference,
        CopyLocal,
        Runtime,
        Platform
    }

    internal interface IConflictItem
    {
        Version AssemblyVersion { get; }
        ConflictItemType ItemType { get; }
        bool Exists { get; }
        string FileName { get; }
        Version FileVersion { get; }
        string PackageId { get; }
        string DisplayName { get; }

        Version PackageVersion { get; }
}
```
and the code https://github.com/dotnet/sdk/tree/master/src/Tasks/Common/ConflictResolution picks the proper assembly based on the type, assemblyversion, etc.

> Where is this version 4.3.0 defined in (ASP).NET Core? Can we bump it to 4.3.4 or something similar to remove a false positive for anything that tries to check for CVE-2018-8292.

If you look in the `yourapp.deps.json` file you can follow the breadcrumbs to System.Net.Http 4.3.0: `Microsoft.AspNetCore.App  -> Microsoft.AspNetCore.Authentication.JwtBearer -> Microsoft.IdentityModel.Protocols.OpenIdConnect -> Microsoft.IdentityModel.Protocols -> System.Net.Http`. All those packages would have to be republished for the false positive to no longer appear.

> Is there a list of other packages that exist on nuget.org but are also available inbox where the inbox version is always preferred?

Note sure where this is. It may be the file in the sdk at `sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.DefaultPackageConflictOverrides.targets`.
Or maybe it's the `Microsoft.NETCore.App.PlatformManifest.txt` file in the Microsoft.NETCore.App package.

**Comment by joperezr** [comment]
>I have verified locally that this is indeed the case - the `System.Net.Http.dll` from the .NET Core installation is used. How does .NET Core decide to both download `4.3.0` from nuget, but decide to use the version inbox in .NET Core?

When you are building your project we have a confict resolution task that runs as part of the build, which will look at all of the assemblies that are referenced, and look for conflicts and pick the right winners of each conflict. When referencing the System.Net.Http NuGet package, the contents of it will conflict with the ones that we see inbox. There are several different things we take into consideration when getting the winner, but in this particular case, we just check the Assembly Version of the inbox assembly and the one from the NuGet package, and the inbox one was choosen because it has a higher assembly version.

When doung a build of your project, you can use `/flp:v=diag` parameter in order to see the output of this conflict resolution task, which will include all the conflicts that were found, and it will show which assembly was picked for each conflict and it will also say why it was picked.

**Comment by tmds** [comment]
> There are several different things we take into consideration when getting the winner, but in this particular case, we just check the Assembly Version of the inbox assembly and the one from the NuGet package, and the inbox one was choosen because it has a higher assembly version.

At some point the SDK also trims away assemblies which are part of the 'shared framework'. Is this part of conflict resolution?

Could an assembly from a nuget package 'override' a shared framework assembly if it as a higher assembly version?

Can you give some more info on the version numbers used? System.Net.Http has a version number for the NuGet package. In that NuGet package there are a number of assemblies, which each have their own version number. And then there is for each version of .NET Core also an assembly version number. How do you pick these different version numbers so they work well together?

**Comment by joperezr** [comment]
> At some point the SDK also trims away assemblies which are part of the 'shared framework'. Is this part of conflict resolution?

Yes, one of the things considered during a conflict is whether or not an assembly is part of the shared framework, and this will take into effect in case all the other higher priority comparisons between both assemblies were inconclusive (meaning they had the same Assembly Version for example)

> Could an assembly from a nuget package 'override' a shared framework assembly if it as a higher assembly version?

I believe so, but I'm not 100% sure on this as I believe the SDK does have a hammer for a specific set of shared framework assemblies. Again, I'm not too sure about this one so it would be better to ask either @ericstj or @dsplaisted 

> Can you give some more info on the version numbers used? System.Net.Http has a version number for the NuGet package. In that NuGet package there are a number of assemblies, which each have their own version number. And then there is for each version of .NET Core also an assembly version number. How do you pick these different version numbers so they work well together?

Versioning is indeed a very complex subject. Usually the version on the NuGet package is tied to Product releases, and the Assembly version is more specific to each assembly depending on API breaking changes, new features, patches and bug fixes. Conflict resolution won't look into the NuGet package version, but the assembly version instead. The reason is that one single NuGet package can carry multiple versions of the same assembly (one per each framework the assembly cross-compiles for). For the specific question of how to pick which of these assemblies in the package applies best, this logic doesn't happen at conflict resolution, and instead it is selected by NuGet. Basically, when restoring a NuGet package for your project, NuGet calculates what is the compile and runtime asset that best applies to the framework and Runtime that you are targeting.

Again, verisoning is a very complex subject so it is really hard to explain it in a single paragraph, but I hope that at least the above help shed some light on the questions you have.

**Comment by karelz** [comment]
@ericstj ping?

**Comment by karelz** [comment]
@ericstj ping again? It's been almost 4 months now ...

**Comment by ericstj** [comment]
This behavior is defined by the host and the SDK.  @vitek-karas and @dsplaisted are better folks to answer these types of questions, but I'll do my best here.

> At some point the SDK also trims away assemblies which are part of the 'shared framework'. Is this part of conflict resolution?

That's what we call it in 2.0, in that case it's a effectively "higher version wins" where it examines assembly version first followed by file version.  Since this issue is discussing 1.x I'm not going to go into much detail on conflict resolution here.

> Could an assembly from a nuget package 'override' a shared framework assembly if it as a higher assembly version?

So this is talking about .NETCore 1.x and System.Net.Http.  In this case the thing that decides "who wins" nuget package  vs shared framework is the SDK + host.  It does so solely on package version in 1.x, not file version / assembly version.

The SDK decides if a nuget assembly should be deployed with app based on if the NuGet package version is included in the shared framework closure or not.  This is calculated by https://github.com/dotnet/sdk/blob/b73819e683af64bd19c961973c77b2239cd20e5d/src/Tasks/Microsoft.NET.Build.Tasks/LockFileExtensions.cs#L188-L204, when invoked by the GenerateDepsFile task.  Essentially NuGet decides which package version wins during restore, then the SDK decides if that package is part of the shared framework (and excluded from the app) based on if that package+version is the one referenced by the shared-framework package.

The shared-framework package is the one built in core-setup, and is automatically referenced by the SDK.  I believe the version of the SDK defines a mapping between TFM and version of the shared framework package it references, which will determine the version of these pacakges that get referenced (and thus go into the SDK's decision about when to honor what's in the app vs not).  

Now once the SDK is done with it, I believe the host (in 1.0) simply honors what's in the deps file: so if the app's deps file said it has a specific file that's local to the app, the host honors that.  I could be wrong about this: @vitek-karas or @steveharter could clarify.  I also think there are docs on this in the core-setup repo.  In 2.x and later the host does some version comparisons to decide this (to handle roll forward cases): so it may reject an applocal copy of an assembly if it found that the app's version is older than what's in the shared framework.

> Where is this version 4.3.0 defined in (ASP).NET Core? 

The "false positives" referenced in the OP are likely transitive dependencies of some ASP.NET packages.  The NuGet ecosystem doesn't require all upstack dependencies to ref when a single package is serviced, so tooling which is flagging these as a problem seems broken to me.  Regardless, if you'd like to identify which packages are being flagged you can examine the project.assets.json file to see who's depending on the older package versions.

> Is there a list of other packages that exist on nuget.org but are also available inbox where the inbox version is always preferred?

As I described: for 1.x the "winning" package is the higher version, so you could look at the dependencies of the specific Microsoft.NETCore.App package you're concerned with (tied to the shared framework version) to get an idea of which version is going to win out.  You can also just create a project, restore, and examine the project.assets.json.

**Comment by carlossanlop** [comment]
@vitek-karas @dsplaisted can you please help answer this question?

**Comment by vitek-karas** [comment]
What @ericstj is correct. In 2.1 and above the runtime resolution is based on assembly version and file version. If the app has the same assembly as the shared framework the assembly version will be compared (based on records in `.deps.json`), the higher will be used. If equal, the file version is compared (again based on records in `.deps.json`), the higher will be used. If both versions are equal, then the file from lower level framework will be used.

So the assembly from the app is only used if it has higher version than the one in framework. On equality the framework assembly is used (we assume that if both versions are the same, then the files are basically identical).

**Comment by terrajobst** [comment]
@bartonjs 

> @terrajobst Do we have a simple or technical explanation anywhere of "inbox + nuget" assemblies?

As this thread proves, there is nothing simple about inbox and NuGet, unfortunately 😢

**Comment by scalablecory** [comment]
This is an unfortunate issue that I see pop up with some frequency. It would be great to improve the user story here. Maybe something VS can do, or an analyzer can do, to help avoid this pitfall.

General advice is to stop using the System.Net.Http package. At best it redirects to the inbox version, at worst it causes weird conflicts.

**Comment by joperezr** [comment]
> General advice is to stop using the System.Net.Http package. At best it redirects to the inbox version, at worst it causes weird conflicts.

This is not entirely true though, there are a bunch of .NET Framework apps that are still targeting 4.7 or lower, which still have System.Net.Http version 4.0.0.0 and might require using 4.1.1.3 provided by the NuGet package instead. What you said is true when targeting .Net Framework 4.7.1 and higher, .NET Standard 2.0 or higher, and .NET Core App 2.0 and higher.

**Comment by scalablecory** [comment]
Seems like we've answer the question and no followup for some time; closing this out.
