### ISSUE TITLE
Alternative to ediditing nuget.config https://github.com/dotnet/core/blob/master/samples/linker-instructions.md

### ISSUE THREAD

**Issue by beppe9000** [dotnet/core#2334]
Should the following command be added as a faster way to try out the linker ?
`dotnet add package ILLink.Tasks -s https://dotnet.myget.org/F/dotnet-core/api/v3/index.json -v 0.1.5-preview-1841731`

Possibly in a way that does not require to specify the full version :)

**Comment by karelz** [comment]
Does the command above work? If it does, maybe we should update the doc @sbomer thoughts?

**Comment by beppe9000** [comment]
> Does the command above work?
So it seems... My problem is that I found no way to specify the latest version like this `0.1.*`.

```
C:\Users\Administrator\Desktop\nc\zApp>dotnet add package ILLink.Tasks -s https://dotnet.myget.org/F/dotnet-core/api/v3/index.json -v 0.1.5-preview-1841731
  Writing C:\Users\Administrator\AppData\Local\Temp\tmp236.tmp
info : Aggiunta dell'oggetto PackageReference per il pacchetto 'ILLink.Tasks' nel progetto 'C:\Users\Administrator\Desktop\nc\zApp\zApp.csproj'.
log  : Ripristino dei pacchetti per C:\Users\Administrator\Desktop\nc\zApp\zApp.csproj in corso...
info : Il pacchetto 'ILLink.Tasks' è compatibile con tutti i framework specificati nel progetto 'C:\Users\Administrator\Desktop\nc\zApp\zApp.csproj'.
info : L'oggetto PackageReference per il pacchetto 'ILLink.Tasks' versione '0.1.5-preview-1841731' è stato aggiornato nel file 'C:\Users\Administrator\Desktop\nc\zApp\zApp.csproj'.
info : Esecuzione del commit del ripristino...
log  : Generazione del file MSBuild 
...
```
Also, while we are at it... Is there a way to get a single statically linked exe file with this, or some other way?

**Comment by sbomer** [comment]
Thanks for the suggestion @beppe9000! It's definitely an alternative for folks who don't want to edit the NuGet.config. I'd prefer to keep recommending adding the source to NuGet.config for now, since passing it on the command line will cause future project restores to fail if the package is somehow removed from the cache (if I'm not mistaken). These instructions will need to be updated soon anyway as the linker experience is going to change a bit.

For static linking... maybe see if https://github.com/dotnet/corert meets your needs. You may also be interested in the design at https://github.com/dotnet/designs/pull/52 for single-file distribution (/cc @swaroop-sridhar).

**Comment by beppe9000** [comment]
Ok.

> For static linking... maybe see if https://github.com/dotnet/corert meets your needs. You may also be interested in the design at [dotnet/designs#52](https://github.com/dotnet/designs/pull/52) for single-file distribution (/cc @swaroop-sridhar).

Thanks, they look promising. It's nice to see dotnet starting to follow the path of 2009-era RealBasic/Xojo
