### ISSUE TITLE
Question about release policy of dotnet foundation projects.

### ISSUE THREAD

**Issue by lemmaa** [dotnet/core#236]
I have a question about release policy of dotnet foundation project, especially for .NET Core project that I have an interest.

In my understanding, .NET Core 1.0 was released by Microsoft not by dotnet foundation. So official support is provided by Microsoft, only for their customers. Is it right?

Then, as a manufacturer, If we plan to ship .NET Core to our product, what we should do? 

1. Can we use the Microsoft release of .NET Core to our product? 
2. Can we expect another official release from dotnet foundation in near future? 
3. Or should we make our own distribution package?

Are there any guide about it?
Thank you in advance!

cc: @martinwoodward @hongsekim

**Comment by leecow** [comment]
@lemmaa 

You're correct that Microsoft releases .NET Core rather than the Foundation and official support .NET Core is provided by Microsoft. You can absolutely use the Microsoft release for your product. The .NET documentation is ever growing and [this topic](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/index) should give you a start on how to think about deploying your applications. 

/cc @blackdwarf @richlander
