### ISSUE TITLE
Date Conversion format mismatch 

### ISSUE THREAD

**Issue by kishorkabadi** [dotnet/core#2452]
I have a .Net 4.5 website on IIS 6 running on Windows Server 2012 R2.
 When converting a date in  format MM/dd/YYYY ,c# converted into MM-dd-YYYY format
with en-IN culture.

code is:

CultureInfo culture = new CultureInfo("en-IN");

DateTime dt = Convert.ToDateTime("02-01-2019", culture);

string result dt.ToString("dd/MMM/yyyy");

result is 02-Jan-2019 

Expected result is 02/Jan/2019 

when i trying to convert date in following format

dd/MM/yy
dd/MMM/yy
dd/MM/yyyy
dd/MMM/yyyy
MM/dd/yy
MMM/dd/yy
MM/dd/yyyy
MMM/dd/yyyy
MMM/yyyy
yy/MMM
yyyy/MMM
yy/MM/dd
yy/MMM/dd
yyyy/MM/dd
yyyy/MMM/dd

date is converted into  following format

dd-MM-yy
dd-MMM-yy
dd-MM-yyyy
dd-MMM-yyyy
MM-dd-yy
MMM-dd-yy
MM-dd-yyyy
MMM-dd-yyyy
MMM-yyyy
yy-MMM
yyyy-MMM
yy-MM-dd
yy-MMM-dd
yyyy-MM-dd
yyyy-MMM-dd

but i am expecting result in following format with en-IN Culture..

dd/MM/yy
dd/MMM/yy
dd/MM/yyyy
dd/MMM/yyyy
MM/dd/yy
MMM/dd/yy
MM/dd/yyyy
MMM/dd/yyyy
MMM/yyyy
yy/MMM
yyyy/MMM
yy/MM/dd
yy/MMM/dd
yyyy/MM/dd
yyyy/MMM/dd

Is it depend on iis setting or system regional setting..

**Comment by svick** [comment]
This is because the `/` character does not represent the literal `/`, but is instead a [custom format specifier for the date separator](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#the--custom-format-specifier-1).

As the documentation says, if you want a literal `/`, you can use `'/'` in the format string.

Also, you're not using the `culture` variable in your call to `ToString()`, which means it's using the current culture, which may not be en-IN.

So, the code to do what you want is: `dt.ToString("dd'/'MMM'/'yyyy", culture)`. Its output is `02/Jan/2019`, which is what you wanted.

**Comment by kishorkabadi** [comment]
Ok. 
What about other characters like '.','-' in date format string when converting date is specific format.
How can convert dates in any format as independent of system setting and IIS Globalization...

**Comment by svick** [comment]
This is explained in [the next section of the same document](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#Literals) (note that the `|` in the table should be `\`, see https://github.com/dotnet/docs/pull/11723). Specifically, the characters `.` and `-` don't have to be enclosed in single quotes, since they are not reserved characters.
