### ISSUE TITLE
ResourceManager Fails With Underscore_ In The BaseName

### ISSUE THREAD

**Issue by vindicatorr** [dotnet/core#2514]
# General
Version:
Arch Linux dotnet 2.2.3+105 = dotnet --version 2.2.105
[resourceManager.tar.gz](https://github.com/dotnet/core/files/3015719/resourceManager.tar.gz)

I was trying to go through https://docs.microsoft.com/en-us/dotnet/api/system.resources.resourcemanager?view=netcore-2.2 (saved as a pdf) to experiment with localization... It did NOT go well.

I swore I had things right and tried a whole multitude of ways, which included using "en-US" in the resource filename, but I found GetManifestResourceNames() didn't like that, which made me try "en_US".
When I still ran into issues getting it to work right, the "\_" stood out for me since my project also contained an underscore. So I ran 2 quick tests which are included in the zipped file.
It led me to the conclusion that the Basename cannot contain a "\_".

I did some other tests while I was at it and you'll notice the folder structure vs filename in the resourceManagerTest project.
Essentially, the whole concept fails if you use "resources/<loc_LOC>/strings.restext" and it must be done in the form of "resources/strings.<loc_LOC>.restext".
If it weren't for GetManifestResourceNames not showing the "filename.loc-LOC.restext" entries, I don't know if I would've every figure it out. That's while ILSpy doesn't work for me either.

Mind you, this is all under linux using Visual Studio Code, where there is no resgenx or al or whatever else the docs site references, so maybe the subdirs for localization will work with those.

EDIT0:
I also want to add that there seems to be no way to change the "base-name".
In the csproj, I tried setting "rootnamespace", but while the generated obj .resource files reflect that, GetManifestResourceNames does not.

**Comment by karelz** [comment]
@tarekgh @krwq can you please help here? (or point to best routing place?) Thanks!

**Comment by tarekgh** [comment]
@vindicatorr

The way to create the right resources for different cultures was the first way you have tried which is, you create a file with the form  {FileName}.{CultureName}.extension. for example in your case hello.fr-FR.restext. Note, the culture name has ```-``` and not ```_```. 

When you have this form of naming and you embed in csproj file like 

```Xml
<EmbeddedResource Include="resources/hello.fr-FR.restext" />
```

The build process will understand you are trying to create a resources for fr-FR culture. The build will produce a satellite assembly under a folder with the culture name fr-FR. something like ./bin/Debug/netcoreapp2.2/fr-FR/resourceManagerTest.resources.dll

Now, you need to understand doing that you have created a resources satellite assembly and there is no resources embedded inside the main code assembly. That is mean when executing a code like 

```C#
            System.Resources.ResourceManager mResourceManager1 = new System.Resources.ResourceManager("resourceManagerTest.resources.hello", typeof(resourceManagerTest.Program).Assembly);
            foreach (System.String mResourceName in typeof(resourceManagerTest.Program).Assembly.GetManifestResourceNames())
                Console.WriteLine(mResourceName);
```

Will not show any entry because you don't really embed any resources in that main assembly. You can embed the default neutral resources in the main assembly by just creating a resource file without a culture name. something like hello.restext and then embed it inside teh main assembly by 

```Xml
    <EmbeddedResource Include="resources/hello.restext" />
```

last note, when you create the resource file with underscore and not a dash, you are not really creating a culture specific resources as this is not a valid culture name. That means you are embedding such resource file inside the main code assembly and not creating culture specific satellite assembly and this will not work as you expect the resources should be associated with the intended culture.

I have attached here a sample demonstrating what I mentioned here and also add some code showing how you can access different culture resources.
  
[resourceManagerTest.zip](https://github.com/dotnet/core/files/3030496/resourceManagerTest.zip)

I am closing this issue but feel free to reply back if you have any question.

**Comment by vindicatorr** [comment]
That clears it up completely.
I neglected to notice before when trying the "en-US" way, using the dash, that the obj and bin folders DID show the satellite dlls being created in their relative culture folders.

I see another way I could have figured out those resources were in fact being included when I thought they weren't by:
```
System.Reflection.Assembly mExeAssembly=System.Reflection.Assembly.GetExecutingAssembly();
foreach (System.String mResourceName in mExeAssembly.GetSatelliteAssembly(new System.Globalization.CultureInfo("en-US")).GetManifestResourceNames())
    Console.WriteLine(mResourceName);
```
This can also help let a person know how it is named for use in the ResourceManager.
For example, if I were to set the "rootnamespace" in the csproj, the resource dll filenames created in the bin will still show the same project-name root which I would normally tell ResourceManager what the basename should be, but the above code shows the real name.

For example, if the project name (dir & csproj) were "thisProject", and I set the "rootnamespace" in the csproj to "thisProject_NS", and everything else was done normally with regard to creating resource files, the bin/....../en-US/\<resourcefilename> would be still look like "thisProject.resources.dll", but with the rootnamespace set to something else, using "thisProject.resources" won't work with the ResourceManager.
Instead I would have to use "thisProject_NS.resources".
