### ISSUE TITLE
.net native compiler exception

### ISSUE THREAD

**Issue by ispysoftware** [dotnet/core#2614]
When building a UWP project for release mode (.net native) i'm getting an internal compiler exception.

"Severity	Code	Description	Project	File	Line	Suppression State
Error		Internal compiler error: Object reference not set to an instance of an object.	App1	C:\Users\sean\.nuget\packages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets	801	
"
I've logged a report but am getting no response to it

https://developercommunity.visualstudio.com/content/problem/536403/internal-compiler-error-26.html

It's very very simple to reproduce:

Create a new blank UWP project, enable unsafe code, add this struct to it and compile in Release mode:

    public unsafe struct long_array4
    {
        public static readonly int Size = 4;
        fixed long _[4];

        public long this[uint i]
        {
            get
            {
                fixed (long_array4* p = &this)
                {
                    return p->_[i];
                }
            }
            set
            {
                fixed (long_array4* p = &this)
                {
                    p->_[i] = value;
                }
            }
        }
    }

.. if you comment out

`p->_[i] = value;`

it compiles also if you change long to int it also compiles.

**Comment by karelz** [comment]
@MattWhilden can you please help to route it to the appropriate feedback channel? Thanks!

**Comment by MattWhilden** [comment]
Well that's certainly a curious one. The crash is super early as we're booting up the analysis engine. Curiously this crash is not present in the 1.7 version of tools. I didn't play around enough to understand if we've generated anything sensible. It's a bit odd I know but if you change the UWP app minsdk to anything before 16299 you'll be able to build with 1.7 and not the typical 2.X you get out of the Microsoft.NETCore.UniversalWindowsPlatform nuget package.

Glancing through your profile I presume this snippet comes from FFMpeg bindings?

Here's the bug number I've created in our internal DB in case that's useful later. 853938

**Comment by ispysoftware** [comment]
Yes, it's crashing in a few places in the ffmpeg bindings. This is the first one i managed to isolate. I'm hoping the root cause is the same. Unfortunately for our project we can't use the earlier SDK.

**Comment by MattWhilden** [comment]
Some good news! Given a compiler update isn't likely for a while and due to where the crash is happening I have what may be a reasonable workaround. 

As above, the compiler is crashing very early. While poking around a bit more it turns out that the phase that is having issues is attempting to determine which types in your application will need information available at runtime to facilitate Reflection (creating instances, inspecting etc). Given the type of library it seems possible that you may not actually need ANY of this and can hint to the compiler that it shouldn't bother inspecting this type. This can be accomplished by adding an element similar to this to the Propeties\Default.rd.xml file in your UWP project:
`<Type Name="App32.long_array4" Dynamic="Excluded"/>`
Or more generally for the entire binding library:
`<Assembly Name="Foo.Bar.Baz" Dynamic="Excluded"/>

I usually recommend keeping the exclusions very narrow but given there's likely to be other hard to diagnose things from this library, that may be more helpful. If the exclusion ends up being too broad you'll get MissingMetadateException errors at runtime that are certainly more helpful than this crash.

Let me know if you have success with that approach.

**Comment by ispysoftware** [comment]
Yes that did help thank you. The types the compiler is failing on are :

```
long
ulong
double
```

**Comment by MattWhilden** [comment]
Lovely. I'll add that info to the issue we're using to track getting a real fix. That's likely later this summer but shipping schedules are **way** above my pay grade.

Certainly let us know if you have other issues and thanks for the concise bug report!!

**Comment by karelz** [comment]
Seems to be addressed. Let's close it here as this is not the right place to track .NET Native issues anyway ;)

**Comment by MattWhilden** [comment]
Reviving this a bit, 6.2.9 is now available on Nuget. Certainly let us know how it goes.

Release notes: https://github.com/microsoft/dotnet/tree/master/releases/UWP/net-native2.2
