### ISSUE TITLE
New problem installing dotnet core on Ubuntu 18.10

### ISSUE THREAD

**Issue by paciook** [dotnet/core#2636]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-10/sdk-current
Operating System: Linux Ubuntu 18.10 - x64

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by karelz** [comment]
@dagood I wonder if we should keep one issue opened with clear description and dupe everything against it ...

**Comment by dagood** [comment]
@paciook, can you run these diagnosis steps and share the results?

```
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
# Show your distro version.
cat /etc/os-release
# This install command will show exactly which dependency can't be met.
sudo apt-get install dotnet-runtime-deps-2.2
```

---

@karelz, there isn't enough info to know what this is quite yet. If it happens to be an attempt to use 18.10 packages on 19.04, then maybe we should open https://github.com/dotnet/core/issues/2526?

What I picture when I think of a dupe target for this is an issue with some diagnosis steps, but there's nothing we could do to close that. There's no root cause. The problem is that `apt-get` et. al. don't log enough info by default to create actionable issues. 😕

The only thing that jumps to mind to make this easier is keeping a doc of common errors to point people to for self-diagnosis.

**Comment by karelz** [comment]
self-diagnosing doc sounds like a great idea. We can even link it from issue template.
Can you create one?

**Comment by dagood** [comment]
Yeah, filed https://github.com/dotnet/core-setup/issues/6116 to track that. Will give it a shot when time permits.

When you press "I ran into an issue" in the "Getting Started" docs, it passes a description through the URL that doesn't seem tied to this repo's template, so there's probably something to change on the doc site side of things too once we have something. (It actually seems good for it to happen there so it can be included contextually for people following the Linux tutorial.)

**Comment by karelz** [comment]
No response, closing. Feel free to reopen when there is actionable info available. Thanks!

I assume the self-help guide is tracked elsewhere.
