### ISSUE TITLE
Can't using ServerManager.OpenRemote

### ISSUE THREAD

**Issue by felipealves** [dotnet/core#2691]
Hello Everybody, I need to manage IIS using Net Core, however when I use the ServerManager.OpenRemote it returns me the nullable objects, in the Net Core it is not possible to manage the remote IIS?

**Comment by Eilon** [comment]
@shirhatti , any idea about Microsoft.Web.Administration, or who would know more about it?

**Comment by shirhatti** [comment]
@bariscaglar

**Comment by bariscaglar** [comment]
@felipealves when you say "nullable" objects, do you mean what is returned is null? ServerManager.OpenRemote is quite tricky to get working even in full framework because it uses DCOM and you need to change server settings to get it to work. It won't work out of the box. This [StackOverflow question](https://stackoverflow.com/questions/22458410/credentials-for-servermanager-openremote) has a good answer that gives links to the individual steps needed to be taken to make it work. If any of the underlying client technologies is not supported in Net Core, then it won't work. In fact, the fact that you didn't get an error but just a null object makes me think so.

The recommended way of administering IIS remotely is through [IIS Administration REST API](https://github.com/Microsoft/IIS.Administration). We do not have an SDK, unfortunately, but you can still send requests from your Net Core Application and manipulate responses easily.

**Comment by felipealves** [comment]
@bariscaglar thanks for the info, using ServerManager.OpenRemote, all objects return nullable, I will implement a REST API.

**Comment by ewan-000** [comment]
Hi Can this be reopened? You can see in the current dotnetcore version of Microsoft.Web.Administration ServerManager.OpenRemote simply news up a new ServerManager and sets _servername. It doesn't setup any of the internal objects at all
