### ISSUE TITLE
Can't get LTS versions for Centos7, Fedora28

### ISSUE THREAD

**Issue by jpfreyen** [dotnet/core#2721]
From here:
https://dotnet.microsoft.com/download/dotnet-core/2.1

If I am interested in **LTS version** (v2.1.10, SDK 2.1.506) for Centos7 or Fedora28 and I follow the Centos7 or Fedora28 instructions how to get SDK 2.1.506:
https://dotnet.microsoft.com/download/linux-package-manager/centos/sdk-2.1.506
https://dotnet.microsoft.com/download/linux-package-manager/fedora28/sdk-2.1.506

I do **NOT** get SDK 2.1.506:

```

================================================================================
 Package                  Arch    Version    Repository                    Size
================================================================================
Installing:
 dotnet-sdk-2.1           x86_64  2.1.603-1  packages-microsoft-com-prod  114 M
Installing for dependencies:
 aspnetcore-runtime-2.1   x86_64  2.1.10-1   packages-microsoft-com-prod   28 M
 dotnet-host              x86_64  2.2.4-1    packages-microsoft-com-prod   44 k
 dotnet-hostfxr-2.1       x86_64  2.1.10-1   packages-microsoft-com-prod  196 k
 dotnet-runtime-2.1       x86_64  2.1.10-1   packages-microsoft-com-prod   27 M
 dotnet-runtime-deps-2.1  x86_64  2.1.10-1   packages-microsoft-com-prod  2.8 k

Transaction Summary
================================================================================
Install  1 Package (+5 Dependent packages)

```

As you can see, I get SDK 2.1.603, which is *NOT* labeled an LTS version on the dotnet-core/2.1 website.

Could you please create a new rpm, or rpm "alias", call it "**_dotnet-sdk-2.1-lts_**", that actually points to the LTS packages Microsoft is advertising in its SDK download website please? (see screenshot):

![Screen Shot 2019-05-13 at 9 49 59 AM](https://user-images.githubusercontent.com/10945795/57639330-8597ac80-7564-11e9-834e-6f8af4941a78.png)

This way there is always a way for people to pull down the LTS version via package manager tools (yum, dpkg, etc).

Thank you.

**Comment by leecow** [comment]
@jpfreyen, there are a few confusing things at play - sorry about that. 

The toolset (SDK) is not LTS; the Runtime is. The latest SDK can be used to target and build for any version of the .NET Core runtime. With the announcements which happened at //BUILD last week, we're working on our LTS policy language and will make sure this part is clear. 

Most package managers give you the ability to specify a specific package version to install. On Fedora, this would look like the following. 

```
dnf --showduplicates list dotnet-sdk-2.1
Last metadata expiration check: 0:00:49 ago on Tue 14 May 2019 12:35:03 PM PDT.
Available Packages
[I shortened the list a bit]
dotnet-sdk-2.1.x86_64                    2.1.504-1                    packages-microsoft-com-prod
dotnet-sdk-2.1.x86_64                    2.1.505-1                    packages-microsoft-com-prod
dotnet-sdk-2.1.x86_64                    2.1.602-1                    packages-microsoft-com-prod
dotnet-sdk-2.1.x86_64                    2.1.603-1                    packages-microsoft-com-prod
dotnet-sdk-2.1.x86_64                    2.1.604-1                    packages-microsoft-com-prod
```

Then you can install using `dnf install dotnet-sdk-2.1-2.1.504-1` (or whatever available version you want). It's by-design that 2.1.507 is not available on the feed because 2.1.604 is the correct choice for folks not developing in Visual Studio.

**Comment by RheaAyase** [comment]
I do have a few notes here... First being that Fedora 28 is soon to be EOL'd and you should hop on 29 or even 30.

Then it's the whole question of using the right install sources. With Linux in mind, always use what's native to the distribution, it's repositories and things maintained by the people who know their distribution the best. In the case of Fedora the information is behind a handy alias [fedoraloves.net](http://fedoraloves.net) which goes on to explain how to install dotnet on Fedora, for example to get the 2.1 (LTS) it would be:

```
$ sudo dnf copr enable @dotnet-sig/dotnet
$ sudo dnf install dotnet-sdk-2.1
```

**Comment by jpfreyen** [comment]
@leecow that is more clear, thanks.

@RheaAyase, sometimes it's not practical for a shipping project to always use what is available to the distribution, especially if the distro keeps moving up packages and there isn't a good way to get the previous package, that is hard on QA.  The dotnet-sdk-2.1.-lts idea is a Ubuntu thing in which they have package "aliases" that will go and get the specific packages (like "build-essentials" for example, using that will go and get 'git', gcc', etc).

**Comment by RheaAyase** [comment]
Well, 2.1 is LTS and it doesn't need an alias for that. As it is described above doesn't make much sense. It would make sense to have `dotnet-lts` though.

Especially in Fedora we package everything so that you can stick to *any* minor and even any feature version of the SDK.

Here is slightly reduced list for `dnf list --showduplicates dotnet-sdk*`
```
rjanek@RedHat:~/dev/qe$ dnf list --showduplicates dotnet-sdk* | grep xx.x86_64
dotnet-sdk-2.1.5xx.x86_64             2.1.506-1.fc30    @group_dotnet-sig-dotnet
dotnet-sdk-2.1.2xx.x86_64             2.0.9-1.fc29      group_dotnet-sig-dotnet 
dotnet-sdk-2.1.3xx.x86_64             2.1.302-1.fc30    group_dotnet-sig-dotnet 
dotnet-sdk-2.1.4xx.x86_64             2.1.403-3.fc30    group_dotnet-sig-dotnet 
dotnet-sdk-2.1.5xx.x86_64             2.1.506-1.fc30    group_dotnet-sig-dotnet 
dotnet-sdk-2.2.1xx.x86_64             2.2.103-1.fc30    group_dotnet-sig-dotnet
```

**Comment by jpfreyen** [comment]
@RheaAyase I agree and think it's a great idea to have a "dotnet-lts" :-).

**Comment by karelz** [comment]
Is there still an outstanding question or follow up?

**Comment by RheaAyase** [comment]
The initial problem is with unclear versioning :P
I guess that the real question is whether it's documented sufficiently or we need to improve that.

**Comment by jpfreyen** [comment]
Were I last commented was the idea of having a dotnet-lts named package.  Is that going to happen?

**Comment by jpfreyen** [comment]
Oh and a question of Fedora 28 EOL'ing brought up by @RheaAyase ...is .NETCore 2.1 LTS going to be updated for: RHEL8, Fedora 29, and Fedora 30 (and others like Linux Mint 19)?  Documentation doesn't mention any newer releases that 2.1 LTS supports:

https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md

**Comment by RheaAyase** [comment]
Microsoft may be building and publishing the built product for some of the Linux distributions, that however isn't the preferred install source from Linux point of view. The release notes you link, or the packages that Microsoft publishes on the download website, are likely to not keep up with the life cycle that many Linux Distributions have.

* RHEL7 has everything currently supported.
* RHEL8 was released only with LTS 2.1 because dotnetcore 2.2 will EOL very soon and that wasn't enough to justify the heroic effort that would be required to also include 2.2 :P
* Fedora 29/30/rawhide (and future versions) has everything currently supported. You can find specific builds, versions, dates, etc here: https://copr.fedorainfracloud.org/coprs/g/dotnet-sig/dotnet
* Can't comment on other distributions as I don't know :)

**Comment by RheaAyase** [comment]
Created [PR#2855](https://github.com/dotnet/core/pull/2855) to address the release-notes/supported-os issue.

**Comment by karelz** [comment]
@RheaAyase can we close now? Or are we still tracking some additional work?

**Comment by RheaAyase** [comment]
Hi @karelz, I don't think that there is more work to be done, unless y'all want to somehow resolve the confusing inconsistency between the different SDK versions :/

(I know that this should be resolved in the future versions. Can't wait the day!)

**Comment by jpfreyen** [comment]
@RheaAyase, yes, if the inconsistencey between the different SDK versions could be resolved sometime that would be great
