### ISSUE TITLE
Circular dependence

### ISSUE THREAD

**Issue by guille31794** [dotnet/core#2739]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.10 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Circular dependence: 
Los siguientes paquetes tienen dependencias incumplidas:
dotnet-sdk-2.2 : Depende: aspnetcore-runtime-2.2 (>= 2.2.4) pero no va a instalarse
Depende: dotnet-runtime-2.2 (>= 2.2.4) pero no va a instalarse

Which means that if I try to install .Net I need aspnetcore, and if I try to install aspnetcore, It ask for .Net..

**Comment by karelz** [comment]
This is weird - @dagood did you see that before?

**Comment by dagood** [comment]
I don't see the circle in the error output, can you clarify? The chain I see is this:

`dotnet-sdk-2.2` depends on `aspnetcore-runtime-2.2` depends on `dotnet-runtime-2.2`

(Note that the first package is the .NET Core SDK, and the last one is the .NET Core Runtime.)

* What happens when you run `sudo apt-get install dotnet-runtime-2.2`?
* The root of this problem is probably `dotnet-runtime-deps-2.2`. Can you try installing that?

This error message usually shows up when the distro release version doesn't match the repository you have set up. These are the diagnosis steps I usually recommend to help us diagnose the problem:

```
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
# Show your distro version.
cat /etc/os-release
# This install command will show exactly which dependency can't be met.
sudo apt-get install dotnet-runtime-deps-2.2
```

**Comment by guille31794** [comment]
So thats it! 
> This error message usually shows up when the distro release version doesn't match the repository you have set up.
I'm trying to install 18.10 sdk version and I forgot I'm running on 19.04 since a trouble a I got a few days ago that makes me reinstall and update. 
So, by the moment I'm unable to install the sdk until a new update, isn't?
Thanks.

**Comment by dagood** [comment]
Cool, thanks for checking it out. 😄

> So, by the moment I'm unable to install the sdk until a new update, isn't?
> Thanks.

Docs for 19.04 are up as of around May 20th, should be good to go. (https://github.com/dotnet/core/issues/2728)

(Maybe you saw this and that's why you closed the issue, but just making sure.)

**Comment by guille31794** [comment]
Indeed! After the update in the official website all came back to normality and I was able to install the package as usual.
Thank you for your support! <3
