### ISSUE TITLE
Cant install new template [ not compatible with netcoreapp1.0 ]

### ISSUE THREAD

**Issue by Amine-Smahi** [dotnet/core#2779]
I cant install the [Razor-Component-Template](https://www.nuget.org/packages/Razor-Components-Template/) from nuget.org 

![image](https://user-images.githubusercontent.com/24621701/58255226-708cfb80-7d64-11e9-9ad4-ff512e70df0e.png)

**Comment by rynowak** [comment]
@Amine-Smahi - this is a template you created right?

![image](https://user-images.githubusercontent.com/1430011/58269085-a2d63300-7d3b-11e9-866f-50bb87cd5342.png)

**Comment by Amine-Smahi** [comment]
Yes @rynowak

**Comment by Pilchie** [comment]
Should this issue be moved to a different repo then?

**Comment by rynowak** [comment]
This seems like a question about how to author templates. @Amine-Smahi - there's a tutorial [here](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template). I'm guessing that the problem is that you have a target for netcoreapp3.0.

@kevinpi As far as whether that's a bug in the templating system or not, I don't know the answer or where those bugs list. @natemcmaster @vijayrkn - do you know where this should be moved?

**Comment by vijayrkn** [comment]
If it an issue in the templating engine, then https://github.com/dotnet/templating is the right place. @SeancPeters - do you know if this is a template content issue or an engine issue?

**Comment by seancpeters** [comment]
The Razor-Components-Template nupkg on nuget.org contains .dlls in the lib\netcoreapp3.0 directory. Are these required to ship with the nupkg, or are these build artefacts that mistakenly got packaged into the nupkg?

I believe those .dlls are causing the netcoreapp3.0 dependency in the .nuspec, as @rynowak mentioned.

In general it is a problem for a template nupkg to contain both templates and .dlls, this isn't a fully supported scenario for dotnet new. Try repackaging the nupkg without those .dlls

**Comment by rynowak** [comment]
Closing due to lack of response. If you're still having problems please open a new issue on the templating repo.
