### ISSUE TITLE
Error installing .net core 2.2 in WSL with openSUSE Leap 42

### ISSUE THREAD

**Issue by ogauthier** [dotnet/core#2785]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux openSUSE Leap - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Running this command 
sudo zypper install dotnet-sdk-2.2
gave this message:
Problem: dotnet-sdk-2.2-2.2.300-1.x86_64 requires dotnet-runtime-2.2 >= 2.2.5, but this requirement cannot be provided
  uninstallable providers: dotnet-runtime-2.2-2.2.5-1.x86_64[packages-microsoft-com-prod]
 Solution 1: deinstallation of krb5-mini-1.12.5-25.1.x86_64
 Solution 2: do not install dotnet-sdk-2.2-2.2.300-1.x86_64
 Solution 3: break dotnet-sdk-2.2-2.2.300-1.x86_64 by ignoring some of its dependencies

**Comment by ogauthier** [comment]
I selected Solution 1, deinstallation of krb5-mini-1.12.5-25.1.x86_64 and the installation completed.
Dotnet seems to run fine now.

**Comment by karelz** [comment]
@dagood @leecow anything we should do here? Maybe better docs/instructions?

**Comment by dagood** [comment]
Our package has a dependency on [`krb5`](https://software.opensuse.org/package/krb5) rather than [`krb5-mini`](https://software.opensuse.org/package/krb5-mini)--I'm guessing they conflict because they provide (mostly) the same functionality. I don't know if .NET Core requires any of the features that `krb5-mini` is intentionally missing.

If we support running on either package, we're unfortunately kind of limited in fixing this. RPM package managers don't generally support boolean expression dependencies yet, which would allow either `krb5` or `krb5-mini` to satisfy our package's dependency.

It looks like `krb5` is more widely available based on https://github.com/dotnet/core-setup/issues/4384, @leecow might know more.

**Comment by karelz** [comment]
Looks like there is nothing else to do here ... closing.
cc @wfurt

**Comment by wfurt** [comment]
option `Solution 3: break dotnet-sdk-2.2-2.2.300-1.x86_64 by ignoring some of its dependencies` should work by brief look. We only need base library and only and only if app does Kerberos. (rare)
