### ISSUE TITLE
1.x release for OSX?

### ISSUE THREAD

**Issue by abjbhat** [dotnet/core#280]
Is there a timeline for when the 1.0/x release will be out for OSX/macOS? The official installer is stuck at preview2 for quite some time now.

**Comment by svick** [comment]
It's the same for all OSes: .Net Core SDK is currently at version "1.0.0 Preview 2 (build 003131)", while .Net Core itself is at version 1.0.1. The reason why the SDK is still called "preview" is because significant changes are planned for it for the near future (namely, switching from project.json to msbuild).

**Comment by Petermarcu** [comment]
@svick is correct. It's not just OSX, its all OS's the tools have been going through major changes. We are going to ship an update to the Mac installers very shortly to fix some issues they encountered on Sierra but those tooling packages will still be preview.
