### ISSUE TITLE
System.Text.Json is a waste of time.

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/core#2802]
I don't get why the .NET Core Json module (`System.Text.Json`) is modelled after the old Xml DOM pattern with objects like `JDocument`, `JElement` and so on. Of course, the complete absence of samples [ref](https://twitter.com/sujayvsarma/status/1132969895505858562) makes it impossible to see if there is a better way around. 

If I was doing this, I would simply merge the hugely popular (and only used?) `Newtonsoft.Json` project into .NET Core itself. That way, you don't need to redo your documentation, you don't need to write new sample code, you don't need to a heck of a lot of things.  The best thing would be that millions of developers who are currently using Newtonsoft.Json don't need to do anything other than change namespaces maybe! 

Why is Microsoft over-complicating things?

**Comment by Szer** [comment]
> and only used?

This is hugely opinionated because [problems](https://github.com/JamesNK/Newtonsoft.Json/issues/862#issuecomment-237539075) with Newtonsoft.Json are [well known](https://github.com/JamesNK/Newtonsoft.Json/issues/924) and plenty.
Performance is not that good too.

On the other hand, there are a bunch of popular serializers:
- https://github.com/neuecc/Utf8Json
- https://github.com/fsharp/FSharp.Data

**Comment by sujayvsarma** [comment]
@Szer : ".NET Core" by itself is a hugely opinionated library. So yes, my post was opinionated.

Both the problems you have referenced are even issues. The first one is by design and the second one can be changed by a simple option flag. I use the library (Newtonsoft.Json) quite heavily across multiple projects, even enterprise and cloud-scale applications and have zero problems with it [I am vociferous getting attention to issue I face, you are free to Google for what I've said about that library!].

**Comment by karelz** [comment]
System.Text.Json is still under construction. It is high-performance (no allocation) API. If you care primarily about dev usability, keep using other more user-friendly APIs like Newtonsoft.Json, etc.

cc @joshfree @ahsonkhan @steveharter

**Comment by KamranShahid** [comment]
> I don't get why the .NET Core Json module (`System.Text.Json`) is modelled after the old Xml DOM pattern with objects like `JDocument`, `JElement` and so on. Of course, the complete absence of samples [ref](https://twitter.com/sujayvsarma/status/1132969895505858562) makes it impossible to see if there is a better way around.
> 
> If I was doing this, I would simply merge the hugely popular (and only used?) `Newtonsoft.Json` project into .NET Core itself. That way, you don't need to redo your documentation, you don't need to write new sample code, you don't need to a heck of a lot of things. The best thing would be that millions of developers who are currently using Newtonsoft.Json don't need to do anything other than change namespaces maybe!
> 
> Why is Microsoft over-complicating things?

You are making opinion when the thing was under implementation and not even releases 5 months back. 
When there is something available in the framework then it obviously have performance gain rather then using external api for the same functionality. .net core 3. is released less then couple of week ago. Let's see the performance gains

**Comment by jwilson-proag** [comment]
> > and only used?
> 
> This is hugely opinionated because [problems](https://github.com/JamesNK/Newtonsoft.Json/issues/862#issuecomment-237539075) with Newtonsoft.Json are [well known](https://github.com/JamesNK/Newtonsoft.Json/issues/924) and plenty.
> Performance is not that good too.
> 
> On the other hand, there are a bunch of popular serializers:
> 
> * https://github.com/neuecc/Utf8Json
> * https://github.com/fsharp/FSharp.Data

System.Text.Json is riddled with limitations. Just look at Microsoft's own documentation.  

https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0

Much of expected functionality is not offered out of the box. The offer workarounds, but those are not solutions, those are hacks. So more performance (which is usually meaningless since we are talking about milliseconds), but now I have to write my own converters? No thanks. Newtonsoft.json is still used more than any other json libraries available by over 10 fold, even in new .net core applications.  There is something to be said about that.  Yes, OP is posting an opinion, but it appears is the opinion held by the vast majority of the dev community, myself included.

**Comment by KamranShahid** [comment]
What i believe is in .net core 3 it was the first step to at-least use within framework implementation of simpler thing rather then using newtonsoft or other third party libraries. in 5.0 early feedbacks about shortcoming were address  (as 5.0 is not LT release) and possibly expecting more improvement by the time of .net core 6.0 finalized.
moreover writer of newtonsoft library was even full time associated with Microsoft around 2019 if i remember correctly. So things will improve as per new versions. it is true that lots of third party libraries using newtonsoft internally but they are also gradually moving to System.Text.Json only where ever possible.

**Comment by jwilson-proag** [comment]
> What i believe is in .net core 3 it was the first step to at-least use within framework implementation of simpler thing rather then using newtonsoft or other third party libraries. in 5.0 early feedbacks about shortcoming were address (as 5.0 is not LT release) and possibly expecting more improvement by the time of .net core 6.0 finalized.
> moreover writer of newtonsoft library was even full time associated with Microsoft around 2019 if i remember correctly. So things will improve as per new versions. it is true that lots of third party libraries using newtonsoft internally but they are also gradually moving to System.Text.Json only where ever possible.


Good call.  I have been doing a little research into the topic and what I found is that the major reasons for moving towards System.Text.Json is because Newtonsoft releases updates on a pretty regular schedule, much faster than Microsoft.  This opened the door to runtime errors if there were version mismatches within the .net core framework and the implemented version in a given software.  Implementing their own Json library removes this risk.  Now users can upgrade there newtonsoft libraries without risk of breaking the underlying .net core framework.  For that I think it is a good idea.  I "mostly" retract my given statement that it is a waste of time.  I will still use Newtonsoft in most my applications simply because of the robustness of it, but I def understand now why Microsoft chose to go this direction.

**Comment by uffebjorklund** [comment]
We removed Newtonsoft in favor of System.Text.Json in our products when we moved to .net 5.
Sure, we had to implement some custom converters, but we get less allocations and more control.
Can see why some would like to continue using Newtonsoft, but the move to System.Text.Json was an easy decision for us.

**Comment by KamranShahid** [comment]
> We removed Newtonsoft in favor of System.Text.Json in our products when we moved to .net 5.
> Sure, we had to implement some custom converters, but we get less allocations and more control.
> Can see why some would like to continue using Newtonsoft, but the move to System.Text.Json was an easy decision for us.

same here

**Comment by arman-g** [comment]
> We removed Newtonsoft in favor of System.Text.Json in our products when we moved to .net 5. Sure, we had to implement some custom converters, but we get less allocations and more control. Can see why some would like to continue using Newtonsoft, but the move to System.Text.Json was an easy decision for us.

Because it has too many limitations like it was motioned. Here is one simple limitation below, you can only specify one **DefaultIgnoreCondition** globally. Is this a limitation? of course. 

Can you do this?
```
services.AddControllersWithViews().AddJsonOptions(opts =>
{
        opts.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;
        opts.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault; //?
});
```
Nope, why not? they do not contradict and have many used cases.

Why have this limitation if they simply could make the **JsonIgnoreCondition** Enum marked with [Flag] attribute so it can be combined using bitwise operator '|'?

```
services.AddControllersWithViews().AddJsonOptions(opts =>
{
        opts.JsonSerializerOptions.DefaultIgnoreCondition = 
                  JsonIgnoreCondition.WhenWritingNull | JsonIgnoreCondition.WhenWritingDefault;
});
```

How about having an ignore condition for empty arrays? Should we write a converter for that?

**Comment by steveharter** [comment]
Note that `JsonIgnoreCondition.WhenWritingDefault` implies `WhenWritingNull` for reference types. The default value for a reference type is `null`.
