### ISSUE TITLE
PowerShell 7 - fails to perform the coercion on all point assignments in WinForms controls 

### ISSUE THREAD

**Issue by jvierrajrv** [dotnet/core#2834]
The following works in WMF 5.1 and earlier:

**[system.drawing.Pont]'10,20'**

PowerShell 7 - fails to perform the coercion on all System.Drawing.Point assignments in WinForms controls (location,size, etc) fail to coerce the assignment.

This will break compatibility with earler scrips using System.Windows.Forms and System.Drawing.

Issue originally posted in PowerShell 7 "Issues" but was asked to move it here:

[https://github.com/PowerShell/PowerShell/issues/9815#event-2392059220](https://github.com/PowerShell/PowerShell/issues/9815#event-2392059220)

**Comment by karelz** [comment]
If it is not PowerShell problem, can you please create repro without PS? Eg in C#?

**Comment by karelz** [comment]
Oh, you probably meant to ask this: https://github.com/PowerShell/PowerShell/issues/9815#issuecomment-498736673
I recommend to create such specific issue, asking to bring back the attribute in CoreFx repo. O Will not nové this issue there as it is confusing, filed in terms of PowerShell, which is higher level concept and obscures what has to happen in lower levels.
I assume coercion is PowerShell term ...

**Comment by jvierrajrv** [comment]
> Oh, you probably meant to ask this: PowerShell/PowerShell#9815 (comment)
> I recommend to create such specific issue, asking to bring back the attribute in CoreFx repo. I will not move this issue there as it is confusing, filed in terms of PowerShell, which is higher level concept and obscures what has to happen in lower levels.
> I assume coercion is PowerShell term ...

"coercion" is a programmatic term or a reference to automatically forcing an object or value to a specific type.  It is similar to and a corollary of "cast".  It is an implicit cast during an assignment.  The basic PowerShell spec stated that PS would use coercion under the covers when parsing code.  Other languages and scripting systems have done this for decades; most notably VB.

Net Core is missing certain types that allow PowerShell to implement this. (see my post in the PS 7 issues).

**Comment by karelz** [comment]
Ok, can you then file an issue (in dotnet/CoreFx repo) stating which types are missing and then for motivation explain how PS uses them to achieve what it needs? (That will help us assess the option to modify PS to use different scheme instead)

**Comment by jvierrajrv** [comment]
> Ok, can you then file an issue (in dotnet/CoreFx repo) stating which types are missing and then for motivation explain how PS uses them to achieve what it needs? (That will help us assess the option to modify PS to use different scheme instead)

Ok - I give up.  The place that the error or deficiency surfaces is in PowerShell. PS blames it on Core. Core says no - go to fx, don't pass go, don't get a fix.

THis is one of the main issues of design-by-committee.   Everyone points at the next guy.  

For me the place that I started is the consumer of Net Core(FX) and they are the ones to field the issue.  Only a collaboration between PS development and the resource providers can sort this out.  

Of course both PS and Net groups will take a hit if no one chooses to take ownership.  I can wait.

**Comment by karelz** [comment]
@jvierrajrv I think you just misunderstood what I tried to say -- just to clarify, I am trying to help you here and route the issues efficiently.
The fact is that the bug report as is is going to get little attention (if any) in the place where it (maybe?) belongs - dotnet/corefx repo. If I didn't care, I would just move it there and then let it live its life. Because I care, I am trying to triage it and help the filer (you) to file something that has higher chance of action.
That filing requires higher-level stack knowledge (PowerShell), which we do not posses, therefore involving PS folks would be best. IMO it was a bit of mistake they sent you here at this stage - it was a bit premature.

This is not design-by-committee problem, this is a large stack with many, many components built on top of each other with thousands of developers building them. Not everyone can know everything in such large stack. Components need to communicate with each other in terms that resonate with the other side.
Imagine a large app like SharePoint would say "hey .NET team, we have this complicated thing - it is your interop bug" without additional details. What could we do? Go and learn SharePoint? Or is it more efficient to ask "OK, can you tell us what you have in mind? Can you please try to give us C# isolated repro" (e.g. to avoid us debugging a bug in SharePoint which would take us likely 100x more time than the SharePoint engineers who know the space.

**Comment by jvierrajrv** [comment]
I already posted over there.  Same issue.

**Comment by karelz** [comment]
I understand that you might feel dismissed and ignored. We will fix that. I am just asking for a little patience and perspective, because in large complex products, with multiple components involved, communication is key and it is extremely rarely ALWAYS perfect.
When communication is not working, it needs a fix and that is what we're working on - see my post on PS bug. It may take a while, some iterations, etc. Functioning orgs will get there. The key is to be able to adjust flow and fix communication/expectation gaps and also be prepared for mishaps and inefficiencies while trying to make them not very common. Imagine yourself being on the other side and give us some benefit of doubt and understanding please.

**Comment by jvierrajrv** [comment]
Karel - I know you are.  I am just pushing back a little.  I know this is a big multi-project and these things get up and running slowly.  Teme-to-team interaction has to be grown in as a project evolves.  I will say that the overall project has impressed the help out of me.  All groups have done more much faster than I expected.

I have worked on many large projects so I am very sensitive to what can go wrong and the difficulty of getting things going smoothly.  It is clear that there is a lot of excitement and the project looks like everyone is having fun.  When projects are fun they always work better.

Keep up the good work.  I am sure PS 7 will be excellent as it already is.  I may continue testing it and I will try to post better the next time I find something.

This actually started when someone asked in a forum why PS 7 wouldn't run some forms code.  I installed PS 7 and immediately found the issue.  The missing type will likely get built as I am sure that the WinForms guys are testing more.
