### ISSUE TITLE
Serialize RuntimeType in .NET Core issue

### ISSUE THREAD

**Issue by TempeBrennan** [dotnet/core#2849]
# .NetCore can not serialize RuntimeType

RuntimeType IsSerializable is marked as false.

# General
In .NET Framework, we use this code to serialize and works fine.
```
 BinaryFormatter bf = new BinaryFormatter();
 MemoryStream ms = new MemoryStream();
 bf.Serialize(ms, typeof(bool).GetType());
```

Now .NET Core will throw exception.
It seems RuntimeType is not support serialize anymore.

Is this a design?  Would you mind share your workaround?
Thanks a lot.

**Comment by svick** [comment]
From reading https://github.com/dotnet/corefx/issues/23213 and especially https://github.com/dotnet/corefx/issues/23213#issuecomment-378424343, this is intentional and is unlikely to change, because serializing `RuntimeType` is problematic.

That issue also has some discussion about workarounds, for example [this code](https://github.com/CXuesong/BotBuilder.Standard/blob/d77d50e/CSharp/Library/Microsoft.Bot.Builder/Fibers/NetStandardSerialization.cs).

**Comment by TempeBrennan** [comment]
Thank you so much.

**Comment by carlossanlop** [comment]
@bartonjs, @joperezr since you own System.Runtime.Serialization, can you assist with this question and confirm if it's intentional behavior or not?

**Comment by bartonjs** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/23213
