### ISSUE TITLE
Restore packages failed 

### ISSUE THREAD

**Issue by renecl** [dotnet/core#2886]
# Issue Title

After update Mac vs, can not restore packages
# General

After update to the latest version. of vs, packages can not restored. 
I updated sdk  to 2.2.300 

After that I upgrade vs to preview 8.2 and 3.0.100-preview6-012264
Still the same issue

running Mac VS 8.2 Preview (8.2 build 732)

looking at the error:
....../Caches/VisualStudio/8.0/MSBuild/25821_1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5) : error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.

could VisualStudio/8.0 be the wrong location?

**Comment by carlossanlop** [comment]
@jeffschwMSFT not sure if this issue belongs to your area. Can you please take a look? If it's not for your area, it sounds like it should belong to VS for Mac, but I'm not sure who owns that.

**Comment by jeffschwMSFT** [comment]
It is not my area, but adding @livarcocc and @mhutch

**Comment by livarcocc** [comment]
@renecl do you have a MSBuildSDKsPath environment variable set pointing to that location? That seems like a weird place for us to be looking for an SDK.

**Comment by mhutch** [comment]
The location is expected - since VSMac uses the global installation of MSBuild, it copies MSBuild into a cache folder so it can patch in SDKs bundled with extensions (and a few workarounds too) https://github.com/mono/monodevelop/blob/7613d8065f06c8fd11b97dd27c0200b3d7ff50d2/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngineManager.cs#L463

@renecl are you still seeing this error with newer previews? What do you see listed in **Preferences > Projects > SDK Locations > .NET Core**?

**Comment by renecl** [comment]
No I  don't see the issue and more after I change in de global.json:

"version" : "2.2.300"

**Comment by carlossanlop** [comment]
No follow up since July. Closing. @renecl feel free to ping us to reopen if you need more help.
