### ISSUE TITLE
Need to check if .net core is installed for Inno setup installer 

### ISSUE THREAD

**Issue by RaminderRandhawa91** [dotnet/core#2915]
For .Net frameworks it could be done easily by 
RegQueryDWordValue(HKLM, 'Software\Microsoft\NET Framework Setup\NDP\v4\Full', 'Release', regVersion);

How to check the same for .NET Core ?

**Comment by carlossanlop** [comment]
@dagood seems to be related to install/setup. Is it possible to check the .NET Core installation in the registry?

**Comment by dagood** [comment]
Yeah, here are a couple previous discussions:

https://github.com/dotnet/core-setup/issues/4904 mentions the plans for a registry key for 3.0, [install-locations.md](https://github.com/dotnet/designs/blob/master/accepted/install-locations.md).

https://github.com/dotnet/core-setup/issues/3381 is a bit old, but I still see recent versions in my registry where it mentions them:
`HKLM\SOFTWARE\WOW6432Node\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.NETCore.App`

Note that that path is for shared frameworks (runtimes), rather than SDK installs. The SDK keys are around the same place. I don't know of any official docs describing this, though. (Other than the source code, I suppose. 😄)

If you have any more questions about the runtime installers, feel free to ask in https://github.com/dotnet/core-setup directly.

**Comment by carlossanlop** [comment]
Closing since the question seems to be answered.
