### ISSUE TITLE
ResXResourceReader class in .NET Core 3.0 Preview 6 is unavailable

### ISSUE THREAD

**Issue by RengarsRice** [dotnet/core#2958]
# Issue Title
ResXResourceReader class in .NET Core 3.0 Preview 6 is unavailable
https://docs.microsoft.com/en-us/dotnet/api/system.resources.resxresourcereader?view=netcore-3.0
# General
We are building an app to help with management of .resx files in .NET Core.

The docs include the system.resources.resxresourcereader class in this version of .net core 3.0 preview 6, but in a console app using the VS 16.2.0 preview 3 IDE the class isn't there.

this is a snippet from the csproj file
PropertyGroup
    OutputType Exe OutputType
    TargetFramework netcoreapp3.0 TargetFramework
PropertyGroup

ItemGroup
    PackageReference Include="System.Resources.Reader" Version="4.3.0"
    PackageReference Include="System.Resources.ResourceManager" Version="4.3.0"
    PackageReference Include="System.Resources.ResourceWriter" Version="4.0.0-beta-22816" 
ItemGroup

**Comment by karelz** [comment]
Can you try Preview 7?
Did you try to compile the app? Note that the docs / IntelliSense can be missing.
@ericstj any pointers?

**Comment by RengarsRice** [comment]
it's there now if I add  <UseWindowsForms>true</UseWindowsForms> into the csproj file
feel free to close the issue

I have a question though, why is this class tied into windows forms? 
cheers
Joe

**Comment by ericstj** [comment]
It's tied to WindowsForms because that's where it is implemented: https://docs.microsoft.com/en-us/dotnet/api/system.resources.resxresourcereader?view=netframework-4.8

>ResXResourceReader Class
Namespace: System.Resources
Assembly: System.Windows.Forms.dll

There's been discussion in the past of moving the type down, but in its current form its rather coupled to WindowsForms and other technolgies (TypeConverter, BinaryFormatter) that require it to reside higher in the stack.

Question for you: how do you use ResXResourceReader in your application?   /cc @tarekgh @rainersigwald

**Comment by dwarfland** [comment]
i personally would love this being moved down so it could be used from a compiler tool-chain (www.elementscompiler.com) without requiring the compiler to depend on WinForms, on .NET Core.
