### ISSUE TITLE
Error response from daemon: driver failed programming external connectivity on endpoint [random name]

### ISSUE THREAD

**Issue by kylepeters** [dotnet/core#2972]
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/run-docker
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Everything went well in the tutorial up to the point where I tried to access the Docker image via web browser.  Then I received this...
C:\Users\petejk01\source\repos\MicroservicesTutorial\myMicroservice>docker run -it --rm -p 3000:80 mymicroservice
docker: Error response from daemon: driver failed programming external connectivity on endpoint tender_albattani (181bd8ce3ccabf0b3b863addbc7ecc3a054bc03e598b2fec4c8dfb2d4579dbfb): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:3000:tcp:172.17.0.2:80: input/output error.

I am assuming "tender_albattani" is the rnadom name that Docker assigns even though the tutorial uses the -t rather then the -n to name the image.

**Comment by carlossanlop** [comment]
@MichaelSimons I was told you'd be a good contact for docker related questions. Would you be able to help here? If not, do you know who would be a good contact?

**Comment by karelz** [comment]
@MichaelSimons ping? (3 weeks no response)

**Comment by kylepeters** [comment]
for @MichaelSimmons - FYI - I am not a good contact for Docker related issues for sure.  As far as my issue goes, it was a wash - I gave up.  I don't really need Docker - I just wanted to learn more about it, and what I learned is that is gets complicated.

**Comment by MichaelSimons** [comment]
I'm sorry for not responding sooner, I didn't see this issue.  This doesn't look like an issue specific to the tutorial, rather it is a general Docker for Windows issue.  I found this [issue](https://github.com/docker/for-win/issues/573) which has a number of people reporting a similar problem.  A couple suggestions I saw:

1. Ensure you are not running Docker with Experimental features enabled.
2. Try rebooting.
3. Try cleaning up all container instances.

The last two aren't great at all as they don't identify the root cause.  I would suggest chiming in on the Docker issue.

**Comment by carlossanlop** [comment]
2 weeks of inactivity. Closing issue. Feel free to ping us @kylepeters if you'd like to ask additional questions.
