### ISSUE TITLE
MySql.Data.EntityFrameworkCore - MySQL SELECT command denied to user

### ISSUE THREAD

**Issue by omriman12** [dotnet/core#3058]
I am running this simple query

SELECT * FROM db_a4b20a_reales.properties_residental;

It's working when using MySql.Data.MySqlClient, seems like the problem is with the MySql.Data.EntityFrameworkCore(8.0.16) connector

The error i am facing when using EFCore is:
SELECT command denied to user 'a4b20a_reales'@'{the server ip...}' for table 'properties_residental'

This is my connection str server=...;port=3306;user id=a4b20a_reales; password=***; database=db_a4b20a_reales; pooling=true; CharSet=utf8; Allow User Variables=True; Convert Zero Datetime=True; default command timeout=720

Same environment, works using MySql.Data.MySqlClient, fails with MySql.Data.EntityFrameworkCore(8.0.16).

I am using a 3th party webhostring and i don't permission to 'grant' extra permissions to my user, so this is an issue for me.

The thing is its working with mysqlclient, the problem only occures on EFCore connector

**Comment by carlossanlop** [comment]
@divega do you know who would be the best person to look into this? Is this a bug we should transfer to another repo?

**Comment by divega** [comment]
MySql.Data.* are from Oracle. I seriously doubt there is anything at the EF Core layer because EF Core doesn’t handle auth concerns: it just delegates them to the underlying ADO.NET provider (unless this particular EF Core provider for MySQL is doing something very unusual).

@omriman12 I see you mentioned it doesn’t repro using the ADO.NET provider but have you tried doing it with the ADO.NET provider running on the same hosting environment?

Besides contacting MySQL/Oracle for support, another thing you can try is an alternative provider like https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql.

**Comment by carlossanlop** [comment]
21 days of inactivity, question seems to be resolved. Closing.

**Comment by buster95** [comment]
I know why, see this post https://github.com/aspnet/EntityFrameworkCore/issues/18828 I'm looking for more information about if dbcontext scaffold without schema in mysql is possible
