### ISSUE TITLE
Does .NET Core support Raspberry Pi 4?

### ISSUE THREAD

**Issue by Penergy** [dotnet/core#3080]
I have seen the instructions for .Net Core on RPi 2 and RPi 3 from this link.
https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

I want to know whether .Net Core has the plan to support RPi 4. Because we are going to use RPi 4 later.

**Comment by danmosemsft** [comment]
@joperezr can answer that

**Comment by joperezr** [comment]
hello @Penergy, thanks for logging the issue. Yes, .NET Core does run on Raspberry Pi 4. 

In case your project involves controlling sensors or devices attached to the Raspberry Pi 4 using the GPIO header pins, head down to our new https://github.com/dotnet/iot repo where we are developing a .NET Standard 2.0 library that will support communication protocols (GPIO, SPI, I2C, PWM) with those pins in order to control other devices like motion and temperature sensors or motors.

**Comment by carlossanlop** [comment]
The question was answered 14 days ago so I'm closing it as resolved. @Penergy feel free to ping us to reopen it if you have additional questions.

**Comment by Carlos-Carreno-Berlanga** [comment]
@joperezr I tried to install .net Core on my Raspberry Pi 4 unsuccessfully. Can you shed some light how can we do it? Thanks in advance.

**Comment by joperezr** [comment]
Hello @Carlos-Carreno-Berlanga have you tried these instructions: https://github.com/dotnet/core/blob/rpi/samples/RaspberryPiInstructions.md

I usually follow those and it works, but another way you could also do it is by running the following in a terminal window:
```sh
wget https://download.visualstudio.microsoft.com/download/pr/3cb1d917-19cc-4399-9a53-03bb5de223f6/be3e011601610d9fe0a4f6b1962378ea/dotnet-sdk-2.2.401-linux-arm.tar.gz
mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-2.2.401-linux-arm.tar.gz -C $HOME/dotnet
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet
```

**Comment by Carlos-Carreno-Berlanga** [comment]
@joperezr  The first link did'nt work. When I tried to execute dotnet command, I got "Exec format error".
The second set of instructions worked like a charm. Thanks a lot, I really appreciate that!!

**Comment by joperezr** [comment]
Nice! do note that the second instructions I sent only work on during the lifetime of the terminal window, since you would be exporting to variables (DOTNET_ROOT and PATH) only in your current window. If you want to instead make this a permanent change so that they are available in all of your windows you can follow these instructions:

```
You can edit your shell profile to permanently add the commands. There are a number of different shells available for Linux and each has a different profile. For example:

Bash Shell: ~/.bash_profile, ~/.bashrc
Korn Shell: ~/.kshrc or .profile
Z Shell: ~/.zshrc or .zprofile
Edit the appropriate source file for you shell and add :$HOME/dotnet to the end of the existing PATH statement. If no PATH statement is included, add a new line with export PATH=$PATH:$HOME/dotnet.

Also add export DOTNET_ROOT=$HOME/dotnet to the end of the file.
```

**Comment by Carlos-Carreno-Berlanga** [comment]
@joperezr Thanks again for that.

**Comment by emiliano84** [comment]
it's really a pity that they're not going to support windows iot for pi4
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/8092f66a-2910-48dd-abd6-141c8487eec6/raspberry-pi-4-is-now-available-where-is-windows-iot

**Comment by vlyakh** [comment]
Hey guys. Any chance that pi4 would support sending the command to the USB connected printer from NET Core? I am interesting about Zebra printers and ZPL commands in particular
