### ISSUE TITLE
File conflict with /usr/bin/host in dotnet-runtime

### ISSUE THREAD

**Issue by onny** [dotnet/core#3139]
Hey,
I was packaging dotnet runtime prebuild binaries for Linux and had an issue with file conflicts. The dotnet binary is looking for the fxr folder in /usr/bin/host/fxr. The problem is, that /usr/bin/host is also a typical tool commonly installed via. the package bind-tools.
```
A fatal error occurred, the folder [/usr/bin/host/fxr] does not exist
```
Is it possible to configure a different runtime path?

Best regards,
Jonas

**Comment by omajid** [comment]
Hi! I am one of the packagers working on packaging .NET Core for Fedora and RHEL. I have not seen this error before. I do have both `dotnet` and `/usr/bin/host` (`bind-utils` in Fedora) installed. Can you please share more details about what you are doing?

In particular:

- What version of .NET Core is this?
- Where are you extracting the files?
- What is /usr/bin/dotnet? Is it a real file or a symlink to where the real dotnet SDK is installed?

**Comment by onny** [comment]
@omajid 
thanks for the replay. here is my package build file: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dotnet-runtime-bin
this might be a good hint to place the dotnet binary into /usr/share/dotnet-runtime and symlink it to /usr/bin ... so the working directory should be /usr/share/dotnet-runtime. i'll give that a try later

**Comment by omajid** [comment]
Yup, that should fix it: you dont want to split up anything out of the main `dotnet` directory. Otherwise everything will break. The `dotnet` binary mostly looks next to itself to find things. 

On Fedora, we install everything to `/usr/lib64/dotnet`. `/usr/bin/dotnet` is just a symlink to `/usr/lib64/dotnet/dotnet`.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dotnet-core-preview does it okay too:

```
cp -dr --no-preserve='ownership' dotnet host "${pkgdir}"/opt/dotnet/
...
install -Dm 755 "${srcdir}"/dotnet.sh "${pkgdir}"/usr/bin/dotnet
```

where [`dotnet.sh`](https://aur.archlinux.org/cgit/aur.git/tree/dotnet.sh?h=dotnet-core-preview) basically does `exec /usr/opt/dotnet/dotnet`.
