### ISSUE TITLE
[v3.x] Is there any way to find out what dlls are included in final exe file?

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/core#3170]
First of all thanks for v3.0, ability to generate single exe is huge feature, at least for me.

I used following command to generate single exe file for my project:
`dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true`

In following folder I got 321 dlls, ~80MB _and one exe file, less than 200KB and some other files_
`\bin\Release\netcoreapp3.0\win-x64`

The size of final exe file is ~55MB.

My project is not hello world, neither IDE, so 55MB is really big. _the size here is another issue and it's not related to this issue_

I really need to optimize the size, so I need to know used dlls, so maybe I could drop some of them. Is there any way to find out what dlls are included in final exe file? (the answer is that 321 dlls?)

**Comment by carlossanlop** [comment]
@nguerrera @livarcocc can you help with this issue?

**Comment by nguerrera** [comment]
PublishTrimmed=true will determine all of the dlls that are kept after trimming. PublishSingleFile=true will just put them into a single file.

So if you Publish with just PublishSingleFile=true, you can see which dlls are being kept in the publish folder. Make sure to clean the publish folder between publishes when switching these options as it will otherwise leave files from the previous option around.

Currently, the trimming is not very aggressive. See https://aka.ms/dotnet-illink

cc @sbomer @swaroop-sridhar

**Comment by sbomer** [comment]
I think you mean "if you Publish with just PublishTrimmed=true".

**Comment by nguerrera** [comment]
Yes, edited.

**Comment by dehghani-mehdi** [comment]
@nguerrera thank you for your great answer, now inside `publish` directory, I have my exe file and 240 dll files (~61MB) and also `refs` folder, contains 160 dll files (~5MB), what is `refs` doing here?

And another question, all I got in publish folder (`.dll`, `.pdb`, `.md`, `.json`) will be included in the final exe file? (when using `PublishSingleFile=true`), if so, is there any way to drop them? I think other files but dll are useless.

**Comment by nguerrera** [comment]
The refs folder is something that comes from a feature to preserve compilation context for runtime. Is this a web app? Otherwise that feature isn't on by default and even for web apps in 3.0, the refs shouldn't be pulled in unless you pulled in the runtime compilation feature. Did you turn on PreserveCompilationContext=true yourself otherwise?

The deps.json and runtimeconfig.json files are needed. I would have to look at what contributed the .md and .pdb.

If you can share the results of `dotnet publish /bl`, which will generate a binary log called msbuild.binlog, I can look at all the files that are published and why. See https://aka.ms/binlog before sharing this file to understand that it will disclose details about your project and environment

**Comment by swaroop-sridhar** [comment]
>> And another question, all I got in publish folder (.dll, .pdb, .md, .json) will be included in the final exe file? (when using PublishSingleFile=true), if so, is there any way to drop them? I think other files but dll are useless.

The PDB files are not included by default. Are you seeing this behavior? 
The PDB files are included only if  `<IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>` is set.

How did the `.md` files get included? These are likely additional content getting included in the project files. If so, you can add excludes for them via the `<ExcludeFromSingleFile>true</ExcludeFromSingleFile>` switch. 

Please see: https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md#build-system-interface

**Comment by dehghani-mehdi** [comment]
@nguerrera 
> Did you turn on PreserveCompilationContext=true yourself otherwise?

Yes

> Is this a web app? 

Kind of, I used razor as my template engine.

> If you can share the results of `dotnet publish /bl` ...

I'll asap!

@swaroop-sridhar 
> Are you seeing this behavior?

Yes!

The `<ExcludeFromSingleFile>true</ExcludeFromSingleFile>` looks promesing, I'll try it.

**Comment by carlossanlop** [comment]
@nguerrera can you please follow up?

**Comment by dehghani-mehdi** [comment]
After updating to .net core 3.0, the size of generated exe file increased to ~68MB, I could find anything about that.

**Comment by joperezr** [comment]
@dehghani-mehdi I'm not an expert in this area, but if you want to know exactly which files made it to the bundle, you can do a diagnostic log (by building like `dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true /flp:v=diag` and checking in the log what got passed to the "GenerateBundle" as the FilesToBundle parameter. This item will contain all of the files that were includded in the final exe.

**Comment by swaroop-sridhar** [comment]
There are a few ways to see what files are bundled within a single-file app:
1) Through diagnostic logs of the build, as @joperezr mentioned [above](https://github.com/dotnet/core/issues/3170#issuecomment-555761486) 
2) Run the single-exe, and examine the extraction directory (ex: `%TEMP%/.net/<app-name>/<id>/...`)
3) Use the [Extractor package](https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.NET.HostModel/Bundle/Extractor.cs) in the [HostModel library](https://www.nuget.org/packages/Microsoft.NET.HostModel/) to see the files in the bundle (`Extractor(<bundle-file>, <output-dir>).ExtractFiles()`)

**Comment by swaroop-sridhar** [comment]
Not sure if this issue needs any more work. If not, @dehghani-mehdi, please close the issue. Thanks.
