### ISSUE TITLE
hii everyone am new on GitHub and fresher programming learner and i installed visual stdio code on my mac book pro and i also installed c# and want to make make application in .net anyone please guide me how i can install .net core sdk i already tryed but i dnot how i can check its installed or hows its work 

### ISSUE THREAD

**Issue by sarbjee** [dotnet/core#3171]
# Issue Title

Be as descriptive as you can with your title.

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by scalablecory** [comment]
what have you tried so far? how doesn't it work?

**Comment by Jaguar-515** [comment]
> i already tryed but i dnot how i can check its installed or hows its work 
In the title, you said that you were on a Macbook.
This article should help check if .NET Core is installed on your Macbook: http://osxdaily.com/2015/05/25/list-all-applications-mac-os-x/

**Comment by sarbjee** [comment]
I am trying to create console application CSC(c sharp compiler) command is not found, what it means I successfully installed  .net core SDKs .

**Comment by Jaguar-515** [comment]
The csc (C# complier) command is included with the Developer Command Prompt for Visual Studio. Maybe check this article out? https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs

**Comment by 15134803783** [comment]
I am new coder.

**Comment by MythreyaK** [comment]
Hoping you don't take this the wrong way, a few pointers to keep in mind...
* You're more likely to get help when you demonstrate what you have already tried since an issue is easier to isolate when you show some output/errors to us.
* GitHub issues are more relevant to actual issues in the library or the program it is connected to, in this case, `.Net Core`. Questions along the lines of "How do I …" are better suited for StackOverflow. 
* You might also want to format your title and issue properly, as it can be easy for people reading the issue to assume it was an insincere attempt, a 'joke issue' (it's hard to convey them through just text!). 

Going step by step, 
* Get the SDK [here](https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-2.2.401-macos-x64-installer) and follow the instructions. 
* After the installer is done, reboot your system (as more often than not, it refreshes your environment) and check if it was successful by running `dotnet --info` in your terminal. If you get an output along the following lines, then you're good to go. 

    ```
    .NET Core SDK (reflecting any global.json):
     Version:   2.2.401
     Commit:    729b316c13
    
    Runtime Environment:
    OS Name:     Windows
    ...
    ```
* Get the C# extension for VSCode [here](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp).
* Follow the tutorials [here](https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/intro?initial-os=macos) and (then) [here](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code) to learn C#. 
* Make your own programs with C#!
* Profit!

If you encounter issues, kindly be more descriptive (what did not run, what did not work, what all you've tried, your OS version, and anything else the kind helpful members from the community ask of you) and the step that didn't work. 

Good Luck!

**Comment by leecow** [comment]
Closing as great getting started advice has been given.
