### ISSUE TITLE
Azure scale out and IHostedService

### ISSUE THREAD

**Issue by FWorren** [dotnet/core#3178]
What happens when adding singleton IHostedServices to DI when scaling out the app service to multiple instances in Azure? Will all new instances initiate a new hosted service each? Or will the hosted service run as a shared single process between the app instances?

**Comment by ltouro** [comment]
I think DI is local to the process. The WebJobs SDK, which plays nicely with App Service, has features to enable singleton feature for multi-process env. It uses a Storage Account to keep track (locks) of running processes

**Comment by scalablecory** [comment]
Hi @FWorren. You will get a separate process for every server scaled out to. So, you will have multiple instances of your class.

**Comment by codestellar** [comment]
Is it good to create IHostedService in Microservice Architecture? Or we should always prefer Azure Functions?
What if I want to scale out my app and still want only one IHostedService?

**Comment by ltouro** [comment]
@codestellar Can't see any problem in using IHostedService, as it is a convenient way to handle service threads and it plays nice with Kestrel. You don't need to use it with Azure Functions though, as the library will handle threads for you. 

To comply with Microservice Architecture principles, you may want to make sure all services hosted on the same process are part of the same bounded context. Otherwise, it may be better to go with multiple projects/processes.

For the scale out, each executing process will have its own IHostedService instance, which may not scale well if you can only have one running at time (it will scale only vertically, not horizontally). 

On the other hand, you may have "multiple processes behaving like a single one" using the Singleton attribute in Azure Functions (or WebJobs SDK). It is a way to scale horizontally without loosing the ability of having only one "piece of code" being executed at given time.
