### ISSUE TITLE
ColorTranslator exists in both System.Drawing.Primitives and System.Drawing.Common.

### ISSUE THREAD

**Issue by lucapivato** [dotnet/core#3244]
Since ColorTranslator exists in both System.Drawing.Primitives and System.Drawing.Common it seems to be impossible to use it when importing the System.Drawing.Common package.

I can't find any way to differentiate the two. It's probably something easy that escapes me.

How to reproduce:

- Add the System.Drawing.Common nuget package.
- Try to use ColorTranslator.

Result:

Won't compile.

Resolution:

None I could find.

**Comment by safern** [comment]
@lucapivato thanks for reporting this issue. I'm pretty sure this is because you're using an outdated version of the `System.Drawing.Common` package. We moved `ColorTranslator` type into `System.Drawing.Primitives` for `.NET Core 3.0` but in order for this to be reflected when using `.NET Core 3.0` you also need to use the latest version of `System.Drawing.Common` unfortunately.

Could you please try it with `System.Drawing.Common` version `4.6.0-preview8.19405.3` ?

I will close the issue and wait for confirmation as I didn't see the issue with this version. Could you please confirm that and if it still happens re-open?

**Comment by lucapivato** [comment]
Thanks works. I was using the latest stable, now with the latest 4.6.0-preview it's all good.

**Comment by GeoMarkou** [comment]
In case this helps anyone else: I got this error after removing a NuGet package (`Microsoft.Extensions.Caching.StackExchangeRedis (6.0.14)` of all things). I resolved it by manually adding a reference to `System.Drawing.Common (6.0.0)`.

**Comment by MyInviteacc** [comment]
May someone tell me exactly how to solve this error?
The type 'ColorTranslator' exists in both 'System.Drawing.Common, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'System.Drawing.Primitives, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by 0brine** [comment]
> May someone tell me exactly how to solve this error? The type 'ColorTranslator' exists in both 'System.Drawing.Common, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'System.Drawing.Primitives, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Install the newest NugetPackages
