### ISSUE TITLE
Tutorial deployed to Azure doesn't seem to work

### ISSUE THREAD

**Issue by cnolewajka** [dotnet/core#3246]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

I managed to deploy to Azure as the tutorial guides, but I cannot connect and actually test my service. I am a newbie to Azure, and not an expert in infrastructure. Nonetheless, tried to see and verify the resources, load balancing, routing tables, etc, and can't spot the problem. 

The browser reports "the site can't be reached" and I don't get the result when trying to browse for:
http://13.91.37.132/api/Values

The image worked on the desktop docker. The command:
kubectl get service mymicroservice --watch

seems to produce correct data.

I would be grateful for some help around this.

**Comment by rowanmiller** [comment]
@carlossanlop - I'll find the right person to help with this

**Comment by rowanmiller** [comment]
Assigning to @shirhatti who is going to focus on this area of the product now

**Comment by carlossanlop** [comment]
@shirhatti ping. No response since September 5th. Can you please take a look?

**Comment by mairaw** [comment]
@shirhatti can you look at this issue?

**Comment by mairaw** [comment]
@nishanil @sughosneo is this something you can help with?

**Comment by sughosneo** [comment]
Hi @cnolewajka, thank you for reaching out and sorry for the long delay.

Could you please try to validate the results of the following steps?

`STEP -1:` Are you able to see the external IP address of the `LoadBalancer` service? For e.g :

![image](https://user-images.githubusercontent.com/13281246/128464184-797f181e-36d0-4576-81f7-0da262f81b52.png)

`STEP-2:` If yes, then open a browser and browse the URL `http://[YOUR EXTERNAL IP ADDRESS]/WeatherForecast`? You should see the result from the API. Because this is the service URL.

![image](https://user-images.githubusercontent.com/13281246/128464811-c7afe794-db7c-413e-b9ca-6f7cccd1fc37.png)

`STEP-3:` Only applicable if `STEP-2` doesn't work. Check if the deployed pod is running? Do that by using the command `kubectl get pods`?

![image](https://user-images.githubusercontent.com/13281246/128464205-049acc6c-8310-4bf4-8605-66cf5ea26b93.png)

`STEP-4:` In `STEP-3`, if you see any issue, then you can collect the pod logs by using the command `kubectl logs <POD_ID>` and share it here for further investigation.
> NOTE: In the above screenshot the `POD_ID` is `mymicroservice-9944bfccb-rw6ks`

**Comment by cnolewajka** [comment]
Hi,

I greatly appreciate the reply and following up, but that was 2y ago.
I don’t even have the project anymore, and I totally don’t remember how to reproduce the issue.

Let’s just close the case. I am not interested anymore in following up.

Kindest regards,
Cezary Nolewajka
