### ISSUE TITLE
Install 2.2.401 SDK and CLI is missing

### ISSUE THREAD

**Issue by mvarga6** [dotnet/core#3333]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.401
Operating System: Linux Ubuntu 18.04 - x64

I installed the SDK as instructed [here](https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.401) 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  dotnet-sdk-2.2
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/92.0 MB of archives.
After this operation, 248 MB of additional disk space will be used.
Selecting previously unselected package dotnet-sdk-2.2.
(Reading database ... 222020 files and directories currently installed.)
Preparing to unpack .../dotnet-sdk-2.2_2.2.401-1_amd64.deb ...
Unpacking dotnet-sdk-2.2 (2.2.401-1) ...
Setting up dotnet-sdk-2.2 (2.2.401-1) ...
This software may collect information about you and your use of the software, and send that to Microsoft.
Please visit http://aka.ms/dotnet-cli-eula for more information.
Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

Configuring...
--------------
A command is running to populate your local package cache to improve restore speed and enable offline access. This command takes up to one minute to complete and only runs once.
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
```

and immediately after install I try `dotnet --version` and get met with

```
$ dotnet --help

Command 'dotnet' not found, but can be installed with:

sudo snap install dotnet-sdk
```
Taking a look at what got installed, 
```
$ ls /usr/share/dotnet/
sdk
```
(notice there's not dotnet binary there to run)

What is going on and why wont a `sudo apt-get purge dotnet-sdk-2.2  && sudo apt-get install dotnet-sdk-2.2` fix a bad install (if something got broken during installation)

Any help or experience on the matter would be greatly appreciated.

**Comment by dagood** [comment]
The `dotnet-sdk-2.2` package only contains the SDK, it depends on packages for the `dotnet` host, the runtime, etc. It looks like the purge and reinstall only affects the SDK package itself, not its dependencies.

I'm able to repro in a Docker container by installing `dotnet-sdk-2.2`, deleting `/usr/bin/dotnet` and `/usr/share/dotnet`, then running `sudo apt-get purge dotnet-sdk-2.2 && sudo apt-get install dotnet-sdk-2.2`. Maybe something like this happened to you? I spotted this line in the purge that may help you recover your machine:

```
The following packages were automatically installed and are no longer required:
  aspnetcore-runtime-2.2 dotnet-host dotnet-hostfxr-2.2 dotnet-runtime-2.2
  dotnet-runtime-deps-2.2 krb5-locales libgssapi-krb5-2 libicu60 libk5crypto3 libkeyutils1
  libkrb5-3 libkrb5support0 liblttng-ust-ctl4 liblttng-ust0 liburcu6
```

Everything before and including `dotnet-runtime-deps-2.2` needs to be reinstalled too because they place the missing files and symlink. (`krb5-locales` and further are Ubuntu packages that .NET Core depends on.) I'm not familiar with the best way to do it--in my case it says `Use 'sudo apt autoremove' to remove them.`, but it might be different for you.

/cc @leecow

**Comment by leecow** [comment]
Closing due to the thread getting stale. If you're still having trouble, please re-open this issue.
