### ISSUE TITLE
No provider of 'aspnetcore-runtime-2.2.0-1' found.

### ISSUE THREAD

**Issue by unitrix0** [dotnet/core#3362]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/opensuse/runtime-2.2.0
Operating System: Linux openSUSE Leap - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I've tried to install the run time on opensuse leap 15 but when I ran the command: `zypper update` it told me:

> Building repository 'packages-microsoft-com-prod' cache ................................................................................................[done]
> Loading repository data...
> Reading installed packages...
> 
> The following package update will NOT be installed:
>   libgstgl-1_0-0
> 
> Nothing to do.

and the `zypper install aspnetcore-runtime-2.2.0-1` command told me:

> Loading repository data...
> Reading installed packages...
> 'aspnetcore-runtime-2.2.0-1' not found in package names. Trying capabilities.
> No provider of 'aspnetcore-runtime-2.2.0-1' found.
> Resolving package dependencies...
> 
> Nothing to do.

**Comment by carlossanlop** [comment]
@dagood this seems to be an install issue. Do you know what could be happening here?

**Comment by dagood** [comment]
Thanks for the report.

The `zypper update` output doesn't seem like it'd affect the results at first glance, but the dot.net page has a bad `zypper install` command. The part of the package name that specifies a specific version is incorrect: the last bit of the string should be `2.2-2.2.0-1`, not `2.2.0-1`. I've filed an internal issue to get that fixed. For now, if you need a specific version, you can make that tweak in your install command.

However, `2.2.0` is way out of date! To get the latest, go to https://dotnet.microsoft.com/download/linux-package-manager/opensuse/runtime-current.

The install command there is simpler since you are grabbing the latest version, and it's correct:

```
sudo zypper install aspnetcore-runtime-2.2
```

**Comment by unitrix0** [comment]
Thank you for your response. In the meantime I used the Software Management in YaST and thankfully the source is registered there too and it had led me automatically to the latest version.
