### ISSUE TITLE
C:\Local Disk D_8282019143\Temp\myMicroservice>docker build -t mymicroservice . Sending build context to Docker daemon   1.16MB Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build 2.2: Pulling from dotnet/core/sdk no matching manifest for windows/amd64 10.0.16299 in the manifest list entries

### ISSUE THREAD

**Issue by akashchavan4691** [dotnet/core#3369]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by akashchavan4691** [comment]
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src
COPY myMicroservice.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "myMicroservice.dll"]

**Comment by akashchavan4691** [comment]
![image](https://user-images.githubusercontent.com/22362223/64914498-c43aaf00-d770-11e9-833e-0c20fd9fe04f.png)

**Comment by scalablecory** [comment]
@shirhatti any ideas?

**Comment by shirhatti** [comment]
Looks like you're on Windows 10 Fall Creators Update/ Windows Server, v1709 OS running under the Windows Docker daemon.

Try pulling the specific images `mcr.microsoft.com/dotnet/core/sdk:2.2-nanoserver-1709` and `mcr.microsoft.com/dotnet/core/aspnet:2.2-nanoserver-1709` instead.

@MichaelSimons Is this expected behavior?

**Comment by shirhatti** [comment]
As an aside, I'd recommend updating your Windows version as it's woefully out of date

**Comment by MichaelSimons** [comment]
This is the expected behavior.  NanoServer 1709 is EOL therefore .NET no longer produces 1709 based images.  The `nanoserver-1709` suffixed tags should work as @shirhatti suggested but please keep in mind they are based on an EOL OS and are therefore vulnerable.  See this [announcement](https://github.com/dotnet/dotnet-docker/issues/1041) for more details.

**Comment by scalablecory** [comment]
Closing stale issue; @akashchavan4691 feel free to reopen if you think there's more to discuss.
