### ISSUE TITLE
Error: An assembly specified in the application dependencies manifest not found Package:Newtonsoft.Json when deploying .Net core 2.2

### ISSUE THREAD

**Issue by shubhamjainy** [dotnet/core#3405]
I am deploying a .Net core 2.2 console application using self contained deployment and using some 3rd party libraries like(**log4net** and **Newtonsoft.Json**). The application is working fine on the system it is developed but not working when deployed to any other system. The below error displays:

_C:\Users\shubhamjain\source\repos\Collect\Collect\bin\Release\netcoreapp2.2\win-x64>Collect.exe_

**Error: An assembly specified in the application dependencies manifest (Collect.deps.json) was not found: package: 'Newtonsoft.Json', version: '12.0.2' 
path: 'lib/netstandard1.3/Newtonsoft.Json.dll'**

I have tried the below things:

1. Changing the .Net core version from 2.1 and 2.2
2. changing the version of Newtonsoft.Json from nuget
3. Updating visual studio 2019

Nothing worked but when I looked to a file ("**Collect.runtimeconfig.dev.json**" in path _C:\Users\shubhamjain\source\repos\Collect\Collect\bin\Release\netcoreapp2.2\win-x64_) and change the **shubhamjain** with the deployed system username, everything works fine.

**Now, What I observe that Newtonsoft.Json is depends on file (.runtimeconfig.dev.json) and in order to make it work I have to change the username in this file.**

Is there any way to resolve this automatically? 

Collect.runtimeconfig.dev.json :

`{
  "runtimeOptions": {
     "additionalProbingPaths": [
        "C:\\Users\\shubhamjain\\.dotnet\\store\\|arch|\\|tfm|",
        "C:\\Users\\shubhamjain\\.nuget\\packages",
        "C:\\Program Files\\dotnet\\sdk\\NuGetFallbackFolder" ]
  }
}`

**Comment by carlossanlop** [comment]
@joperezr do you know what could be causing this?

**Comment by joperezr** [comment]
how are you publishing? I would try doing the following in your case: `dotnet publish -r win-x64` from directory `C:\Users\shubhamjain\source\repos\Collect\Collect`, which should put everything that you will need inside a publish folder including the 3rd party dependencies. Deploying that publish folder into another win-x64 machine should then just work as expected.

**Comment by shubhamjainy** [comment]
@joperezr , I am publishing with visual studio 2019 and that's put all the 3rd party dependencies in the publish folder. I can see **newtonsoft.Json.dll** inside publish folder and has version **12.0.2**. But deploying the code into another win-x64 machine does not work. Is there any difference in publishing with visual studio or with the above mentioned command.

**Comment by shubhamjainy** [comment]
@joperezr , I have one more query, I can see the executable file (collect.exe) on two different folders, publish and win-x64. Which executable file should I execute after deploying to another machine? I was trying to execute the one from win-x64 folder which results the mentioned issue. but when I execute the executable (collect.exe) from publish folder, everything works as expected.  please clarify

**Comment by joperezr** [comment]
> Is there any difference in publishing with visual studio or with the above mentioned command.

This part I'm not 100% sure. I would imagine that VS should internally just call the same command behind the scenes but I'm not sure if that is what is happening. If you can repro this problem where it is working using the command I suggested, but it doesn't work using VS publish, I would suggest logging a bug into VS Feedback portal.

Regarding your other question: when you call publish, you want to only use the output inside the publish directory. So what you would deploy in a different machine is all the content inside the publish folder, and you would run the collect.exe from within the publish folder. The other collect.exe you are seeing is the one produced by the regular build output, so it is not the one from the set of assemblies that the publish command produces. Think of everything under the win-x64 folder (except the publish folder) as the build output that MSBuild generated from your code, and everything under the publish folder what you need to have (so this includes build output + your dependencies) in order to run your app in a different machine.

**Comment by shubhamjainy** [comment]
@joperezr Thank you for your help. I have another query that if i had to deploy the application in different OS say **win-x64**, **osx-x64** and **linux-x64**. Then First I have to create profile for each OS and publish them. After publishing all 3 profiles, the only thing I have to do is to use the content of publish folder only and the executable inside the publish folder will execute in all the different OS.

**Comment by joperezr** [comment]
In .NET Core there are 2 different kinds of deployments:
- Framework-Dependent Deployments: The advantage here is that you only have to publish once using `dotnet publish` command, and the contents of the publish folder will be able to run on different platforms (like win-x64, osx-x64, linux-x64, etc.). That said, in order to be able to run this app on those different platforms, you will need .NET Core to be installed on those machines.
- Self-Contained Deployments: The advantage with this is that you don't require .NET Core to be installed on the machine where you want to run, since you are carrying .NET Core framework with your app. That said, the disadvantage is that you would have to publish to all the different OSes where you want to run like `dotnet publish -r win-x64` and t hen `dotnet publish -r linux-x64`. These commands will generate two different publish folders, each one for a different platform.

You can learn more about all of the .NET Core deployments here: https://docs.microsoft.com/en-us/dotnet/core/deploying/

Given that this issue was just a question, I will go ahead and close it since it has been answered. That said, feel free to re-open if you have any follow up questions and we will gladly help.
