### ISSUE TITLE
.NET Core 3.0.0

### ISSUE THREAD

**Issue by vivmishra** [dotnet/core#3430]
[Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0.0/3.0.0.md)
[Download](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0.0/3.0.0-download.md)

**Blog posts**

[.NET Core](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0)
[ASP.NET Core](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0)
[EF Core](https://devblogs.microsoft.com/dotnet/announcing-ef-core-3-0-and-ef-6-3-general-availability)

Please report any issues you find with .NET Core 3.0.0, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/aspnet/Home) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for Winforms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by scalablecory** [comment]
🎉🎉🎉🎉🎉

**Comment by 80dB** [comment]
This file is currently not updated with the 3.0.0 release information:
https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json
( https://github.com/dotnet/core/blob/master/release-notes/releases.json )

This file is used by Azure DevOps Image Generation scripts to create the hosted Azure DevOps build agents. Because it's missing the .NET Core 3.0 release information it's not possible to build .NET Core 3.0 apps using the hosted Linux agents in Azure DevOps (because it's not installed :)).

You get:
The current .NET SDK does not support targeting .NET Core 3.0.

**Comment by scalablecory** [comment]
@80dB please open a separate issue so we can track that getting fixed.

**Comment by jtorjo** [comment]
Please excuse my incredibly noob question - how do I use .netcore 3 for UWP ?
Do I just nuget install Microsoft.NETCore.Platforms ?

**Comment by vivmishra** [comment]
@tommcdon

**Comment by dpaulino** [comment]
I'm curious to know how I could update a uwp app to .netcore 3.0 as well. Anyone know?

**Comment by mairaw** [comment]
Closing given 3.0 has reached end of line. If the UWP upgrade is still an issue, do you mind opening a new issue on the repo? Thanks.
