### ISSUE TITLE
Unable to locate the package

### ISSUE THREAD

**Issue by deveshreddy** [dotnet/core#3437]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu14-04/sdk-current
Operating System: Linux Ubuntu 14.04 - x64

E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'

Soource : https://dotnet.microsoft.com/download/linux-package-manager/ubuntu14-04/sdk-current
I ran into this error in the final step of installing. I am currently running on Linux mint 19.2 . It supports all apps which are supported in linux ubuntu 14.04.

**Comment by dagood** [comment]
.NET Core 3.0 doesn't support Ubuntu 14.04: https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md. Have you tried using a later Ubuntu repository that .NET Core 3.0 supports and Linux Mint 19.2 is compatible with?

I'm filing an internal issue about the 14.04 dropdown entry being there--it probably shouldn't be because it's not a valid selection for 3.0. Arguably we should have a direct entry for Linux Mint, I believe that's tracked over at https://github.com/dotnet/core/issues/2576.

**Comment by dagood** [comment]
The change to remove the Ubuntu 14.04 entry from the dropdown is merged and deployed now.
