### ISSUE TITLE
The 3.0 SDK is not available on rhel8 

### ISSUE THREAD

**Issue by pepone** [dotnet/core#3491]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel8/sdk-3.0.100
Operating System: Linux RHEL 8 - x64

The 3.0 SDK is not available on rhel8 

```
 sudo yum list dotnet-sdk*
Updating Subscription Management repositories.
Last metadata expiration check: 0:02:17 ago on Thu 26 Sep 2019 02:17:43 PM UTC.
Available Packages
dotnet-sdk-2.1.x86_64                                     2.1.509-1.el8_0                                 rhel-8-for-x86_64-appstream-rpms
dotnet-sdk-2.1.5xx.x86_64                                 2.1.509-1.el8_0                                 rhel-8-for-x86_64-appstream-rpms
[vagrant@el8-dev-3da0ee0e ~]$ uname -a
Linux el8-dev-3da0ee0e 4.18.0-80.el8.x86_64 #1 SMP Wed Mar 13 12:02:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by KoteshBoda** [comment]
@leecow

**Comment by omajid** [comment]
cc @Bob-Davis

**Comment by RheaAyase** [comment]
Hello there,

3.0 will not be available in RHEL 8.0 due to its minor version coming to an end with the upcoming release of RHEL 8.1, which will contain dotnet3.0

There are various RHEL lifecycle policies in play that affect these decisions as dotnet packages ship within ApplicationStream, you can read all about those at https://access.redhat.com/support/policy/updates/errata#RHEL8_Life_Cycle

Should you have any questions please feel free to ask =)

**Comment by RheaAyase** [comment]
In the meantime perhaps a RHEL7 based container with 3.0 might be of interest? These should be available a little bit earlier. Or for development purposes Fedora is the closest thing to RHEL8 with the last 3.0 preview available [via copr.](https://copr.fedorainfracloud.org/coprs/g/dotnet-sig/dotnet-preview/)

**Comment by pepone** [comment]
Thanks @RheaAyase that sounds great, we use RHEL8 in our CI environment among other distributions, so it is fine for us to wait for 8.1. We are already testing 3.0 in a few other platforms.
