### ISSUE TITLE
Ubuntu 16.04 3.0.0 release native symbols missing

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/core#3494]
# Issue Title

Ubuntu 16.04 3.0.0 release native symbols missing

# General

The 3.0.0 Ubuntu 16.04 release stripped symbols from the native binaries. (They were included in the preview9 release).

The download instructions do not contain the information to locate and install the needed symbol packages. https://dotnet.microsoft.com/download/dotnet-core/3.0#sdk-3.0.100

The normal debian packaging naming convention would suggest the symbols should be available in something like:

- `dotnet-sdk-3.0-dbgsym`
- `dotnet-sdk-3.0-dbg`
- `dotnet-runtime-3.0-dbgsym`
- `dotnet-runtime-3.0-dbg`

None of these packages are found.

This limits developers ability to profile and debug dotnet.

/cc @dagood

**Comment by dagood** [comment]
> (They were included in the preview9 release).

This is surprise to me, they're always meant to be stripped in our official builds, for size reasons. An infra error in CoreCLR, CoreFX, or Core-Setup could explain this, but would need to know which binaries were affected.

---

The supported way to get Microsoft build symbols is through the symbol servers using the `dotnet-symbol` tool: https://github.com/dotnet/symstore/tree/master/src/dotnet-symbol. We don't build dbg packages and no longer create the symbol package archive zips.

I'm not able to find a pointer to `dotnet-symbol` in the 3.0 notes or download page... thought I saw one there at some point. I do think we need some documentation about the symbol servers, since it's AFAIK a very unusual approach on Linux/macOS. @leecow @vivmishra 

(I'd consider this issue tracking making this sufficiently documented/discoverable. Whether that goes all the way to `dot.net` or just the release notes markdown doc, I'm not sure.)

/cc @mikem8361

**Comment by sdmaclea** [comment]
Symbols were in `3.0.0-preview9-19423-09/libcoreclr.so`

**Comment by sdmaclea** [comment]
>  AFAIK a very unusual approach on Linux/macOS.

👍 If we are trying to be consistent, we should probably reconsider this for 5.0.

**Comment by dagood** [comment]
> Symbols were in `3.0.0-preview9-19423-09/libcoreclr.so`

Might be worth figuring that out to make sure there isn't some flakiness that may repro. If you could file an issue on CoreCLR (and any info about other versions having/not having symbols if you have it) that would be appreciated.

There was a symbol stripping problem fixed with https://github.com/dotnet/coreclr/pull/22083, but that was waay back.

> 👍 If we are trying to be consistent with our targeted distros, we should probably reconsider this for 5.0.

I agree, this would also make the Microsoft build more consistent with source-build.

(I think we'd need to continue having them up on the symbol server since that's consistent with the Windows way, though.)

**Comment by dagood** [comment]
Closing: main concern is answered, and https://github.com/dotnet/core-setup/issues/8356 and https://github.com/dotnet/coreclr/issues/26946 are filed for followup.
