### ISSUE TITLE
Missing libicu?

### ISSUE THREAD

**Issue by ThalesVC** [dotnet/core#3500]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/opensuse15/sdk-current
Operating System: Linux openSUSE 15 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

As the message says, I'm trying to install dotnet.sdk in OpenSUSE.  My system is tumbleweed and not 15, which has no guide in the site - its ok, i think it will be the same process to OpenSUSE 15. 
I don't know if my system has no libicu or the dotnet.sdk doesn't recognize him. I have installed libicu-devel and others libicu libraries. However, the error persist.   See the photo above:
![b](https://user-images.githubusercontent.com/35850530/65820403-bec47680-e1fe-11e9-80e4-4eb755f27853.png)

**Comment by dagood** [comment]
In the future, can you please post the text instead of the screenshot? (You can format with code fences for monospace readability: three backticks on a new line above and below the text you want to format.)

---

This is unfortunate... in the past, packages like `libicu-suse64_2` had a "provides" clause for `libicu`, so the dependency `dotnet-runtime-deps` has on `libicu` was resolved by having that package installed. ("Provides" dependencies are a little hard to dig up, IIRC they work with `zypper install` but don't show up in `zypper search`.) This "provides" clause allowed the same RPM package to work on 15 and Tumbleweed. 

For now, I believe you can safely ignore the dependency (solution 2) because you have the `libicu-suse64_2` package installed.

It looks like the "provides" removal was an intentional change by the package's maintainers: https://build.opensuse.org/request/show/724944.

> Remove old obsoletes/provides for migration from very old
> 6+  products, as they break our shared library policy

Looks like we will have to start producing a separate package for Tumbleweed now. 😕 Related issue about being more specific to each distro: https://github.com/dotnet/core/issues/2576.

/cc @leecow

**Comment by dagood** [comment]
> Looks like we will have to start producing a separate package for Tumbleweed now. 😕 Related issue about being more specific to each distro: #2576.

I forgot that we actually don't support openSUSE Tumbleweed, only Leap versions. https://github.com/dotnet/core-setup/issues/5662#issuecomment-479651127. I don't anticipate making a new package for Tumbleweed.

That said, manually making sure you have the dependencies installed and using the Leap packages with broken dependencies will likely continue to work, and you can also get the Snap or install from binaries. https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md
