### ISSUE TITLE
Cannot run my project on Fedora 30

### ISSUE THREAD

**Issue by Mebus** [dotnet/core#3505]
Hallo, 

on Fedora 30 I have got this problem after migrating my project from .NET core 2.2 to 3.0:

```
→ dotnet run
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/lib64/dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
```

This is my .csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

</Project>
```

Mebus

**Comment by omajid** [comment]
Hi! I am one of the maintainers of [the Fedora DotNET SIG packages](https://copr.fedorainfracloud.org/coprs/g/dotnet-sig/dotnet/) for .NET Core. The `/usr/lib64/dotnet` path makes me suspect that you had installed the 2.2 packages from there. I know we haven't release packages for .NET Core 3.0 there. Can you confirm that you had installed 2.2 packages from the Fedora copr repo? How did you install .NET Core 3.0?

If you are using the [Microsoft repository](https://dotnet.microsoft.com/download/linux-package-manager/fedora30/sdk-current) for 3.0, I think the fastest fix would be:

    $ sudo dnf remove '*dotnet*'
    $ sudo dnf install dotnet-sdk-3.0

I also reccomend disabling the Fedora DotNET SIG repository if you are using packages from the Microsoft repository. Mixing them is probably not a good idea because they expect things in different locations.

**Comment by Mebus** [comment]
Ok, good hint:

I disabled the repository `/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_dotnet-sig:dotnet.repo` and reinstalled dotnet.

Now if I do `dotnet run`I get this:

```
→ dotnet run
A fatal error occurred. The required library libhostfxr.so could not be found.
```

If I do then:

```
export DOTNET_ROOT="/opt/dotnet"
```

My program runs. Although this workaround works... is there a proper solution for this?

Mebus

**Comment by Mebus** [comment]
`/opt/dotnet` doesn't even exist :scream: 

Mebus

**Comment by RheaAyase** [comment]
Well, you can now get the [fedoraloves.net](http://fedoraloves.net) packages, from our Fedora copr repository. It's usually worth waiting a few days than struggling with the updates, etc. =)

3.0 was exceptionally late for all the linux maintainers, that situation hopefully won't repeat again.

**Comment by Mebus** [comment]
Great! Thank you. 

I did this:

https://developer.fedoraproject.org/tech/languages/csharp/dotnet-installation.html

and now it just runs :-)
