### ISSUE TITLE
.NET Core 3.0. Framework-dependent deployments

### ISSUE THREAD

**Issue by vitaaaly91** [dotnet/core#3512]
.NET Core 3.0 builds and publish framework-dependent executables application by default.
How can I publish my application framework-dependent deployments?

**Comment by scalablecory** [comment]
You should be able to just copy the bin folder to wherever you want.

Or, did you mean you're interested in a self-contained deployment that is *not* dependent on the framework?

**Comment by vitaaaly91** [comment]
@scalablecory I need to run my application on different platforms: Windows, Linux etc.
There are several .Net Standard projects in my solution. When I published them using .Net Core SDK 2.2, a runtime directory was created. Platform specific assemblies are found in this directory:
![image](https://user-images.githubusercontent.com/55979571/65907794-b5d5cf80-e3cd-11e9-8883-136c02b900da.png)
But when I use .Net Core SDK 3.0, this directory is not created.
So I want to get these platform specific assemblies.

**Comment by per-samuelsson** [comment]
I guess this is about what can be read from the table early in this article:

https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli#framework-dependent-deployment

It kind of confuses me too.

In pre-3.0, doing `dotnet publish -c Release` would produce a FDD. Then, starting with 3.0, it instead produces a FDE.

Since FDE's are platform-specific, and FDDs x-plat, that's a pretty major change.

Question I have: how do I even produce a FDD in 3.0? Is it as simple as creating a FDE and just dropping (or ignoring) the executable being produced? Any way, this should be made clear in the docs.

**Comment by dagood** [comment]
Related issue: https://github.com/dotnet/cli/issues/12716. Quoting https://github.com/dotnet/cli/issues/12716#issuecomment-535331850:

> Your app will still work as a FDD app. You can still run `dotnet program.dll`. The `program.exe` that is in the output can simply be ignored.
> 
> The type of app that gets built has not been changed.
> 
> If you don't want the exe generated because you don't want to pay the file cost for it, you can turn that off by setting `<UseAppHost>false</UseAppHost>`.

---

I'm not familiar with those runtime directories from 2.2. It seems like they may be a red herring, for example, maybe they're not required for your 3.0 app to run anymore due to some cross-platform improvements. A minimal project that reproduces the issue would be useful in this situation.

**Comment by per-samuelsson** [comment]
@dagood 

Thanks for that. Makes it a lot clearer. Than I have nothing more to ask. Cheers.

**Comment by vitaaaly91** [comment]
@dagood This project reproduce the issue:
[TestRuntimeDirectory.zip](https://github.com/dotnet/core/files/3679628/TestRuntimeDirectory.zip)

Try publishing this project first with .Net Core 2.2, and then with .Net Core 3.0.
The assembly set is very different.
For example, where is the assembly System.Private.ServiceModel.dll ?
In .Net Core 2.2 it is in directories runtimes/unix and runtimes/win.

**Comment by dagood** [comment]
Hi @vitaaaly91, sorry for the delay. The behavior does repro for me, however it's unclear to me what problem/error it results in. Why is it important to have those `runtime` files in a `netstandard2.0` project's publish directory?

(If I try changing it to a `netcoreapp2.2` project, the `runtimes` directory does show up when I `dotnet publish`.)

**Comment by vitaaaly91** [comment]
@dagood  Unfortunately, I cannot change it to a netcoreapp2.2 project in my solution, since this project is used in projects .Net Core and .Net Framework.
This is important because my host project throws an exception at startup with the message that the assembly System.Private.ServiceModel.dll was not found.
This problem appeared when switching to the .Net Core SDK 3.0.

**Comment by carlossanlop** [comment]
23 days with no response, closing. Feel free to reopen if you'd like to continue the conversation, @vitaaaly91 .
