### ISSUE TITLE
Group Permission of produced binaries to be at least Read+Execute

### ISSUE THREAD

**Issue by am11** [dotnet/core#3559]
On Linux, the file permission of produced binary by dotnet (1) is 744. As in, the group permission (middle digit), is read-only.

This causes `permission denied` runtime error in our container-based setup, where a builder container is producing/publishing binaries with a certain user and a separate runtime container requires the group permission to have execute bit on, to succeed.

It is stricter than Clang or GNU compilers, which set group permission to read+write+execute: <code>7<ins>7</ins>5</code>.

It would help if the group permission is at least set to Read+Execute to form `754` octal out of the box.

clang/gcc:

```sh
$CC -x $LANG -o hwapp - << EOF
#include <stdio.h>
int main(void)
{
  printf("Hello World!\n");
  return 0;
}
EOF

# with CC=clang or CC=gcc; LANG=c or LANG=c++
stat -c "%n %a" hwapp
hwapp 775
```

dotnet:

```sh
dotnet new console -n hwapp
dotnet publish hwapp -o out

# or as a single file "bundled" app
dotnet publish hwapp -o out-single -r linux-x64 /p:PublishSingleFile=true

stat -c "%n %a" out/hwapp out-single/hwapp
out/hwapp 744
out-single/hwapp 744
```

```sh
dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26
```

**Comment by tmds** [comment]
I just ran into this too. The apphosts are only executable by the user:

```
$ dotnet new console -o console
$ cd console/
$ dotnet build
$ ls -lah bin/Debug/netcoreapp3.0/console
-rwxr--r--. 1 tmds tmds 96K Oct  9 15:18 bin/Debug/netcoreapp3.0/console
```
Expected permission: `-rwxr-xr-x.`.

CC @vitek-karas @dagood

**Comment by dagood** [comment]
There's an issue tracking having the HostModel library set the execute bit here: https://github.com/dotnet/core-setup/issues/7062.

(There's an alternative mentioned in the thread of having the installers/packages install the apphost *template* as executable so the output inherits that mode, however since there is no legitimate reason to run the apphost template as-is, the better solution is to have HostModel set the permissions on the generated apphost.)

**Comment by am11** [comment]
Thanks for the info and link! :)
Interestingly, `dotnet` (executable) itself is `-rwxr-xr-x`, checked on macOS:

`stat -f "%A %N" $(command -v dotnet)` => `755 /usr/local/share/dotnet/dotnet`

IMO, we can expect `dotnet-build` to produce all binaries with same permission for mainstream use cases. If the template author wants to have different permission, they can change it as a post-build step.

**Comment by dagood** [comment]
Agreed, and I believe that's what's being tracked--a bit of a summary in case we're not on the same page:
* `/usr/local/share/dotnet/dotnet` is the shared host, which you use to run FDD apps (and SDK commands).
* `/usr/local/share/packs/Microsoft.NETCore.App.Host.osx-x64/.../apphost` is a binary template the SDK uses to generate the host for FDE/SCD apps.
  * It should never be executed (shouldn't have execute bit) and never be signed, since it doesn't do anything useful when you run it in its pre-fill state.
* `.../bin/.../yourapp` after `dotnet build` is the generated apphost.
  * This should be executable the same way as `dotnet`. Devs are free to modify it--permissions, signing, etc.
  * Since the SDK generates it, the HostModel lib that actually generates the apphost is the place the execute bit needs to be set. That's where https://github.com/dotnet/core-setup/issues/7062 comes in, this is not currently done properly.

**Comment by am11** [comment]
Thanks for the explanation @dagood! 🎉
We can close this issue and track dotnet/core-setup#7062.
