### ISSUE TITLE
Simd calculus error

### ISSUE THREAD

**Issue by FrantzUml** [dotnet/core#3645]
The Absolute Sum of items in array is not the same between classic sum and simd sum.

With an array of double of length 1000 with random initialization, i got (with Core 3.0):
506.17984231988885 with classic sum
506.1798423198891 with simd sum
As each items is between [0; 1[, the precision would be up to 15/16 digits after decimal point.

Classic Sum :
static double L1Norm([DisallowNull] double[] array)
{
	ReadOnlySpan<double> span = array;
	double sum = 0D;
#pragma warning disable CA1062
	for (var i = 0; i < span.Length; i++)
#pragma warning restore CA1062
	{
		sum += Math.Abs(span[i]);
	}
	return sum;
}

Simd Sum:
static double L1Norm([DisallowNull] double[] array)
{
	ReadOnlySpan<double> span = array;
	double sum = 0D;
	int simdLen = Vector<double>.Count;
	var simdSum = new Vector<double>(0D);
	Vector<double> tmp;
	int k;
	for (k = 0; k <= span.Length - simdLen; k += simdLen)
	{
		tmp = Vector.Abs(new Vector<double>(span.Slice(k, simdLen)));
		simdSum = Vector.Add(tmp, simdSum);
	}
	for (var j = 0; j < simdLen; j++)
	{
		sum += simdSum[j];
	}
	for (; k < span.Length; k++)
	{
		sum += Math.Abs(span[k]);
	}
	return sum;
}

**Comment by benaadams** [comment]
I think simd uses a different precision? /cc @tannergooding

**Comment by tannergooding** [comment]
> I think simd uses a different precision? 

Not quite. SIMD still uses IEEE 754 compliant binary floating-point arithmetic. The issue here is that SIMD changes the order that elements are summed today.

With floating-point arithmetic, `(a + b) + c` is not the same as `a + (b + c)` because you must round after each operation. That is, floating-point arithmetic requires you to first do `tmp = a + b` or `tmp = b + c` using the inputs, as given, and computing a result as if to infinite precision and unbounded range. It then rounds that result to the nearest representable result. It then repeats the operation for the remaining operation (`res = tmp + c` or `res = tmp + a`).

With the "naive" scalar approach, you are doing `res = arr[0] + arr[i] + ... arr[length - 1]`
With the "simd" approach, you perform `n` operations at a time. So for `Vector128<double>` you do 2 elements at a time, resulting in:
```cs
vres[0] = arr[0] + arr[2] + ... + arr[length - 2]
vres[1] = arr[1] + arr[3] + ... + arr[length - 1]
res = vres[0] + vres[1]
```

This means you have changed how the operations are being added together and therefore the rounding error that accumulates over the course of the operation.

A simple way to see this with the naive algorithm is to change the sort order of the array.
That is, take the following example which sums `500000` followed by `10` values of `1E-11` (`0.00000000001`) and compare its output when the contents of the array is reversed.

```csharp
var arr = new double[11];

for (int i = 0; i < arr.Length; i++)
{
    arr[i] = 1E-11;
}

arr[0] = 500000;

var sum1 = 0.0;

for (int i = 0; i < arr.Length; i++)
{
    sum1 += arr[i];
}

Array.Reverse(arr);

var sum2 = 0.0;

for (int i = 0; i < arr.Length; i++)
{
    sum2 += arr[i];
}

Console.WriteLine($"0x{BitConverter.DoubleToInt64Bits(sum1):X16}; {sum1:G17}"); // 0x411E848000000000; 500000
Console.WriteLine($"0x{BitConverter.DoubleToInt64Bits(sum2):X16}; {sum2:G17}"); // 0x411E848000000002; 500000.00000000012
```

In the first case, because you have a large value and many small values; the result never changes.
This is because `500000` has an epsilon (distance to the next representable value) of ~`5.820766091346741E-11`, so any addition or subtraction that is less than this, will actually have no impact (because the result is closer to the original input).

However, in the second case, we start by adding `1E-11` (which is actually ~`9.9999999999999994E-12`) to itself and repeating this 9 times. This is within the epsilon of each subsequent sum and so it continues mutating the input.
This ultimately gives us a sum of ~`1.0000000000000002E-10` which is greater than the epsilon of `500000`, so it mutates the final computed sum.

**Comment by FrantzUml** [comment]
Of course, you're right : (a + b) + c is different from a + (b + c).
So I close the issue
Thanks very much
