### ISSUE TITLE
downloading dotnet

### ISSUE THREAD

**Issue by nick0528** [dotnet/core#3694]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

how can you download the dotnet without having an admin rights because i need it for my work computer but i do not have admin rights on my work computer. its windows 10, 4 gb of ram. please tell me what i should put on here

**Comment by scalablecory** [comment]
@dagood

**Comment by dagood** [comment]
> i need it for my work computer but i do not have admin rights on my work computer

Ideally you should ask someone who does have admin rights to install it! 🙂 This is by far the easiest way to install and use it on Windows.

---

You can put the .NET Core SDK in a directory you control and run it that way, rather than installing. Note that this is an advanced scenario.

* You can download a `zip` for the specific version you want at [the dotnet-core detailed downloads page](https://dotnet.microsoft.com/download/dotnet-core).
  * At the moment, 3.0.100 is the most current version: https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-windows-x64-binaries
* Another way to get a copy is through the [dotnet-install scripts](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script). You may not be able to run the script on your machine depending on what policies your machine has set.

After putting it on your machine, you have to do some extra work to run `dotnet` commands:

* A simple way to get going is to use the full path to `dotnet.exe`, rather than just typing `dotnet`.
* To set up your system so that typing `dotnet` works, you need to set up the `PATH` environment variable to include the extracted directory that contains `dotnet.exe`.
  * You need to do this whenever you start a new `cmd` or `powershell` terminal. It is possible to set it permanently, but search results aren't showing me anything obvious for how to do that without admin access in Windows 10.

**Comment by scalablecory** [comment]
It sounds like the question has been answered, so I'm closing the issue. Please reopen if you think there's more to discuss. Thanks.
