### ISSUE TITLE
These is something wrong when I add Mysql.data

### ISSUE THREAD

**Issue by Messilimeng** [dotnet/core#372]
vs 2017 win10  core 1.1

Package MySql.Data 6.9.9 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package MySql.Data 6.9.9 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with .NETStandard,Version=v1.4.

**Comment by svick** [comment]
The error message is correct: MySql.Data 6.9.9 is indeed not compatible with netstandard1.4.

There seems to be a prerelease version of the package available: MySql.Data 7.0.6-IR31, but it only supports netstandard1.6.

So, if you want to use that library in your netstandard library, you will have to:

* upgrade the MySql.Data library to the prerelease version
* change your library to target netstandard1.6 instead of netstandard1.4

**Comment by Messilimeng** [comment]
![image](https://cloud.githubusercontent.com/assets/12272166/20736240/3a69ef74-b6e0-11e6-9c94-10e24963aeec.png)

**Comment by Messilimeng** [comment]
@svick  I changed  library to target netstandard1.6 It works But when it install completed  the target netstandard return to 1.4
