### ISSUE TITLE
Why is there no Microsoft.UI.WinForms .Net Core package

### ISSUE THREAD

**Issue by XdX-Software** [dotnet/core#374]
Hi,

I have a general question, that really is not clear to me, it's not a troll question.

I don't understand the Microsoft strategy at this point, why is it not possible to create a WinForms project on .NET core?
Why developing 2 .NET Frameworks? If everything could be possible with one? (.NET core)

It would be great to have packages like:
Microsoft.UI.WinForms
Microsoft.UI.WPF
Microsoft.UI.KDEGuiManager (I don't know the real name)
Microsoft.UI.GnomeGuiManager (I don't know the real name)

Or do you plan to bring all the features of .NET Monolith to .NET core and shut it down some time in the future?

In my opinion, .NET Monolith does not have any benefits in the near future over .NET core, if the projects are using MSBuild projects and the API's grow further let's say on .NET Core 2.0 I think there is API's wise no benefit for .NET Monolith.

But, if you still just allow UI applications with the old .NET, you force people to use it, why?

I hope you can answer may be a few of this questions/thoughts or just share your developers opinion.

Kind regards

**Comment by mrpastewart** [comment]
Agreed, It puzzles me why Microsoft has chosen to have multiple frameworks other than the fact that the full framework is years in the making and obviously still in heavy use. But, Why in the world would you not have a roadmap to make a better framework that can eventually replace both the full windows only versions and mono. There are plenty of API's that can be wrapped to provide Native UI and OS libraries that can be accessed in both Mac and Linux in addition to what works on windows. Just look at AvaloniaUI, ETO.Forms and Xamarin.Forms all prove that a consistent method can be provided to provide desktop application capability to .NETCore that will provide native interfaces across major OS's including mobile devices. 

Why not capitalize on this concept and once and for all provide a cross platform solution that allows developers to get things done. Why can't we write apps on any OS that can work anywhere including IOT and mobile devices with one unified framework. Also it IMHO is a crime that Microsoft has not embraced the entire .NET ecosystem which would in my opinion provide them with a clear winner for example, there have been many of languages ported or created to run on the platform, Boo, Java, Python, Ruby, PHP, Cobra, Cobol, Typescript, Javascript and several others. It baffles me why Microsoft does not support these efforts so that .Net can attract more usage I suspect many developers of PHP or Java or Ruby would love to be able to maintain their skill set using the dotnet core as it provides many benefits and allows for seamless integration not to mention it opens up a whole lot of mature code that has been written over the years to the dotnet ecosystem. It actually makes me upset to see addins and plugins for these languages fall unmaintained and become not usable in monodevelop, sharpdevelop and even VS has seen some come and go. It would be awesome to be able to have multiple langage projects using one framework to maximize the best of the entire development ecosystem not just one companies vision.

Now that .Net is opensource it would be wonderful to see these efforts united to bring the framework inline with what it should be and see these languages being ported to Roslyn and brought inline with the current modern direction and standards of the .net core as a whole. It's totally possible and as example php is currently being ported to the Roslyn stack and dotnet core it's called peachpie and is the natural evolution of the Phalanger project. How come nobody tries to embrace a community instead of just their vision? Why can't we use the .NET Foundation as a way to bring a team together that consist of these projects spearheaded by a common goal for example we have the ASP.Net team, The Roslyn Team the .NET Core team how come we can't extend an offer and official support to the developers of relevant projects like Boo, PeachPie, IronPython, IronRuby and the many others including ETO.Forms and AvaloniaUI to become a unified foundation with the goal of making dotnetcore a defacto standard with all the love bells and jingles of a xplat framework that supports not just C# and VB.Net but all the other languages that have already been proven to run on the CLR with full development capabilities including a UI kit, Web, API, Mobile and IOT out the box. It's a shame... Just my opinion..

**Comment by maikebing** [comment]
I hope this .

**Comment by richlander** [comment]
Related to: #388.

My team (the Microsoft .NET team) is focused on .NET Core as a cloud and web framework. We know that folks would like us to build additional application types for .NET Core. For now, we're remaining focused. Many other developers want us to stay focused on what we've started with .NET Core and that's our intention.

> Or do you plan to bring all the features of .NET Monolith to .NET core and shut it down some time in the future?

Neither. We plan to keep both in place and invest in both. In some cases, there is overlap in scenarios and other cases not. That's part of building something new for .NET developers.

**Comment by richlander** [comment]
Please re-activate if you would like to discuss further.

**Comment by Mds92** [comment]
Does Microsoft .NET team has a plan to bring .Net WinForm in .Net Core?

**Comment by Petermarcu** [comment]
Still focused on services and command line applications.

**Comment by ricardopolo** [comment]
Any way to create a Windows Service using .net core?
Or just console apps?

**Comment by roji** [comment]
With the [Windows Compatibility Pack](https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/) providing access to Windows-only APIs on .NET Core, I hope Winforms (and WPF) support would be reconsidered as well. This is not about providing a full-fledged, cross-platform UI toolkit (an enormous endeavor), just to allow writing .NET Core applications which can access Winforms.

.NET Core and .NET Framework are starting to diverge. Up to now it's been reasonable to just write your winforms application in .NET Framework, and take a dependency on a .NET Standard 2.0 library. However, .NET Core 2.1 contains some valuable API additions and optimizations (Span/Memory) which are completely inaccessible to a .NET Framework application, as there's no .NET Standard 2.1. So this will become more and more of a problem as .NET Core evolves and .NET Framework stagnates.

**Comment by roji** [comment]
@markusschaber, regardless of how obsolete and outdated Windows Forms is, it's widely used by applications which could benefit from being ported to .NET Core. I'm assuming that simply making Windows Forms available in .NET Core on Windows shouldn't be a huge challenge (I may be wrong). The same could be argued for WPF.

The "fresh, future-proof UI framework, which is platform independent" which you're asking for is a *huge* undertaking (just look at the history of this in Java or other technology spaces). Of course it would be great to have this one day, but I'm more concerned with the short- and medium-term here.

.NET Core is clearly still focused on server workloads at the moment, and that's fine. But as it starts to jump ahead of .NET Framework and a gap starts to appear, it may make sense to at least allow Windows applications to be ported, depending on how much effort it would involve. Someone could also create bindings for Similarly, someone could set up bindings for Gtk and/or Qt to allow for cross-platform GUI (not sure what state Gtk# is in and what it would take to bring it to .NET Core).

**Comment by markusschaber** [comment]
@roji I know, we have some large Windows Forms Codebase in our house. We had plans to replace the UI by WPF and started some prototypes, but then stopped those plans, as WPF also is not quite the future. 

As far as I can see, Xamarin.Forms is already heading this direction (https://blog.xamarin.com/glimpse-future-xamarin-forms-3-0/), but it's not ready for prime time yet.

**Comment by collinoswalt** [comment]
> Neither. We plan to keep both in place and invest in both. In some cases, there is overlap in scenarios and other cases not. That's part of building something new for .NET developers.

This comment didn't age well

**Comment by DataJuggler** [comment]
As a WinForms developer, I have been ignored by Microsoft since 2005 on this topic.

**Comment by svick** [comment]
@DataJuggler I'm confused. Most of the information in this issue is severely outdated, since [Winforms are part of .Net Core starting with .Net Core 3](https://devblogs.microsoft.com/dotnet/net-core-3-and-support-for-windows-desktop-applications/). Were you not aware of that? If you have some issues with the support that's in .Net Core now, I'd suggest you to open a new issue with more details.
