### ISSUE TITLE
Patching .NET Core.

### ISSUE THREAD

**Issue by MCKPRO** [dotnet/core#3746]
I tried to Patch 2.1.5 to 2.1.13 but now I have 2 Version.
My question is, is there a patch for 2.1.5 or do I need to Uninstall 2.1.5 and then install 2.1.13.

Windows Server 2016

Thanks

**Comment by leecow** [comment]
Some of this depends on the OS you're running on and how you are installing. Let me these 2 things and I can be more specific. 

Until recently, the .NET Core installers were always side-by-side. This means that you would have several versions of the runtime present, for example, under dotnet/shared/Microsoft.NETCore.App. Because of the way .NET Core decides which runtime to use, an application will run on the latest patch version. In your example, 2.1.13 would be used even though 2.1.5 is also present.

**Comment by carlossanlop** [comment]
Question answered. Closing.
