### ISSUE TITLE
Unable to locate package dotnet-sdk-3.0 on Ubuntu 19.04 emulator on Termux Android mobile application

### ISSUE THREAD

**Issue by jainudi48** [dotnet/core#3758]
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
Operating System: Linux Ubuntu 19.04 emulator installed on Termux mobile application on Android.

Environment:
root@localhost:/etc# cat os-release
NAME="Ubuntu"
VERSION="19.04 (Disco Dingo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.04"
VERSION_ID="19.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

How did I install Ubuntu emulator on my Termux mobile application?
Ans: I followed this article: https://wiki.termux.com/wiki/Ubuntu

Now, when I tried to install dotnet sdk 3.0 on my Ubuntu emulator by trying all ways given in https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current, I failed with following errors:
E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'

**Comment by leecow** [comment]
This is probably because the .NET Core packages are x86_64-only and, if I'm reading things correctly, the termux environment is either ARM or AArch64. If that's true, you should be able to install using the appropriate [tarball (ARM64 or x64 Alpine)](https://dotnet.microsoft.com/download/dotnet-core/3.0) or by using [dotnet-install.sh](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script).

**Comment by scalablecory** [comment]
Looks like this was answered and no discussion for some time, closing out.
