### ISSUE TITLE
Unable to locate package dotnet-sdk-3.0

### ISSUE THREAD

**Issue by Qiangong2** [dotnet/core#3777]
# Issue Title

Unable to install dotnet-sdk-3.0 through package manager on Ubuntu 19.10

# General

I've gotten everything setup until the install process on Ubuntu Kylin 19.10. However, when I go to install, I get this:

```~/Downloads$ sudo apt-get install dotnet-sdk-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'
```

I followed the 19.04 instructions listed here: https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-3.0.100 and I substituted 19.10 in the guide where required.

Even the workaround method does not work.

I can get it to mostly work by just installing the binaries directly, but even then I have issues with installing tools such as `dotnet-ef`

Any help would be greatly appreciated

**Comment by dagood** [comment]
> I substituted 19.10 in the guide where required.

This seems like the reasonable thing to do, but it's actually the problem here--until we add a dropdown entry for the next release, you have to stick to the exact instructions on the closest one we have. (I tried this out earlier on 19.10 and it worked fine, so I'm going to go ahead and close the issue, but do let us know if you have any problems.)

Us getting better at keeping up with the distros is tracked over at #2576.
