### ISSUE TITLE
The application to execute does not exist - Error when starting app

### ISSUE THREAD

**Issue by rohitisinhk** [dotnet/core#3830]
# Application would not start, event viewer shows "Application to execute does not exist" error

Application Type: Winform application is published as single file, self-contained binary using .net core 3.0 SDK (RTM version as of date)

All of a sudden the application would not start, looking at event viewer, it seems it is extracting the binary to a temporary folder and errors out with "The application to execute does not exist c:\users\<username>\AppData\Local\Temp\.net\\ApplicationName\\**ShortGUID**\App.dll"

# Resolution

Deleting the  ShortGUID  fixes the issue and app could start again. I see the same issue on RedHat 7 once (with a console app) but thought was one off or something, but I see this on windows now too. Very frustrating cause the same app worked earlier but suddenly broken out of nowhere.

**Comment by scalablecory** [comment]
Can you provide a sample solution which reproduces the problem?

**Comment by jeffschwMSFT** [comment]
@swaroop-sridhar

**Comment by rohitisinhk** [comment]
Sorry I can't reproduce this issue at will, I deployed the app in production two weeks ago, it works well for our internal users, but today one user could not run the same app all of a sudden, since I didn't see any logs generated I realized the app is not even initializing (we print info on app start). 

Digging into event viewer I see it has to do with some extraction of single file assembly deployment. Deleting the folder helped

**Comment by swaroop-sridhar** [comment]
@rohitisinhk, I understand the problem.

In the current release, there's one solution to mitigate it: The location where the bundle contents are extracted is configurable via the DOTNET_BUNDLE_EXTRACT_BASE_DIR environment variable. So, it can be set to any user directory that's not cleaned up automatically.

Currently, the DOTNET_BUNDLE_EXTRACT_BASE_DIR must be set in the client environment, and not within the app (because it inherently depends on the runtime file structure). https://github.com/dotnet/core-setup/issues/8865 tracks the issue of setting the extraction location at compile time. 

Subsequent implementation of single-file solution will reduce/eliminate the reliance on temporary extraction directories.

**Comment by swaroop-sridhar** [comment]
Dup of https://github.com/dotnet/core-setup/issues/8314

**Comment by Hphipps** [comment]
Having the same issue on net core 3.1

**Comment by chrisevans9629** [comment]
Same here

**Comment by Decimation** [comment]
Same problem here

**Comment by swaroop-sridhar** [comment]
@Hphipps  @chrisevans9629  This problem should be fixed for apps built with SDK in the 3.1.4 release. Thanks.

**Comment by NotLazy** [comment]
@swaroop-sridhar how do we publish with 3.1.4?

**Comment by swaroop-sridhar** [comment]
@NotLazy  Please install the 3.1.4 SDK from https://dotnet.microsoft.com/download/dotnet-core 
Then build the app using this SDK. Thanks.

**Comment by NotLazy** [comment]
@swaroop-sridhar Do i install 3.1.300?
