### ISSUE TITLE
Fedora 31 dotnet-sdk-3.0 checksum error during installation

### ISSUE THREAD

**Issue by oldmalk** [dotnet/core#3873]
I'm trying to install dotnet-sdk-3.0 on Fedora 31 and got a checksum error on both 3.0.100-1 and 3.0.101 versions when dnf tries to install netstandard-targeting-pack-2.1.0. 

> [MIRROR] netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match. Calculated: 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480(sha256)  Expected: fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41(sha256)

**Comment by suvayu** [comment]
I have the same issue, on Fedora 30.  What was your resolution @oldmalk?

**Comment by oldmalk** [comment]
@suvayu the suggested workaround is manually install the package.

> dnf install https://packages.microsoft.com/fedora/30/prod/netstandard-targeting-pack-2.1.0-x64.rpm

After this, the installation runs fine.

**Comment by suvayu** [comment]
@oldmalk Thanks.

I tried installing that package individually with just the name, it still failed, but using the url like you suggest worked.  I think the metadata in the repo is incorrect, and a direct install by url bypasses the checksum verification (which would actually be a bug in `dnf`).  Maybe it's worthwhile to leave this issue open, otherwise it won't get fixed.

**Comment by scalablecory** [comment]
Do you still have this issue? I know we had some issues with our package repos, but I expect they've been resolved by now -- CC @dagood @leecow
