### ISSUE TITLE
PLINQ for aggregation

### ISSUE THREAD

**Issue by fansgit** [dotnet/core#389]
It seemed that only a single CPU core was consumed below,
```csharp
Enumerable.Range(1, 1000000000).AsParallel().Aggregate(0, (sum, n) => sum + n - n);
```

Does current `dotnet-core-linux` support [PLINQ for aggregation](https://msdn.microsoft.com/en-us/library/ff963547.aspx)?

**Comment by stephentoub** [comment]
> It seemed that only a single CPU core was consumed below

That's because the AsParallel is operating on an enumerable, which means that it needs to lock to get access to the elements, and as there's basically no work happening as part of the aggregation itself, all of the work here is really happening under a lock and is getting serialized.  Aggregate in corefx does support executing in parallel, you just need to give it more work to do on each element.

**Comment by fansgit** [comment]
FYI, the simliar style of parallel aggregation processing in `Java 8` takes up all the CPU cores below,
```java
LongStream.range(1, 10000000000L).parallel().reduce(0, (sum, n) -> sum + n - n)
```

**Comment by stephentoub** [comment]
Have you tried ParallelEnumerable rather than Enumerable?

**Comment by fansgit** [comment]
Test results below,

| Data Source  | Iterations | Performance(roughly) | Busy CPU Cores |
| - | - | - | - |
| Enumerable(C#) | 10E9 | some seconds | 1 |
| ParallelEnumerable(C#) | 10E9 | some 10 seconds | 1 |
| LongStream(Java) | 10E10 | some seconds | all |

**Comment by stephentoub** [comment]
Can you share the code you used in each case?
