### ISSUE TITLE
Core 3.1 release shows as Microsoft .NET Core Host - 3.1.0 Preview 3 (x86)

### ISSUE THREAD

**Issue by zulander1** [dotnet/core#3962]
When installing Hosting Bundle (https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-3.1.0-windows-hosting-bundle-installer)  it shown as:
Microsoft .NET Core Runtime - 3.1.0 Preview 3 (x86)
Microsoft .NET Core Host - 3.1.0 Preview 3 (x86)

![image](https://user-images.githubusercontent.com/12099546/70187974-7e311f80-16bd-11ea-8d8e-743f4ed4d6e3.png)

**Comment by scalablecory** [comment]
@dagood @leecow

**Comment by dagood** [comment]
Thanks for filing this. It was also reported in the 3.1.0 announcement post (https://github.com/dotnet/core/issues/3950) and there are some details about what's going on in a related issue (https://github.com/dotnet/runtime/issues/492), but it might be good for this problem to have its own dedicated issue.

An important detail about this bug is the hosting bundle didn't actually install the 3.1.0 preview 3 build from last month. What's being installed is a more recent build that happens to have a 3.1.0 preview 3 label.

The .NET Core Runtime version in the rightmost column shows you have the newest version available right now:

* `3.1.0.28312` is the newest build, close to 3.1.0. (This is in the screenshot, thanks for including it. :+1:)
* `3.1.0.28303` was the version of the 3.1.0 preview 3 build released a month ago.

You can also check to see what you have installed with `dotnet --info`, which should show `Microsoft.NETCore.App 3.1.0`, rather than the old `3.1.0-preview3.19553.2`.

We're still investigating this issue.

**Comment by leecow** [comment]
We have had a look at this to evaluate risks in updating the installer basically 'in-place' but are really nervous about that idea. There are too many interesting msi interactions we may not be able to account for. Because we can't convince ourselves that such an in-place update is safe, we're going to wait to fix this in the January update. The only commits missing are cosmetic so no functional worries if you need to use the current Hosting Bundle. The next servicing release in January will have the branding cleared up.

**Comment by virzak** [comment]
@leecow Our installer (Wix) will install this 3.1 Desktop Runtime on client machines.

Can you confirm that what you said about hosting bundle also applies to Desktop Runtime? That is that the only missing functionality is cosmetic and otherwise is it not different from any other stable versions?

Thanks.

**Comment by leecow** [comment]
@virzak - Yes, the same holds true. We did, however, update the Windows Runtime installers on Tuesday. So, you can grab the x86 or x64 installer exe's from https://dotnet.microsoft.com/download/dotnet-core/3.1 which do now have the preview branding. 

We were OK doing just the Runtime installer because the internally referenced MSI's didn't present the same difficulty as the Runtime reference in the Hosting Bundle.

**Comment by wtgodbe** [comment]
I've checked in fixes for this in 3.0 & 3.1, which will be included in our January release: https://github.com/aspnet/AspNetCore/pull/17592, https://github.com/aspnet/AspNetCore/pull/17593

**Comment by carlossanlop** [comment]
@wtgodbe @leecow can we consider this issue resolved so we can close it?

**Comment by dagood** [comment]
It will only be resolved once we release 3.1.1, however I added it to the 3.1 known issues doc so I believe this issue can be closed. https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md.

**Comment by SimonCropp** [comment]
@dagood will 3.1.1 be considered LTS?

**Comment by bording** [comment]
@SimonCropp If you look at https://dotnet.microsoft.com/platform/support/policy/dotnet-core you'll see that it is .NET Core 3.1 that is LTS, so 3.1.1 is just a patch of that version, so yes it will be the latest patch of the LTS release.

**Comment by SimonCropp** [comment]
@bording thanks
