### ISSUE TITLE
3.1.0 on macOS 10.12.6, dotnet run gives "dyld: lazy symbol binding failed: Symbol not found: _utimensat"

### ISSUE THREAD

**Issue by Redux23** [dotnet/core#4005]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: macos

> Brights-MacBook-Pro:myWebApp bright$ dotnet run dyld: lazy symbol binding failed: Symbol not found: _utimensat Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.0/System.Native.dylib Expected in: /usr/lib/libSystem.B.dylib dyld: Symbol not found: _utimensat Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.0/System.Native.dylib Expected in: /usr/lib/libSystem.B.dylib The build failed. Fix the build errors and run again.

My OS is MacOS Sierra, version 10.12.6

**Comment by Redux23** [comment]
my OS is MacOS Sierra, version 10.12.6

**Comment by dagood** [comment]
(I moved the description to the issue body and shrunk the issue title because it was huge on the issue list, hope that's ok.)

.NET Core 3.1 doesn't support 10.12, only 10.13+: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md#macos

.NET Core 2.1 supports 10.12+: https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md#macos

**Comment by Redux23** [comment]
Thanks. And yeah it's cool (with the shrinking ;) )

**Comment by dagood** [comment]
Cool. 🙂 Closing as answered, then.
