### ISSUE TITLE
After installing 3.1.0 many CLI commands don't work anymore

### ISSUE THREAD

**Issue by SkydivingAngel** [dotnet/core#4006]
# After installing 3.1.0 many CLI commands don't work anymore
eg: dotnet new --list, dotnet new console, dotnet new mvc --auth Individual

# The reported error is:

A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.0'.

**Comment by dagood** [comment]
This happens due to a known issue with the 3.1.0 release's installers. Running "Repair" on the 3.1.0 .NET Core Runtime or SDK should fix the issue. (If you have both x86 and x64 runtimes installed, you may need to repair both.)

Known issue doc with more details: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#310

Please do let us know if that doesn't work for you and we can look into it further. Getting the install logs from `%temp%` is the next bit of info that would be useful.
