### ISSUE TITLE
Access to Office.Interop from .NET Core?

### ISSUE THREAD

**Issue by TechiMe** [dotnet/core#402]
Is there a plan to add Office.Interop.Excel to available namespaces in .Net Core Class Library?

**Comment by TechiMe** [comment]
Just to add that that the major reason for doing this would be if it could be made available on OSX as well as Windows, thereby offering cross-platform portability of applications that interwork with Microsoft Office (externally via COM objects) on Windows and OSX.

**Comment by terrajobst** [comment]
Hey @TechiMe, thanks for filing this.

I assume the question isn't about adding the Excel automation APIs to .NET Core directly but instead have a way to automate Excel from .NET Core. Is that correct?

**Comment by TechiMe** [comment]
Hi Immo, Yes, exactly!

The only way to automate Excel for Mac at present is via embedded VBA or Javascript (Office Addins), neither of which come anywhere close to the power and flexibility of the manipulation of objects in C# which is possible for Excel for Windows.  So we were hoping that .Net Core might be able to fix this hole!

Many thanks.

**Comment by terrajobst** [comment]
Ah, so that's an even different question.

* First, it's about whether you can automate Office using the COM automation APIs on Windows. I've asked our interop team to see whether it's supported and if so how.
* Secondly, the question is whether we can make that part available cross-platform. Considering that COM is a Windows technology I highly doubt that we can make this scenario work in a cross-platform fashion.

That being said, whatever mechanism JavaScript/VBA is using on Mac, we could look into supporting this for .NET Core, but I have no idea how much would be required to do so.

**Comment by TechiMe** [comment]
Well the first is definitely possible because we do it all the time, just by referencing Office.Interop.Excel.

But, in line with what you suspect I think, I have read in various places that (up until now at least, before the advent of .Net Core) it would not be possible to make this API available on the Mac because the "unix-like architecture of OSX is not compatible with COM automation".

But, exactly as you say in your final para, somehow it is being done for the JavaScript/VBA interfaces on the Mac, so if you can make "whatever THAT is" available in .NET Core, you'll be the hero of the hour!!!

**Comment by richlander** [comment]
Related: #409

**Comment by richlander** [comment]
We have no plans to make Office COM APIs work on Mac or Linux. If the Office team produces docs on how to do this, we'd be happy to take a look. Closing as a result.

**Comment by SpiritBob** [comment]
I'm confused - isn't Interop currently supported for all three platforms? Windows is certainly supported right now in .NET Core?
