### ISSUE TITLE
Publish single file, temp location being emptied

### ISSUE THREAD

**Issue by genifycom** [dotnet/core#4023]
# Issue Title

We are deploying a .NET Core 3.1 Application as PublishSingleFile after some time, the temp directory is appearing empty and the application fails to run

# General

Our .NET Core 3.1 Application is loaded into a directory using a user account (because it requires user credentials to do this). After deploying the single exe, it is tested under the user account and unpacks and functions fine. The Application is a Console application and is called from Task Scheduler using the Local System account (these are non-domain machines). The tasks run fine for some period of time. After a couple of days, the tasks stop running. Investigation shows that the unpack directory is empty e.g. C:\Windows\Temp\.net\BVLocalSync\bsg0ymk1.aov is empty. When this happens, the task fails to run with "The application to execute does not exist: 'C:\Windows\TEMP\.net\BVLocalSync\bsg0ymk1.aov\BVLocalSync.dll'."

Checking the temp directory, Administrators have full control.

Can we at least have a 3.1 PublishSingleFile fix that unpacks again if the application specific temp directory is empty? We are having to run around multiple machines deleting the temp directory to allow the tasks to start running again.

This was also a problem in .Net Core 3.0 

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by genifycom** [comment]
Note that when the directory is recreated by PublishSingleFile, it recreates with the same identifer e.g.
C:\Windows\Temp\.net\bvlocalsync\bsg0ymk1.aov

How can I identify which task is emptying the directory?

**Comment by genifycom** [comment]
Just following up. This is continuing to happen slowly across our 30 machine deployment. In the meantime I am replace each one with the version not published as a single file.

I cannot be the only one noticing this. These are new machines with Windows 10 and we have noticed this happening on both Windows 10 Pro and Windows Server 2019.

**Comment by swaroop-sridhar** [comment]
@genifycom  thanks for reporting the issue.

If parts of the extraction directory are deleted, then it is bad for the single-exe app, because:

The current run may fail because of missing DLLs
Subsequent runs may fail because of trying to use the extraction directory with partial contents.
Were the files removed soon after the extraction (ex: the first run of the app failed) or several hours/days after the extraction? Several apps rely on the use of temporary files (ex: some msbuild targets), which may fail if files in the temp directory are arbitrarily deleted.

In the current release, there's one solution to mitigate it:
The location where the bundle contents are extracted is configurable via the DOTNET_BUNDLE_EXTRACT_BASE_DIR environment variable. So, it can be set to any user directory that's not cleaned up automatically.

We're working on a servicing fix for the issue for .net core 3.1

Subsequent implementation of single-file solution will reduce/eliminate the reliance on temporary extraction directories.

Dup of https://github.com/dotnet/core-setup/issues/8314
