### ISSUE TITLE
Installing .net SDK on MacOS : "dotnet: command not found"

### ISSUE THREAD

**Issue by assemzh** [dotnet/core#4091]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Here is the problem when I try to verify my installation:

$ dotnet
-bash: dotnet: command not found
$ export PATH="/usr/local/share/dotnet/"
$ dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

/////////
I dont really want to run "export PATH="/usr/local/share/dotnet/"" everytime I open the terminal

**Comment by Matsa59** [comment]
A temporary solution is to add this to your bash profile.

I assume you use the default bash, so add the following line into the file `~/.bashrc`.

```
export PATH="/usr/local/share/dotnet/"
```

It looks like a bash / shell issue rather than a dotnet issue. 

Are you using the last version of MacOS? Did you try in the past to change your bashrc or change yo another shell?

I have installed dotnet last week on my Mac and it works.

**Comment by dagood** [comment]
Changing `PATH` without properly appending to it is actually a known **cause** of this problem. If you add a line like that to your bash profile/rc, make sure it preserves the existing value of `PATH`:

```
export PATH=$PATH:/usr/local/share/dotnet/
```

See https://github.com/dotnet/core-setup/issues/6521 for more details and alternatives.

I'd be interested to see your profile/rc script though, to confirm you hit that issue in the way it seems to happen.

**Comment by scalablecory** [comment]
Closing due to lack of response; please re-open if you can provide more detail.
