### ISSUE TITLE
Process.Start("URL") is not working.

### ISSUE THREAD

**Issue by ChanyaKushima** [dotnet/core#4109]
# General
Do not working code in [this MSFT's site](https://support.microsoft.com/en-gb/help/305703/how-to-start-the-default-internet-browser-programmatically-by-using-vi) on .NET Core 3.0.  
The following code on .NET Framework 4.8 opened a page on default web browser, but not on .NET Core 3.0.

## Actual Code
~~~cs
using System.Diagnostics;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            Process.Start("https://www.google.com");
        }
    }
}
~~~

# Versions
## OS
Edition: Windows 10 Home
Version: 1909
OS Build: 18363.535 
## .NET Core
SDK Version: 3.0.100

**Comment by svick** [comment]
This was an intentional breaking change in .Net Core. Specifically, `UseShellExecute`, which is required to be `true` for your code to work, [defaults to `true` on .Net Framework, but it's `false` on .Net Core](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.useshellexecute). This means the following code will work on both frameworks:

```c#
Process.Start(new ProcessStartInfo("https://www.google.com") { UseShellExecute = true });
```

**Comment by ChanyaKushima** [comment]
I see. Thank you @svick . I could run the code thanks to your comment!
