### ISSUE TITLE
SDK 3.1.101 on CentOS 7 requires .NET core runtime 3.1.1

### ISSUE THREAD

**Issue by peval27** [dotnet/core#4135]
# SDK 3.1.101 on CentOS 7 requires .NET core runtime 3.1.1

# General

I have a build server which was running fine when I installed SDK 3.1.100 (i.e. I could build a ASP.NET Core project targeting SDK 3.1.100 (in global.json) and single projects targeting 3.1.
I've just installed SDK **3.1.101** (`yum install dotnet-sdk-3.1`) and it fails to build complaining that ASP.NET **3.1.1** is not installed. 

I was expecting the SDK was enough to build. The workaround is to install the runtime on the build machine (`yum install aspnetcore-runtime-3.1`).

Is this expected?

If so the documentation isn't clear enough.

**Comment by dagood** [comment]
This sounds unexpected to me... taking a look. The SDK RPM package should take a dependency on the ASP.NET Core runtime of the right version.

**Comment by dagood** [comment]
I'm not able to reproduce the issue. Installing on a fresh `centos:7` Docker container gives me the right runtimes:

```
$ dotnet --info
...
Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
...

$ yum list | grep '@packages-microsoft-com-prod'
aspnetcore-runtime-3.1.x86_64          3.1.1-1     @packages-microsoft-com-prod
aspnetcore-targeting-pack-3.1.x86_64   3.1.0-1     @packages-microsoft-com-prod
dotnet-apphost-pack-3.1.x86_64         3.1.1-1     @packages-microsoft-com-prod
dotnet-host.x86_64                     3.1.1-1     @packages-microsoft-com-prod
dotnet-hostfxr-3.1.x86_64              3.1.1-1     @packages-microsoft-com-prod
dotnet-runtime-3.1.x86_64              3.1.1-1     @packages-microsoft-com-prod
dotnet-runtime-deps-3.1.x86_64         3.1.1-1     @packages-microsoft-com-prod
dotnet-sdk-3.1.x86_64                  3.1.101-1   @packages-microsoft-com-prod
dotnet-targeting-pack-3.1.x86_64       3.1.0-1     @packages-microsoft-com-prod
netstandard-targeting-pack-2.1.x86_64  2.1.0-1     @packages-microsoft-com-prod
```

Could you include some more info about what's missing on your machine? (The above commands plus anything else you can think of?)

**Comment by peval27** [comment]
To follow up. Since it was then working, I've:

- removed all the .NET SDK and runtimes (rm -rf )
- installed the SDK again
- this time I got `dotnet command not found`

I ended up manually downloading the runtime (with the host) and creating the symlink.

Not sure if it's my CentOS VM, or there's something weird with the installer.

see my comments on [this issue](https://github.com/dotnet/core/issues/3846)

**Comment by dagood** [comment]
You're doing a lot of stuff without showing any console output. `rm -rf` isn't a reasonable way to uninstall .NET Core SDK on Linux, you should use your package manager. It sounds like you removed the files, then tried to install, but the package manager knows it already installed so it didn't put anything back on disk, hence you don't have `dotnet` anymore.

I would suggest running the `yum list` command I recommended, and uninstalling all .NET Core packages, then installing the SDK again. However now that you've set it up manually, you'll have multiple installs and `PATH` may get complicated.

Installing via package manager is a little better because you get automatic updates when new releases come out, so it might still be worth it to you to get that set up. Let me know.

Note that https://github.com/dotnet/core/issues/3846 is a macOS issue, it wouldn't be related to any issues you're having with the RPM packages.

**Comment by dagood** [comment]
There are some useful commands at https://superuser.com/q/338296 for broken installs:

>     rpm -Va
> 
> ...this will do a check on all the packages you have installed, and you can then reinstall anything that doesn't verify.

**Comment by peval27** [comment]
Ok thanks for the tip. I ended up manually removing stuff since the package manager wasn't removing the SDK (`sudo yum erase ..`)

**Comment by peval27** [comment]
Closing the issue as it might be something weird on my VM.
