### ISSUE TITLE
Fix RaspberryPiInstructions for .netcore 3

### ISSUE THREAD

**Issue by softlion** [dotnet/core#4209]
# Issue Title
File
https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

explains how to use netcore 2.2 on pi. It should be updated for netcore 3.1

**Comment by scalablecory** [comment]
@danmosemsft is there anyone with the know-how for this in @krwq's absence?

**Comment by scalablecory** [comment]
@joperezr can you take a look at this?

**Comment by joperezr** [comment]
The instructions over there are actually not specific to .net Core 2.2, the command outputs happen to be using a .NET Core 2.1 SDK but the instructions for 3.1 are exactly the same except that the publish folder will be `./bin/Debug/netcoreapp3.1/<runtime identifier>/publish` instead of `./bin/Debug/netcoreapp2.1/<runtime identifier>/publish`. The only thing I that I see in those instructions which is outdated, is the part where it tells you to add a NuGet.config. That shouldn't be required at all, and even if you wanted to add it, the url for the feed has changed now so it is no longer accurate. I'm happy to put up a PR to address this, but other than that the RPi instructions for 3.1 seem good to me.

**Comment by scalablecory** [comment]
@ericstj seems like we should update this sample for 5.0. It still references 2.1.

**Comment by scalablecory** [comment]
It looks like these instructions have been updated for .NET 5, closing.
