### ISSUE TITLE
problem edit code

### ISSUE THREAD

**Issue by martinpriv-cyber** [dotnet/core#4241]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://user-images.githubusercontent.com/60798320/74076298-03a2ba00-49f6-11ea-9682-a64ea883a761.png)

**Comment by carlossanlop** [comment]
You should not save a web app folder inside `C:\Windows\System32`. Your web app should be saved in a different location, like My Documents.
Closing this issue since it does not have anything to do with dotnet.
No es correcto almacenar una aplicación web dentro del directorio `C:\Windows\System32`. Tu aplicación web debe ser almacenada en una ubicación diferente, como en Mis Documentos.
Cerraré este problema porque no tiene relación con dotnet.
