### ISSUE TITLE
latest 2.2, SDK 2.2.402 or SDK 2.2.207 ?

### ISSUE THREAD

**Issue by dluc** [dotnet/core#4443]
# Issue Title

.NET Core 2.2 version numbers, what's the latest? 

# General

Could you help understanding which one is the latest version from https://dotnet.microsoft.com/download/dotnet-core/2.2 ? Should I look at the release information or the build number? 

Looking at the page:

1. v2.2.8 ==> SDK 2.2.**207**
2. v2.2.7 ==> SDK 2.2.**402**

If one wants to use the latest of 2.2, which number should we look at?
207 or 402 ?  
2.2.7 or 2.2.8?

207 seems the latest, but 402 > 207, not sure how to interpret these versions.

**Comment by igoventura** [comment]
The dotnet core v2.2.7 has multiple SDK's for choose, according with the version of your OS and Visual Studio. I think that they had to fix something because de SDK version 2.2.402 used by dotnet core 2.2.7 is suggested for VS v16.2.

Use dotnet core v2.2.8, that uses the SDK v2.2.207, that is available to all* versions of VS v16.

P.s.: I recommend you to use dotnet core v3.1+ because it's now the LTS version.
