### ISSUE TITLE
Can't run command in cmd window after dotnet run

### ISSUE THREAD

**Issue by SergeiASP** [dotnet/core#4476]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Hello! I can't understand why after running 'dotnet run' command there is disabled to run other commands. To run next command I have to close current cmd.exe window and open new one. Screenshot is attached below. Thanks
![2020-03-27_2258](https://user-images.githubusercontent.com/62763365/77781299-87d0ff80-707f-11ea-82dd-3c26c81d75b6.png)

**Comment by carlossanlop** [comment]
dotnet run executes a process and stays running in the foreground, preventing executing more commands for the command line. This is expected.
If you want to execute commands, you have to open a separate command line window and execute the commands there, while your app runs in the initial window.
Since the question is answered, I will close this.
