### ISSUE TITLE
.Any() fails on collections using a in-line null check

### ISSUE THREAD

**Issue by bwinchester02** [dotnet/core#4533]
# Issue Title

.Any() fails on collections using a in-line null check

# General

.NET Core Version: 3.1.201

```      
public class TestClass
{
     public List<string> listOfStrings { get; set; }
} 

static void Main(string[] args)
{
     TestClass test = new TestClass();

     if(test.listOfStrings?.Any(s => s == "Hello"))
     {
          // do something
     }
}
```

test.listOfString?.Any() should return a bool if it finds any string that are equal to "Hello". .NET is complaining that it can't implicity convert type 'bool?' to 'bool'

https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.any?view=netframework-4.8

**Comment by bartonjs** [comment]
When the member after `?.` evaluates to a value type, the evaluated type of the `?.` expression is a Nullable wrapper over that type, because the `?.` operator is just a syntactic shortcut for  `a?.B()` becomes `(a != null ? a.B() : null)`.

In your case, it expands to

```C#
List<string> tmp;
if ((tmp = test.listOfStrings) != null ? tmp.Any(s => s == "Hello") : null))
{
    // do something
}
```

but the if-expression isn't a valid boolean expression (it's an expression that evaluates to `Nullable<bool>`, aka `bool?`).  You can use `?? false` (or `?? true`) to express the behavior for when listOfStrings was `null`:

```C#
if (test.listOfString?.Any(s => s == "Hello") ?? false)
{
    // do something
}
```

**Comment by bartonjs** [comment]
(Closing since there's not a product bug here, just nuance of a C# language feature)
