### ISSUE TITLE
Is it possible to get started with dotnet core on android tablets

### ISSUE THREAD

**Issue by AbhimanyuAryan** [dotnet/core#456]
It is possible to write dotnet core asp.net MVC application android tablets like this [one](https://www.amazon.com/gp/product/B00XCRJ428/ref=ox_sc_sfl_title_1?ie=UTF8&psc=1&smid=A946JKMEW2VE9)

at the end android itself is Linux Kernel & dotnet core runs on Linux

**Comment by TimurZanagar** [comment]
@AbhimanyuAryan Why you would like to run .NET Core on Android device? I think you're looking for [https://www.xamarin.com](url).

**Comment by Petermarcu** [comment]
The community is actively working on bringing up builds for Android. You can see the issue here: https://github.com/dotnet/coreclr/issues/1097 . There are also active pull requests for it. Once the runtime is building for it, getting a bunch of the .NET Code like MVC running on top of it should just work.

**Comment by AbhimanyuAryan** [comment]
Great to hear @Petermarcu

**Comment by Petermarcu** [comment]
I'll go ahead and close this here and the work can be tracked on the issue I linked.
