### ISSUE TITLE
Do you plan to officially support ArchLinux?

### ISSUE THREAD

**Issue by aloisdg** [dotnet/core#462]
Hello,

I come back to archlinux after a quite long time. I didnt find an official package for dotnet core. Do you plan to make one? We can rely on alternative like a [docker image](https://blog.rendle.io/run-dotnet-cli-on-unsupported-linux-distros-with-docknet/) or [outdated  unofficial package](https://aur.archlinux.org/packages/coreclr-git/).

With the release of  .NET Core 1.0 – RC3, it would be a great time. Thank you!

Related to [Archlinux - Enable Support](https://github.com/dotnet/coreclr/issues/4409)

Cheers

**Comment by Petermarcu** [comment]
Probably best to track this on the issue you linked to. If as a community we are able to do the work to build for archlinux reliably, we'll be happy to start running end to end builds, running tests, and publishing outputs for it. I'm going to close this here because the first step is to get that issue in coreclr completed and then we can make it easy for folks to consume.

**Comment by aloisdg** [comment]
Ok sure.
