### ISSUE TITLE
stand alone and selfcontained, after a while; must install .net core 3.1?

### ISSUE THREAD

**Issue by ErikGrav** [dotnet/core#4670]
![IMG_3115](https://user-images.githubusercontent.com/17234673/81659715-42537080-943a-11ea-9310-7553bea0191c.jpg)

Build:  
.net core 3.1, asp.net core 3.1.3. 
Deployment mode: Self-Contained
Target Runtime Win-x64
RedyToRun, single file. 

User: win 10 x64, 1903, 18362.788

I am out of ideas of what is wrong. 
it should not need to have .net core runtime installed. ( as far as I understand it) 
It runs smoothly upon installation.  User side, my test VMs and my own development environment. 

Yet a handful of users have reported that "after not using it for a while" (say a week)  they receive the message box saying "To run this application, you must install .net core. would you like to download it now?" 
The weird part is: Even if runtime is installed, it keeps asking for it. 

Its self Contained, not runtime dependent, this should -not- be needed.

Has anyone else had this issue or ideas?

**Comment by dagood** [comment]
Single-file .NET Core 3.1 apps self-extract into a temporary folder then run from that location--I wonder if your users are getting this issue because specific files are being deleted from the temp folder in a way that makes the host think installing the runtime is the right solution, so it prompts?

Searching dotnet/runtime shows some potentially related issues: https://github.com/dotnet/runtime/issues?q=is%3Aissue+temp+label%3Aarea-Single-File

@swaroop-sridhar

**Comment by swaroop-sridhar** [comment]
@ErikGrav I think the problem here is that the files extracted into the temp-directory are partially cleaned up -- causing the application to crash because of missing files. However, it is surprising that temp-files are cleaned up after a week on Windows.

Anyway, this problem will be fixed in the upcoming servicing release .net core 3.1.4.
In the meantime, users can set DOTNET_BUNDLE_EXTRACT_BASE_DIR to a non-temp location so that the extracted files are not cleaned up by the OS.

Dup of https://github.com/dotnet/runtime/issues/3830
