### ISSUE TITLE
VS2015 Class Library?

### ISSUE THREAD

**Issue by eliashdezr** [dotnet/core#48]
When trying to add a new project to an existing solution, I cannot see .NET Core as an option.

Is there any template for this in the works? Or any information how to add a new project manually using the CLI? Can't find anything on the documentation.

**Comment by psibernetic** [comment]
Right now the templates are under the Web subsection.

**Comment by Petermarcu** [comment]
These templates are definitely in the works and as @psibernetic mentioned, they are currently under web. @Pilchie, can you confirm we're moving these to a more central location?

**Comment by Pilchie** [comment]
There will be a new ".NET Core" node that will include a "Console application (.NET Core)" template and a "Class Library (.NET Core)" template, instead of the "Console Application (package)" and "Class Library (package)" templates that are currently under Web.

I forget where we landed on also showing a web template under .NET Core.  @cartermp do you know?

cc @rchande

**Comment by cartermp** [comment]
Yup, we're going to have the ASP.NET web template under the ".NET Core" node.  When opened from there, the One ASP.NET dialog will only show ASP.NET Core templates.

@sayedihashimi have we landed on the name of the ASP.NET template under the .NET Core node being "ASP.NET Core Web Application"?

**Comment by Lewiscowles1986** [comment]
any ETA on .NET core stable, and the VS2015 tools for .NET core projects?

**Comment by sayedihashimi** [comment]
@Lewiscowles1986 we don't have a date, we are still working through it. Not trying to be secretive, just don't have any info to share currently.

**Comment by joshfree** [comment]
Closing now that .NET Core 1.0 has shipped.  Instructions can be found at http://dot.net/core.
