### ISSUE TITLE
Windows Installer doesn't install in the specified location

### ISSUE THREAD

**Issue by nikibobi** [dotnet/core#485]
I set an explicit path during installation in `F:\NETCoreSDK\` and after the installation completed the folder was empty. Then I found out that it installed it in `C:\Program Files\dotnet\` folder and that wasn't my intention.
I am using `dotnet-dev-win-x64.1.0.0-rc4-004771.exe`

**Comment by Petermarcu** [comment]
I'm not sure it was intended to be retargetable. How did you launch the installer? 

If you want to just put it in folder somewhere, I've found it much easier to just download the zip and extract it to that folder. You can also add that folder to your path if you want. Thats really all the installer does for you.

@vivmishra

**Comment by blackdwarf** [comment]
The installers are hardwired to install to a specific location due to our SxS model requirements. As @Petermarcu said, if you need to install into a specific location, you can use the zips and/or the [install script](https://dot.net/v1/dotnet-install.ps1). 

We have an issue to remove that option from the Windows installer to not confuse users.

**Comment by nikibobi** [comment]
Thanks for the info
