### ISSUE TITLE
Ошибка 

### ISSUE THREAD

**Issue by MadiyarTastanbekov** [dotnet/core#4883]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://user-images.githubusercontent.com/66208532/85933343-d3ea4500-b8f7-11ea-9552-3b382009b282.png)

**Comment by shyboylpf** [comment]
Hi, you can change a directory, or use command ` dotnet new console -o
myApp --force `

MadiyarTastanbekov <notifications@github.com> 于2020年6月28日周日 上午6:29写道：

**Comment by mairaw** [comment]
This happens when you already ran the command in that folder, so the dotnet command founds an existing project in that path. You can either use the `--force` option as @shyboylpf mentioned, or delete the myApp folder and start over. 

I'll close this issue for now but let us know if you need more help!
