### ISSUE TITLE
Enum class not automatically recognized as being in System namespace

### ISSUE THREAD

**Issue by rambotech** [dotnet/core#4896]
# Issue Title

Enum.Parse() or its other methods must be referenced as System.Enum.Parse(), despite having "using System': at the top of the code file.

# General

This behavior started in an existing project last modified in June of 2019, and appeared after an upgrade to Visual Studio 16.6.3

The project was idle for a number of months, so I am not sure this particular version of the update is the specific cause.

See StringEx.cs (lines 604 and 606) at [https://github.com/rambotech/BOG.SwissArmyKnife](https://github.com/rambotech/BOG.SwissArmyKnife/blob/develop/src/BOG.SwissArmyKnife/StringEx.cs)

This is .NET Standard 2.0, Visual Studio 16.6.3 running on Windows 10

**Comment by bartonjs** [comment]
The codefile you're complaining about is defined as being in `namespace BOG.SwissArmyKnife.Extensions`.

That's a semantic shortcut for

```C#
[your usings]

namespace BOG
{
    namespace SwissArmyKnife
    {
        namespace Extensions
        {
            [the rest of your code]
        }
    }
}
```

When evaluating typeOrNamespace names, it starts from the current namespace, then tries the current namespace's nested usings, the parent namespace scope, it's nested usings, etc, until you hit the global namespace scope usings and nothing works.

Since you have a namespace of BOG.SwissArmyKnife.Enum in the project, the best binding for that search order for the bare word Enum is that namespace.  Then it can't find a typeOrNamespace named Parse within that scope, and compilation fails.

The easiest solution is to not name your sub-namespace Enum.

**Comment by rambotech** [comment]
@bartonjs Thank you for this explanation.  I didn't realize the potential name conflict.
