### ISSUE TITLE
Unable to create new blazor app

### ISSUE THREAD

**Issue by Inthu94** [dotnet/core#4913]
I couldn't create new blazor app. It takes too long time to complete the task. Still new project is not created in Visual studio 2019 community edition. Can you give a solution to create project in Visual studio 2019 itself without using command prompt.
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Do you get any errors or does it simply not work @Inthu94? I'd like to understand better why this is not working for you since creating with the command line should be faster than VS. 

But in Visual Studio, you can search for the blazor template
![image](https://user-images.githubusercontent.com/12971179/86862833-daf31f00-c07e-11ea-9c29-dface8e5c980.png)

/cc @danroth27
