### ISSUE TITLE
.NET Core Updates via Microsoft Update channels

### ISSUE THREAD

**Issue by nakarnam** [dotnet/core#5013]
**Objective:** 
Offer .NET Core Updates for Windows Platform via the Microsoft Update Channels – Automatic Updates, WSUS and Microsoft Catalog. 

**Execution:** 
Scope includes .NET Core Runtime, SDK and the bundles (SDK plus Runtime), Hosting bundles, Desktop bundles, available via Automatic updates, WSUS updates and Microsoft Catalog. This is for both security and non-security updates. Minimum supported version is expected to be Win 7. 

For automatic updates, the plan is to offer Opt-in functionality - once a user has opted in to receiving automatic .NET core updates, the default location will receive the new updates as they are released. 

This will be independent of Visual Studio updates. .NET Core obtained via Visual Studio will continue to be updated by Visual Studio updates.

This proposal for Microsoft Update deployment is applicable to Framework dependent deployments only for .NET Core. For Self-contained deployments, where the .NET Core runtime is bundled as part of an application - the app developer is responsible for servicing this. We are working on ClickOnce support for .NET Core apps – more details at [this issue](https://github.com/dotnet/deployment-tools/issues/9).

**Comment by svick** [comment]
> For automatic updates, the plan is to offer Opt-in functionality

How exactly will that work? Are you talking about this option?

![](https://user-images.githubusercontent.com/287848/89228177-6230a580-d5df-11ea-94de-82a64f7da940.png)

Or is there going to be some .Net-specific option? If so, how is that going to be set?

**Comment by deathchurch** [comment]
Is there any rough timeline for the WSUS updating functionality? Are we talking .NET 5 or .NET 6 timelines?

**Comment by jamshedd** [comment]
@svick, here's our current thinking for the different user scenarios - 

1. Enterprise deployment (WSUS/SCCM) - 
.NET Core updates will be available under a new Category in the WSUS console (these will not be updates to the Windows OS hence new category). a An enterprise admin would either (auto) approve the category or individual updates under the category. Additionally the admin would set a switch on the end user desktop to signal what types of updates should flow automatically (security fixes only, all fixes, major/minor, etc.) and the version(s) for which these should flow automatically. Current thinking for the switch is this could be a regkey since that's what we've done for Framework in the past) and its easy to deploy via group policy.

2. end-user (AU/Site) which is what you're referring to with that switch in your screenshot
Customers would opt-in to MU itself. Additionally, the app that deploys the shared Framework (.NET Core installer) needs to set the switch to signal which updates should be automatically installed by MU. One can imagine the app developer would want servicing fixes to be installed automatically but would want to make an explicit choice about when to update to the next feature (major/minor) update.

**Comment by nakarnam** [comment]
@deathchurch this is being planned for the .NET 5 timeframe.

**Comment by deathchurch** [comment]
> @svick, here's our current thinking for the different user scenarios - 
> 
> 
> 
> 1. Enterprise deployment (WSUS/SCCM) - 
> 
> .NET Core updates will be available under a new Category in the WSUS console (these will not be updates to the Windows OS hence new category). a An enterprise admin would either (auto) approve the category or individual updates under the category. Additionally the admin would set a switch on the end user desktop to signal what types of updates should flow automatically (security fixes only, all fixes, major/minor, etc.) and the version(s) for which these should flow automatically. Current thinking for the switch is this could be a regkey since that's what we've done for Framework in the past) and its easy to deploy via group policy.

I assume the same method will be used for server deployment, this for me is where the real issue is rather than the desktop?

**Comment by ernstscheithauer** [comment]
> @deathchurch this is being planned for the .NET 5 timeframe.

Since .NET Core 3.1 has long term support and .NET 5 will not, then it will take until .NET 6 to have a long term support version with WSUS/SCCM support. This is a downer, because as an ISV with annually upgrades at the customer sites any versions without long term support are hardly an option.

Could you therefore consider supporting .NET Core 3.1 with WSUS/SCCM as well?

**Comment by jamshedd** [comment]
> I assume the same method will be used for server deployment, this for me is where the real issue is rather than the desktop?

WSUS/SCCM deployment will cover both client and server deployment.

**Comment by jamshedd** [comment]
> Could you therefore consider supporting .NET Core 3.1 with WSUS/SCCM as well?

Yes - that's the plan :)

**Comment by bachratyg** [comment]
> This will be independent of Visual Studio updates. .NET Core obtained via Visual Studio will continue to be updated by Visual Studio updates.

What is the patching strategy for Build Tools? I guess since it gets installed throug the same VS Installer as full VS it won't be updated through WU.

**Comment by jamshedd** [comment]
@bachratyg, if by build tools you mean the .NET Core SDK then that will be patched via MU as long as it was installed outside of of Visual Studio. If on the other hand you were referring to the VS build tools SKU then that is patched like any other VS SKU, via a VS update.

**Comment by bachratyg** [comment]
Yes, I meant the latter, thanks for the clarification.

VS Build Tools are usually installed on a CI server and as such out of sight. Would it be possible to install the SDK separately (that gets patched by MU) then install VS Build Tools that reuses the existing SDK installation instead of deploying its own? For the NET Core workload the SDK is mandatory.

**Comment by DM2489** [comment]
Will this fix sites being dead when new .NET core hosting bundles are installed on servers? We've had issues with the recent hosting bundles where installing them has killed off sites. It's been a nightmare to try and figure out why. When the issue strikes, we have to manually remove all instances of the .NET core hosting bundle from the affected server and manually install the latest bundle. It's highly annoying as it is inconsistent, takes sites offline.

**Comment by leonardder** [comment]
Is this still in scope for .NET 5.0?

**Comment by deathchurch** [comment]
Is there any further update to this now .NET Core 5 has been released?

**Comment by leonardder** [comment]
I'm also looking forward to an update on this, as our company is in the 
process of deciding how to deal with .NET updates in the near and 
distant future.

**Comment by jamshedd** [comment]
I wanted to share an update on this. We just shipped .NET 5.0 yesterday. As I mentioned earlier we're working on adding support for deploying updates for .NET Core 2.1, 3.1, and 5.0 via Microsoft Update. You're probably familiar with our "patch Tuesday" release cycle, we ship updates on the second Tuesday of each month, we plan to ship the first patch for .NET 5.0 on patch Tuesday i.e. 12/8, and it is our goal that we ship the patch (for Windows) via Microsoft Update in addition to the usual download channels. 

We're furiously working on this and since the work is not all done there's a small possibility we don't make it in time for December or we find a last minute issue we need to address in which case we would deliver updates on MU starting January instead of December, but in either case this is coming pretty soon within the next 2 months.

We plan to put together a blog post detailing what you should expect in terms of experience and will get that out a week or so ahead of the first MU update.

**Comment by cremor** [comment]
The blog post is now up: https://devblogs.microsoft.com/dotnet/net-core-updates-coming-to-microsoft-update/
Thanks!

**Comment by jamshedd** [comment]
Given that the work here is mostly done and we're expecting to ship 5.0.1 next week and MU updates for 3.1 and 2.1 in Jan I'm going to close out this issue now.

**Comment by deathchurch** [comment]
@jamshedd is there any news on when the Hosting Bundle will be included with WU?

**Comment by jamshedd** [comment]
@deathchurch, I do not have an update to share on the hosting bundle. I do want to share something else though - the hosting bundle is just a wrapper around 3 other installers - the .NET Core Runtime, ASP.NET Core Runtime, and the ASP.NET Core Module (ANCM) for IIS. The first 2 (.NET Core runtime and ASP.NET Core runtime) are already individually deployable via MU (including if you deployed the hosting bundle previously these components will be updated via their stand alone installers on MU).  

The third piece - ANCM is not on MU, but this is not a component that changes often. Since there can only be 1 copy of ANCM at any time, the compat bar is very high and this component is updated very infrequently, usually just once a year. We have not shipped any updates to the ANCM component since the summer of 2020 and certainly nothing since we started shipping updates on MU. So even if we had the entire hosting bundle were available MU the bits you install would be no different than what you're already getting today from MU. To summarize, you should deploy the .NET Core runtime and ASP.NET Core runtime from MU just like you would the hosting bundle.

**Comment by ernstscheithauer** [comment]
Thanks for sharing that @jamshedd

One question to make sure I got it right: So I can install the hosting bundle and after this, the two components that usually get changed are patched using Windows Update? I just don't see the version number of "Microsoft .NET Core 3.1.14 - Windows Server Hosting" change in Control-Panel - "Programs and Features"?

I ask this because I only see one of the 3 installers mentioned by you in the software list, the "Microsoft .NET Core Runtime" but not any of the two "ASP.NET Core...." installers you mentioned.

Since patching .NET Core is relevant for security I need to make sure there is no misunderstanding.

**Comment by bachratyg** [comment]
> Since there can only be 1 copy of ANCM at any time, the compat bar is very high and this component is updated very infrequently, usually just once a year.

Does this include the older v1 module? If I change the handler in web.config to point to the v2 module for a legacy app (aspnetcore2.1 on net48, out of process hosting) would it work? Or should I still use the 2.1 hosting bundle?

**Comment by jamshedd** [comment]
@bachratyg The latest ANCM always works with older runtimes, for eg. if you have 2.1, 3.1 and 5.0 installed then the 5.0 hosting bundle always has the latest ANCM and that works with all 3 runtimes. So you can install the hosting bundle corresponding to the highest runtime you plan to use.

**Comment by jamshedd** [comment]
> Thanks for sharing that @jamshedd
> 
> One question to make sure I got it right: So I can install the hosting bundle and after this, the two components that usually get changed are patched using Windows Update? I just don't see the version number of "Microsoft .NET Core 3.1.14 - Windows Server Hosting" change in Control-Panel - "Programs and Features"?
> 
> I ask this because I only see one of the 3 installers mentioned by you in the software list, the "Microsoft .NET Core Runtime" but not any of the two "ASP.NET Core...." installers you mentioned.
> 
> Since patching .NET Core is relevant for security I need to make sure there is no misunderstanding.

@ernstscheithauer, that's exactly right. Once run the hosting bundle it will run 3 internal installers - for the .NET Core runtime, ASP.NET Core runtime, and ANCM. Once these 3 are installed they can be individually updated via MU. We have shipped updates for both the .NET Core runtime and ASP.NET Core runtime and those would get offered and installed.

You can check the version of the .NET Core runtime is updated by using the CLI: dotnet --list-runtimes

**Comment by deathchurch** [comment]
So for the ANCM package is the best place to check for updates to that on the get dotnet download page?

**Comment by jamshedd** [comment]
ANCM doesn't ship stand-alone, it ships only as part of the hosting bundle. We've not had any ANCM fixes since we started shipping on MU back in Dec 2020. So if you were to take the latest hosting bundle it will install the same version as 6 months ago.

**Comment by deathchurch** [comment]
@jamshedd thanks for the replies and additional info, I think I am almost there, but for this last query.

If MU takes care of .NET Core and ASP.NET Core runtimes, that is fine, but as you say it does not currently take care of the hosting bundle which is the only way that the ANCM is updated, there could be a false pretence that you are feeling you are keeping up to date with MU but maybe once a year this will not be case as the ANCM might be updated and the only way to get that update is by manually downloading and running the hosting bundle again., is this correct?

**Comment by asymmetricblue** [comment]
@jamshedd in your blog post last November, you wrote:
"The third component not independently serviced outside the hosting bundle – ASP.NET Core Module (ANCM) does not need frequent servicing, **and we plan to enable MU updates for the hosting bundle before we need to service this.**"

Given that the hosting bundle will need to change for .NET 6 this fall, is it safe to assume that this is still a target for that time frame?

Is there another issue number we could be tracking that addresses this last piece?

**Comment by jamshedd** [comment]
@asymmetricblue , the bug blocking delivery of the hosting bundle via MU is being tracked by this issue:

https://github.com/dotnet/aspnetcore/issues/28537#issuecomment-838772912

**Comment by TuminD** [comment]
Hi

> and we plan to enable MU updates for the hosting bundle before we need to service this.

1. @jamshedd, are there any news about this? 
Or it is postponed due to [dotnet/aspnetcore#28537 (comment)](https://github.com/dotnet/aspnetcore/issues/28537#issuecomment-838772912)

> The first 2 (.NET Core runtime and ASP.NET Core runtime) are already individually deployable via MU (including if you deployed the hosting bundle previously these components will be updated via their stand alone installers on MU).

2. We've installed hosting bundle (v.3.1.14) on some web-servers and then approved Net Core updates (v.3.1.21 - kb5007885) via WSUS - .NET Core runtime was replaced by new version, but ASP.NET Core runtime was installed side by side - is there some issue with updating Net Core via wsus or is this the expected behavior?

dotnet --info output before update:

```
Host (useful for support):
  Version: 3.1.14
  Commit:  826c2c2f8f

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

dotnet --info output after update:

```
Host (useful for support):
  Version: 3.1.21
  Commit:  df8abc0f7e

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by jamshedd** [comment]
We do intend to start offering the hosting bundle via MU starting with December's updates. That said I do not think the issue you're seeing is relevant to that. If you have another machine without the update, can you share the output of dotnet --info both before and after for the x86 version i.e. run dotnet --info from Program Files (x86)\dotnet instead of Program Files.

**Comment by TuminD** [comment]
I found something similar (update 3.1.18 -> 3.1.21):

**Before update (x86 version):**
```
C:\Program Files (x86)\dotnet>dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.18
  Commit:  5d3919d34e

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
```
**After update (x86 version):**
```
C:\Program Files (x86)\dotnet>dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.21
  Commit:  df8abc0f7e

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
```
**Before update (x64 version):**
```
C:\Program Files\dotnet>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.412
 Commit:    751fd182ef

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.412\

Host (useful for support):
  Version: 3.1.18
  Commit:  5d3919d34e

.NET Core SDKs installed:
  3.1.412 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
**After update (x64 version):**
```
C:\Program Files\dotnet>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.415
 Commit:    52a108342e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.415\

Host (useful for support):
  Version: 3.1.21
  Commit:  df8abc0f7e

.NET Core SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by jamshedd** [comment]
@wtgodbe , this shouldn't happen after the fix to include the ASP.NET Core runtime bundle inside the hosting bundle?

**Comment by TuminD** [comment]
Hi,

> hosting bundle updates should now always update the installed asp.net runtime

@jamshedd, @wtgodbe, "_should now always update the installed asp.net runtime_" - that is, beginning with the next release\update?

**Comment by wtgodbe** [comment]
This should have started with the November release

**Comment by EamonNerbonne** [comment]
Given the hosting module's security advisory that was just released, what's the status on rolling out ANCM (asp.net core module) updates via microsoft update?

Ref:

 - https://github.com/dotnet/aspnetcore/issues/39028
 - https://github.com/dotnet/announcements/issues/206

**Comment by jamshedd** [comment]
@EamonNerbonne , take a look at the blog post announcing this release: https://devblogs.microsoft.com/dotnet/december-2021-updates/, we call out the hosting bundle is now available on MU :)

**Comment by EamonNerbonne** [comment]
Hmm, it's not getting installed here; I have "Give me updates for other Microsoft products when I update Windows" option enabled; other updates are getting installed (e.g. KB5008218), but the file version of aspnetcorev2.dll is still 16.0.21299.

Perhaps relevant: that blog post talks of updates to "the Hosting Bundle"; however, I've installed the asp.net core module v2 via https://community.chocolatey.org/packages/dotnet-aspnetcoremodule-v2, and not e.g. the full hosting bundle (which would be choco package https://community.chocolatey.org/packages/dotnet-windowshosting) - is the ACNM installed separately not updated, but is when installed as part of the hosting bundle?

**Comment by jamshedd** [comment]
We don't explicitly block offering the update to machines that installed ANCM via a package manager like chocolatey, but I cannot say whether it should or should not work since we do not test for that. The scenario we support is where you install our hosting bundle. 

Are you using MU (client) or WSUS? If the latter you will need to download and approve the Software category for .NET 6.0.

**Comment by EamonNerbonne** [comment]
I'm using the client MU on a server 2019 test VM; perhaps that's the issue.  Anyhow, it's of course easy to upgrade via chocolatey too, but I was interested whether it would work had I not done so.  I tried installing the hosting bundle separately and then checking for upgrades, and that didn't work either. In any case: thanks for the response; I'll apply the update manually now - so my specific issues are moot.

**Comment by jamshedd** [comment]
Yes that is the issue and it is by design - we do not offer .NET Core updates via MU client to Server OS versions, they're only offered to client OS versions. For Server we offer updates via WSUS only. Most customers do not want their servers automatically updated by MU.

**Comment by mess84** [comment]
I'm going to counter argue Hosting Bundle being updated... We are seeing the same behaviour, Hosting Bundle is *not* updated.
The underlying ASP.NET Core Shared Frameworks (x64 & x86) are updated.
The underlying .NET Core Runtimes (x64 & x86) are updated.
This is leaving behind aspnetcorev2.dll (under C:\Program Files\IIS\Asp.Net Core Module\V2) on the original vulnerable version.
![image](https://user-images.githubusercontent.com/97301354/148569958-f3a1618b-a086-4f3d-94ef-a8aa7e7267c3.png)
This particular server is patched via SCCM (CB) up until today we have not been syncing the WSUS classification/products for dotnet core. I have turned it on today, forced a SUP sync and created and ADR which is targeting a couple of test machines.

SUP Config:
![image](https://user-images.githubusercontent.com/97301354/148570506-80562e5c-a887-49ad-8862-a263fcba2ab6.png)

![image](https://user-images.githubusercontent.com/97301354/148570862-21b07843-6fd7-4ce1-a32e-cf00bb8ea4e9.png)

I was expecting to see 3.1.22 also? But it appears only 3.1.21 is available via WSUS? and no hosting bundle / ANCM at all?! This could lull a lot of people into a false sense of security. Has 3.1.22 been pulled / ever published via WSUS?
