### ISSUE TITLE
.NET Core 3.1 projects fails on restore on Debian Linux 9

### ISSUE THREAD

**Issue by efgiese** [dotnet/core#5062]
After upgrading the SDK to .NET Core 3.1.401 (v3.17) any project with the target _netcoreapp3.1_ fails on restore. On my system (Debian 9) are SDK 2.2.402 and SDK 2.1.x additional installed. The project with SDK 2.2 works properly. 
I am working with VSCode 1.4.3.

I have generated a new project:

`dotnet new webapi -o testapp` and run `dotnet restore`

I opened it in VSCode and it shows many errors because it can not find the modules like 'System' etc. I could build the project, but code intellisense do not work.

**Comment by Frisch12** [comment]
We encountered the same issue on 3.1.401 so we changed our docker files back to 3.1.301 and on 2.1.809 so we changed them back to 2.1.808. 
Furthermore we observed a misbehavior in nuget package resolving. We are using an external Package.props file for all our projects so we can pin package versions for all Projects at once. Since the docker images were automatically updated this did not work anymore so the "restore" action resolves to the wrong versions.

**Comment by svick** [comment]
Do you see any errors in OmniSharp Log inside VS Code under the Output view? Does it help if you restart VS Code after you successfully build the project?

**Comment by efgiese** [comment]
No OmniSharp - errors but a lot of errors like "Predefined type 'System.String' is not defined or imported". I have updated all PackageReferences, but no luck.

**Comment by efgiese** [comment]
I fixed it with `"omnisharp.useGlobalMono": "never"` in preferences
