### ISSUE TITLE
[BUG] Not catching System.Net.WebException

### ISSUE THREAD

**Issue by Banyc** [dotnet/core#5076]
# Not catching System.Net.WebException

Not catching System.Net.WebException.

## Reproduce

1. Go to `appsettings.json`
1. Set `SecondsBeforeTimeout` to 1
1. Uncomment out the statement <https://github.com/Banyc/LinkDownloader/blob/master/src/LinkDownloader/App.cs#L147>
1. Comment out the statement <https://github.com/Banyc/LinkDownloader/blob/master/src/LinkDownloader/App.cs#L152>
1. run `dotnet run`

**Comment by svick** [comment]
When I run the code, no exceptions are thrown, so it makes sense that no exception is caught.

I think the reason why there is no exception is that you're setting `WebRequest.Timeout` and then making an asynchronous request, but [the documentation says](https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest.timeout?view=netcore-3.1#remarks):

> The `Timeout` property affects only synchronous requests made with the `GetResponse` method.

I'd suggest you to use `HttpClient` instead of `WebClient`, it shouldn't have this kind of pitfalls.

**Comment by Banyc** [comment]
> When I run the code, no exceptions are thrown, so it makes sense that no exception is caught.
> 
> I think the reason why there is no exception is that you're setting `WebRequest.Timeout` and then making an asynchronous request, but [the documentation says](https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest.timeout?view=netcore-3.1#remarks):
> 
> > The `Timeout` property affects only synchronous requests made with the `GetResponse` method.
> 
> I'd suggest you to use `HttpClient` instead of `WebClient`, it shouldn't have this kind of pitfalls.

If that's the case, I would recommend making this class `WebClient` deprecated and guides users to use `HttpClient` instead.

**Comment by svick** [comment]
@Banyc I think deprecating it wouldn't be practical, because it's quite widely used. But one of the first things in [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient#remarks) says:

>  **Important**
>
> We don't recommend that you use the `WebClient` class for new development. Instead, use the `System.Net.Http.HttpClient` class.
