### ISSUE TITLE
Provide a method to dynamically load libraries and obtain delegates to its exports from within code

### ISSUE THREAD

**Issue by bastos80** [dotnet/core#5140]
I searched all over and could not find a way of doing this without hacks.

What I would like is to be able to **load a library from code** (dll/dylib/etc.), obtain delegates to that library's exported functions.

For example:

```c#
var Lib = Marshal.LoadLibrary ( "/usr/lib/libobjc.dylib" );
var Function = Lib.FunctionFromEntryPoint ( "objc_msgSend", CallingConvention.Cdecl );
var Result = Function.Invoke ( arg1, arg2 );
```

Now, I realize that this would require to somehow specify MarshalAs information for arguments, perhaps through an additional array argument on the invoke call?

So basically this would be the dynamic version of the DllImportAttribute.

Perhaps this functionality has been suggested before, but if so, I couldn't find it.

**Comment by svick** [comment]
This already exists. .Net Core 3.0 introduced [`NativeLibrary`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary?view=netcore-3.1&WT.mc_id=DOP-MVP-5002735), which lets you load a library dynamically (using `NativeLibrary.Load`) and get an exported symbol from it (using `NativeLibrary.GetExport`). You can then get a delegate to it using [`Marshal.GetDelegateForFunctionPointer`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getdelegateforfunctionpointer?view=netcore-3.1&WT.mc_id=DOP-MVP-5002735). And in C# 9.0, you'll also be able to use [a function pointer](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/function-pointers?WT.mc_id=DOP-MVP-5002735) instead of a delegate. I *think* the intention is that function pointers are low-level, so you'll need to do most of the marshaling yourself. (Or at least I didn't figure out how to make it marshal `string` as UTF-16 `LPCWSTR`.)

Here is an example of how that works (Windows-based, because I don't have access to a Mac):

```c#
using System;
using System.Runtime.InteropServices;

unsafe class Program
{
    [UnmanagedFunctionPointerAttribute(CallingConvention.StdCall, CharSet = CharSet.Ansi)]
    delegate int MessageBox(IntPtr hWnd, string lpText, string lpCaption, uint uType);

    static void Main()
    {
        string text = "Command-line message box";
        string caption = "Attention!";

        var lib = NativeLibrary.Load("user32.dll");
        var function = NativeLibrary.GetExport(lib, "MessageBoxA");

        var @delegate = Marshal.GetDelegateForFunctionPointer<MessageBox>(function);
        @delegate(IntPtr.Zero, text, caption, 0);

        var functionPointer = (delegate* unmanaged[Stdcall] <IntPtr, string, string, uint, int>)function;
        functionPointer(IntPtr.Zero, text, caption, 0);

        NativeLibrary.Free(lib);
    }
}
```

**Comment by carlossanlop** [comment]
Closing since it's been answered.
