### ISSUE TITLE
.Net 5 and further VSTO

### ISSUE THREAD

**Issue by EuroEager2008** [dotnet/core#5156]
Are there any plans for including VSTO or similar framework supporting .Net 5 and up?

The rationale for this is obviously the ability of using future .NET functionalities.
Another aspect of this is that net 4.8 (currently the newest framework that VSTO may be based on) supports .net standard only up to 2.0 which does not enable the usage of libraries based on .Net 5 and up (and Core 3.1 for that matter) which may be very beneficial also for the cross-platform aspect of such library (possibly being consumed by something other than VSTO of course).

**Comment by Alex-ley** [comment]
Some clarity on this would be very useful.

**Comment by carlossanlop** [comment]
@AaronRobinsonMSFT is this something you could help answer? (Office Interop)

**Comment by AaronRobinsonMSFT** [comment]
The best person to discuss our plans for VSTO is @richlander.

**Comment by carlossanlop** [comment]
Ping @richlander

**Comment by KiranHyd** [comment]
@richlander Can you please answer this ?

**Comment by ernstscheithauer** [comment]
https://developercommunity.visualstudio.com/idea/757925/please-port-visual-studio-tools-for-office-vsto-to.html

+1 from me for implementing this

**Comment by richlander** [comment]
We don't have a plan for this yet, but we are looking into it and have discussed it initially with Office.. I have nothing to share yet. It's a good question.

**Comment by dan-vasilov** [comment]
Please consider open sourcing VSTO, I think many of us will be eager to help with porting it to .NET 5 and newer versions.

**Comment by herbfickes** [comment]
Please do this.  We have a large VSTO addin for Word that could benefit from a number of .Net Core features.

**Comment by schmitch** [comment]
@richlander 

> We don't have a plan for this yet, but we are looking into it and have discussed it initially with Office.. I have nothing to share yet. It's a good question.

unfortunatly outlook office-js addin does only work with EXO and Exchange Servers (https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/requirements-for-running-office-add-ins, https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/requirements-for-running-office-add-ins) until that is lifted, it's basically impossible to create **all** stuff with office-js.
We actually have a plugin that can archive mails via office-js unfortunatly because of that madness we also develop a VSTO addin.

**Comment by JSWorkspace1** [comment]
Just to cross-reference and show the importance of this. There is a Feature request over on the Visual-Studio Developer Community  Site  with close to 100 up votes and many lengthy developer stories  for wanting this feature: https://developercommunity.visualstudio.com/idea/757925/please-port-visual-studio-tools-for-office-vsto-to.html

**Comment by tefaye** [comment]
This is a huge deal for us. We sell software that includes Office integrations built with VSTO. Unfortunately we are unable to use the OfficeJS APIs because they are too limited and, frankly, our customers expect an integrated solution that simply can't be delivered with OfficeJS.

We are seeing demand for our software on ARM-powered devices (e.g. Surface Pro X) and are looking to migrate to .NET 5/6 to take advantage of WPF on ARM64 native. The current .NET Framework WPF emulated experience is pretty much unusable for our workloads, so migrating to .NET 5/6 is our only option. We have pretty much exhausted our options having spent the last 3 months working with Microsoft App Assure.

Because there is no VSTO support in .NET 5/6 we cannot migrate and our customers cannot use ARM-based devices.

I think the lack of VSTO support in .NET 5/6 is a bigger issue than you realize.

**Comment by alpensturm** [comment]
We have a large scale Outlook VSTO PlugIn that we need to migrate from .NET4 and Win Forms to .NET 5/6, so updating or porting the VSTO tools  to .NET 5/6 is a much needed feature for us, we have no viable alternatives and would greatly appreciate this move forward! Thanks, cheers!

**Comment by tommcq** [comment]
This is vital to maintain compatibility with partner companies and partner projects who are targeting .NET5/6, counting on the VSTO developer/integration company(s) to be compatible with their codebase.  

This is a huge issue here; 
the subject of time consuming workarounds; 
the perception of "legacy" provider; 
and a significant cost impact for all concerned.

**Comment by AaronRobinsonMSFT** [comment]
We want to thank everyone for their comments and votes on this. We have also received this feedback on other forums and wanted to provide you with an update.
 
The VSTO/COM Add-Ins platform is very important to Microsoft, and we plan to continue to support it in Office with .NET Framework 4.8 as the last major version. If you have existing .NET Framework solutions that you are maintaining, there is no need to move them to .NET Core and .NET 5+. We will continue to both service and support .NET Framework. You can find more details here: https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/
 
However, VSTO/COM Add-Ins cannot be created with .NET Core and .NET 5+. This is because .NET Core/.NET 5+ cannot work together with .NET Framework in the same process and may lead to add-in load failures. Microsoft will not be updating VSTO or the COM Add-in platform to use .NET Core or .NET 5+. You can take advantage of .NET Core and .NET 5+, including ASP.NET Core, to create the server side of Office Web Add-ins.
 
The VSTO/COM Add-Ins platform was built before today's cross-platform world. Moving forward, we need to provide the ability for developers to take advantage of opportunities with cloud-centered, cross-platform, and cross-device development. The recommendation moving forward is to use the cross-platform JavaScript APIs. More can be found here: https://docs.microsoft.com/office/dev/add-ins/overview/office-add-ins
 
Again, we appreciate the developer passion around VSTO/COM Add-In platform, and we will continue supporting COM/VSTO Add-In platform.
