### ISSUE TITLE
Dot net core referencing projects

### ISSUE THREAD

**Issue by PeterKottas** [dotnet/core#517]
Good morning all.

I have been seeing a weird problem lately, probably the most unexplainable I've ever seen tbh and I am very much seeking any help anybody can provide. The issue is actually quite complex and no matter how I tried to explain it in text form, I always failed. It looks like something interconnected between dotnet core, visual studio, nuget (maybe) and who knows what else. That's why I've recorded my screen and I am hoping  it will help you understand what I am struggling with. 

https://www.youtube.com/watch?v=t4nkKYYxY_0

Info about system:
.NET Core 1.1 SDK
win 8 64bit
vs 2015 community (although as I've said, this will fail with command line as well)

**Comment by PeterKottas** [comment]
Yeah ... you know what they say. Try everything, bang your head against the table for 2 days. Then submit a bug to github and be sure you'll figure it out in 5 minutes yourself. 
So through tears ... Here's the solution :
My global.json was missing "Source/Common/Hosts" in it. Therefore this, the final version now works ok:
{
  "projects": [ 
"Source\\Services", 
"Source\\Tests\\Services", 
"Source/Common", 
"Source/Common/Hosts", 
"Source/Plugins", 
"Source/Proxies",
 "Source/Tests" ],
  "sdk": {
  }
}

**Comment by PeterKottas** [comment]
And it stopped working again. What the hell? Reopening the issue as it's not resolved and there might even be some sort of instability around it.

**Comment by Petermarcu** [comment]
@PeterKottas , my best recommendation is to use the RC4 build and migrate your solution to csproj instead of project.json. There were lots of bugs around referencing from library to library in the project.json world and the best thing to get support on is the new project system. There is a dotnet migrate command that should make it easy to convert. You just need to get VS 2017 Community installed for a VS experience that will also install the command line tools.

Hope that helps.

**Comment by PeterKottas** [comment]
Thanks @Petermarcu . Sounds fair. Tbh I was expecting this to happen and just trying to buy time :) I will update and let you know if the problem persists.

**Comment by PeterKottas** [comment]
Solved by upgrading to vs17 and rc4. Thanks
