### ISSUE TITLE
I can't run the following command

### ISSUE THREAD

**Issue by AbelSaul** [dotnet/core#5183]
I can't run this command, blank spaces appear when I put the $ sign in the password.

Before
Scaffold-DbContext "Server=tcp:iappserver.database.windows.net,1433;Initial Catalog=demo;Persist Security Info=False;User ID=demo;Password=demo$$240;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" Microsoft.EntityFrameworkCore.SqlServer -F

After
Scaffold-DbContext "Server=tcp:iappserver.database.windows.net,1433;Initial Catalog=demo;Persist Security Info=False;User ID=demo;Password=demo$
$240;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" Microsoft.EntityFrameworkCore.SqlServer -F

**Comment by GrabYourPitchforks** [comment]
__\$__ represents a variable in Powershell, and if it appears in a string containing double-quotes like `"Hello, $Name!"` substitution will be performed during evaluation. Use single quotes instead of double quotes to avoid the substitution process and to treat embedded \$ characters as literals. See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules for more information.

Reminder: GitHub issues are public. Please do not include real credentials in GitHub issues. If you accidentally provided a live credential, please do not edit the issue (since the edit history is also public). Instead, change the credentials in the server itself.
