### ISSUE TITLE
why has Microsoft gotten so lazy that we have to do all this ourselves I am not a coder nor do I know anyone who is even able to help with this stuff

### ISSUE THREAD

**Issue by DTMENNIS** [dotnet/core#5313]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
How did you end up in this tutorial @DTMENNIS? This tutorial is supposed to be for people wanting to learn how to develop.

I'm trying to figure out if in some tool or process we're sending people to this page when we shouldn't.

**Comment by riddletom76** [comment]
@mairaw I think the issue is related to the fact that whenever a new dotnet core app is created, by default it has the hello world and people visit the page with an expectation to get a tutorial, whereas all they get is the instruction to create and run the app which is confusing for people just starting out with dotnet.
