### ISSUE TITLE
Epic: Enable Power Platform Scenarios with HTTP APIs

### ISSUE THREAD

**Issue by bradygaster** [dotnet/core#5367]
Since November 2019, we’ve done significant work to improve the overall end-to-end experience for developers who need to extend PowerApps (or any other Power Platform resource). The goals of this multi-organization partnership spanning DevDiv, Azure, and Power Platform, have been to enable the following application development scenario: 

1. A citizen developer needs to build a business app using PowerApps. 
2. The PowerApp needs to use existing application infrastructure, so the citizen dev works with a .NET developer who is either building or who has already built and deployed an existing HTTP API. 
3. The API developer creates a PowerApps Custom Connector to give the citizen developer a connection to the HTTP API. 
4. The citizen developer uses the connection to the HTTP API to build their PowerApp. 
5. The citizen developer makes the PowerApp available to users in their enterprise via Teams. 

Since the partnership began in November, we’ve accomplished significant strides across all partner teams, and now ASP.NET Core Web API customers have a clear path to getting HTTP APIs published into Azure API Management, which makes them easy to ingest into PowerApps.  

User Stories under this Experience:

- [ ] [As an HTTP API developer using Open API to enable integration, my APIs include an opinionated convention of ensuring operationId attributes are created for each Web API controller method](https://github.com/dotnet/core/issues/5411).

**Comment by ltouro** [comment]
**disseminate async request-reply pattern**

A common scenario for APIs is to have async operations. 

In order to ease the use of such APIs, Power Automate allows the usage of a simple "async request-reply" pattern, which consists using 202 response codes along with a Location header. (see https://docs.microsoft.com/en-us/azure/architecture/patterns/async-request-reply)

From personal experience, such pattern seems to not be very well-known altough very useful in different scenarios. I have seem people implementing this pattern "manually" in different "flows", which leads to more bloated workflows and thus, increases maintenance costs. 

I think it would be great if the .NET tooling could provide generators or samples to help disseminate this use case (for instance, Azure Functions CLI tool, which inclused function generators).

__As an HTTP API developer using Open API to enable integration, my APIs include an easy-to-learn and easy-to-use async request-reply pattern that allows me to expose long-running operations more easily to no-code/low-code platforms, such as Power Automate._

**Comment by danmosemsft** [comment]
@bradygaster can you set engineering owner(s)? Is this all on ASP.NET?

**Comment by bradygaster** [comment]
cc @mkArtakMSFT - the only .NET team item here would be a small set of updates [but ones with significantly positive impact to Open API fidelity] to the Web API template and potentially the scaffolders. Between @mkArtakMSFT and @vijayrkn we're covered.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
