### ISSUE TITLE
pyodbc packages failing due to ODBC connection

### ISSUE THREAD

**Issue by mohansiddegowda** [dotnet/core#5371]
# ODBC packages having issue

ODBC drivers are not downloaded entirely and it says missing index files and error's out causing odbc not to work.

Below is the path we use for downloading packages

By the update date, looks it was code was updated recently.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/27874467/96215569-fa35fe00-0f43-11eb-876f-8824c6416fb2.png)

https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages

Also please check the error message in the screenshot

**Comment by carlossanlop** [comment]
@dagood is this something you could help with?

**Comment by dagood** [comment]
Based on timing (13 days ago), this was probably related to a packages.microsoft.com outage that also hit the Ubuntu 18.04 and 20.04 repos: https://github.com/dotnet/core/issues/5373. We aren't involved with any `msodbcsql17` package, but it seems to share the same underlying services as the .NET packages.

That outage was resolved within about a day. @mohansiddegowda, can you try again?

(Side note: please post text rather than screenshots in the future. I sometimes use searches to link together related issues when an outage happens, but I wasn't able to find this issue because all the useful information is in a screenshot. Also, if we did need to follow up, it helps to have text that we can copy.)

**Comment by carlossanlop** [comment]
No reply in 9 days. I suppose the outage is gone, we haven't heard any more about this. Closing.
