### ISSUE TITLE
Epic: Path to migrate an app from Framework to .NET 6.0 is well understood and streamlined

### ISSUE THREAD

**Issue by cathysull** [dotnet/core#5396]
The team has just released (on 2/25) a Preview of a tool to help developers migrate their .NET Framework apps to .NET 5.

Take a look at the tool here (and share your thoughts and feedback in that repo).

https://github.com/dotnet/upgrade-assistant

# User Stories

- [ ] As a developer, I get compile time diagnostics for unsupported APIs https://github.com/dotnet/runtime/issues/47228

**Comment by rgwood** [comment]
A story suggestion for this epic (or a related one?): **Office VSTO add-ins can be ported to .NET 5/6**. Until this is possible many enterprise devs will remain stuck on Framework.

**Comment by govert** [comment]
One frustrating aspect of migrating to .NET 5+ is the handling and state of documentation for PlatformNotSupported APIs. As an example, I use the API `CodeDomCompiler.CompileAssemblyToSource`. This API is not supported under .NET Core (see  https://github.com/dotnet/runtime/issues/18768). I understand this and have no problem that the API is not supported in .NET Core.

However, the development experience when migrating, and state of documentation around this (as an example) is terrible.
* My code compiles for the .net5.0-windows target framework with no without warnings or errors.
* At runtime I get a PlatformNotSupprtedException.
* The [documentation for the relevant API](https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.codedomprovider.compileassemblyfromsource?view=dotnet-plat-ext-5.0#System_CodeDom_Compiler_CodeDomProvider_CompileAssemblyFromSource_System_CodeDom_Compiler_CompilerParameters_System_String___) gives not indication that this API has any issues under .NET 5 - it all seems supported. There is no indication whether this or an adjacent API might be a replacement, or that the whole compile feature has not been ported.
* When I run my project through the Portability Analyzer does not pick this up, since the API stub exists (unhelpfully) on .NET 5.
* I can Google enough to figure out what's going on eventually, but basically the compiler and documentation have both failed to help me migrate.

Some suggestions:
* The API documentation should clearly indicate when a feature is not supported on some target frameworks and platforms. Having an API stub so that it compiles is not 'supported'.
* This list of unsupported APIs https://docs.microsoft.com/en-us/dotnet/core/compatibility/unsupported-apis need to be linked back from the individual API pages, so that the status of adjacent APIs is easier to discover.
* APIs that are not supported on the target platform should give an error (or at least a warning) at compile time. It was decided by the .NET Core team as a design decision not to mark these as 'obsolete' so that warnings are not generated, which might stop  the compile if warning-as-errors is set. This decision must be revisited - success at compile-time when you know it will certainly (or possibly) fail at runtime is no help. 
* I would prefer a clear indication in the .NET docs front pages that there is an old world (.NET Framework), and a new world (.NET Core / .NET 5+), and that there is the list of things that are different. The current approach hides this change, making it hard for a new (or old) developer to see why an an API or code snippet they found somewhere doesn't work anymore.

**Comment by govert** [comment]
@terrajobst added a user-story that covers most of my suggestions above https://github.com/dotnet/runtime/issues/47228 , so that issue might be one of the user stories here too (considering Framework -> Core as a kind of cross platform scenario).

**Comment by pappasa** [comment]
Please provide a path for migrating COM+ (System.EnterpriseServices) applications. Especially a path to migrate distributed transactions.

**Comment by jjmanton** [comment]
@cathysull One of the biggest challenges we have is in the project system. Our ASP.NET Framework applications cant run on an SDK style project, and that hinders us from adopting all the new tooling. While on the surface this seems trivial, but we have 300+ projects in a solution, and are slowly trying to get our infrastructure and build CI on the latest tooling so we can slowly start porting more and more projects to `netstandard`.

This issue on project-system seems to be by FAR the most requested feature, but the community has not seen any support from Microsoft. Would it be possible for MS to host (on GitHub) or "bless" the work done by the community so far?

https://github.com/dotnet/project-system/issues/2670

**Comment by terrajobst** [comment]
Two questions:

1. Have you considered moving your ASP.NET projects to ASP.NET Core on top of .NET Framework first?
2. What prevents you from porting your libraries from .NET Framework to .NET Standard (or multi-targeting them to .NET Framework & .NET Standard)? I'd think you can do this without porting the applications.

**Comment by jjmanton** [comment]
@terrajobst Great questions. And we are definitely pursuing both! 

- On the ASP.NET side, I have one of our smaller web projects that I am already working on. There will be more to come once we prove that there aren't any major hiccups in the pipeline and deployment. A few web applications will never make it to Core, and I think we are OK with that.
- On the library side, we have a number of APIs and NuGet dependencies in our "edge of the tree" that aren't compatible with NetStandard. We have one library that is included virtually everywhere, that only scores about a 74% on the Portability Analyzer. We have a significant dependency on MSMQ we need to solve as well.

My hope on the Project system side would be tooling consistency. Can we get to a point where all our CI, build pipeline, and developer day to day is based on `dotnet` instead of msbuild.exe, nuget.exe, and various others? We already have 90-95% of our solution contains SDK style projects, and we are just in limbo on the last few.

Happy to share more if you want to learn about our challenges, jmanton at VMware dot com

**Comment by terrajobst** [comment]
The challenge is that we don't plan to ever support all of the .NET Framework tooling with dotnet.exe and the .NET SDK. There is a difference between allowing libraries to target .NET Framework and, for example, having support for the old WCF designer, workflow designer, or Web Forms designers. Part of this would require work in the project system, part of it would require work in the SDK.

At a high level, I'd separate applications from libraries:

* For **applications**, you should make a determination whether you want to move them to .NET Core. WinForms and WPF would be easiest, for ASP.NET I'd recommend first porting them to ASP.NET Core on .NET Framework and then moving them to .NET Core.
* For **libraries**, you should analyze the upstream dependencies. Will you have app on .NET Framework and .NET Core or are they .NET Core/.NET Framework only? If all consumers remain on .NET Framework, leave the library on .NET Framework. If they are .NET Core only, I'd move them to the same version of .NET Core you're moving the apps to. If you have consumers for both .NET Framework and .NET Core, use .NET Standard 2.0. In cases where you want to give the .NET Framework consumer extra features that require APIs that don't exist in .NET Standard, you can multi-target for .NET Framework and .NET Standard.

Tooling wise, this would mean that .NET Core applications and libraries would be on the new projects system, while apps and libraries that remain on .NET Framework would remain on the old project system.

**Comment by jamshedd** [comment]
@cathysull can we close this 6.0 item down? I assume we have new tracking items for the 7.0 work?

**Comment by cathysull** [comment]
Closing as we are tracking latest work in the .NET 7 themes.
