### ISSUE TITLE
Developers can be successful creating their first project using tools

### ISSUE THREAD

**Issue by shanselman** [dotnet/core#5472]
### Summary

Reduce cognitive overload of all options in CLI/VS in ‘new’ experiences

### User Stories

User Stories under this Epic:

- [ ] [Title of the linked User Story](hyperlink to the User Story issue).

**Comment by loic-sharma** [comment]
Currently customers need to pick the right architecture to download the .NET SDK:

![image](https://user-images.githubusercontent.com/737941/117199600-3aa18000-ad9f-11eb-85f2-47004c4fa537.png)

I imagine that many students and newbies don't know which architecture they use, or how to find out. Things I would consider:

* Remove the architectures from the downloads page. Ideally the .NET SDK installer would magically work on all architectures and choose the best architecture for your computer. Or...
* ... Order the architectures by most commonly used. I imagine most Windows developers would want to install x64 instead of arm64. If so, putting x64 first will help customers fall into the pit of success as they may simply click the first option. I would also provide a guide on choosing the right architecture.

**Comment by mairaw** [comment]
I can't comment on the SDK auto-magically doing things for customers but I'm happy to work on website improvements to make the experience better. I've been thinking about the ordering since we added Arm64 recently, so I can definitely implement that chance on the website. It feels that the architecture picking guidance would be something I could link to docs /cc @leecow @rbhanda @adegeo

**Comment by adegeo** [comment]
We don't cover this in the article because we assume it's handled via the website choice the user makes when downloading .NET.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
