### ISSUE TITLE
.NET has good defaults for running in containers

### ISSUE THREAD

**Issue by richlander** [dotnet/core#5485]
People expect that the default behavior of .NET (or any container platform) is good in the general case. To a large degree, the conversation we had in [Environment.ProcessorCount incorrect reporting in containers in 3.1](https://github.com/dotnet/runtime/issues/622) was about that, and we chose to bias default product behavior for the general case. 

The assumption at this point is that .NET has good defaults, for the general case. The remaining work is to test this assumption. The following are cases that we will validate (and publish results). Please share if you believe that we should consider more cases, or if you have data to share. These cases are not a list of configurations, but guidance that we can document.

- [ ] Define smallest container size that a .NET app can tolerate, with various load: 10, 100, 1000 RPS.
- [ ] Define the smallest memory size that a .NET app can tolerate, with soft (`--memory-reservation`) and hard (`--memory`) memory limits set, with soft limit n% smaller: 10%, 25%, 50%
- [ ] Define maximum RPS that can be achieved with a given CPU limit (memory is variable, documented): .5 CPU, 1 CPU, 2 CPU, 4 CPU.

Note: The tests will be run with API template.

Note: For these cases, only docker, not .NET, settings can be changed. The question is whether we are happy with the results we get, with .NET defaults.

**Comment by nycdotnet** [comment]
I am greatly looking forward to this documentation.  I would request that you go down as low as 100 or 250 millicores for an app, as densely packing containers - especially with techniques such as vertical pod autoscaling in k8s - is an attractive cost saving measure when possible.  Also, especially for the resource constrained pods, I would love to see RPS figures for the first seconds and minutes of runtime rather than only in steady state.  I suspect that adapting something like TechEmpower Fortunes would be a wonderful test case that is already optimized but does real-world work.  We are so excited to see what you come up with for .NET 6.

**Comment by madhub** [comment]
Also good default GC for constrained environment , today by default asp.net core apps select Server GC, it is issue for constrained environment.

**Comment by mairaw** [comment]
Bulk closing .NET 6 epics and user stories. If you think this issue was closed in error, please reopen the issue and update it accordingly.
