### ISSUE TITLE
 Failed to fetch https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size

### ISSUE THREAD

**Issue by kakins** [dotnet/core#5574]
# Issue Title
 Failed to fetch https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size

# General
This task started failing yesterday afternoon.  It had worked every time before then.

Powershell command, running in ADO pipeline
```
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.170.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
```

yml
```
- pwsh: |
    Write-Host "Installing SQL Server Express..."
    Write-Host "`nSetting SA password..."
    Write-Host "##vso[task.setvariable variable=SqlSAPassword;]$sqlSAPassword"
    Write-Host "`nAdding GPG keys..."
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    Write-Host "`nAdding SQL server repository..."
    $version = (cat /etc/lsb-release | Where-Object { $_ -like "*RELEASE*" }).Split("=")[1]
    sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/$version/mssql-server-2019.list)"
    Write-Host "`nInstalling..."
    sudo apt-get update
    sudo apt-get install -y mssql-server
    Write-Host "`nConfiguring..."
    sudo MSSQL_PID=Express MSSQL_SA_PASSWORD=$sqlSAPassword /opt/mssql/bin/mssql-conf -n setup accept-eula
    sudo systemctl restart mssql-server
  condition: eq(variables['Agent.OS'], 'Linux')
  displayName: Install SQL Server Express
```

Output:
```
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (13511 != 13352). Mirror sync in progress? [IP: 13.82.67.141 443]
   Hashes of expected file:
    - Filesize:13352 [weak]
    - SHA512:efa35638712a6a5045f5468c8d6aca6b4ab9c5dff13439863e7fef91681ec0916076bb76dcf2e96dd72f3089984472a62b5a2cd0c98dd885c66bcb868e888b23
    - SHA256:db00281d8aaa1f1b3d292c430a60093f8978519bd152b6bbd395371af7ceb922
    - SHA1:68eaba4fa381374b1f719fb36f06464af2e9317e [weak]
    - MD5Sum:279ba725c2e9338dd9bbacd65af6de2e [weak]
   Release file created at: Mon, 02 Nov 2020 18:14:11 +0000
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019/dists/bionic/main/binary-arm64/Packages.bz2  
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019/dists/bionic/main/binary-armhf/Packages.bz2  
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package mssql-server
```

**Comment by kakins** [comment]
I hope this is the right repo to post this issue.  I saw a similar issue posted last year in this repo, so I figured it could be related.

**Comment by muhammad2k18** [comment]
Getting the same issue trying to install mssql server on ubuntu 20.04.1 x64
![Screenshot from 2020-11-12 10-56-59](https://user-images.githubusercontent.com/36593756/98901576-d1b70a80-24d5-11eb-8ff9-4a3e8a7c3ecc.png)

**Comment by Darknox-nl** [comment]
Same issue here at ubuntu 18.04.3. I thought I was doing something wrong because I am installing SQL Server on Linux for the first time.

`
Get:7 https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019 bionic/main amd64 Packages [13.4 kB]
Err:7 https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019 bionic/main amd64 Packages
  File has unexpected size (13511 != 13352). Mirror sync in progress? [IP: 13.81.215.193 443]
  Hashes of expected file:
   - Filesize:13352 [weak]
   - SHA512:efa35638712a6a5045f5468c8d6aca6b4ab9c5dff13439863e7fef91681ec0916076bb76dcf2e96dd72f3089984472a62b5a2cd0c98dd885c66bcb868e888b23
   - SHA256:db00281d8aaa1f1b3d292c430a60093f8978519bd152b6bbd395371af7ceb922
   - SHA1:68eaba4fa381374b1f719fb36f06464af2e9317e [weak]
   - MD5Sum:279ba725c2e9338dd9bbacd65af6de2e [weak]
  Release file created at: Mon, 02 Nov 2020 18:14:11 +0000
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (13511 != 13352). Mirror sync in progress? [IP: 13.81.215.193 443]
   Hashes of expected file:
    - Filesize:13352 [weak]
    - SHA512:efa35638712a6a5045f5468c8d6aca6b4ab9c5dff13439863e7fef91681ec0916076bb76dcf2e96dd72f3089984472a62b5a2cd0c98dd885c66bcb868e888b23
    - SHA256:db00281d8aaa1f1b3d292c430a60093f8978519bd152b6bbd395371af7ceb922
    - SHA1:68eaba4fa381374b1f719fb36f06464af2e9317e [weak]
    - MD5Sum:279ba725c2e9338dd9bbacd65af6de2e [weak]
   Release file created at: Mon, 02 Nov 2020 18:14:11 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by Darknox-nl** [comment]
The packages from https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019/dists/bionic/ have received an update on 10-Nov-2020 23:39. The update is probably related to our issues.

**Comment by loremipsumpy** [comment]
Same issue at Ubuntu-server 20.04.1 LTS
`Get:7 https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019 bionic/main armhf Packages [2,713 B]
Err:7 https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019 bionic/main armhf Packages
  File has unexpected size (2887 != 2713). Mirror sync in progress? [IP: 13.90.56.68 443]
  Hashes of expected file:
   - Filesize:2713 [weak]
   - SHA512:6b55eac2ae39323c25d51414bcfc63074679cab4ccdcc2235aac8a701eb586311ca77a9759ca91a335797677a4807e1f64ad4f01ac776355c2a87abfdb113e38
   - SHA256:eebc8dab8e902d7c70715e900bcddec6da6271f9a5a6bff27ad9f0038c4564a0
   - SHA1:ff8ed892dec099cf67334b4238359fc6ea25864c [weak]
   - MD5Sum:43fdd9bcfb30ab466e1c4b16c39d32e5 [weak]
  Release file created at: Mon, 02 Nov 2020 18:14:11 +0000
Get:8 https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019 bionic/main amd64 Packages [13.4 kB]
Err:8 https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019 bionic/main amd64 Packages
`

**Comment by kubaporebski** [comment]
Not only you have a problem. I am also affected, and [this guy also](https://askubuntu.com/questions/1291397/cant-install-mssql-server-in-ubuntu-20-04).

**Comment by kakins** [comment]
A colleague at work pointed me to a workaround to use offline installation rather than utilizing the package repository:

Changed this:
```
sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/$version/mssql-server-2019.list)"
sudo apt-get update
sudo apt-get install -y mssql-server
```
To this:
```
sudo add-apt-repository "$(wget https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019/pool/main/m/mssql-server/mssql-server_15.0.4073.23-4_amd64.deb)"    
sudo apt-get update
sudo apt install -y ./mssql-server_15.0.4073.23-4_amd64.deb
```

**Comment by thirstyape** [comment]
As far as I can tell this is not a new occurrence [#3221](https://github.com/dotnet/core/issues/3221). There are also other issues linked within that issue.

@dagood Any comments? Not sure if this is something you are involved in, just saw you were on several of the other issues.

**Comment by dagood** [comment]
This is kind of an odd situation because what you're seeing is an outage of this repository, specific to `mssql`:
`https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019`
and .NET uses this repository instead, which is currently working fine (but only has .NET packages, not `mssql-server`):
`https://packages.microsoft.com/ubuntu/18.04/prod`

(For background, these are both using the same underlying service that we (.NET) don't control. Unfortunately the service owners have no public presence so this `dotnet/core` repo probably has the most info about it. 😅)

Do you have any support contact in Azure or know the owner of `mssql-server` who you could report this to?

We might be able to get this report to the right people to get it fixed, but it would help us out if you can also report this on more direct channels if you can find them.

**Comment by kakins** [comment]
@dagood Thanks a lot for the response!  Sadly I don't believe I know of any contacts in Azure or elsewhere related to this repository.  I'll try to see what I can find though.

**Comment by dagood** [comment]
The packages.microsoft.com team has run a republish to fix this, can you try it again now to confirm?

**Comment by thirstyape** [comment]
@dagood Looks to be working now, thank you for the help

**Comment by dagood** [comment]
Thanks for checking. 🙂 Closing as resolved.

**Comment by kakins** [comment]
@dagood   Thank you!

**Comment by rohitmishraatshell** [comment]
Issue seems to occur again!

**Comment by dagood** [comment]
> Issue seems to occur again!

When you see this happening, please open a new issue (feel free to include a link back to this issue as a reference) or look for an issue currently tracking it--commenting on a closed issue isn't likely to ping the right person.

The current problems are tracked by https://github.com/dotnet/core/issues/6381.
