### ISSUE TITLE
Starting a Process in a WPF .NET Core vs WPF .NET Framework in ProcessWindowStyle.Minimized mode does not work on  WPF .NET Core

### ISSUE THREAD

**Issue by dorofino** [dotnet/core#5668]
Hi 
I'm having an issue starting a Process in ProcessWindowStyle.Minimized mode in .NET Core.

You can get the project from here
https://github.com/dorofino/WPF.NET-Core-vs-.NET-Framework

The solution is really simple; two projects one using WPF .NET Core and another using WPF .NET Framework.
Each project has one button that starts a Process in WindowStyle Minimized mode.
The  WPF .NET Framework works really good and starts the process in minimize mode, but the  WPF .NET Core project starts the process but does not minimize it.

```
        private Process emulatorProcess;
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            emulatorProcess = new Process();
            emulatorProcess.StartInfo.FileName = @"c:\windows\System32\notepad.exe";
            emulatorProcess.StartInfo.WindowStyle = ProcessWindowStyle.Minimized;
            emulatorProcess.Start();
        }
```

The question/issue is why the same code does not work the same in both frameworks.
My goal is to use WPF .NET Core to start a process in minimize mode. 

Any help will be greatly appreciated meaning.
Diego

**Comment by danmosemsft** [comment]
Hello this is because the default value of ProcessStartInfo.UseShellExecute is now false, and WindowStyle only works when it is true. Please add `emulatorProcess.StartInfo = true;`

See https://docs.microsoft.com/en-us/dotnet/core/compatibility/fx-core#change-in-default-value-of-useshellexecute and also I have put up a PR to improve the docs.
