### ISSUE TITLE
System.AddIn (plugin) support with .Net core

### ISSUE THREAD

**Issue by TJSoftware** [dotnet/core#57]
I am curious if there is expected to be support for System.AddIn (in whatever namespace) for .Net core?  I took a look at http://packagesearch.azurewebsites.net/ and did not find a match and I was not able to find any namespaces that looked like they are *.AddIn in this repo and a few others.  I might not be looking in the right place.  If so would you please direct me to the correct place.  Although I can follow examples from StackOverflow or other places and recreate this using `Activator.CreateInstance` I would prefer to use built in tech first.

**Comment by mms-** [comment]
System.Addin seems to be forgotten by the .Net team perhaps because it's only mean for larger projects, though it's still just as relevant, even in the new .Net Core/UWP env. With nothing to replace it, and with .Net Remoting going away, it may finally be time to update it. Why not release it on Nuget? With PCL implementation to allow UWP/Net core usage.

**Comment by TJSoftware** [comment]
I did ask in a few chat rooms (gitter, jabbr) about this.  Pinpoint Towers thought that David Fowler might be working on something along these lines.  Outside of that I have not heard of anything concrete.

**Comment by bitbonk** [comment]
@davidfowl once promised a blog post about it. But it seems it never happened. https://twitter.com/davidfowl/status/703475472592572416

**Comment by joshfree** [comment]
This request is being tracked in the corefx repo @ https://github.com/dotnet/corefx/issues/6920
