### ISSUE TITLE
WinPE support

### ISSUE THREAD

**Issue by madhav5589** [dotnet/core#571]
Hello,

I have an windows application running on .NET 4.5.1 version. I am planning to migrate APIs to .NET core. Wonder if .NET core has any plan to support WinPE (Windows Pre-installed Environment) platform. I looked at the potential road map section but couldn't find anything specific to WInPE platform support. 

Thanks.

**Comment by Petermarcu** [comment]
WinPE hasn't been something we've considered for the project but if you want to try running .NET Core under WinPE it may work. It would be limited by all the limitations of WinPE but I don't know of a reason off the top of my head why a basic application wouldn't be able to run. What are you trying to do with it that needs to work in WinPE?

**Comment by madhav5589** [comment]
@Petermarcu I have an windows application which I use to run in WInPE environment for Imaging purpose (using Ghost).

**Comment by Petermarcu** [comment]
I would suggest creating a self contained .NET Core application and use it where you use your .NET 4.6 app. Yes, if you want to run .NET on Linux, .NET Core is a great path to that.

**Comment by madhav5589** [comment]
@Petermarcu Thanks. I followed the doc from [here](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-vs) for simple SCD console application. After publishing the app, when I try to run the published app.dll inside WinPE, it shows an error that 

> dotnet is not recognized as internal or external command

 in the command prompt.
I thought that SCD project contains the .net core library files and dependent dll files with it. Any thoughts?

**Comment by mellinoe** [comment]
@madhav5589 If you have a self-contained deployment, then you don't need to invoke it with `dotnet`. You should have an actual executable file ("myappname.exe") in the published output that you can run directly.

**Comment by madhav5589** [comment]
@mellinoe I was using `<OutputType>Exe</OutputType>` in the project file with RunTimeIdentifier as "Any". Since I am trying to run it in WinPE, is there specific RID dedicated for that? RID catalog reference: [click here](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)

**Comment by mellinoe** [comment]
@madhav5589 Disclaimer: I don't know much about WinPE, and as far as I know it's an untested scenario.

> I was using <OutputType>Exe</OutputType> in the project file with RunTimeIdentifier as "Any".

If you are using a self-contained deployment (which I think makes sense in this case), then you need to choose a specific, concrete RID. In this case, I would try "win7-x64". The output of this should include coreclr.dll, "myapp.dll", and "myapp.exe", as well as a bunch of other miscellaneous files.

**Comment by MrM40** [comment]
madhav5589, did you succeed running dotnet in WinPE?

**Comment by madhav5589** [comment]
@MrM40 Yes, I was able to run SCD console app in WinPE environment.

**Comment by madhav5589** [comment]
@MrM40  Yes, I could run .NET core console app in WinPE environment. But not WPF app. I installed .NET  core 3.0 preview version and created a sample WPF app using default template and published it using Self Contained Deployment. Couldn't run it in WinPE environment. It throws "an unknown software exception".  @Petermarcu @mellinoe  Any thoughts on this?

**Comment by karelz** [comment]
@madhav5589 WinPE is specific OS setup, which does not contain all components, so I would not be surprised if some parts of .NET Core or WPF/WinForms won't work.
Supporting WinPE for WPF is not on our backlog AFAIK.
BTW: Neither Peter nor Eric are on our team anymore ...

**Comment by madhav5589** [comment]
@karelz Thanks for the update. It makes sense now to me.

**Comment by codenotworking** [comment]
I'm a bit late to the party but I found a solution for getting .NET working in WinPE.

Basically, you'll have to edit the WinPE image's PATH environment variables and copy the .NET SDK binary (not installer) to a folder of your choosing in the WinPE image.  Yes, I used the SDK, because it's an extractable zip file, which includes both the runtime and desktop runtime.

NOTE: The published console or WPF application can be self contained or not, and can be published as a single file or not.  Your choice.  I personally chose to not [publish self contained](https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained), reducing the file size of the WinPE image.

Here is the solution:

1. Mount the WinPE image
2. Load WinPE image's **SYSTEM** registry hive file (located under **\mount\Windows\System32\config**).  Follow the steps outlined here for loading an offline registry hive: [Load registry hive for offline registry editing](https://smallvoid.com/article/winnt-offline-registry-edit.html)
3. Within the loaded hive, navigate to "_\ControlSet001\Control\Session Manager\Environment_"
4. Modify PATH by appending the path to where .NET SDK is on the WinPE image.  For example, I've extracted the latest .NET (9.0.203 as of writing this solution) into a folder called "_dotnet_" at the root of the WinPE image.  I appended "_%SystemDrive%\dotnet;_" (without quotes) to the PATH environment variable in the offline registry
5. Create a new expandable string (REG_EXPAND_SZ), name it "_DOTNET_ROOT_" (without quotes of course), and add the path "_%SystemDrive%\dotnet_" (without quotes of course) to the registry entry
6. Copy your console application(s) and/or WPF application(s) into the WinPE image you need
7. Commit and unmount the WinPE image
8. Create WinPE ISO media

### ADDITIONAL INFORMATION
Make sure to use "_%SystemDrive%_" environment variable since letter assignment _may_ change each time WinPE boots.  See this script for identifying the drive letter: [WinPE: Identify drive letters with a script](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-identify-drive-letters)

Screenshot proof I have it working with .NET 9:

- **test.exe** is a simple console application
- **testwpf.exe** is a simple WPF application

![Image](https://github.com/user-attachments/assets/e61d8d6f-e280-4a09-afc8-54864caeddd2)
