### ISSUE TITLE
I can't dotnet new console but i can dotnet

### ISSUE THREAD

**Issue by PyScrtipter** [dotnet/core#5740]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What error message do you get when you run dotnet new console?

Can you run `dotnet --info` and past the output here?

**Comment by PyScrtipter** [comment]
I already found the solution.Thanks  Van: Maira WenzelVerzonden: zaterdag 12 december 2020 21:29Aan: dotnet/coreCC: PyScrtipter; AuthorOnderwerp: Re: [dotnet/core] I can't dotnet new console but i can dotnet (#5740) What error message do you get when you run dotnet new console?Can you run dotnet --info and past the output here?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DmeleroC** [comment]
I have the same problem, i had installed the NET core, and in my console i can do dotnet, but when i want to create a new proyect with dotnet new console it displays this message: "

C:\Users\Daniel>dotnet newApp
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
What can i do? because i´ve tried installing two diferrent versions and a have the same results.

**Comment by mairaw** [comment]
@DmeleroC it seems you only have the runtime installed. Can you paste the output of `dotnet --info`?
