### ISSUE TITLE
.NET CORE 5 problem installing

### ISSUE THREAD

**Issue by DmeleroC** [dotnet/core#5767]
I have the same problem, I had installed the NET kernel, and in my console I can do dotnet, but when I want to create a new project with dotnet new console, it shows this message: "

C: \ Users \ Daniel> dotnet newApp 
Could not find any .NET Core SDK installed Did you want to run .NET Core SDK commands? 
Install a .NET Core SDK from: https://aka.ms/dotnet-download

Tengo el mismo problema, había instalado el núcleo NET, y en mi consola puedo hacer dotnet, pero cuando quiero crear un nuevo proyecto con dotnet new console, muestra este mensaje: "

C: \ Users \ Daniel> dotnet newApp
No fue posible encontrar ningún SDK de .NET Core instalado
¿ Quería ejecutar comandos del SDK de .NET Core? Instale un SDK de .NET Core desde:
https://aka.ms/dotnet-download
¿Qué puedo hacer? porque intenté instalar dos versiones diferentes y obtuve los mismos resultados.
![Captura1](https://user-images.githubusercontent.com/71845621/102503346-ea3fb500-407f-11eb-94b9-e10b24af3a54.JPG)

**Comment by mairaw** [comment]
You have installed two different runtimes but no SDK. If you have a Windows 64-bit version, you can install the SDK from https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.101-windows-x64-installer.
Otherwise, choose your appropriate OS and version here: https://dotnet.microsoft.com/download/dotnet/5.0

Then you should be able to create apps with the dotnet command. But it should be dotnet new "apptype" such as `dotnet new console` or `dotnet new webapp`. You can find the help for the dotnet new command at https://docs.microsoft.com/dotnet/core/tools/dotnet-new.

Let us know if this helped!
