### ISSUE TITLE
Nuget restore is failed in Windows build.

### ISSUE THREAD

**Issue by vsafonkin** [dotnet/core#5881]
### Description

* Sometimes `dotnet build` command is failed on Nuget restore step. The error:
```
error NU1101: Unable to find package <package name>. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
```
* repro: https://github.com/vsafonkin/ualbion/runs/1726489951?check_suite_focus=true

### Configuration

* Which version of .NET is the code running on? 5.0.101
* What OS and version, and for Linux, what distro? Windows
* What is the architecture (x64, x86, ARM, ARM64)? x64

It can be fixed either with creation `nuget.config` file with nuget sources list or running `dotnet nuget locals all --clear` before build.

**Comment by carlossanlop** [comment]
Are you using Visual Studio? If yes, do you see nuget sources when you go to Tools -> Options -> NuGet Package Manager -> Package sources? I ask because your error message says `Microsoft Visual Studio Offline Packages`

@dagood is this something in your area?

**Comment by xt0rted** [comment]
@carlossanlop this happened in a couple of my repos as well. It only happens when building on github actions with a windows vm while using the `setup-dotnet` action. I fixed it by adding a `nuget.config` even though I don't need one.

The issue popped up out of no where for me, and by the sound of it the same is true most of the people reporting the issue (and linking to it) in https://github.com/actions/setup-dotnet/issues/155.

**Comment by dagood** [comment]
I don't know what could cause this, especially with `dotnet nuget locals all --clear` being a way to fix it. That makes me think it can't be something as simple as a machine misconfiguration (a bad global or user-level NuGet.config file). However, it isn't my area.

I think https://github.com/NuGet/Home/issues would be the right place to get help debugging this.

**Comment by danmoseley** [comment]
@aortiz-msft  could you transfer to https://github.com/NuGet/Home/issues?

**Comment by mairaw** [comment]
This issue was moved to NuGet/Home#10586
