### ISSUE TITLE
docker build -t mymicroservice . run fail

### ISSUE THREAD

**Issue by stonezhao28** [dotnet/core#5888]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/docker-image
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

<img width="763" alt="图片" src="https://user-images.githubusercontent.com/55523272/106093793-e9646d80-616b-11eb-9d1a-80d0e18cbb53.png">

<img width="759" alt="图片" src="https://user-images.githubusercontent.com/55523272/106093816-f5502f80-616b-11eb-8271-3ad7afaace29.png">

**Comment by mairaw** [comment]
There's a problem going on with NuGet today. You can follow the latest status updates at https://github.com/NuGet/Announcements/issues/49

Apologies for the inconvenience.

**Comment by stonezhao28** [comment]
@mairaw thanks for your replay. But I'm mac os version 11.1 Big Sur.Can This solution  work?

**Comment by mairaw** [comment]
I think it's because of the Docker containers. On https://status.nuget.org/, they suggest the following:
If using docker, change your base image from "FROM mcr.microsoft.com/dotnet/sdk:5.0" to " FROM mcr.microsoft.com/dotnet/sdk:5.0-focal" or " FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine"

So maybe that change on the Dockerfile would help. @nishanil any other suggestions here?

**Comment by mairaw** [comment]
Given this was likely a temporary issue, I'm closing this. Please reactivate it if you still need assistance.
