### ISSUE TITLE
proper version naming communication

### ISSUE THREAD

**Issue by d4e666** [dotnet/core#591]
how difficult can it be to use some proper versioning when placing it in communication.

you claim the latest version is 1.1 of the SDK but the real version is 1.0.1. WHY CAN'T UP KEEP THE VERSIONS IN SYNC??? IS IT THAT HARD TO ACT AS GROWN-UP DEVELOPERS AT MICROSOFT????

it's that kind of childish lazyness that makes .NET so fucking difficult. you need to use version X with component Y to be able to address the features of service version Z, which can then be extended by version A, .....

even angular consists of multiple independent libraries and still the manage to keep the same version numbers upon release. This is just a matter of using a global version file. EVEN I USE IT TO KEEP 2 LIBRARIES VERSION SYNCED so how hard can this be? you only need to do it once.

**Comment by joelharkes** [comment]
@d4e666 Or whatever your name might be.

The problem is not the version sync but its the bad naming of things that make it confusing.

the whole idea of versions is that you can depend on SemVer for you. An update is an update:

* Major update potentially breaks things
* Minor update adds features
* Bugfix updates fixes bugs. (Although this could be a major update sometimes)

Thats why there is different versions for different packages and im happy we do.

**Comment by leecow** [comment]
We're striving to ease the version story with .NET Core 2 so hopefully it will be a bit cleaner across the Core, SDK, ASP stack but divergences at some point would not be surprising. Have a look at these documents addressing some of this. 

* [.NET Core 2+ Naming and Versioning](https://github.com/dotnet/designs/issues/2)
* [.NET Core 2+ Version Binding](https://github.com/dotnet/designs/issues/3)
