### ISSUE TITLE
cannot run dotnet --version

### ISSUE THREAD

**Issue by Lookman98** [dotnet/core#5921]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

It was not possible to find any installed .NET Core SDKs. Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
https://aka.ms/dotnet-download

![image](https://user-images.githubusercontent.com/29520080/107138764-30fbae00-6951-11eb-9595-b2cb07fc28de.png)

already installed the sdk but not found

**Comment by mairaw** [comment]
I've seen an issue with this before if you installed two versions of the SDK or runtime: an x86 and an x64 version.
Do you think that could have happened?

Can you confirm first that you have an x86 or x64 machine first?

If you have an x64 machine and you want to see the x64 versions that you have installed, you might have to edit your system environment variables to point to C:\Program Files\dotnet instead of C:\Program Files(x86)\dotnet.

The shared host can only see either the x86 or the x64 versions at a time.

/cc @joeloff

**Comment by fillerd53** [comment]
Thanks I have a 64

**Comment by mairaw** [comment]
You can run the command `where dotnet` to figure out which order the host is picking up. In my machine, for example:

![image](https://user-images.githubusercontent.com/12971179/107426341-edca4800-6ad4-11eb-88be-936207480432.png)

If you have an x64, that would be the order you'd expect to see. If it's not, edit your system variables to make sure C:\Program Files\dotnet comes first.

**Comment by fillerd53** [comment]
Thanks again sorta new to this stuff

**Comment by mairaw** [comment]
No worries @fillerd53. These things can be tricky!

I also posted this on SO to help other customers having similar problems: https://stackoverflow.com/a/66128116/5075671

**Comment by VeronicaHex** [comment]
I've just done a clean install of dotnet-sdk-5.0.103-win-x64.exe; I shouldn't have to be fiddling with Environment paths to get it working.

Running where Produces:
![image](https://user-images.githubusercontent.com/39120779/107976387-5f146a00-6fb1-11eb-8bd2-c263a610b608.png)

I've corrected the Order of Path
![image](https://user-images.githubusercontent.com/39120779/107976642-cd592c80-6fb1-11eb-9c07-e2f22e0f5c63.png) however where is still not finding it.

Looking on SO people have been having this issue for months... I'm just glad it's not affecting my work machine.
