### ISSUE TITLE
created myApp and cannot get program.cs to work

### ISSUE THREAD

**Issue by Jdahir0511** [dotnet/core#5923]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment]
> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by fillerd53** [comment]
I did everything then computer went nuts so I am noqw in the process of a reset Sent from Mail for Windows 10 From: Carlos SanchezSent: Wednesday, February 10, 2021 12:36 PMTo: dotnet/coreCc: SubscribedSubject: Re: [dotnet/core] created myApp and cannot get program.cs to work (#5923) Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
