### ISSUE TITLE
TLS cipher suites restriction does not work

### ISSUE THREAD

**Issue by norbertpfeifer** [dotnet/core#5993]
### Description
We are trying right now to restrict the TLS cipher suites in our environment.
[https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux](url)
Example: the SQL connection and service bus connection should be limited!

## Environment
* Microsoft Azure
* Kubernetes cluster
* Docker with .net 5 service
* SQL Azure
* Service Bus

### Configuration
* [Dockerfile.txt](https://github.com/dotnet/core/files/6028019/Dockerfile.txt)
* [openssl.txt](https://github.com/dotnet/core/files/6028010/openssl.txt)
* sslscan to SQL server
![sslscan](https://user-images.githubusercontent.com/79509376/108825616-8bd50c80-75c3-11eb-85e6-71802bbfde51.png)

### Issue
The restriction has no effect. The connections are still established.

**Comment by bartonjs** [comment]
Your `sslscan.exe` command seems to be run from Windows, and you're scanning a SqlAzure server.  I don't see where your docker container running on Ubuntu Focal comes into play...

**Comment by marcflohrer** [comment]
Hi @bartonjs, 
The application is running in kubernetes cluster running on Azure VM.
We have to ensure that the TLS ciphers configured in the configuration file ```/etc/ssl/openssl.cnf``` is having an effect on our TLS connections that our application opens towards the Azure SQL Database and Azure ServiceBus.

We thought the only way to prove that the TLS ciphers in ```/etc/ssl/openssl.cnf``` have an impact is to misconfigure them so that we eventually get an TLS handshake error that tells us that the unification set between the TLS ciphers of Azure SQL Database and / or Azure ServiceBus is empty. To do so we checked the TLS ciphers of the Azure SQL Db with ```sslcan.exe``` and translated the IANA names to openssl compatible ciphers using this mapping table: (../openssl-iana.mapping.html)[https://testssl.sh/openssl-iana.mapping.html]. This way we know what TLS ciphers to avoid in our  ```/etc/ssl/openssl.cnf```  configuration in order to get the TLS handshake error.

Unfortunately the TLS can be established no matter how much we restrict the TLS ciphers. Now we are doubting that the configuration in  ```/etc/ssl/openssl.cnf``` has any effect at all.

I know the more simple approach to check the TLS ciphers would be to publish a REST API and perform a TLS scan on it. 
This is not an option here as all external connections are managed by a internet facing web server and so are the TLS ciphers for these connections...

**Comment by bartonjs** [comment]
> We thought the only way to prove that the TLS ciphers in /etc/ssl/openssl.cnf have an impact is to misconfigure them 

Currently you have a `CipherString` value of `TLS_AES_128_GCM_SHA256`.  In OpenSSL's configuration, TLS 1.3 ciphersuites get configured in the CipherSuites property, and SSL 2 through TLS 1.2 ciphersuites get configured via the CipherString property.  Since you've specified a TLS 1.3 ciphersuite in the TLS 1.2 and below entry I think it ignores it, then decides you basically don't have a configuration for that setting.  That's just how openssl.cnf works (and I'm guessing as to what it does in this situation :shrug:).

A more reasonable entry that should make your test result in a connection failure would be a TLS 1.2 ciphersuite that doesn't appear in the list, like `ECDHE-ECDSA-CHACHA20-POLY1305`.

**Comment by norbertpfeifer** [comment]
Hi @bartonjs,
I changed the config but it still doesn't work. Any idea?

openssl_conf = default_conf

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
Ciphersuites = TLS_CHACHA20_POLY1305_SHA256

**Comment by bartonjs** [comment]
`CipherSuites` only modifies TLS 1.3+ ciphersuites, and SqlAzure doesn't support TLS 1.3

Assuming you're trying to get things to fail (with a no mutually available ciphersuites error)

```
openssl_conf = default_conf

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = ECDHE-ECDSA-CHACHA20-POLY1305
```

**Comment by marcflohrer** [comment]
It worked, I with your latest proposal we get the expected TLS handshake error. 

```
{"Timestamp":"2021-02-26T09:12:05.0705739+00:00","Level":"Error","MessageTemplate":"An exception occurred while iterating over the results of a query for context type '{contextType}'.{newline}{error}","Exception":"Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)\n ---> System.IO.EndOfStreamException: End of stream reached\n   at Microsoft.Data.SqlClient.SNI.SslOverTdsStream.ReadInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token, Boolean async)\n   at Microsoft.Data.SqlClient.SNI.SslOverTdsStream.Read(Byte[] buffer, Int32 offset, Int32 count)\n   at System.IO.Stream.Read(Span`1 buffer)\n   at System.Net.Security.SslStream.FillHandshakeBufferAsync[TIOAdapter](TIOAdapter adapter, Int32 minSize)\n
```

Thanks a lot!

**Comment by norbertpfeifer** [comment]
Thanks a lot.
