### ISSUE TITLE
Official support for D-Bus on Linux systems

### ISSUE THREAD

**Issue by danielmeza** [dotnet/core#6012]
Linux is one of the main supported OS for .NET but we have not a official D-Bus implementation. 

We had a [D-Bus](https://github.com/tmds/Tmds.DBus) implementation that works very well but does not below to the .NET Foundation and had not the attention or the support required for a Linux first Citizen characteristics like D-Bus. 

We can use the [@tmds](https://github.com/tmds) work as a starting point.

**Comment by mairaw** [comment]
@leecow can you check this request?

**Comment by danmoseley** [comment]
@danielmeza i am not familiar with DBus, but the first step would be to build a community that performs active development on it (if there is not one) then propose to the foundation to bring it on board.

**Comment by danmoseley** [comment]
Cc @glennc  in case this has been mentioned by other customers

**Comment by danielmeza** [comment]
@danmoseley there is already a community implementation https://github.com/tmds/Tmds.DBus, I have opened an issue there to join it to the .NET Foundation, will be great if you or any on the team can contact to [@tdms](https://github.com/tmds) to accelerate the process.

**Comment by danmoseley** [comment]
I think you have a typo in his user name -- it's @tmds. 

it's a foundation decision what projects they support, but @tmds, let me know if you need anything from us.

**Comment by tmds** [comment]
hi @danielmeza 

> and had not the attention or the support required for a Linux first Citizen characteristics like D-Bus.

The library should allow you to consume D-Bus services in a straight forward way, and there are no major issues I'm aware of. If you have an issue, you can create a ticket in the repo, cc me, and I'll do my best to support you.

I'd like to make some major changes to the library, like using `Span` and friends for protocol implementation, and change to generating code during build instead of runtime. I don't have time to work on this currently.

My employer allows me to spend some time on maintaining and supporting this library, which is great for me and its users!

> does not below to the .NET Foundation

I think the main thing missing is lack of people working on it actively (including myself). Personally, I consider this a requisite to be a .NET foundation project, and not something that can be achieved by becoming a .NET foundation project.

If this were a .NET foundation project today, it would raise expectations, and give me stress because I don't have time to meet them.

**Comment by danielmeza** [comment]
Hi @tmds, first let me say tanks you for you excellent work whit the library, my intention is not to demerit you effort but help to spread it. 

As the work you did is great, we will need call for maintainers to split the work load and  make the repository healthier, so you can be free four your own work. 

I know that to become a .NET Foundation member some requirements should be meet, and that’s why I call you here, to give the first steps in that direction. 

Ad you know I have been working with your library building BlueZ server apps, in the next days I will publish and initial repository with samples and possibly a NuGet package, I hope this redirect users to endorse the use of your library and join the effort of support it. After that I should be able to help you with the Span implementation and also spread the use of ValueTask to reduce memory footprint.

My best for yo, I’m keep in touch!

**Comment by danmoseley** [comment]
@danielmeza shall we close this issue now? I think it would be good to have such discussion in the Tmds.DBus repo.

**Comment by danielmeza** [comment]
@danmoseley  yes
