### ISSUE TITLE
Can we reference Microsoft dynamic CRM sdk in .net core 1.1?

### ISSUE THREAD

**Issue by ruonan59** [dotnet/core#604]
Thanks for your interest in .NET Core. 

Please note that this repo (dotnet/core) is not for filing product issues. Here are some repos where you can file an issue:
 * dotnet/cli - for CLI tools and questions
 * dotnet/corefx - for API issues and questions
 * dotnet/coreclr - for runtime issues
* nuget/home - for NuGet questions and issues

**Comment by svick** [comment]
As far as I can tell, you can't. The [package Microsoft.CrmSdk.CoreAssemblies](https://www.nuget.org/packages/Microsoft.CrmSdk.CoreAssemblies/) only supports .Net Framework 4.5.2, but not .Net Core.

**Comment by conterio** [comment]
Is there any  around this?

**Comment by richlander** [comment]
Sorry for the delay! I just sent a message to the CRM team.

**Comment by richlander** [comment]
I'd love to learn a bit more about what you plan to do with .NET Core and CRM. Please (anyone) send mail to rlander@ms. I'm collecting scenarios so that we can have better insight on using these two products together.

**Comment by Petermarcu** [comment]
It should be possible to reference it now in a .NET Core 2.0 project. I'm not sure if it will work, it depends on what those libraries do, but you can at least reference them now and see if they work for you.

I'm going to close this out for now.

**Comment by kgacova** [comment]
I couldn't get it to work with Core 2.0.

**Comment by Petermarcu** [comment]
Which part didnt work? Referencing the dll, or the dll working on .NET Core 2.0?

**Comment by kgacova** [comment]
The working part didn't work.

**Comment by Petermarcu** [comment]
Ok, that is always a possibility with pulling .NET Framework binaries into  :(  Running this on the binaries to get a report of what it needs that is missing may be a good net step. https://docs.microsoft.com/en-us/dotnet/standard/portability-analyzer

**Comment by daneise** [comment]
I just today tried the same thing and got to the point:

**Method not found: 'Void System.ServiceModel.ClientBase`1..ctor(System.ServiceModel.Description.ServiceEndpoint)'.**

according to:

https://stackoverflow.com/questions/45545013/system-servicemodel-not-found-in-net-core-project

System.ServiceModel seems to be deprecated in .Net Core.

I needed to install **System.ServiceModel.Primitives** to get to that point - i installed **System.ServiceModel.Http** and **System.ServiceModel.Security** along with it just to try if it would solve the problem.

Or did anybody manage to get it working already and can share a solution?

**Comment by fberasategui** [comment]
@richlander any news on this?

We are very (very) fond of XRM (now Power Platform), and with all the performance improvements and the direction MS seems to be taking on the .NET/.NET Core dichotomy, it would seem that by staying on the "desktop" framework version we are staying "behind".

Examples of typical use cases for XRM SDK on .NET Core are:
  - ASP.NET Core Web App on Azure consuming XRM data 
  - [Integration](https://colinvermander.com/2016/09/18/using-the-azure-service-bus-with-dynamics-crm-2016-spring-update/) between XRM Plugins and Azure Service Bus
  - Application architectures that enable re-use of business logic code in both internal (Plugins) and external components.
  - General Command Line tooling for XRM
  - 

All of these are being covered at the moment by the. NET Framework XRM SDK, however I must insist that not going towards .NET Core is really concern for us in terms of future-proofing our projects and products.

As an aside, going directly to the XRM Web API via `HttpClient`  and bypassing the SDK altogether, while doable, is really really cumbersome (needing to compose requests and JSON manually instead of using a proper object model and proper abstractions) and practically destroys all the [abstractions](https://github.com/LeximSoluciones/Lexim.Xrm) we've build through all these years working on XRM.

In an ideal world, Microsoft would provide an implementation of `Microsoft.Xrm.Sdk.IOrganizationService` that would hit the XRM Web API behind the scenes (instead of the classic WCF-based OrganizationService.svc), but still maintain the level of abstraction that the XRM SDK provides (including, of course, a LINQ provider ;) )

**Comment by MattB-msft** [comment]
@fberasategui 
All, this is an area that the PowerPlatform team is aware of and we are looking at it.
We have been working closely with the .NET core team to help close a number of gaps that prevented us from developing a .NET core sdk. 
The changes to support us have been now been added into the .NET Core 3.0 SDK ( which is still in preview at the time of this writing ). 

While we do not yet have a release timeline for preview,
It is our intent to provide a .NET core based version of our core SDK's ( Non UX ) for .NET core 3.0+.  
We hope to be able to talk more definitively about this over the next few months. 

MattB.

**Comment by fberasategui** [comment]
@MattB-msft I'm happy to hear these news.

#### (the following is probably totally off-topic here, apologies in advance)

However I'm left wondering if it would make sense to create an implementation of `IOrganizationService` that would hit the XRM Web API underneath. My primary motivation for this is performance: right now I'm writing a proof of concept using Azure Functions to compare the performance of inserting 100k records in a CDS instance using  `ExecuteMultipleRequest` with the WCF endpoint versus sending 100k messages to Azure Service Bus and having 100000 instances of an Azure Function insert them simultaneously.

Hitting the Web API directly without any SDK at all is totally unfeasible for us at the moment since we need to write complex business logic that would be extremely hard to write and maintain using lower level concepts such as string concatenation, manual JSON serialization and raw HTTP calls, compared to using LINQ and a proper object model.

Can you comment on any of this? 

  - What mechanism would you recommend for massive (millions of records) creation and modification of CDS data (based on business logic, not static data)?
  - Would it make sense at all for me to create such an abstraction (even if I improve an existing one)?

Thanks in advance

**Comment by MattB-msft** [comment]
I will respond here once, and then ask you to take it to the email thread you had started with us so as to not disrupt the .NET core team's issue lists :) 

In short,  ( without a understanding of what your actually trying to do )
Remapping the SDK onto the WebAPI is , for folks outside the platform, extremely difficult.  I would suggest you avoid trying to make IOrganizationService work with it directly and wait till we produce the .NET core libs. 

Your second question is dealt with using the CrmServiceClient or equiv' lib and taking advantage of .Clone + Batching support.  Throughput is a function of API Throttles, + connections + batches per connection. 

You are of course welcome to use the WebAPI client stack of your choice + our metadata file, or roll your own, for a custom, targeted behavior.  The same rules and concepts I mentioned in the second point still apply.

MattB.

**Comment by lressem** [comment]
Hi, any updates on sdk being compatible with .net core?
Thanks!
b.r.
L.R

**Comment by MattB-msft** [comment]
All I can say at this time is that this is actively under development by the PowerPlatform Team,  
so.. look for info "Soon(tm)"

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hello problem with the package System.ServiceModel.Primitives 
 
System.TypeLoadException: Could not load type 'System.ServiceModel.Description.MetadataConversionError' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceConfiguration..ctor(Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateConfiguration[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateConfiguration[TService](Uri serviceUri)
   at Microsoft.Xrm.Sdk.Client.ServiceProxy`1..ctor(Uri uri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy..ctor(Uri uri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)

**Comment by thijstijsma** [comment]
@MattB-msft We're currently at a crossroads with the architectural implementation of our platform and are wondering if we should try proxying the requests through a .NET Framework proxy service or wait for the .NET Core libraries.

Is there anything more you can share after 3 months? Even a quarter or year would be very helpful in making decisions.

Kind regards,

Thijs Tijsma

**Comment by MattB-msft** [comment]
We are inflight on an alpha now.   We should be making a public statement about it here https://powerusers.microsoft.com/t5/Power-Apps-Component-Framework/bd-p/pa_component_framework which is our pro dev community,  with cross posts to the cds community.

Likely next week .

________________________________

**Comment by thijstijsma** [comment]
Thank you for the update, we will subscribe to the feed!

**Comment by deckerix** [comment]
thanks :)

**Comment by thijstijsma** [comment]
There has been an announcement. This is amazing!

https://powerusers.microsoft.com/t5/Power-Apps-Component-Framework/Announcing-the-net-Core-SDK-for-Common-Data-Service-CDS-External/m-p/470035#M1745

Excerpt:

> Today we have posted the alpha version of the Microsoft.Powerplatform.Cds.Client on nuget.  along with a few additional packages that we are using to split out the Dynamics Sales / Service and Marketing centric messages and helpers from the core CDS platform SDK
