### ISSUE TITLE
How many previews will .NET 6 have before release?

### ISSUE THREAD

**Issue by mingtong** [dotnet/core#6144]
I am developing ASP.NET Core and WPF on Windows, I want to know when is the proper time to migrate to .NET 6 from .NET 5?
Yes, I am asking is it stable enough to do early development?

**Comment by Jozkee** [comment]
> How many previews will .NET 6 have before release?

It will have 7 previews, and 2 release candidates after preview 7. 

>  I want to know when is the proper time to migrate to .NET 6 from .NET 5? is it stable enough to do early development?

I would say yes, it is a good idea to start using .NET 6 for new development, cc @leecow since he might know better about any guidelines for this.

**Comment by leecow** [comment]
The answer to when you should begin adopting really depends on what you're doing. We want folks to begin using Previews as early as possible so that we can hear feedback early enough to use before the final release.

Previews are inherently more unstable than the final release, though we work hard to ensure core functionality is as solid as possible. When we do find something that could present a problem for Preview users, we document it in the [Known Issues document](https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md) for the release. 

New features and functionality provide opportunities for your projects to possibly solve problems in new ways. We have "what's new" issues available detailing many of the new features of .NET 6. Here's the issue for Preview 3 - [dotnet/core#5890](https://github.com/dotnet/core/issues/5890).

**Comment by srxqds** [comment]
hi, I found there are so many tests not passed https://github.com/dotnet/runtime/projects/48, will there be fixed at last?
the .net5 has 8 previews, why .net6 only 7 previews?

**Comment by Gabriel-Tavares-GB** [comment]
When Microsoft released version 1.0 it rated it stable for production. So we can objectively and officially say that yes, it is ready to be used in commercial applications.

In fact, a lot of people are already using it under these conditions.

Some people complain about some things. Including the lack of some components. Some that will never be implemented because it doesn't make sense in the .NET Core (but even that has changed a bit), others that we need to wait for a while, or get some alternative, as many people have done.

**Comment by angelochu7** [comment]
I visited this page because I tried to google "Why there are so many previews in .net 6?".
I am very confused by this preview thing in .net 6 and Xamarin MAUI preview 14,15 whatever. As a developer, I just want to focus on using a product which is stable enough and not confused by the update of .net version number like .net 4, .net 5, .net 6 or whatever.

**Comment by mairaw** [comment]
Closing this issue since .NET 6 already released. .NET 6 had 7 preview releases and two release candidate releases before the final release in November.

The preview releases are meant to give developers a chance to try out the product before it's final. Right now, .NET MAUI is in preview as well as .NET 7.
You don't need to use any of the preview releases. You can always head to https://dotnet.microsoft.com/download and download the latest stable version.

**Comment by angelochu7** [comment]
Thanks a lot mairaw for your prompt reply. It's clear now that I can ignore all the preview thing and updates about preview as I have already seen a lot or too much on the youtube.
By the way, the rapid change of updated .net version just make a simple person like me gone crazy.

**Comment by mairaw** [comment]
Our product is now set to release every November:
https://dotnet.microsoft.com/platform/support/policy#dotnet-core

Upgrade from one version to the next should be straightforward. But you can adopt one LTS release (.NET 6, for example) and they are supported for 3 years.
