### ISSUE TITLE
Facing issue in building my project on build server. <query>

### ISSUE THREAD

**Issue by arpit-nagar** [dotnet/core#619]
I am facing issue in building my project on build server.
My .net core configurations are
```
   D:\>dotnet --info
   .NET Command Line Tools (1.0.0-preview2-1-003177)
   
   Product Information:
    Version:1.0.0-preview2-1-003177
    Commit SHA-1 hash:  a2df9c2576
   
   Runtime Environment:
    OS Name: Windows
    OS Version:  6.3.9600
    OS Platform: Windows
    RID: win81-x64
```

My Solution structure is    
 ```
  abc.sln
       a.csproj
       b.xproj
       
```
where b has multitargeting class library which supports net461 and netstandard1.6
while a is in net461 and has reference of b.

I want to build this project on my build server that is jenkins (installed on windows) which has dotnet core installed.

Please suggest how to build this project via command line.

FYI : It builds on my Local via VS15.

**Comment by Petermarcu** [comment]
I think the best approach would be to migrate your xproj to a csproj and get onto the 1.0 RTM tooling. After that, you should just be able to run `dotnet build`.

@livarcocc

**Comment by livarcocc** [comment]
Correct. Migrate your xproj to csproj using the dotnet migrate command.

**Comment by richlander** [comment]
Your scenario isn't well supported. We didn't have good support for xproj / csproj interop in VS 2015. And we don't support xproj in VS 2017 where the interop between various .NET project types is much better because everything is based on msbuild.

Closing because this experience isn't going to get better. Best plan is to move to VS 2017 to get the experience I believe you are looking for.
