### ISSUE TITLE
Error when trying to create a microservice during a tutorial

### ISSUE THREAD

**Issue by MarkusEicher** [dotnet/core#6192]
![Error](https://user-images.githubusercontent.com/83175378/115999143-f538c200-a5ea-11eb-9d5c-6d9404db6c40.PNG)
![DotNet-Info](https://user-images.githubusercontent.com/83175378/115999219-40eb6b80-a5eb-11eb-83ee-27c20d2ef92c.PNG)

Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/intro/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
From what I read on forums, this issue seems to be related to NuGet package sources.
Can you check the file `%appdata%\NuGet\NuGet.Config` and see if it has the package source configured it correctly?
Similar to https://stackoverflow.com/questions/62102318/hello-world-dotnet-core-example-not-working

**Comment by MarkusEicher** [comment]
Hi Maira

Thanks a lot! Great work. That was the problem. After setting the path to the default NuGet Repo, the build was successful. Your link was helpful and lead me to the Microsoft docs page [https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior](url) explaining it further. Have a great day and greetz from old Switzerland to California.

**Comment by mairaw** [comment]
Great to hear! 🌞
