### ISSUE TITLE
Wrong NuGet package version is selected during docker build dotnet core 3.1 web app

### ISSUE THREAD

**Issue by denissoloviy** [dotnet/core#6194]
### Description

Sometimes after the docker image is built and the container is created requests fail in runtime with an error: 
`System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

The issue is that the application uses two NuGet packages and both of them use System.Data.SqlClient but different versions of it:
1. System.Data.SqlClient 4.6.1 (Assembly 4.5.0.1)
2. System.Data.SqlClient 4.7.0 (Assembly 4.6.0.0)

According to the dependency resolution article, version 4.7.0 should be selected: https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#cousin-dependencies

But sometimes the image is built in the way that version 4.6.1 of System.Data.SqlClient is copied to the bin folder. At the same time, the correct version "System.Data.SqlClient": "4.7.0" was written to the file deps.json.

It is a very rare case, but it happens several times per month. After rebuilding, containers from the new image work properly without exceptions.
We have noticed that this error mainly occurs when many builds are running on the build machine at the same time, but not always.

Does anyone know what can cause this issue and how it can be fixed?

### Configuration

* .NET Core 3.1
* Docker 1.153.5, Linux container
* Base build image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
* Base runtime image: mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim

### Regression?

From Internet articles, I see that this problem arises for the .Net Framework and it was fixed with bindingRedirect and in .Net Core it should be resolved automatically.

**Comment by joperezr** [comment]
Thanks for logging the issue @denissoloviy! Do you happen to have some logs or something to look at for the restore? I assume that somwhere in the build of the docker image, you are running `dotnet restore` on the project since it is the one in charge of generating the deps file, and that one seems to be pointing to the right higher version, but looks like for some reason that isn't the one getting restored. My suggestion in here is that if you happen to get a repro, having some diagnostic logs for that restore would be very useful for the NuGet team to diagnose what might be going on. In order to do that, I would suggest to add the generation of a binlog when you call `dotnet restore /bl:Restore.binlog` in your Dockerfile so that they can have more info on what is going on.
