### ISSUE TITLE
Unable to build aarch64 wheel

### ISSUE THREAD

**Issue by odidev** [dotnet/core#6198]
Hi Team,
I am trying to test Dotnetcore2 on ARM64 architecture but it seems there are **no wheels available for arm64** and **no 'pyproject.toml' or ‘setup.py’** file available to install/build it through source code.

Also, I am not sure which CI is being used here to test as it is not mentioned anywhere in the ReadMe document.

May I know how you are building and testing the wheels?

**Comment by joperezr** [comment]
Hello @odidev  thanks for logging your issue. Is there a reason why you want to install dotnet core via wheels/python? My suggestion would be to check out our main download page: https://get.dot.net where you can find the links to all install packages for all of the supported archs as well as some instructions on how to install using package managers for some Linux distros. Also, I would suggest to not install .NET Core 2.0 since that is no longer supported, and instead you might want to take a look at one of our LTS versions ([.NET Core 2.1](https://dotnet.microsoft.com/download/dotnet/2.1), or [.NET Core 3.1](https://dotnet.microsoft.com/download/dotnet/3.1)), our latest stable version ([.NET 5.0](https://dotnet.microsoft.com/download/dotnet/5.0)), or our v-next preview version ([.Net 6.0](https://dotnet.microsoft.com/download/dotnet/6.0))
