### ISSUE TITLE
Is there any internal command line parser in dotnet 

### ISSUE THREAD

**Issue by ajithvallabai** [dotnet/core#6334]
Hi, 
Is there any internal command line parser in dotnet that doesnt create a .dll file while execution ?

**Comment by ManickaP** [comment]
I assume you could easily find multiple libraries and check if some of them fit your requirements.

Note that this is my personal recommendation and not an official one from Microsoft, but I've seen this https://github.com/dotnet/command-line-api used for instance here: 
https://github.com/dotnet/runtime/blob/5c0a1faf8fc3c8e9d4596b31ac0fbc3173a1915e/src/libraries/System.Net.Http/tests/StressTests/HttpStress/Program.cs#L33-L109

I found also https://github.com/commandlineparser/commandline with quick search. Although I have never personally used it, it seems to be quite popular.

I hope this answers your question.

**Comment by ajithvallabai** [comment]
@ManickaP  i checked those libaries (Commandlineparser, System.CommandLine ) they are prodcing a .dll file when i am building it . Is there any libariry that i can use from references(Assemblies or COM objects) for command line parsing

**Comment by ManickaP** [comment]
What do you mean by "prodcing a .dll file when i am building it"? Do you mean that there's an extra dll in the output for the referenced library? Like `System.CommandLine.dll`? Or do you mean something else?

If yes, there's not baked-in support for command line parsing in .NET AFAIK. 

BTW, this is normal behavior for referenced packages. If you'd prefer more compact output you can check out `-p:PublishSingleFile=true` here: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish.

**Comment by ajithvallabai** [comment]
yes there is a extra dll file(System.CommandLine.dll) in the "Release"(output) folder. if i want to use only .exe file in a separate place i need to include .dll file along with it , my target is to elimiate the need to .dll file .      I will look into the link you gave . also another question Is there any library for commandline parser avaliable here (https://ibb.co/Hgcy2mk ) in Assemblies or COM panel

**Comment by ManickaP** [comment]
If your goal is to have a single exe to deploy than what I linked should help you, there's some more detailed documentation about it: https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file

> Is there any library for commandline parser avaliable here (https://ibb.co/Hgcy2mk ) in Assemblies or COM panel

What you are linking is .NET Framework, that's out-of-scope for this repository, but AFAIK there isn't framework support for command line parsing. You could use one of the linked libraries (as a nuget package) since both of them seem to support `.NET Standard 2.0` so they should be compatible with `.NET Framework` from 4.6.1 and higher. However, there's no such thing as single-file publish for .NET Framework (or at least I don't know of any).

I hope your question was answered here, I'll close this. Feel free to reopen if you have some more.

**Comment by ajithvallabai** [comment]
@ManickaP  thanks
