### ISSUE TITLE
Is cd a command or not?

### ISSUE THREAD

**Issue by NASIM537** [dotnet/core#6414]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hi, I wonder if cd is a dotnet command?
What does it stand for?
best regards nasim

**Comment by krwq** [comment]
No, `cd` stands for "change directory". It's command line equivalent to opening a folder. In this specific tutorial:
- `dotnet new console -o myApp` creates a folder `C:\Users\Ana\myApp` with a new .NET console project
- without `cd` command all commands would execute from `C:\Users\Ana` so the tutorial tells you to go to `myApp` folder so that commands become simpler

**Comment by krwq** [comment]
I'll mark this question as answered and close the issue. Please go ahead and re-openor create a new issue should you have any more quuestions.
