### ISSUE TITLE
it shows not installed .net core SDK Even after I installed it

### ISSUE THREAD

**Issue by Pranshu-Desai** [dotnet/core#6523]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![Screenshot (46)](https://user-images.githubusercontent.com/84431499/127758070-652b9154-904f-4c6e-9104-5d26be3da5e3.png)

**Comment by mairaw** [comment]
Can you paste the output of `where dotnet.exe`? If your system is x64 and the x86 path is shown first, I'd recommend you follow the steps I explain here to fix the issue: https://github.com/dotnet/core/issues/5962#issuecomment-780084535

**Comment by SamUnimelb** [comment]
Having exactly the same issue.

**Comment by Calkines** [comment]
related to #6542

**Comment by mairaw** [comment]
@SamUnimelb what is the output of `where dotnet.exe` for you? Did you try the steps outlined on https://github.com/dotnet/core/issues/5962#issuecomment-780084535?

@Calkines I try to help every customer reporting this issue since they're usually new to the platform. The actual duplicate issue is #5962 and you can see how many times I referred back to that issue from other dupes.
