### ISSUE TITLE
Uri constructor different behavior on Unix/Windows

### ISSUE THREAD

**Issue by HenadziBaranau** [dotnet/core#6530]
### Description
Same path is handled differently on different platforms. For unix systems - it's treated as file path, so we have access to instance's props. For windows - it's relative path and exception is thrown. Would expect same behavior cross platforms.

```
Uri uri = new Uri("/relative/path");

string path = uri.PathAndQuery;
Console.WriteLine(path);

//Unix output
"/relative/path"

//Windows
System.UriFormatException : Invalid URI: The format of the URI could not be determined.
```

### Configuration

* Which version of .NET is the code running on?
 .NET 5

* What OS and version, and for Linux, what distro?
Microsoft Windows 10 Pro, 0.0.18362 Build 18362
mcr.microsoft.com/dotnet/aspnet:5.0.7-alpine3.12

* What is the architecture (x64, x86, ARM, ARM64)?
x64

### Other information
Stacktrace:
```
System.UriFormatException : Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
```

**Comment by ryank425** [comment]
According to Docs, https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=net-5.0

These implicit file paths are not compliant with the URI specification and so should be avoided when possible. When using **.NET Core on Unix-based systems, implicit file paths can be especially problematic, because an absolute implicit file path is indistinguishable from a relative path**. When such ambiguity is present, Uri default to interpreting the path as an absolute URI.

So UNIX would interpret implicit file path as absolute URI.

/relative/path cannot be absolute path in Windows. For any file uri to be absolute path in Windows, it has to qualify all conditions in either DOS or UNC paths. 

https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths

**Comment by MihaZupan** [comment]
That's correct, this is (sadly) by design.

In general, try to specify the desired `UriKind` to the constructor - `new Uri("/foo", UriKind.Relative)`.

**Comment by HenadziBaranau** [comment]
Thank you for explanation! Then seems that issue can be closed.
