### ISSUE TITLE
Problems with .net

### ISSUE THREAD

**Issue by PASTASGRAVA** [dotnet/core#6542]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

I have an error after installing .net and trying to give it any command it says this
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

**Comment by adamsitnik** [comment]
Hi @PASTASGRAVA 

Could you please open a new terminal and run the following command and share it's output?

```cmd
dotnet --info
```

**Comment by PASTASGRAVA** [comment]
It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.12
  Commit:  0267ad09c6

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
thats it

**Comment by adamsitnik** [comment]
@PASTASGRAVA is there any chance that you have used the `Runtime` instead of `SDK` installer?

![obraz](https://user-images.githubusercontent.com/6011991/128516782-7d36591e-3f70-46e5-abf0-9b4ad3e01a5c.png)

Could you please try to download the SDK installer and run it? It can be found at: https://dotnet.microsoft.com/download/dotnet/3.1

**Comment by PASTASGRAVA** [comment]
I think i downloaded the right one the first time it is called dotnet-sdk-3.1.411-win-x64

**Comment by adamsitnik** [comment]
I've run out of ideas. @NikolaMilosavljevic joeloff could you please help us?

**Comment by NikolaMilosavljevic** [comment]
@PASTASGRAVA, do you have the following log in your %TEMP% folder?

`Microsoft_.NET_Core_SDK_3.1.411_(x64)_20210805002246.log`

The date would be different, as the log name is unique but the log name would start with `Microsoft_.NET_Core_SDK`

Can you share all of those logs?

cc @joeloff

**Comment by joeloff** [comment]
Based on your output you have an x86 runtime install, so it's likely that the x86 copy of dotnet is on your path.

```
NET Core runtimes installed:
Microsoft.NETCore.App 3.1.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Run ```SET PATH``` and check if "Program Files (x86)\dotnet" is on your path first.

You can swap the PATH order if you go to the OS settings and change system environment variables

**Comment by PASTASGRAVA** [comment]
C:\Program Files (x86)\dotnet\ i have it in the set path

**Comment by PASTASGRAVA** [comment]
buuuuuuut how do in get to the os settings

**Comment by PASTASGRAVA** [comment]
i have a lot of that type of file in the temp folder too
![Microsoft_ NET_Core_SDK - Risultati ricerca in Temp 06_08_2021 20_45_11](https://user-images.githubusercontent.com/88540949/128557645-c8627b82-f315-477e-89f3-3131908ed0a0.png)

**Comment by joeloff** [comment]
> buuuuuuut how do in get to the os settings

Go to start, click on settings (the little gear icon) and search for system environment variables

![image](https://user-images.githubusercontent.com/7409981/128560889-10a25b41-6a51-4e94-923b-dc0d28825232.png)

**Comment by PASTASGRAVA** [comment]
on what option should i pick?

**Comment by joeloff** [comment]
The system environment variables. The problem you're running into is coming from the global PATH environment variable

**Comment by PASTASGRAVA** [comment]
![Uploading Variabili d'ambiente 06_08_2021 21_21_59.png…]()

**Comment by PASTASGRAVA** [comment]
![Uploading Variabili d'ambiente 06_08_2021 21_21_59.png…]()

**Comment by PASTASGRAVA** [comment]
and what should i do

**Comment by joeloff** [comment]
Your path likely contains two entries: Program Files (x86)\dotnet;Program Files\dotnet. You need to swap them around so that Program Files is first. 

You can verify it another why by opening a command prompt and running "Where dotnet" and it's likely going to point you at the 32-bit host

**Comment by PASTASGRAVA** [comment]
C:\Users\Utente\AppData\Local\Programs\Python\Python38\Scripts\ this is my path directory

**Comment by PASTASGRAVA** [comment]
C:\Users\Utente>Where dotnet
C:\Program Files (x86)\dotnet\dotnet.exe
C:\Program Files\dotnet\dotnet.exe

**Comment by PASTASGRAVA** [comment]
so?

**Comment by joeloff** [comment]
the SDK you installed is 64-bit, it lives under Program Files, not Program Files (x86). When you run dotnet, the host is running against the 32-bit runtime you installed and there are no corresponding SDKs, that's why dotnet --info tells you there are no SDKs. The fix is to swap the dotnet paths on the global PATH environment variable.

**Comment by PASTASGRAVA** [comment]
can u write step per step how to do it?

**Comment by joeloff** [comment]
Open the environment variable settings like I previously described and select the Environment Variables button

![image](https://user-images.githubusercontent.com/7409981/128565394-cf3837eb-2d5d-4edb-b8cb-709b774a7914.png)

Select the the Path variable under System Variables and click on Edit

![image](https://user-images.githubusercontent.com/7409981/128565506-47f22791-31a6-41f5-9b2c-99515a78d067.png)

Then swap the dotnet path entries around so that Program Files\dotnet is first and save the changes,

Then open a new command prompt, run "where dotnet" to verify that it's selecting the 64-bit copy of dotnet

**Comment by PASTASGRAVA** [comment]
idk why i cant hit the edit button

**Comment by PASTASGRAVA** [comment]
![Screenshot 06_08_2021 22_09_07](https://user-images.githubusercontent.com/88540949/128565932-1233d735-b93f-4271-b48d-5771ff89030b.png)

**Comment by PASTASGRAVA** [comment]
edit is modifica in italian

**Comment by joeloff** [comment]
You need to have administrator rights, or at least belong to the local administrators group usually

**Comment by PASTASGRAVA** [comment]
i am the only one using this pc

**Comment by PASTASGRAVA** [comment]
how can i have admin

**Comment by joeloff** [comment]
If you created the OS installation originally, it should have given you the option to create an administrators account or make the default account part of the administrators group. The latter seems true since you were able to install .NET and that would require additional permissions. You can try looking at your account settings and see if you can add your user account to other groups.

You might find more information on some of the general Windows forums or Stack Overflow as well

**Comment by mairaw** [comment]
You'll need admin permissions to your machine in order to install the SDK. If you don't, you might try the .NET Coding Pack:
https://dotnet.microsoft.com/learntocode

Hopefully that helps.
