### ISSUE TITLE
Sample Hello world code not running

### ISSUE THREAD

**Issue by nagamanikandank** [dotnet/core#66]
Sample Hello world code not running. The error I get is 
error NU1001: The dependency NETStandard.Library >= 1.0.0-rc2-23704 could not be resolved. Any of you have solved this?

**Comment by zerkms** [comment]
Yep, the same here for ubuntu 14.04:

```
vagrant@vagrant-ubuntu-trusty-64:~/src/helloworld$ dotnet restore
log  : Restoring packages for /home/vagrant/src/helloworld/project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json 1314ms
error: Unable to resolve NETStandard.Library (>= 1.0.0-rc2-23704) for DNXCore,Version=v5.0.
info : Committing restore...
log  : Restore failed in 1990ms.

Errors in /home/vagrant/src/helloworld/project.json
    Unable to resolve NETStandard.Library (>= 1.0.0-rc2-23704) for DNXCore,Version=v5.0.

NuGet Config files used:
    /home/vagrant/.nuget/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
```

**Comment by blackdwarf** [comment]
The issue here is that for dev builds you need to have a feed configured to restore from that has the packages. https://github.com/dotnet/core/blob/master/cli/known-issues.md#on-dev-builds-of-the-tools-restoring-default-project-from-dotnet-new-fails has all of the details.

With that, I will close this issue. If you have more questions/problems, please file issues on dotnet/cli.
