### ISSUE TITLE
NET5.0.9 ListView BackgroundImage GDI object leakl

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/core#6667]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET509-ListView-BackgroundImage-GDI-ob/1523781)._

---
[severity:I'm unable to use this version]
When a win forms app shows a form with a ListView Control that has its BackgorundImage set it does not release 3 GDI objects each time it is disposed and Garbage collected, this is causing major memeory leaks in our application.

Attached is a sample application to demonstrate the issue.

All I did to re-create this, is the following.

1. Create a new winforms application

! [image.png] (https://aka.ms/dc/image?name=B61a68d46b0fe4c56a909fffec5bba42b637666225390710726_20210907-154216-image.png&tid=61a68d46b0fe4c56a909fffec5bba42b637666225390710726)
! [image.png] (https://aka.ms/dc/image?name=B090d5835c06a4ece80cfb42692a4281a637666225584792968_20210907-154236-image.png&tid=090d5835c06a4ece80cfb42692a4281a637666225584792968)

2. Add a new form so you have a Form1 and a Form2.

! [image.png] (https://aka.ms/dc/image?name=B62ef700bdc9a485ca07611967b59f3e9637666226095119777_20210907-154328-image.png&tid=62ef700bdc9a485ca07611967b59f3e9637666226095119777)

3. Add two buttons on Form1, one to garbage collect, and one to open Form2.

private void btnGarbageCollect_Click(object sender, EventArgs e)
		{
			GC. Collect();
		}

private void btnOpenFormWithListView_Click(object sender, EventArgs e)
		{
			Form2 oForm = new Form2();

oForm.Show();
		}

4. On Form2 add a listview and set a backgroup image from a resource.

! [image.png] (https://aka.ms/dc/image?name=B3d624fa9f8d34f70a6c1e4505fb6f070637666227324751896_20210907-154531-image.png&tid=3d624fa9f8d34f70a6c1e4505fb6f070637666227324751896)

5. Open Task manager with the GDIObjects coulmn enabled, and keep opening and closing from 2 from the app and garbage collecting, you will see a jump of 3 GDI objects each time you open and close the form.

! [image.png] (https://aka.ms/dc/image?name=B09d1a6e34f0d459e89d8f070ca89bf26637666228779511636_20210907-154755-image.png&tid=09d1a6e34f0d459e89d8f070ca89bf26637666228779511636)

---
#### Feedback Bot on 9/8/2021, 09:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Marie-Shi** [comment]
**More info:**
1.	This is not a regression issue, it can repro in .Net Framework, also can repro in .NET 3.1, 5.0& 6.0.
2.	This issue cannot repro in imageList.

**Repro Steps:**

1.	Extract the attachment “BackGroundImageIssue.zip” and open it in VS.
2.	Open Task manger, select the 'Details' tab and add GDI objects column if not already visible.
3.	Build and run the application, click ‘Open Form With List View’ button to open Form2 then close Form2, then click ‘Garbage Collect’ button, repeat this operation several times.

**Actual behavior:**
The number of GDI objects are increasing.
![feedback](https://user-images.githubusercontent.com/45864017/132482817-39086948-5b66-4053-b626-5748b930ace7.gif)

**Expected behavior:**
"GDI objects" don't increase.

**Comment by Marie-Shi** [comment]
It is a Winforms issue, dup of https://github.com/dotnet/winforms/issues/5717, please help to close it.
