### ISSUE TITLE
i cant add counter in home page

### ISSUE THREAD

**Issue by Arunima-98** [dotnet/core#6703]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/add
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by tannergooding** [comment]
Can you please provide additional details such as what happens when you add `<Counter />` to your home page and what you expected to happen?

Ideally you would provide a series of steps such as:

> **Repro:**
> 1. Run `dotnet new console` using the .NET 6 RC1 SDK
> 2. Add the following code to the project:
> ```csharp
> Console.WriteLine("Hello");
> ```
> 3. Run `dotnet run`
>
> **Expected Behavior:**
> I expected the following to happen
>
> **Actual Behavior:**
> This actually happened

This makes it very easy for anyone reading the issue to reproduce the same issue and understand the context of what's happening.
