### ISSUE TITLE
Unable to Find MDK

### ISSUE THREAD

**Issue by rgphys** [dotnet/core#6832]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Every time I run the dotnet command, it throws me an error saying that it's unable to find a MDK, however if I open the directory the MDK is installed in, type in CMD from there(doesn't work if I navigate to it through the CD command), it works correctly.

**Comment by CrazeXD** [comment]
![image](https://user-images.githubusercontent.com/90533906/138354777-bed8f63d-7163-4af3-bbb1-9d7d7e92c658.png)

**Comment by steveharter** [comment]
Can you try `dotnet --list-sdks`? If no SDKs are reported back, the SDK wasn't installed successfully.

Also try opening a new command prompt to ensure the PATH environment variable is properly set.

**Comment by CrazeXD** [comment]
I got it to work, here were the steps I took.
I completely uninstalled the SDK instead of just clicking repair I guess I'm stupid i dont know why I didn't do it before. I reinstalled and now it is able to find the SDK. 
However now, when I run `dotnet build` it say's it cant find any projects, even though I am in the directory. I tried it with the --project as well, then it just throws 
![image](https://user-images.githubusercontent.com/90533906/138368344-4652ff50-60cb-4d9c-b929-23c740de239e.png)
This is my first time with C#, so the only code I have written is Console.WriteLine("hello world!") so i dont see what the problem is.
