### ISSUE TITLE
Unclear what should happen.  Changing a property of an object in a collection doesn't change equality of comparing parent records.

### ISSUE THREAD

**Issue by sharpninja** [dotnet/core#6854]
### Description

While doing some edge case research on records, I found an inconsistent behavior with the Equals method.

Scenario:

A record contains a collection of data.  If any values inside the collection change, there is no effect on the Equals comparison of two instances of the record.

```csharp
void Main()
{
	var array = new ClassNode[10];
	Enumerable.Range(0,10).ToList().ForEach(i => array[i] = new ClassNode(i));
	var list = new List<ClassNode>(array);
	
	var record1 = new RecordNode("Data", list);
	var record2 = record1 with { };
	
	Console.WriteLine(record1.Equals(record2));

	record2.Children[0].I++;

	Console.WriteLine(record1.Equals(record2));
}

public record RecordNode(string Data, List<ClassNode> Children)
{
}

public class ClassNode
{
	public int I {get; set;}
	public ClassNode(int i)
	{
		I = i;
	}
	public int Hash => GetHashCode();
}
```

In this case I would expect output to be 

```
true
false
```

Actual output is

```
true
true
```

### Configuration

.Net 5.0.11
Windows 11 version 22000.282

### Regression?

New feature in .Net

### Other information

I would expect that the Equals method of record would do a deep comparison o it's object hairarchy.

**Comment by svick** [comment]
This is behaving exactly as it should, for several reasons:

1. The `with` operator creates a shallow copy of the record. This means the two records in the example *share* the same instance of `List<ClassNode>` and so any modification to the list of `record2` is reflected in the list of `record1`. (Because it's the same list). One way to see that is by printing `record1.Children[0].I`.
2. The automatic implementation of `Equals()` for records uses default equality for each of its values. For .Net collection types, that (unfortunately) means reference equality: it doesn't matter what's inside the collection, two different instances of a `List<T>` will always compare as not equal.
3. `ClassNode` is a class and you didn't override equality, so it uses the default reference equality. This means incrementing `I` will have no effect on equality of `ClassNode`s.

**Comment by eerhardt** [comment]
cc @333fred @agocke @jcouv

**Comment by 333fred** [comment]
As svick said, this is behaving as intended. The only thing the record can do is trust what the collection says for equality, and List doesn't do value equality. If you need that, you need to either write the `bool Equals(RecordNode other)` member by hand, or wrap the list in a custom type that will do equality by value instead of by reference for the collection.

**Comment by sharpninja** [comment]
> As svick said, this is behaving as intended. The only thing the record can do is trust what the collection says for equality, and List doesn't do value equality. If you need that, you need to either write the `bool Equals(RecordNode other)` member by hand, or wrap the list in a custom type that will do equality by value instead of by reference for the collection.
