### ISSUE TITLE
C:\Users\admin>dotnet new webApp -o myWebApp --no-https Failed to load the dll from [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\6.0.0-rc.2.21480.5\hostpolicy.dll], HRESULT: 0x800700C1 An error occurred while loading required library hostpolicy.dll from [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\6.0.0-rc.2.21480.5]

### ISSUE THREAD

**Issue by muneerah1418** [dotnet/core#6861]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by eerhardt** [comment]
What version of windows are you using?

@vitek-karas @agocke - are there steps to diagnosing these kinds of issues? Does the VC runtime need to be installed?

**Comment by vitek-karas** [comment]
On OSes below Win 10 there are prereqs which must be installed. The full error should actually point this out and include a URL to the docs. Here's the relevant doc: https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50#additional-deps

Since this is looking for 32bit hostpolicy - I think this might be some problem with the project/setup. Something like 64bit dotnet trying to run 32bit runtime...

* Can you please run `where dotnet.exe` - to see if it's using the 32bit or 64bit executable?
* What command are you executing?
* Do you have any environment variable set which starts with `DOTNET_`?

**Comment by vitek-karas** [comment]
I'm not familiar with that bug - do you have specifics?
@joeloff for windows installer details.

**Comment by joeloff** [comment]
There's no real detection logic other than opening a prompt and running SET PATH to look at the contents and determine whether the x86 path is first. We've made some changes that will become available in the next servicing releases, but the only fix for now is to edit the PATH variable if it's swapped.

**Comment by mairaw** [comment]
@adegeo have we documented the path issue on docs already? I know we discussed it in the past, but I'd like to point to a more official location rather than stack overflow. I'm adding that as a verification step on our activation tutorials.

**Comment by adegeo** [comment]
@mairaw this got lost in my inbox. I did update the doc with some info about this kind of issue with ARM processors. How prevalent is this issue? I thought you wouldn't want both x32 and x64 on the same machine anyhow?
