### ISSUE TITLE
(dotnet-sdk-6.0.100-osx-x64) cannot be installed

### ISSUE THREAD

**Issue by Ktomo1995s** [dotnet/core#6903]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

I installed  cannot be installed, but when I enter (dotnet), it outputs (zsh: command not found: dotnet).
Please tell me how to solve the problem.

**Comment by mairaw** [comment]
So did you manage to install the SDK or not? And what is your macOS version?

Here are some topics that perhaps might help you:
https://docs.microsoft.com/dotnet/core/install/how-to-detect-installed-versions?pivots=os-macos
https://docs.microsoft.com/dotnet/core/install/macos

**Comment by Be3y4uu-K0T** [comment]
I'm facing the same problem. And I just downloaded for `Arm64 download` on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install.

Operating System: macOS Monterey 12.0.1
MacBook Air (M1, 2020)

**Comment by Ktomo1995s** [comment]
thank you for your reply.
I'm using MacBookPro(M1 Pro).
Installation of (SDK6), (SDK5), and (Core3.1) is completed.

The reason I'm asking this question is that I got the error [The .NET Core SDK cannot be located. .NET Core] when I was using VSCode.

**Comment by Ktomo1995s** [comment]
But VS Code is working fine now.
Is it necessary to install SDK?

**Comment by mairaw** [comment]
Are you being able to follow the tutorial now @Ktomo1995s? The SDK (or the .NET Coding Pack for VS Code) is necessary for you to create .NET applications.

**Comment by EnricoTirotta** [comment]
Some issue here with .Net SDK standalone installation.
I try on my new **MacBook Air M1 2020**. **Monterey OS**.

_home@Air-di-Enrico ~ % dotnet
zsh: command not found: dotnet_

Spotlight didn't find any folder _dotnet/sdk_ or something else. I manually search for dotnet, there isn't on HD.

I installed Visual Studio Preview 3 for Mac, with .Net 6. This fix the issue

home@Air-di-Enrico ~ % dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
home@Air-di-Enrico ~ % 


So, there is some problem with standalone package

**Comment by mairaw** [comment]
@marcpopMSFT can you check this issue?

**Comment by marcpopMSFT** [comment]
Did the customer install the arm64 or the x64 version of the SDK? If I were guessing based on the details of not finding it, I'd guess x64 which no longer sets itself on the path by default and installs to an alternative location.  See more details here: https://github.com/dotnet/sdk/issues/22380

CC @richlander

**Comment by ericstj** [comment]
Assuming this is an M1 machine.  Check that `/usr/local/share/dotnet/dotnet` exists.  If it doesn't install the ARM64 SDK.   `dotnet` may be missing if an `x64` runtime or SDK is installed on a machine which previously had an unsupported `x64` version of `dotnet`.

This could also happen if you install x64 SDK instead of arm64.  Be sure you're downloading and installing the `arm64` pkg.  You may need to explicitly select it here:
https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-6.0.100-macos-arm64-installer

I strongly suspect you accidently installed x64.  It looks like this is actually what's recommended by default for M1 machines on get.dot.net.

If this didn't help resolve the issue, to collect some information, run the following commands and share the result with us:
```
find /usr/local/share/dotnet -name "dotnet"
cat /etc/paths.d/dotnet
uname -m
sysctl sysctl.proc_translated
```

If you suspect a problem during installation you can access installation logs during an install using `command + L` from the installer and choosing `Show All Logs` from the `Installer Log` window, then choosing `Save`.  You can do the same from the terminal using `sudo installer -verboseR -dumplog -target / -pkg pathToInstaller.pkg > install.log`

**Comment by EnricoTirotta** [comment]
@ericstj  You're right. The automatic recommended package on Website is wrong for M1 machines.
I didn't check if there were multiple versions, I thought the download for the current computer was correct.

**Comment by mairaw** [comment]
@richlander and I were discussing about the page detecting the right OS but there seems to be some issues about user-agent info on M1 machines. A quick workaround would be to offer both x64 and Arm64 on that page until we can figure out if we can show just one.

@adegeo do we cover this scenario on the install docs for macOS as @ericstj described above with the location changes for M1?

**Comment by kumarrrr** [comment]
Still the problem exists with M1 machine,

**Comment by mairaw** [comment]
@kumarrrr try installing the Arm64 version for your M1 machine.
