### ISSUE TITLE
how to install .net 6 in centos 8?

### ISSUE THREAD

**Issue by FreshmanChina** [dotnet/core#6913]
how to install .net 6 in centos 8 please?
 "*CentOS 8 will reach an early End Of Life (EOL) on December 31st, 2021. For more information, see the official CentOS Linux EOL page. Because of this, .NET 6 won't be supported on CentOS Linux 8."
[https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos#centos-8-](https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos#centos-8-)

**Comment by eiriktsarpalis** [comment]
The CentOS distribution is being discontinued, and as such new releases of .NET won't be supporting it. cc @Thraka @leecow

**Comment by FreshmanChina** [comment]
Thank you!

**Comment by omajid** [comment]
FWIW, .NET 6 is available as a part of RHEL 8 repositories, so it's possible that the CentOS 8 maintainers will build .NET 6 and include it too, when they update CentOS to match the RHEL 8.5 release.

**Comment by johnwc** [comment]
@eiriktsarpalis My understanding of CentOS 8 is not that they are discontinuing it, but rather changing it's distribution model. CentOS 8 stream is the replacement distribution, and is still CentOS 8 no? Also it gives it extended support till 2024. Why drop the support all together for the OS, when it still will be supported for so long?

**Comment by goforgold** [comment]
![image](https://user-images.githubusercontent.com/1727061/151395395-d6c6fff4-24b7-487f-87e2-909731690c69.png)

CentOS 8 Stream is very much supported. Is there a way to install the .NET 6 on CentOS 8?

**Comment by johnwc** [comment]
Since Centos, Alma, Rocky, etc... are red hat(Enterprise Linux) binary compatible, why not just produce a Enterprise Linux install?

The .net that comes via the red hat repos is usually not always at the current released version. We need a repo that we can install from for Enterprise Linux compliant distros that contains current released version. Especially when there is security updates.

**Comment by omajid** [comment]
In general, .NET packages are included with CentOS Stream 8 (eg, `sudo dnf isntall dotnet-sdk-3.1` should work out of the box)

We have been having some trouble with .NET 6, though. The CentOS 8 maintainers pinged me a few weeks ago about a bug building .NET 6 on CentOS 8, and I couldn't reproduce it. I *just* narrowed it down to https://github.com/dotnet/source-build/issues/2731 and we are still trying to understand what the issue is and how to fix it.

@goforgold In the meantime, try a manual install: https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual
