### ISSUE TITLE
Choice of pinned repos seems odd

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/core#6948]
Why is "installer" important, for example?

Many good candidates (sorted by stars):

![image](https://user-images.githubusercontent.com/4169187/142765992-452c62d0-ad39-4f6e-a979-0a403883dda1.png)

**Comment by eiriktsarpalis** [comment]
cc @terrajobst @richlander

**Comment by terrajobst** [comment]
I believe I have added installer because it includes the giant table in the README.md that allows people to download nightlies. As such, it's probably one of more useful ones. corefx and coreclr are merged into runtime, which is why I unpinned those two. There is a limit of 6 pinned repos, so we just more or less pinned the "big rocks". But yeah, there is no perfect set.

**Comment by eiriktsarpalis** [comment]
I suppose we can close this as answered.
