### ISSUE TITLE
Ubuntu 21.04 (Hirsute Hippo) reaches End of Life on January 20 2022

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#7028]
[Ubuntu 21.04 reaches end of life on Jan 20, 2022](https://lists.ubuntu.com/archives/ubuntu-announce/2021-December/000275.html#:~:text=Ubuntu%2021.04%20(Hirsute%20Hippo)%20reaches,Life%20on%20January%2020%202022/)
This issue is created to track progress for the remove support for Ubuntu 20.10 from .NET Core 2.1, .NET Core 3.1 and .NET 5.0

### Repos team to update:

- [ ] Remove installers for the outdated distro
- [ ]  Remove build support
- [ ]  Remove test assets

### Infrastructure Team Accountabilities/Deliverables:

- [x]  Notification to NetCore Engineering Partners
- [x]  Remove the outdated version from the hardware pool 

### Release Team

- [x]  Send Notification to every team in .NET for upcoming addition
- [ ]  Supported OS content gets updated on GitHub and marketing sites. 
- [ ]  Update release manifest files. 
- [ ]  Docker files which are used for install testing needs to be updated. 

### Document updates:
- [ ] Add/Remove OS prerequisites to the dependencies document
- [ ] Update distro install page

**Comment by MattGal** [comment]
@rbhanda I've checked both things under "infra team" since we don't have any hardware running 20.10 or 21.04, and the only support we have are docker images.  For the docker images that exist today my understanding is that they will not be removed on the EOL date for the operating systems in question, so notification about end of support does not seem to be necessary from a dnceng perspective.

**Comment by mthalman** [comment]
> For the docker images that exist today my understanding is that they will not be removed on the EOL date for the operating systems in question, so notification about end of support does not seem to be necessary from a dnceng perspective.

@MattGal - Are you referring to the Docker images at https://github.com/dotnet/dotnet-buildtools-prereqs-docker? When you say "they will not be removed on the EOL date" are you referring to the actual images in MCR or the Dockerfiles in the repo? Because we would want to delete the Dockerfiles. But the published images in MCR would be preserved.

**Comment by MattGal** [comment]
> Because we would want to delete the Dockerfiles. But the published images in MCR would be preserved. 

Yes, this is what I meant, users of the tags don't need to be notified, since we have [tags from dead OSes like Ubuntu 14 from 2017](https://github.com/dotnet/runtime/blob/main/eng/pipelines/installer/jobs/base-job.yml#L26) still used for building today.  Teams can choose to remove it from their test matrix at their own pace.

**Comment by ashnaga** [comment]
Resolving this one
