### ISSUE TITLE
win10 21H2 WU (with "receive updates for other microsoft products") does not detect the .net 6.0.1 update

### ISSUE THREAD

**Issue by bughit** [dotnet/core#7047]
was ok on a win11 vm

**Comment by rbhanda** [comment]
is this issue similar to https://github.com/dotnet/core/issues/7044 ? 

A workaround has been mentioned in the https://github.com/dotnet/core/issues/7036 known issues section.

**Comment by bughit** [comment]
No, that's failure to install. This is failure to detect on win10 21H2. WU is otherwise working, it detected and installed the normal win10 monthly update.

Obviously the workaround is manual installation.

So why is it not detecting the 6.0.1 update? Either it's failing to detect that 6.0.0 is installed or 6.0.1 is not being offered by the servers for win10 21h2.

**Comment by rbhanda** [comment]
Sorry about the confusion. I can confirm that win10 21H2 is not a part of our offering for December. 

@csnellgrove1  as FYI

**Comment by bughit** [comment]
By accident or policy? If the latter, why?

**Comment by bughit** [comment]
@rbhanda Can you ask someone else. This deserves an explanation.

**Comment by rbhanda** [comment]
Hi @bughit i am following up on this. My apologies for a delayed response.

**Comment by rbhanda** [comment]
I talked to the servicing team, it looks like Win10 21H2 was slated to begin servicing for .Net in January, which is why it wasn’t part of the December release.  We see that this was a timing issue resulting in Win10 21H2 customers not being serviced through Microsoft Update and we apologize for any inconvenience this caused you and others.  On January 10th .Net 6.0.1 will be available on Windows Update for Win10 21H2.  In the meantime if you need to update you can do so by downloading and installing from Download .NET 6.0 (Linux, macOS, and Windows) (microsoft.com).  Thank you for the feedback and bringing this to our attention, we appreciate it!
