### ISSUE TITLE
'dotnet' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Bhargav450** [dotnet/core#7079]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jeffhandley** [comment]
Hello @Bhargav450. Thanks for reporting this. This error is typically caused by not having the .NET SDK installed on your computer or not yet having `dotnet` on you `PATH`.

The instructions for installing the .NET SDK can be found here:
http://get.dot.net/

If you already had a command/terminal prompt open before the installation, please close and reopen the command/terminal and try running `dotnet` again. If this doesn't address your issue, please provide more details such as which version of the .NET SDK you have installed, which command/terminal prompt you're using, and confirmation that the .NET SDK folder is in your `PATH`.
