### ISSUE TITLE
Not getting the page

### ISSUE THREAD

**Issue by NareshKumarPanneerSelvam** [dotnet/core#7086]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by buyaa-n** [comment]
Hi @NareshKumarPanneerSelvam the issue description submitted doesn't provide any details about the error that you received; we need that info for further investigating and/or fixing the issue as needed, without details your issue is not actionable therefore I'm closing the issue. If you are still experiencing the error, please submit a new issue with the exact error message, which part of the code sample you were working on, and what steps were taken immediately before receiving the error.

Thanks!
