### ISSUE TITLE
Keeps saying I need to rerun the command to overwrite it

### ISSUE THREAD

**Issue by etaylor16** [dotnet/core#7098]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. It keeps saying I need to overwrite something and rerun the command

**Comment by buyaa-n** [comment]
Hello @etaylor16 . The issue description submitted doesn't provide any details about the error/problem that you received; I'm closing the issue since it's not actionable. If you are still experiencing the error, please submit a new issue with the exact problem you are encountering, which part of the code sample you were working on, and what steps were taken immediately before the problem occured.

Thanks!

**Comment by mairaw** [comment]
Perhaps you ran the `dotnet new` command already @etaylor16 so the SDK will tell you to pass the --force option to overwrite your project. If you see the directory created with the project, you can just continue the tutorial.
