### ISSUE TITLE
Insufficient file permissions after 'new webapp ...'

### ISSUE THREAD

**Issue by AssaultedPeanut** [dotnet/core#7111]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/modify#
Operating System: Windows Server 2019 Standard 1809

Missing file permissions. Continual file permission errors on all files in a folder created from 'new webapp'. My user account and \Adminstrators have Full Control (with replaced permissions on all descendents in the above created project folder). Project folder in non-special location on D:\ (OS on C:\). Edit "Pages/Index.cshtml", save - permission denied, verify effective access for my account and for \Adminstrators = Full Control. Still locked after exiting "dotnet watch". One solution is to save as alternative file, delete original from File Explorer, rename alternative back to original file. Also "dotnet watch" from Visual Studio Developer Command Prompt fails to start due to permissions failure, has to be executed from an elevated Admin cmd prompt instead.

One workaround is to grant full control to Authenticated Users to the project folder originally created from the 'new webapp' command, so there's a missing user on the project folder, but which User?

**Comment by jeffhandley** [comment]
Hello @AssaultedPeanut. This sounds like it might be caused by files that were downloaded from the internet needing to be unblocked. Did you by chance download a copy of the sample application as a Zip file that you then extracted and started to work within? Or perhaps download a file that is part of the folder structure?

If there was a downloaded Zip/file involved in your file structure, then you might see the following section on the files' Properties from File Explorer:

![image](https://user-images.githubusercontent.com/1031940/149427292-5343c308-ff28-4570-830c-21a988e4ea24.png)

In that case, you'd need to ensure all of the files are unblocked for them to work properly in Visual Studio and dotnet watch. If this isn't the case, then it seems something else is amiss with your permissions that is more related to Windows than Visual Studio or .NET.
