### ISSUE TITLE
Generate proper symbol name when use C# keywords as variable name.

### ISSUE THREAD

**Issue by hangacs** [dotnet/core#7215]
Souce generator will generate wrong code and cause compile error when use C# keywords like @class @event as variable name. This appear to [CommunityToolkit](https://github.com/CommunityToolkit/dotnet/blob/081377955682164b86ed6fb5e56eec45b2409cd1/CommunityToolkit.Mvvm.SourceGenerators/ComponentModel/ObservablePropertyGenerator.Execute.cs#L46) `string fieldName = fieldSymbol.Name;`. `Name` will ignore "@" prefix.

**Comment by hangacs** [comment]
Currently the only way to get proper symbol name I found is to use `symble.ToDisplayParts().Last()`.

**Comment by tarekgh** [comment]
CC @jaredpar

**Comment by jaredpar** [comment]
The API behavior here is "By Design". The name of the symbol here is the name modulo the `@`. The `@` is just not a part of the name, it's a signal to the compiler on how to treat the name that follows. Code that emits names and needs to be conscious of emitting keywords and escape them appropriately. 

@333fred this is the second generator issue where we don't have a good API for encoding namse with `@` prefix when they are keywords.
