### ISSUE TITLE
Error in running dotnet command

### ISSUE THREAD

**Issue by TT-talhatariq** [dotnet/core#7241]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install
Operating System: windows

I Got the error of "'dotnet' is not recognized as an internal or external command,
operable program or batch file." in command prompt.

**Comment by carlossanlop** [comment]
Hello @TT-talhatariq - This error shows up if you install dotnet while you have a command line window open. You need to close the window and open it again so the environment variables get refreshed and the dotnet executable can be found. This is well described at the bottom of the link you provided: https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/install

Closing since it has been answered.
