### ISSUE TITLE
.NET Tutorial run problem

### ISSUE THREAD

**Issue by Fishman1991** [dotnet/core#7352]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
C:\Users\tiger\MyApp\Program.cs(2,1): error CS8802: Only one compilation unit can have top-level statements. [C:\Users\tiger\MyApp\MyApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by joperezr** [comment]
Hello @Fishman1991 thanks for logging the issue. Is it possible that you have other Program.cs files in the directory or subdirectories where you are running `dotnet run` from? I suggest trying this tutorial by starting on a brand new folder which doesn't have any other projects or subdirectories. If the problem persists after doing so, please let us know so that we can help you further.
