### ISSUE TITLE
"Hello World" output error

### ISSUE THREAD

**Issue by PET109** [dotnet/core#7360]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Followed tutorial to the letter, get this message on output...  Win 10 Pro v21H2

C:\Windows\System32\MyApp>Console.WriteLine("Hello, World!");
'Console.WriteLine' is not recognized as an internal or external command,
operable program or batch file.

**Comment by joperezr** [comment]
Hello @PET109, thanks for logging the issue. The line `Console.WriteLine("Hello, World!");` is not supposed to go into your command prompt, instead the tutorial is asking you to open the Program.cs file that got created (when you ran `dotnet new console`) and then `Console.WriteLine` should go there (which by default, Program.cs should already have that line for you so no need to change it). In order to execute the program, from your command prompt please run: `dotnet run`

**Comment by mairaw** [comment]
@PET109 have you managed to continue the tutorial? Let us know.

I might remove that step since it seems to confuse some learners.
