### ISSUE TITLE
Command dotnet new blazorserver -o BlazorApp --no-https -f net6.0 from tutorial throws error

### ISSUE THREAD

**Issue by sinedied** [dotnet/core#7381]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Running `dotnet new blazorserver -o BlazorApp --no-https -f net6.0` results in:
```
Error: Invalid parameter(s):
-f net6.0
    'net6.0' is not a valid value for -f (Framework).

```

**Comment by joperezr** [comment]
Hello @sinedied thanks for logging your issue. Seems like your machine doesn't have the 6.0 SDK yet, which is why that command is failing. You must have an older SDK installed like 5.0 or bellow. Could you please install the 6.0 SDK by clicking on the purple button on the top of the page of this page: https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install

**Comment by sinedied** [comment]
Seems that was the issue, thanks! Though I'm curious why the need to use `-f net6.0`, as if I have 6.0 SDK installed it will be the default version used anyways?

**Comment by joperezr** [comment]
Correct, if you are using the 6.0 sdk, templates will be created targeting 6.0 by default so that parameter becomes optional. I will go ahead and close this issue for now, but do feel free to ping us or open new issues if you have any follow up questions 😄

**Comment by mairaw** [comment]
We added that to make sure you're creating the app with the version the tutorial was built for. We saw a lot of people having issues later at the tutorial because `dotnet watch` doesn't work in .NET 5, for example.
Another option would be to remove the -f parameter from the dotnet new command but add a step on the install page to make sure you have .NET 6.
