### ISSUE TITLE
Issue using dotnet in command prompt

### ISSUE THREAD

**Issue by M4nu3K07** [dotnet/core#7382]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

I entered dotnet on command prompt and outcome was that it's not recognized as a command. [This a is link](https://we.tl/t-MlPbllifKU) to a picture of the issue.

**Comment by joperezr** [comment]
Hello @M4nu3K07 thanks for logging the issue. Seems like the issue you are hitting is that you don't have the .NET SDK installed in your machine. Before running dotnet on the command prompt, you first need to install the SDK by clicking on the purple button on that tutorial page:

![image](https://user-images.githubusercontent.com/13854455/163650042-9a70692a-a455-4669-88e1-f15268d41c59.png)

I will close the issue for now since doing the above should fix the issue, but please feel free to reopen if that is not the case or if you have any follow up questions.

**Comment by mairaw** [comment]
And if you do have the SDK installed and you're still not able to type `dotnet`, then it might be an issue with PATH.

Check the output of the `where.exe dotnet` command and if your system is x64 and the x86 path returns first, please follow the steps at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the issue.
