### ISSUE TITLE
Security Updating for .net core under Windows.

### ISSUE THREAD

**Issue by Rovastar** [dotnet/core#742]
Are there any plans to integrate the security into Windows Update?

I need to rewrite my security and compliance procedures for now adding (asp).net core (Under windows) and with asp.net x.x it was included in Windows Update. 

If there are no plans at this time. What is the best way of being informed of security updates with this.

I subscribe to the Microsoft security bulletins but I didn't see any mention of previous security issues with (asp).net core version although I found issues 
https://blogs.msdn.microsoft.com/dotnet/2017/05/09/net-core-may-2017-update/
 
Could it be added to there too?
Microsoft Technical Security Notifications
https://technet.microsoft.com/en-us/security/dd252948.aspx

Or is there some other place for now?

**Comment by Petermarcu** [comment]
@leecow @blowdart can you provide the guidance for @Rovastar

**Comment by blowdart** [comment]
There are no plans to publish on Windows Update unless it's an active 0-day exploit with a severity that requires such a process. That severity is decided by management.

.NET Core and ASP.NET Core are published as [advisories](https://technet.microsoft.com/en-us/security/advisories?f=255&MSPPError=-2147217396), not bulletins, because bulletins are linked to MSU patches.  The advisory is mirrored in the announcements repo for [.net core (https://github.com/dotnet/announcements/issues?q=is%3Aopen+is%3Aissue+label%3ASecurity) and [asp.net core](https://github.com/aspnet/announcements/issues?q=is%3Aopen+is%3Aissue+label%3ASecurity) and labeled as security.

**Comment by Petermarcu** [comment]
Thanks @blowdart. I'm going to close this issue now. @Rovastar if you have any other questions, please let us know.

**Comment by DanJ210** [comment]
I could ask @blowdart something @Petermarcu it would help to know this. The IT department is telling me to use .Net instead of .Net Core because .Net is given security updates through WSUS while .Net Core is not. I'm still going to use Core and update manually but is that pretty much the case for enterprise? Should enterprise not use Core? If I'm away on vacation or gone then someone would have to know if there's a security vulnerability and also know how to update Core in order to keep the company safe?

I don't want to use .Net but I can see their point. If I don't know about a severe security threat and I don't manually update .Net Core then the company is wide open. Is this correct?

**Comment by karelz** [comment]
I think it is covered by #1541 - @shawnro can comment on further progress in the space ...

**Comment by shawnro** [comment]
CC @leecow, @dleeapho.  We are actively thinking about these types of enterprise scenarios for .NET Core and how best to keep things updated and secure

**Comment by dleeapho** [comment]
@DanJ210 for now the best place to track our thinking around servicing .NET Core for Windows clients is #1541 as @karelz mentioned.
