### ISSUE TITLE
What's new in .NET 7 Preview 5 [WIP] 

### ISSUE THREAD

**Issue by danmoseley** [dotnet/core#7441]
# What's new in .NET 7 Preview 5

This issue is for teams to highlight work for the community that will release .NET 7 Preview 5

To add content, use a new conversation entry. The entry should include the team name and feature title as the first line as shown in the template below. 

```
## Team Name: Feature title

[link to the tracking issue or epic item for the work]

Tell the story of the feature and anything the community should pay particular attention 
to be successful using the feature.
```
Preview 1: https://github.com/dotnet/core/issues/7106
Preview 2: https://github.com/dotnet/core/issues/7107
Preview 3: https://github.com/dotnet/core/issues/7108
Preview 4: https://github.com/dotnet/core/issues/7378
Preview 5: https://github.com/dotnet/core/issues/7441
Preview 6: https://github.com/dotnet/core/issues/7454
Preview 7: https://github.com/dotnet/core/issues/7455

**Comment by danmoseley** [comment]
[Higher performance reflection invoke](https://github.com/dotnet/runtime/pull/67917) by @steveharter

**Comment by tarekgh** [comment]
## Observability

### Expose performant ActivityEvent and ActivityLink tags enumerator methods https://github.com/dotnet/runtime/issues/68056

The exposed methods can be used in the perf critical scenarios to enumerate the Tags objects without any extra allocations and with fast items access.

```C#
namespace System.Diagnostics
{
    partial struct ActivityLink
    {
        public Activity.Enumerator<KeyValuePair<string, object?>> EnumerateTagObjects();
    }

    partial struct ActivityEvent
    {
        public Activity.Enumerator<KeyValuePair<string, object?>> EnumerateTagObjects();
    }
}
```

**Comment by sajjadarashhh** [comment]
in preview 5 we can create blazor and maui projects with .net 7 target!?
and when is maui released!?

**Comment by eerhardt** [comment]
## System.IO.Stream

### Add Stream ReadExactly and ReadAtLeast https://github.com/dotnet/runtime/issues/16598

One of the most common mistakes when using `Stream.Read()` is that the programmer doesn't realize that `Read()` may return less data than what is available in the `Stream` and less data than the buffer being passed in. And even for programmers who are aware of this, having to write the same loop every single time they want to read from a `Stream` is annoying.

To help this situation, we have added new methods to the base `System.IO.Stream` class:

```C#
namespace System.IO;

public partial class Stream
{
    public void ReadExactly(Span<byte> buffer);
    public void ReadExactly(byte[] buffer, int offset, int count);

    public ValueTask ReadExactlyAsync(Memory<byte> buffer, CancellationToken cancellationToken = default);
    public ValueTask ReadExactlyAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken = default);

    public int ReadAtLeast(Span<byte> buffer, int minimumBytes, bool throwOnEndOfStream = true);
    public ValueTask<int> ReadAtLeastAsync(Memory<byte> buffer, int minimumBytes, bool throwOnEndOfStream = true, CancellationToken cancellationToken = default);
}
```

The new `ReadExactly` methods are guaranteed to read exactly the number of bytes requested. If the Stream ends before the requested bytes have been read an `EndOfStreamException` is thrown.

#### Example

```C#
using FileStream f = File.Open("readme.md");
byte[] buffer = new byte[100];

f.ReadExactly(buffer); // guaranteed to read 100 bytes from the file
```

The new `ReadAtLeast` methods will read at least the number of bytes requested. It can read more if more data is readily available, up to the size of the buffer. If the Stream ends before the requested bytes have been read an `EndOfStreamException` is thrown. You can opt out of throwing an exception, however that means `ReadAtLeast` will read less than the requested bytes if the Stream ends.

#### Example

```C#
using FileStream f = File.Open("readme.md");
byte[] buffer = new byte[100];

int bytesRead = f.ReadAtLeast(buffer, 10);
// 10 <= bytesRead <= 100
```

**Comment by danmoseley** [comment]
New analyzer and fixer for Regex source generator - @joperezr 
https://github.com/dotnet/runtime/pull/69872/

**Comment by JulieLeeMSFT** [comment]
# CodeGen

## Community PRs
@singleaccretion made [23 PR contributions ](https://github.com/dotnet/runtime/pulls?q=is%3Apr+is%3Aclosed+label%3Aarea-CodeGen-coreclr+closed%3A2022-04-18..2022-05-24+author%3Asingleaccretion+) during Preview 5 with some highlighted items below:
- Improve the redundant branch optimization to handle more side effects [PR#68447](https://github.com/dotnet/runtime/pull/68447)
- PUTARG_STK/x86: mark push [mem] candidates reg optional [PR#68641](https://github.com/dotnet/runtime/pull/68641)
- Copy propagate on LCL_FLDs [PR#68592](https://github.com/dotnet/runtime/pull/68592)

@Sandreenko completed allowing StoreLclVar src to be IND/FLD [PR#59315](https://github.com/dotnet/runtime/pull/59315).
@hez2010 fixed CircleInConvex test in [PR#68475](https://github.com/dotnet/runtime/pull/68475).

See contributions from @anthonycanino, @aromaa and @ta264 in the below sections.

## Arm64

- [Arm64: Have CpBlkUnroll and InitBlkUnroll use SIMD registers](https://github.com/dotnet/runtime/pull/68085)  uses SIMD registers for initialization of copy a block of memory less than 128 bytes. Some performance wins are shown [here](https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_28_2022/refs/heads/main_arm64_Windows%2010.0.19041_Improvement/System.Numerics.Tests.Perf_Matrix4x4.html).

![image](https://user-images.githubusercontent.com/63486087/171935234-e1971000-03a2-4fcd-ab18-e8fff2921cc6.png)
 
- [PR#68363](https://github.com/dotnet/runtime/pull/68363) consolidated 'msub' and 'madd' logic. 

## Loop Optimization
- [PR#67930 Handle more scenarios for loop cloning ](https://github.com/dotnet/runtime/pull/67930) now supports to operate on loops that go backwards or forwards with the increment of > 1. The performance wins can be seen [here](https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_03_2022/refs/heads/main_x64_Windows%2010.0.18362_Improvement/System.Collections.ContainsTrue(String).html).

![image](https://user-images.githubusercontent.com/63486087/171935331-761be714-7e68-4ee9-9fd3-aa435db57ffd.png)

- [PR#68588 Hoist the nullchecks for 'this' object](https://github.com/dotnet/runtime/pull/68588) moves the nullchecks on an object outside the loop. Performance wins can be seen [here](https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_03_2022/refs/heads/main_x64_Windows%2010.0.18362_Improvement/System.Text.Encodings.Web.Tests.Perf_Encoders.html).

![image](https://user-images.githubusercontent.com/63486087/171935666-2d6d957c-ceec-4973-8a3c-95599864dafd.png)

## x86/x64 Optimizations
There were a number of optimizations targetted for x86/x64 platforms:
- [PR#67182 Emit shlx, sarx, shrx on x64](https://github.com/dotnet/runtime/pull/67182)  optimized mov+shl, sar or shr to shlx, sarx or shrx on x64. 
- [PR#68091](https://github.com/dotnet/runtime/pull/68091) enabled UMOD optimization for x64.
- @anthonycanino added X86Serialize hardware intrinsic in [PR#68677](https://github.com/dotnet/runtime/pull/68677 ).
- @aromaa optimizec bswap+mov to movbe in [PR#66965](https://github.com/dotnet/runtime/pull/66965). 
- @ta264 fixed linux-x86 compilation for clr.alljits subset in [PR#68046](https://github.com/dotnet/runtime/pull/68046).

## Modernize JIT
As more and more community contributors participate in the JIT code base, it is increasingly getting important to restructure our code and modernize it in order to allow our contributors to easily ramp up and rapidly develop code.  
This release we did a lot of work on the internals of the JIT, cleaning up the JIT’s intermediate representation and removing limitations as a result of old design decisions. In many cases this work resulted in **less memory usage** and **higher throughput** of the JIT itself, while in other cases it resulted in **better code quality**. Some of these changes were:
- Delete CLS_VAR [PR#68524](https://github.com/dotnet/runtime/pull/68524)
- Delete GT_ARGPLACE [PR#68140](https://github.com/dotnet/runtime/pull/68140)
- Delete GT_PUTARG_TYPE [PR#68748](https://github.com/dotnet/runtime/pull/68748)
 
The above allowed us to **remove an old limitation in the JIT’s inliner** when inlining functions with parameters of byte/sbyte/short/ushort type, resulting in better code quality:
- Allow the inliner to substitute for small arguments [PR#69068](https://github.com/dotnet/runtime/pull/69068)
 
As .NET has become a more and more popular platform for writing high-performance code the coding style has changed. One area where the JIT was lacking was in its understanding of **unsafe code involving reads and writes of structs and struct fields**. **@SingleAccretion** contributed great changes in this area by switching the JIT’s internal model to a more general “physical” model. This paves the way for the JIT to **better reason about unsafe code using features like struct reinterpretation**.
- Physical value numbering [PR#68712](https://github.com/dotnet/runtime/pull/68712)
- Implement constant-folding for VNF_BitCast [PR#68979](https://github.com/dotnet/runtime/pull/68979)

Other minor cleanups were also made to **simplify the JIT IR**:
- Remove GTF_LATE_ARG [PR#68617](https://github.com/dotnet/runtime/pull/68617)
- Substitute GT_RET_EXPR in inline candidate arguments [PR#69117](https://github.com/dotnet/runtime/pull/69117)
- Remove stores as operands of calls in LIR [PR#68460](https://github.com/dotnet/runtime/pull/68460)

## General Optimizations
A few general JIT optimizations were done in below PRs:
- [PR#68105](https://github.com/dotnet/runtime/pull/68105) enabled multiple nested "no GC" region requests.
- [PR#69034](https://github.com/dotnet/runtime/pull/69034) removed "promoted parameter" tailcall limitation.

**Comment by hez2010** [comment]
I think we may also want to mention that [crossgen2 now has been published with NativeAOT](https://github.com/dotnet/runtime/pull/67636)?

/cc: @agocke

**Comment by agocke** [comment]
An interesting question -- it does demonstrate that we're shipping programs using NativeAOT, but crossgen is also effectively private surface area, so I'm not sure if it would be helpful to most blog readers

**Comment by steveharter** [comment]
## System.Reflection performance improvements when invoking members

The overhead of using reflection to invoke a member (whether a method, constructor or a property getter\setter) has been substantially reduced when the invoke is done several times on the same member. Typical gains are 3-4x faster.

See https://github.com/dotnet/runtime/pull/67917 for more information.

Using the `BenchmarkDotNet` package:
```C#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System.Reflection;

namespace ReflectionBenchmarks
{
    internal class Program
    {
        static void Main(string[] args)
        {
            BenchmarkRunner.Run<InvokeTest>();
        }
    }

    public class InvokeTest
    {
        private MethodInfo? _method;
        private object[] _args = new object[1] { 42 };

        [GlobalSetup]
        public void Setup()
        {
            _method = typeof(InvokeTest).GetMethod(nameof(InvokeMe), BindingFlags.Public | BindingFlags.Static)!;
        }

        [Benchmark]
        // This went from ~116ns to ~39ns or 3x (66%) faster.
        public void InvokeSimpleMethod() => _method!.Invoke(obj: null, new object[] { 42 });

        [Benchmark]
        // This went from ~106ns to ~26ns or 4x (75%) faster.
        public void InvokeSimpleMethodWithCachedArgs() => _method!.Invoke(obj: null, _args);

        public static int InvokeMe(int i) => i;
    }
}
```

**Comment by AngelosP** [comment]
> ## Observability
> ### Expose performant ActivityEvent and ActivityLink tags enumerator methods [dotnet/runtime#68056](https://github.com/dotnet/runtime/issues/68056)
> The exposed methods can be used in the perf critical scenarios to enumerate the Tags objects without any extra allocations and with fast items access.
> 
> ```cs
> namespace System.Diagnostics
> {
>     public partial struct ActivityLink
>     {
>         public Activity.Enumerator<KeyValuePair<string, object?>> EnumerateTagObjects();
>     }
> 
>     public partial struct ActivityEvent
>     {
>         public Activity.Enumerator<KeyValuePair<string, object?>> EnumerateTagObjects();
>     }
> }
> ```

Can you please provide some sample code for the above?

**Comment by eiriktsarpalis** [comment]
@AngelosP one minor erratum concerning the IAsyncEnumerable example:

```C#
// It now works and no longer throws NotSupportedException
JsonSerializer.Serialize(new MyPoco { Data = ... }, MyContext.MyPoco); 
```
The above is not support and will always throw, since IAsyncEnumerable requires one of the async serialization methods. For the sake of correctness it should probably read:
```C#
// It now works and no longer throws NotSupportedException
await JsonSerializer.SerializeAsync(new MyPoco { Data = ... }, MyContext.MyPoco); 
```

**Comment by leecow** [comment]
.NET 7 GA is available. Closing these pre-release issues.
