### ISSUE TITLE
Convert.FromBase64String fail with João in string

### ISSUE THREAD

**Issue by xiaolang124** [dotnet/core#7523]
### Description
```
string s = "eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC81Mjg5MTliZC04N2ViLTRmMjMtOGU3ZC02NTkxOWIyMTQ3NzIvIiwiaWF0IjoxNjU0NTgyNDkxLCJuYmYiOjE2NTQ1ODI0OTEsImV4cCI6MTY1NDU4ODE4NSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFTUUEyLzhUQUFBQUx3WC9XbEJaek8rbEdPVHBwSXRNTStyaDh2RmJNek1zenByc0NFYStESU09IiwiYW1yIjpbInB3ZCJdLCJhcHBfZGlzcGxheW5hbWUiOiJWaXN1YWwgU3R1ZGlvIiwiYXBwaWQiOiI4NzJjZDlmYS1kMzFmLTQ1ZTAtOWVhYi02ZTQ2MGEwMmQxZjEiLCJhcHBpZGFjciI6IjAiLCJkZXZpY2VpZCI6IjYxYzhhNzdmLTcxMzUtNGVkMS05N2ZlLTQ3YjFiZmE5NjhhNCIsImZhbWlseV9uYW1lIjoiYWEiLCJnaXZlbl9uYW1lIjoiSm_Do28iLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxNjcuMjIwLjI1NS4zNSIsIm5hbWUiOiJKb8OjbyBhYSIsIm9pZCI6ImEzMjgyNTBhLTJmMDgtNGZlNi1hZTU3LWJjNWJiNjQ0ZjViMSIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwMjAwNjIxMzdBIiwicmgiOiIwLkFYQUF2Um1KVXV1SEkwLU9mV1dSbXlGSGNnTUFBQUFBQUFBQXdBQUFBQUFBQUFCd0FQVS4iLCJzY3AiOiJBcHBsaWNhdGlvbi5SZWFkV3JpdGUuQWxsIGVtYWlsIG9wZW5pZCBwcm9maWxlIFVzZXIuUmVhZFdyaXRlLkFsbCIsInN1YiI6InZyWmNmcFBDSEs2ZG8wMWxhWGVGUFBwMVJucVpjNEpKZVNvUnBHV2ZiT2MiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiQVMiLCJ0aWQiOiI1Mjg5MTliZC04N2ViLTRmMjMtOGU3ZC02NTkxOWIyMTQ3NzIiLCJ1bmlxdWVfbmFtZSI6ImFhQHRpYW4yNC5vbm1pY3Jvc29mdC5jb20iLCJ1cG4iOiJhYUB0aWFuMjQub25taWNyb3NvZnQuY29tIiwidXRpIjoiNk85bjN6aHQ5VTJENnNVdll3eWJBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJlSWJwRVdVd0VTZ3JwWDJmMnFobnFQVU5JeXRfLU5COGZXbm1lc2UzUzlZIn0sInhtc190Y2R0IjoxNjE3MDc1OTg2fQ==";
var base64EncodedBytes = System.Convert.FromBase64String(s);
Console.WriteLine(base64EncodedBytes);
```
This code sample will fail with error like `System.FormatException: 'The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.'`

I have tried this string in `https://www.base64decode.org/`. It works fine. I'm not sure why this happens. No matter how many equal signs I add, this error is always reported. How can I decode this string?

**Comment by svick** [comment]
Your string is not Base64 proper, it's [base64url](https://en.wikipedia.org/wiki/Base64#URL_applications). You can tell that this is the case since it has `_` in it (Base64 uses `/` instead).

You have several options on how to solve this:

1. Convert the string to Base64 using `s.Replace('_', '/').Replace('-', '+')`.
2. If you're writing an ASP.NET Core application, you can use [`WebEncoders.Base64UrlDecode`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.webencoders.base64urldecode).
3. Wait until base64url decoding is added to `Convert` (see https://github.com/dotnet/runtime/issues/31099), which may be never.

**Comment by xiaolang124** [comment]
Thanks for the advice. This is very helpful.

**Comment by tuanv2t** [comment]
You are great @svick ,I've searched hours for this issue but only you know the reason. Follow you now
