### ISSUE TITLE
_dl_fatal_printf version GLIBC_PRIVATE not defined

### ISSUE THREAD

**Issue by shaikhkhamroddin** [dotnet/core#7763]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

While running dotnet run command getting below error :

/opt/lampp/htdocs/RC_Web_API/RC.WebApi/bin/Debug/net6.0/RC.WebApi: relocation error: /usr/lib/libc.so.6: symbol _dl_fatal_printf version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference

System:
Manjaro linux

**Comment by rzikm** [comment]
How did you install .NET on Manjaro? Are you on latest manjaro version with updates installed?

**Comment by Icepickle** [comment]
@shaikhkhamroddin If it helps, I had the same on manjaro because I was using a snap version of dotnet.

I removed the snap version, in favor of the pacman dotnet-sdk, and now I can actually run with webapi under linux.

I used a fairly straightforward tutorial, namely: https://www.jeremymorgan.com/tutorials/linux/how-to-install-dotnet-manjaro/

Probably, don't use the CI integration setup he first demonstrates, but rather the solution with pacman below (I've done it with the CI one and that seems to work, but I think I'll revert that one, as I wouldn't have access to automatic updates in that case)
