### ISSUE TITLE
E: Unable to locate package dotnet-sdk-6.0

### ISSUE THREAD

**Issue by notwave-bow** [dotnet/core#7775]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rzikm** [comment]
Hi, what is your Linux distribution, did you follow installation steps on https://docs.microsoft.com/en-us/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website ?

**Comment by byroniac** [comment]
I just had this issue. I had installed dotnet-6.0-sdk on Ubuntu 22.04 using the Jammy repository, then installed PowerShell from Microsoft (instead of the snap, which probably would have worked and not led to the issue that I had). I found a troubleshooting step for me, and used "Mixed state scenario 2: Use PMC packages after installing native Jammy packages" followed by "Clean machine scenario 2: Use .NET 6 Package via PMC" because there are still other Microsoft packages (ODBC and SQL related) that I want. Apparently, the Jammy repository and Microsoft packages should not be mixed. And so far, it's working again! [Installing .NET 6 on Ubuntu 22.04 (Jammy) #7699](https://github.com/dotnet/core/issues/7699#issue-1335157451)
