### ISSUE TITLE
Error message: "zsh: unknown file attribute: H"

### ISSUE THREAD

**Issue by Quasar003** [dotnet/core#7830]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When attempting to execute Console.Writing("Hello, World!"); I receive "zsh: unknown file attribute: H".

**Comment by Jozkee** [comment]
@mairaw

**Comment by adiletelf** [comment]
I encountered the same problem on MacBook Pro 14'' when trying create a symlink.
<img width="647" alt="image" src="https://user-images.githubusercontent.com/74559101/210477716-88592a2d-8722-49ee-b0b7-ec7f617a6ddb.png">

**Comment by jschlieber-innio** [comment]
try `ln -s $(which nvim) /opt/homebrew/bin/vim`

**Comment by UltraMebius** [comment]
我的是MySQL在终端设置之后，显示错误，然后我直接登录发现没有问题，对于mac版本的MySQL，应该就是在下载包里安装时候就设置好你的root password，然后终端输入mysql -uroot -p
在这里终端会提示你输入密码，你就选择两个，如果你没有设置密码还有这个提示框，那就是默认密码123456；否则就是直接输入密码即可，并且输入密码过程中密码不会自动显示，输入正确密码就可以进入MySQL数据库了

The translation:
[Mine](url) is MySQL after the terminal setup, the error is displayed, and then I log in directly to find no problem, for the mac version of MySQL, should be installed in the download package set your root password, and then terminal input mysql -uroot -p
Here the terminal will ask you to enter a password, you choose two, if you do not have a password and this prompt box, it is the default password 123456; Otherwise, you can directly enter the password, and the password will not be automatically displayed during the password process, enter the correct password can enter the MySQL database
<img width="763" alt="截屏2023-08-16 15" src="https://github.com/dotnet/core/assets/142002664/4e79fb6d-29b0-4731-afa1-4ed37c30254c">

**Comment by mairaw** [comment]
We changed the tutorial quite a bit since then and we no longer do things via the terminal.
Console.WriteLine("Hello, World!"); was not a command to execute, but the code that comes with the template.
Give it a try on the new version of the tutorial that uses VS Code to see if it's easier to follow now.
