### ISSUE TITLE
Consider creating a read-only mailing list for announcements

### ISSUE THREAD

**Issue by raphaelr** [dotnet/core#7924]
### Description

Currently announcements are distributed via issues in the [announcements](https://github.com/dotnet/announcements) repository. This has the downside that anyone can open issues there, not just the .NET team. On a regular basis someone will create an unrelated issue (e.g. https://github.com/dotnet/announcements/issues/238), which then gets sent to everyone subscribed to the repository, for no benefit.

Consider distributing announcements via a better, read-only, channel instead. Options include a mailing list or a RSS feed.

For backwards compatibility, a bot can sync announcements from there to the announcements repository.

**Comment by mairaw** [comment]
@terrajobst @richlander @jamshedd

**Comment by dagood** [comment]
@danmoseley, @terrajobst and I had an email thread ~2022/4/24 about how to improve this--there are another few alternatives that would maybe let .NET still use dotnet/announcements.

One is adding a `.github/ISSUE_TEMPLATE/config.yml` that doesn't actually include a way to file an issue, just redirects to other repos. Users could still file issues, but they would need to find the issue-filing URL manually because GitHub wouldn't show a button they could click to take them there. So far, the repo hasn't had a problem with malicious issues/comments, just unknowing issues/comments, so I think this would end up ok.

Another is using the "temporary interaction limits" to make sure nobody files issues or comments. We actually enabled it at the time, but as the name says, they're only temporary, and they've expired. Making it someone team's job to refresh the limits (or find a way to configure it using a bot?) could make this work out.

Of course, GitHub isn't designed to be used for this purpose, so going for something else entirely makes a lot of sense. 😄

**Comment by csharpfritz** [comment]
What about the Wiki feature of the Announcements repository?  That can be locked down to just contributors having edit access and we can get a little more search indexing capabilities from our friends at Bing and Google.

**Comment by adamralph** [comment]
It appears that GitHub repositories are not designed for making announcements, yet the potential solutions seem restricted to using one for that purpose. Is that the case? If so, why is that?

**Comment by dagood** [comment]
Speaking for myself, I don't mean to restrict the potential solutions. The original post already suggests mailing lists and RSS feeds and I don't personally see a problem with either one. I'm just mentioning a few ideas from a while back that address this line of the original post (the motivation for switching):

> This has the downside that anyone can open issues there, not just the .NET team.

**Comment by tarekgh** [comment]
@terrajobst @richlander @jamshedd any action needed or planned for this issue?

**Comment by jamshedd** [comment]
Playing the data controller or data processor role with PII such as email addresses involves more policy and process overhead than one might imagine. I would not favor that approach, instead I'd explorer cheaper ways to lock down the creation of issues in announcements if there's a way to do that. The 2 workarounds @dagood suggested above might work.

**Comment by terrajobst** [comment]
We discussed the use of email lists at the beginning of the .NET Core project. After a few back and forths we decided against that. I don't think we'll ever want to start using them again. Markdown on GitHub gives us a lot more flexibility than email. You can easily link to it, you can edit it to improve clarity, and there is an obvious place to point people for a public conversation. I'm very much opposed to going that path.

The announcement pattern has worked reasonably well for us, modulo the issue that sometimes people open new issues. I say sometimes, because we basically have continuous restriction that disallows non-contributors from opening issues (it's a GitHub feature, but we need to renew it every 6 months). We have given the feedback to GitHub. There are several ways this could be achieved here (allowing permanently disabling issues or pure announcement issues + notifications). If something better is available, I'm all for it. But it's for sure not a mailing list.
