### ISSUE TITLE
Unable to start Dotnet

### ISSUE THREAD

**Issue by bulbatross** [dotnet/core#8015]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Windows 10
installation was successfull but after restarting the CMD it said that "dotnet" was not recognized as an internal or external command.

**Comment by Velorexe** [comment]
Seems like `dotnet` is not added to your PATH. If the installation was successful, you can add it to the PATH yourself.
Gotten these steps from [stackoverflow](https://stackoverflow.com/questions/42588392/where-is-the-dotnet-command-executable-located-on-windows).

Steps:
1. Open Control Panel > System and Security > System
2. Click on Advanced system settings
3. In advanced section, click in Environment Variables
4. In System variables, select `path` and edit
5. After semicolon, write "C:\Program Files\dotnet" (if you've installed the SDK in a different directory, use that one instead of the default location).
6. Click on Ok button till end.
