### ISSUE TITLE
DateTime.MaxValue returns ambiguously formatted DateTime object

### ISSUE THREAD

**Issue by AlcBrains** [dotnet/core#8056]
### Description

I am not sure if I'm in the right place to open the bug, but here goes:
`DateTime.MaxValue` returns the OS configured format of the max datetime value instead of an unambiguous (and universally comparable) one. Eg. if the system config for the short date is set to dd-MMM-y (or dd-MMM-yy) and time is set to HH:mm:ss, then the max value returned is "31-Dec-99 23:59:59", which can lead to all sorts of problems, like trying to transform this to a string and back to a date time will result in the date being modified to 31st of December 1999.
### Configuration

Encountered on an application written in .Net 7. OS is Windows 10 (x64 architecture).

### Regression?

I am not sure whether the behavior was different in earlier versions of .net
### Other information

 It seems that the issue is related to the System's Datetime data format, because changing the format to a more concise one from the system settings results in the issue disappearing. This kind of leads me to thing about whether or not the issue is not with `DateTime.MaxValue` but rather with the underlying formatting mechanism, but I don't know the specifics of the implementation so I can't really say

**Comment by svick** [comment]
> `DateTime.MaxValue` returns the OS configured format of the max datetime value

No, it doesn't, since it returns a `DateTime`, not a formatted string. If you then convert that to string, either explicitly by calling `DateTime.MaxValue.ToString()` or implicitly by e.g. `Console.WriteLine(DateTime.MaxValue);`, then that will use the system configured date format. That's the same for every `DateTime`, but I understand why that's more of a problem for a date in the year 9999.

This design, where converting a `DateTime` to a string by default produces a human-readable form, which may not be great at being machine-readable, has been part of .Net since the start. And changing it now would have a very high Price, so it's unlikely to happen. What you need to do is to explicitly specify a machine-readable format string, ideally [`"o"`](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#Roundtrip), e.g. `DateTime.MaxValue.ToString("o")` or `Console.WriteLine($"{DateTime.MaxValue:o}");`.

Note that this is not just about `DateTime.MaxValue`. The system configured format has many other problems, which is why you should not rely on it for anything machine-readable.

**Comment by AlcBrains** [comment]
>And changing it now would have a very high Price, so it's unlikely to happen. What you need to do is to explicitly specify a machine-readable format string, ideally ["o"](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#Roundtrip), e.g. DateTime.MaxValue.ToString("o") or Console.WriteLine($"{DateTime.MaxValue:o}");.

I see, that makes total sense. Thanks for providing the explanation and the tip about not relying on the system configured format.
