### ISSUE TITLE
dotnet new hangs indefinitely

### ISSUE THREAD

**Issue by Leviticoh** [dotnet/core#8057]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

operating system version: Arch Linux

the command `dotnet new` just hangs without giving error messages
here is the entire output i get
```
[leviticoh@archlinux dotnet-hw]$ dotnet new console -o MyApp -f net7.0

The template "Console App" was created successfully.

Processing post-creation actions...
Restoring /home/leviticoh/Progetti/dotnet-hw/MyApp/MyApp.csproj:
  Determining projects to restore...
```

also if i try using ctrl+c to abort it starts repeating this line
```
/usr/share/dotnet/sdk/7.0.101/NuGet.targets(132,5): warning MSB4220: Waiting for the currently executing task "RestoreTask" to cancel. [/home/leviticoh/Progetti/dotnet-hw/MyApp/MyApp.csproj]
```

it's my first time using dotnet, so i'm not sure what to do now

**Comment by omajid** [comment]
cc @alucryd

**Comment by Leviticoh** [comment]
now that i tried running it in a virtual machine with a fresh installation of arch i can say it works there, it's probably an issue only on my machine, but i still don't know why it's happening

**Comment by jeffhandley** [comment]
Hello! It's possible this is related to network connectivity, and something is preventing `dotnet` from being able to restore the packages required for the project, but your VM isn't encountering that. Do you possibly have an anti-virus program that could be blocking the package downloads?

**Comment by Leviticoh** [comment]
I don't have an antivirus installed, so i don't think that's the issue, Also i forgot to mention that it pins 1 core to 100% when it hangs, i don't know how important this detail is, but i guess i should've added it

I didn't expect anyone to answer today, but thanks, merry Christmas!

**Comment by ZeroSkill1** [comment]
I too am facing this issue. It seems to have started with [.NET 6.0.10 (SDK 6.0.402+)](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.10/6.0.10.md), and the following is stated:
> Microsoft is releasing this security advisory to provide information about a vulnerability in .NET 6.0, .NET Core 3.1, and NuGet (NuGet.exe, NuGet.Commands, NuGet.CommandLine, NuGet.Protocol). This advisory also provides guidance on what developers can do to update their applications to remove this vulnerability.

> A vulnerability exists in .NET 6.0, .NET Core 3.1, and NuGet clients (NuGet.exe, NuGet.Commands, NuGet.CommandLine, NuGet.Protocol) where a malicious actor could cause a user to execute arbitrary code.

Not only is building broken after that release, `dotnet nuget` also has the same effect. It spikes one CPU core and does not do anything else. Looking at it in a debugger, it is infinitely waiting for some lock or event that never gets released.

**Comment by toraritte** [comment]
(Just leaving a note, mostly to future self: Had this same issue on Mac, so updated dotnet core, the OS, then restarted the whole system and it worked. Not sure which step helped though.)

**Comment by dviererbe** [comment]
@jeffhandley I saw this issue multiple times in the Ubuntu autopkgtest logs for .NET 6,7,8,9.

I also encountered this issue in the past on personal systems. There was definitely a correlation to internet connectivity. I worked around it by using a NuGet proxy.

There was also a user on the Ubuntu Matrix server that encountered this issue in the past ( see [Matrix Thread :thread:](https://matrix.to/#/!uxxTfgsyhbsYVCKZUE:ubuntu.com/$_3IifmqVBnaWPQYUO88DZieInX8RLnTyYQC9kD65wdo?via=ubuntu.com&via=matrix.org&via=rory.gay) )

> `@emma:rory.gay`: has anyone ever dealt with dotnet just not restoring whatsoever?
> [...]
> `@emma:rory.gay`: i think i found the issue
it took 20 minutes because it tried to do ipv6
for 9 addresses, for one addr it takes 130s to time out
> `@dviererbe:ubuntu.com`: Okay, so networking was the problem after all. How did you figure out that it is IPv6 related?
> `@emma:rory.gay`: checked if nuget had ipv6 via dig AAAA api.nuget.org
then tried to curl -6, which timed out, tried a ping from my firewall, same thing
![Image](https://github.com/user-attachments/assets/7f3de607-825d-467f-a8af-fabe7e76b28f)
works after disabling ipv6 on LAN completely on the firwall level

Note that the user was using .NET 8.0.401 on NixOS
