### ISSUE TITLE
Cannot install .net 7 due to .net host 7 not found

### ISSUE THREAD

**Issue by Light-Lens** [dotnet/core#8112]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

I am unable to install .net 7.
![image](https://user-images.githubusercontent.com/73633374/212886544-3a5046ed-2c08-4806-ad46-870ca8ab31b2.png)

I can't also find the download link for .net host 7 What should I do?

**Comment by antonfirsov** [comment]
Looks similar to #8072. @NikolaMilosavljevic any idea what is happening here?
@Light-Lens can you attach the installation log?

**Comment by NikolaMilosavljevic** [comment]
@Light-Lens is it possible to collect installation logs using https://aka.ms/vscollect tool? Please run the Collect tool from administrative command prompt. It will create a log archive (`%temp%\vslogs.zip`), that can be shared on OneDrive or Google Drive.

This issue points at locked MSI file, which can likely be caused by an Anti-virus service.

**Comment by Light-Lens** [comment]
I don't know what's causing the issue. I tried to install .net 6 and it is working properly. So, I guess for now I'll drop the idea of installing .net 7. Thanks for responding btw :)
