### ISSUE TITLE
Problem with downloading dotnet myapp

### ISSUE THREAD

**Issue by BilalAhmad890** [dotnet/core#8127]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![Skärmbild (5)](https://user-images.githubusercontent.com/122674269/213931720-826aa69d-1af1-45eb-8986-f5cff2305f5c.png)

**Comment by mairaw** [comment]
@baronfel do you have any suggestions here? I haven't seen this exception before with a .dotnet path error.

**Comment by baronfel** [comment]
@BilalAhmad890 do you have write permissions to your own user HOME directory? The CLI stores a number of caches/sentinel files in there, and it's not able to write to that directory here. If you can't find/fix the directory permissions, you could try setting the `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` environment variable to `true` to skip all of the sentinel creation, though there are a number of other features (for example, the template engine cache), that may also not work due to permissions errors.

**Comment by carlossanlop** [comment]
No answer in a week. Closing.
