### ISSUE TITLE
Support term is too shorter than .NET Frameworks & Java & Ubuntu; consider 5 years for free and longer for profit

### ISSUE THREAD

**Issue by tats-u** [dotnet/core#8295]
### Description

The support deadline for .NET 6 only differs by just 6 months from .NET 7, which greatly diminishes the benefits of LTS.
Java is planning to shorten the LTS release interval to 2 years, similar to .NET, but with the added benefit of 5 years of free support.
Node.js also has support up to 3 years, similar to .NET, but with LTS releases every year, allowing skipping of one LTS version.
Despite having a very long support period that extended with each passing year, .NET Framework saw a significant reduction in support duration when it became .NET. While the development experience for C# has greatly improved in .NET, the significantly shortened support period has become a hindrance to its adoption. I cannot persuade my boss or lazy customers to use .NET instead of .NET Framework due to the earlier support deadline.
Therefore, if you want lazy users and middle-ware manufacturers of .NET Framework to migrate from it to .NET, you should provide security fix after 3 years (up to 5 years) for free and extended one after 5 years (up to 7-10 years) as a service for a paid subscription. With such an extension of support, lazy customers will stick to .NET Framework and make it into a second IE 11.

### Configuration

- .NET 6 vs .NET Framework 4.7-4.8.1
- Windows x64
- Desktop

### Regression?

.NET Framework 4.8 will be supported at least until 2032, while .NET 6 will only be supported until 2024.

### Other information

The extended support deadline of JDK 17 is not significantly different from that of JDK 8.
Ubuntu also follows a cycle of LTS releases every 2 years similar to .NET, but LTS versions have a 5-year period of free support.

**Comment by krwq** [comment]
cc: @richlander

**Comment by richlander** [comment]
We chose the support timeframes to enable a balance between stable deployment time for users and enabling the team to spend most of their time innovating. The team has made a lot of progress over the years, in functionality, performance, security, and other topics. We've also made it easier to upgrade from version to version. We believe that three years of free support for LTS remains a good option for how much value we offer. We also believe that each new version (LTS and STS) offers compelling value to motivate users to upgrade.

At the same time, we understand that folks like yourself would prefer longer support timeframes and might want an extended paid support offerings. We've discussed that, but have opted to continue with only the free support plan.

**Comment by tats-u** [comment]
Do you think it's not good idea to allow users to skip one LTS version? Even Node.js, whose support period is 3 years, allows by releasing LTS versions every year unlike .NET.

**Comment by tats-u** [comment]
@richlander So it is intentional that the free support period is shorter than twice the LTS release interval. Then, are you not considering “paid” extended maintenance support for enterprise unlike Java, Windows, RHEL, or Ubuntu, either? I believe C# is a much better language than Java (inferior than Kotlin though), so you might want to steal enterprise projects from Java and improve DX for their developers.
I have seen some projects STILL using Java 8.

**Comment by richlander** [comment]
> the free support period is shorter than twice the LTS release interval

I don't understand what you mean. Can you elaborate on that?

**Comment by tats-u** [comment]
I mean that 3 years is shorter than 2 x 2 = 4 years

**Comment by richlander** [comment]
> I mean that 3 years (support period of LTS releases) is shorter than 2 x 2 years (the cycle of LTS releases) = 4 years

OK. Thanks for that. We think of the 3 years as providing 1 year of overlap with the next LTS. That's the model. The 2x2 idea seems arbitrary to me. The duration of overlap seems like the key metric.

> No paid extended maintenance support is planned as now?

Correct. It has come up, but we haven't established such a program.

**Comment by MrRosendahl** [comment]
Sorry to ping an old thread... but its the yearly LTS go through (again).

@richlander I agree that the LTS EOL works, if your team supports a single or a few smaller projects with no external dependencies, but my experience is that most projects tend to grow quite large and also have external dependencies, especiallt web projects. I'm lucky that I don't work with .NET (Core) web projects anymore since the LTS is way too short for those kind of projects and has had too many breaking changes over the years. Back in my consultant days, customers were'nt so keen on paying for huge upgrades due to LTS right after a project was finished and outside agreement, which in the end leads to .NET Core projects with vulnerabilities out in the wild... and I'm guessing that I'm not the only that has had those kind of issues.

Currently I'm working (in house) in a integration team where we create a couple of new integrations per year, and we have (sadly) come to the conclusion that we won't be using .NET because of the short LTS... unless we have an extremely good reason for it, and the project is kept as small as possible with no external dependencies. Instead we've opted to use Azure logic apps standard where we only have to change one setting to switch from one node version to the other.

_**As a .NET developer, .NET is one of the best and easiest languages to use, and as a developer its a dream come true to see the new features being added!!**_ But at the same time, if I look at myself as a .NET customer with many business critical systems... I would be looking somewhere else...

In the long run I believe that if .NET LTS continues in its current pace Microsoft will only end up hurting the itself and the .NET brand since the LTS its a bit too short for larger business critical projects.

_As a developer, thank you for a great .NET product!_ 😄

**Comment by tats-u** [comment]
@richlander I have ***never*** given up or convinced just because of no reply from me.

Some companies (mostly customers of our company or competitors) take time (sometimes more than a year) to decide and outsource the modification of the software they own.
Also, when software development is outsourced, version upgrades are a cost; the .NET Framework only incurs costs for functional modifications and bug fixes, but .NET tries to add to that the non-negligible cost of version upgrades at relatively short intervals of two years.

A one year grace period is far too short. Don't think that all companies can upgrade .NET in their software without incurring costs.

***Who on earth want to use .NET instead of .NET Framework if they don't have sufficient interest on software (development)?***
Your idea will encourage those in charge of such companies to move to Java instead of .NET.
.NET must be reliable than Node.js.

**Comment by tats-u** [comment]
Also don't think most of .NET (Framework) users use it in the cloud or most .NET (Framework) projects have sufficient automated tests to make it easier to upgrade .NET (Framework) versions.

> Correct. It has come up, but we haven't established such a program.

You should do for security fixes. Why not? Windows, Ubuntu, RHEL, and Java have paid extended supports.
In the first place, I wonder why you Microsoft provide .NET (Framework) completely free. Why not do business with it? They have already done.

As a .NET developer: I think C# is better than Java though there are some lacked convenient features (e.g. local variable immutability & discriminated unions), and F# is great (no official template for desktop GUI apps though). I don't want to see .NET gets knocked down by Java.

**Comment by tats-u** [comment]
@richlander I believe C# is better then Java as a place to migrate from COBOL. C# can overload operators and make it easier to write expressions using custom numeric types.
The too short period of support is ruining everything. Not only migrations from COBOL but common enterprise applications!
Since you have designated VB.NET as VB6's successor, you are obligated to respect enterprise applications.

**Comment by tats-u** [comment]
@richlander .NET has killer languages, C# and F# for enterprise users. C#'s latest syntax is similar but mostly upward compatible with that of Java, which has been loved by them, except for some. F# is more difficult to learn and recruit engineers, but has many attractive features (e.g. immutable by default and discriminated union) for users who want their programs to be robuster. I can't understand why you've ignored at such a user base completely.

**Comment by lennoncork** [comment]
For what it's worth we're also feeling the pain of dotnet 6.0 going EOL and the short LTS cycle. We have customers in the field running deployed software and the amount of overhead the EOL causes due to infosec policies is continually challenging. We have abandoned attempting to use regular releases because they are typically EOL at the time of release and we have our own support requirements to juggle. Realistically it would have been better if LTS overlapped each subsequent LTS (i.e 4 years instead of 2), even if the support existed at a reduced level for only serious vulnerabilities. Maybe as .NET 10 evolves we can reconsider the LTS duration, I suspect that we're not the only ones in this situation and this will continue to come up.

**Comment by tats-u** [comment]
Yeah, we just need critical security fixes like .NET Framework and old Visual Studio.

**Comment by tats-u** [comment]
@richlander Even Python provides the support for 5 years. If you want to make C# as popular as Python and Java, you should extend the support of .NET to at least 4 years.

**Comment by GreenWaves400** [comment]
I can also add three things about the current, 3-year duration of these "LTS" releases:

1. Its unreasonably short duration is one major reason multi-targeting and/or .NET Standard 2.0 are still popular: some customers want "the shiniest latest thing" (and generally are clueless about the support duration, taking it for granted), however some other customers are paying closer attention, and want "the best and longest support". The "LTS" policy is one reason .NET (non-Framework) adoption hasn't completely happened;
 
2. People and companies that rushed to switch away from .NET Framework to ".NET" did so before they learned of the duration of support for either implementation stack. Many actually regret the decision, whereas most others are struggling to keep up with the constant fight to stay in support and update their WHOLE software product line between every even-numbered (LTS) release every 2 years;

3. Despite claiming that .NET Standard 2.0/2.1 are still supported, it's clear Microsoft intends to kill it eventually, especially when/if .NET Framework adoption becomes extremely low (which will take more than a decade from even now, so possibly 2040+). However, what they may not realize is that the extremely short term support of current "LTS" releases incentivizes further .NET Standard adoption: as .NET Standard is not a runtime, a .NET Standard project is good to go as long as the main calling program (e.g ASP.NET Core, console app etc.) is using a supported .NET implementation. What this means is if you have e.g. 10 library projects in a solution targeting .NET Standard, you don't have to update all 10 of them every 2 years anymore: it's "automatically" always up-to-date, as long as the "main" project using them is using a supported runtime, thus greatly removing much of the 2-year-update overhead. The bigger the project, the more important this is.

I believe if Microsoft wants to see .NET adoption increase, LTS support has to _actually_ mean LTS, and I don't see this happening unless it lasts for 5 years **minimum** (ideally longer) instead of merely 3 years. I assume it's for increased customer (developer) engagement, but as far as I can tell, this approach has only backfired.

**Comment by Neutrino-Sunset** [comment]
We started a project for a client at the begining of this year. NET 10 was still bleeding edge at that time and NET 8 was already selected for the deployment and the infrastructure was in place. It's only been a short project and it's going live in the next week, and we are already getting warnings about EOL in November.

That feels really bad. We haven't quite finished a 6 month project and are already facing the prospect of having to update the entire tech stack.

.NET LTS is frankly a joke.
