### ISSUE TITLE
_contributor.md_ files that contain lists with personal e-mail adresses.

### ISSUE THREAD

**Issue by Jay-o-Way** [dotnet/core#8374]
I see a number of _contributor.md_ files that contain lists with personal e-mail adresses. Doesn't that count as a privacy leak?

**Comment by svick** [comment]
Those email addresses usually come from git commits, so it shouldn't leak anything that hasn't already been "leaked".

If you're worried about leaking your own address, [GitHub says this](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#about-commit-email-addresses):

> If you'd like to keep your email address private, you can use a GitHub-provided `noreply` email address.

Though be aware that that won't change anything about commits you've made in the past, since git commits are immutable.

**Comment by mairaw** [comment]
As I discussed your previous comment on the chore issue with @richlander and our privacy team, those e-mail addresses are embedded in each git commit and are consistent with https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address. So, they are not a privacy leak. You can see that a number of folks opt to use the no-reply option to keep their email address private.
