### ISSUE TITLE
System.Web is not available on Core 2.0

### ISSUE THREAD

**Issue by pardhumeduri** [dotnet/core#838]
we are using VS2017 15.3 preview 7 and while referring the .Netframework 4.5.1 dll / nuget package in core 2.0 application  , we are getting "System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Web.Services, Version=4.0.0.0, "

old application was using .net framework 4.5.1 which is a class library and has System.Web.Services name space for manage soap exceptions. 

Kindly help.

**Comment by karelz** [comment]
System.Web is not part of .NET Core: https://apisof.net/catalog/System.Web.Services

**Comment by roozbehid-ic** [comment]
@karelz Is there a plan to port it? It seems Xamarin already has it, so shouldn't be that hard to port it to different oses?

**Comment by Petermarcu** [comment]
@DamianEdwards to speak to any plans to port any part of System.Web.

**Comment by DamianEdwards** [comment]
There is no plan to port any part of `System.Web` to .NET Core. Can you explain more of what the class library is doing so that we might recommend some different approaches?

**Comment by richlander** [comment]
I'd suggest running API Port on your codebase so that we can get a better sense of your dependencies. Our [API Catalog](https://apisof.net/catalog/System.Web.Services) claims that we have no API Port information for these types.

I'm assuming that these soap exceptions are produced on the server. Yes? We don't have a SOAP server implementation on .NET Core. What would this code do in absence of that?

**Comment by Petermarcu** [comment]
@richlander, should we move this to corefx or to an aspnet repo so its better on the radar?

**Comment by Petermarcu** [comment]
Ok, at this point @DamianEdwards has confirmed this is not on the asp.net team's roadmap. If you want to have more discussion on this, I'd suggest opening an issue on the aspnet/home repo. I"m going to close this issue now.
