### ISSUE TITLE
What's new in .NET 8 RC 2 [WIP]

### ISSUE THREAD

**Issue by leecow** [dotnet/core#8440]
# What's new in .NET 8 RC 2

This issue is for teams to highlight work for the community that will release in **.NET 8 RC 2**

To add content, use a new conversation entry. The entry should include the team name and feature title as the first line shown in the template below.

## Required

```
## Team Name: Feature title

[link to the tracking issue or epic item for the work]

Tell the story of the feature and anything the community should pay particular attention 
to be successful in using the feature.
```

## Optional

Below are three additional items to consider. These will help the .NET 8 blog team and the community throughout the release.

- [ ] Link to documentation.
  - Where can we send people to learn more about the feature?
- [ ] Link to where you'd like people to provide feedback for this feature.
  - Where can people best comment on the direction of this feature?
- [ ] Whether you would like assistance from the .NET 8 writers to craft a story for this feature. 
  - Please @JonDouglas or @JeremyLikness in your comment if so.

## Index of .NET 8 releases

Preview 1: https://github.com/dotnet/core/issues/8133
Preview 2: https://github.com/dotnet/core/issues/8134
Preview 3: https://github.com/dotnet/core/issues/8135
Preview 4: https://github.com/dotnet/core/issues/8234
Preview 5: https://github.com/dotnet/core/issues/8436
Preview 6: https://github.com/dotnet/core/issues/8437
Preview 7: https://github.com/dotnet/core/issues/8438
RC 1: https://github.com/dotnet/core/issues/8439
RC 2: https://github.com/dotnet/core/issues/8440

**Comment by Saibamen** [comment]
@JonDouglas: I have 404 in all URLs in your message: 
![image](https://github.com/dotnet/core/assets/905878/7e17ef07-994b-445e-b4a3-62e31c92e7c3)

**Comment by JonDouglas** [comment]
> @JonDouglas: I have 404 in all URLs in your message: ![image](https://user-images.githubusercontent.com/905878/268875309-7e17ef07-994b-445e-b4a3-62e31c92e7c3.png)

See the parent issue for more information. Likely the `InSourcePackageReadme` branch was merged and deleted.

**Comment by baronfel** [comment]
## MSBuild: Simple CLI-based project evaluation

* [Issue](https://github.com/dotnet/msbuild/issues/3911#issuecomment-1478468822)
* [PR](https://github.com/dotnet/msbuild/pull/9138)

MSBuild is a very powerful platform, and is great at integrating data and tools from other ecosystems into its view of the world.  It's historically not been so good at making the data that it has available to the broader worlds of scripting and tools.  In the past, tools authors would have to do things like injecting their own MSBuild code to read certain Properties, Items, or Target Outputs into files, and then parse those files. This is work that is very error prone. In .NET 8, the MSBuild team has shipped a new feature that makes it easier to incorporate data from MSBuild into your scripts or tools. Let's take a look at a sample to see what I mean.

```shell
>dotnet publish --getProperty:OutputPath
bin\Release\net8.0\
```

In this simple example, we've used the `--getProperty` flag to request the value of the `OutputPath` property after the `publish` command has run, and MSBuild has written that single property's value to the standard out of my terminal. This is very useful for tooling like CI pipelines - where before you might have hard-coded an output path, now you can be data-driven! Let's look at a more complex example, where we fetch multiple properties. In this example we're publishing a Container Image for a project using the .NET SDK, and we want to use some properties of the container that are generated during that process:

```shell
> dotnet publish -p PublishProfile=DefaultContainer --getProperty:GeneratedContainerDigest --getProperty:GeneratedContainerConfiguration
{
  "Properties": {
    "GeneratedContainerDigest": "sha256:ef880a503bbabcb84bbb6a1aa9b41b36dc1ba08352e7cd91c0993646675174c4",
    "GeneratedContainerConfiguration": "{\u0022config\u0022:{\u0022ExposedPorts\u0022:{\u00228080/tcp\u0022:{}},\u0022Labels\u0022:{\u0022org.opencontainers.image.created\u0022:\u00222023-10-02T18:20:01.6356453Z\u0022,\u0022org.opencontainers.artifact.created\u0022:\u00222023-10-02T18:20:01.6356453Z\u0022,\u0022org.opencontainers.artifact.description\u0022:\u0022A project that demonstrates publishing to various container registries using just\\r\\n      the .NET SDK\u0022,\u0022org.opencontainers.image.description\u0022:\u0022A project that demonstrates publishing to various container registries using just\\r\\n      the .NET SDK\u0022,\u0022org.opencontainers.image.authors\u0022:\u0022Chet Husk\u0022,\u0022org.opencontainers.image.url\u0022:\u0022https://github.com/baronfel/sdk-container-demo\u0022,\u0022org.opencontainers.image.documentation\u0022:\u0022https://github.com/baronfel/sdk-container-demo\u0022,\u0022org.opencontainers.image.version\u0022:\u00221.0.0\u0022,\u0022org.opencontainers.image.licenses\u0022:\u0022MIT\u0022,\u0022org.opencontainers.image.title\u0022:\u0022.NET SDK 7 Container Demo\u0022,\u0022org.opencontainers.image.base.name\u0022:\u0022mcr.microsoft.com/dotnet/aspnet:8.0.0-rc.1\u0022},\u0022Env\u0022:[\u0022PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\u0022,\u0022APP_UID=1654\u0022,\u0022ASPNETCORE_HTTP_PORTS=8080\u0022,\u0022DOTNET_RUNNING_IN_CONTAINER=true\u0022,\u0022DOTNET_VERSION=8.0.0-rc.1.23419.4\u0022,\u0022ASPNET_VERSION=8.0.0-rc.1.23421.29\u0022],\u0022WorkingDir\u0022:\u0022/app\u0022,\u0022Entrypoint\u0022:[\u0022dotnet\u0022,\u0022sdk-container-demo.dll\u0022],\u0022User\u0022:\u00221654\u0022},\u0022created\u0022:\u00222023-10-02T18:20:04.6914310Z\u0022,\u0022rootfs\u0022:{\u0022type\u0022:\u0022layers\u0022,\u0022diff_ids\u0022:[\u0022sha256:d310e774110ab038b30c6a5f7b7f7dd527dbe527854496bd30194b9ee6ea496e\u0022,\u0022sha256:379caff0dd639afb033e114cb8da17c334a36d0c6c01bb4cf5f2d1a811968742\u0022,\u0022sha256:80627b9413613b9703eec6adc7a3a751ac1b7571041c77899456345f823ef63a\u0022,\u0022sha256:6231bc2ccd45860760c09a50d6d059aa4b6aa357e41e6d06f4394f24176f203d\u0022,\u0022sha256:56fa0b94fd5e406124a3d070ec79998698ddea2e635bf53bbf106dc86aeaa240\u0022,\u0022sha256:272eedde5582036a7f26fe5d069f4ba328ba7a5c6be30f6dcbee9838224df148\u0022,\u0022sha256:4b8ab71658cccccfaf8979b1025f3ed1b12e936a448dcd13b9ab4f7709f31357\u0022]},\u0022architecture\u0022:\u0022amd64\u0022,\u0022os\u0022:\u0022linux\u0022,\u0022history\u0022:[{\u0022created\u0022:\u00222023-09-20T04:55:40.8154909Z\u0022,\u0022created_by\u0022:\u0022/bin/sh -c #(nop) ADD file:a1398394375faab8dd9e1e8d584eea96c750fb57ae4ffd2b14624f1cf263561b in / \u0022},{\u0022created\u0022:\u00222023-09-20T04:55:41.1203677Z\u0022,\u0022created_by\u0022:\u0022/bin/sh -c #(nop)  CMD [\\u0022bash\\u0022]\u0022,\u0022empty_layer\u0022:true},{\u0022comment\u0022:\u0022buildkit.dockerfile.v0\u0022,\u0022created\u0022:\u00222023-09-20T12:13:34.5265068Z\u0022,\u0022created_by\u0022:\u0022ENV APP_UID=1654 ASPNETCORE_HTTP_PORTS=8080 DOTNET_RUNNING_IN_CONTAINER=true\u0022,\u0022empty_layer\u0022:true},{\u0022comment\u0022:\u0022buildkit.dockerfile.v0\u0022,\u0022created\u0022:\u00222023-09-20T12:13:34.5265068Z\u0022,\u0022created_by\u0022:\u0022RUN /bin/sh -c apt-get update     \\u0026\\u0026 apt-get install -y --no-install-recommends         ca-certificates                 libc6         libgcc-s1         libicu72         libssl3         libstdc\\u002B\\u002B6         tzdata         zlib1g     \\u0026\\u0026 rm -rf /var/lib/apt/lists/* # buildkit\u0022},{\u0022comment\u0022:\u0022buildkit.dockerfile.v0\u0022,\u0022created\u0022:\u00222023-09-20T12:13:34.8536814Z\u0022,\u0022created_by\u0022:\u0022RUN /bin/sh -c groupadd         --gid=$APP_UID         app     \\u0026\\u0026 useradd -l         --uid=$APP_UID         --gid=$APP_UID         --create-home         app # buildkit\u0022},{\u0022comment\u0022:\u0022buildkit.dockerfile.v0\u0022,\u0022created\u0022:\u00222023-09-20T12:13:36.8764982Z\u0022,\u0022created_by\u0022:\u0022ENV DOTNET_VERSION=8.0.0-rc.1.23419.4\u0022,\u0022empty_layer\u0022:true},{\u0022comment\u0022:\u0022buildkit.dockerfile.v0\u0022,\u0022created\u0022:\u00222023-09-20T12:13:36.8764982Z\u0022,\u0022created_by\u0022:\u0022COPY /dotnet /usr/share/dotnet # buildkit\u0022},{\u0022comment\u0022:\u0022buildkit.dockerfile.v0\u0022,\u0022created\u0022:\u00222023-09-20T12:13:37.1287440Z\u0022,\u0022created_by\u0022:\u0022RUN /bin/sh -c ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet # buildkit\u0022},{\u0022comment\u0022:\u0022buildkit.dockerfile.v0\u0022,\u0022created\u0022:\u00222023-09-20T12:13:39.8264990Z\u0022,\u0022created_by\u0022:\u0022ENV ASPNET_VERSION=8.0.0-rc.1.23421.29\u0022,\u0022empty_layer\u0022:true},{\u0022comment\u0022:\u0022buildkit.dockerfile.v0\u0022,\u0022created\u0022:\u00222023-09-20T12:13:39.8264990Z\u0022,\u0022created_by\u0022:\u0022COPY /shared/Microsoft.AspNetCore.App /usr/share/dotnet/shared/Microsoft.AspNetCore.App # buildkit\u0022},{\u0022author\u0022:\u0022.NET SDK\u0022,\u0022created\u0022:\u00222023-10-02T18:20:04.6914069Z\u0022,\u0022created_by\u0022:\u0022.NET SDK Container Tooling, version 8.0.100-dev\u0022}]}"
  }
}
```

Here we've requested two properties, and received a JSON object with a `Properties` property containing the two properties we requested (both of which MSBuild has stored as strings). From here, we can use any JSON tooling for the CLI or the language of our choice to parse this data and use it.

The same behavior holds for MSBuild Items, which can be requested by Item Type using the `--getItem:<ITEMTYPE>` flag. MSBuild will return these as JSON objects in an array under a key of the Item name, all under the `"Items"` key, like in this example where we request all of the Image Tags published for an image:

```shell
>dotnet publish -p PublishProfile=DefaultContainer --getItem:ContainerImageTags
{
  "Items": {
    "ContainerImageTags": [
      {
        "Identity": "latest",
		.... other MSBuild Item Metadata elided ....
    ]
  }
}
```

Finally, we also support retrieving the outputs of a given Target that's been run using `--getTargetResults:<TARGETNAME>`. These outputs are returned under the `TargetResults` property, like in this example where we get the final image name used by a generated SDK Container Image:

```shell
dotnet publish -p PublishProfile=DefaultContainer --getTargetResult:ComputeContainerBaseImage
{
  "TargetResults": {
    "ComputeContainerBaseImage": {
      "Result": "Success",
      "Items": [
        {
          "Identity": "mcr.microsoft.com/dotnet/aspnet:8.0.0-rc.1",
          .... other MSBuild Item Metadata elided ....
        }
      ]
    }
  }
}
```

We think this will really make it easier for MSBuild to integrate into other tooling, so we're excited to see what you all do with it!

**Comment by baronfel** [comment]
## SDK Container Publish: Publish to tar.gz archive

* [Issue](https://github.com/dotnet/sdk-container-builds/issues/283)
* [PR](https://github.com/dotnet/sdk/pull/35151)

The SDK has been able to publish containers to local container tools like Docker and Podman, as well as Remote Container Registries like Azure Container Registry, Amazon's Elastic Container Registry, and Docker Hub for quite some time now. However, not all workflows are so straightforward. Some teams may prefer to run scanning tools over their images before pushing them, for example. To help support these workflows, community member @Danielku15 implemented an awesome new feature for the SDK Container Publish tooling - the ability to create a container directly as a tar.gz archive. Once this archive is made, it can be moved, scanned, or loaded into a local Docker toolchain - whatever your needs may be! Let's take a look at how simple it is:

```shell
>dotnet publish -p PublishProfile=DefaultContainer -p ContainerArchiveOutputPath=./images/sdk-container-demo.tar.gz
MSBuild version 17.8.0+6cdef4241 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\8.0.100-rc.2.23477.19\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: http
s://aka.ms/dotnet-support-policy [D:\code\sdk-container-demo\src\sdk-container-demo\sdk-container-demo.csproj]
  sdk-container-demo -> D:\code\sdk-container-demo\src\sdk-container-demo\bin\Release\net8.0\sdk-container-demo.dll
  sdk-container-demo -> D:\code\sdk-container-demo\src\sdk-container-demo\bin\Release\net8.0\publish\
  Building image 'sdk-container-demo' with tags 'latest' on top of base image 'mcr.microsoft.com/dotnet/aspnet:8.0.0-rc.1'.
  Pushed image 'sdk-container-demo:latest' to local archive at 'D:\code\sdk-container-demo\src\sdk-container-demo\images\sdk-container-demo.tar.gz'.
```

Here I've added one new property to my publish command: `ContainerArchiveOutputPath`. When this property is specified, instead of pushing the image to Docker or to a remote registry, the tooling instead created the file I chose. In this case I specified a file name explicitly, but if you want you can also just specify a folder to push the image into. If you do that, the generated tar.gz will be named after the image (so in this example the generated name would have been `sdk-container-demo.tar.gz`).

Once you have a tar.gz, you can move it wherever you need, or simply load it into Docker using `docker load`:

```shell
>docker load --input .\images\sdk-container-demo.tar.gz
5d6d1d62da4b: Loading layer [==================================================>]  9.442MB/9.442MB
Loaded image: sdk-container-demo:latest
```

Just like that my image is available for me to run via Docker. We hope this new capability enables new workflows for more teams - let us know what you think at [our repo](https://github.com/dotnet/sdk-container-builds)!

**Comment by baronfel** [comment]
@JonDouglas and team - this next one is an advisory notice that SDK/Roslyn teams think is big enough to call-out somehow on the post. Happy to chat about it more.

> [!IMPORTANT]
> .NET SDK 8.0.100-rc.2 _must_ be used with Visual Studio 17.8 preview 3 due to a dependency error with Razor tooling. See [this SDK Announcement](https://github.com/dotnet/sdk/issues/35810) for more details.

**Comment by luisquintanilla** [comment]
## Introducing Tensor Primitives for .NET

- [Issue](https://github.com/dotnet/runtime/issues/89639)
- [PR](https://github.com/dotnet/runtime/issues/92219)

Over the past few years, .NET has made significant refinements to numeric support in an effort to optimize data-intensive workloads like those of AI and Machine Learning.

Starting with the addition of hardware intrinsics in .NET Core 3, it provided .NET developers with access to hardware specific instructions. By doing so, it enabled .NET applications to utilize modern hardware capabilities like vector instructions which are critical to AI workloads. 

The next step in this effort was Generic Math which was introduced in .NET 6. Generic Math builds on top of hardware intrinsics and provides more type-safe simplified numeric operations. This feature eliminates the need for creating numerous nearly identical implementations to cater to different numeric types, thus simplifying the code and making it more maintainable.

`TensorPrimitives` is the next step in the evolution of Numerics for AI by building on top of hardware intrinsics and Generic Math. TensorPrimitives aims to introduce built-in support tensor operations. 

For more details, see the [Future of Numerics and AI proposal](https://github.com/dotnet/runtime/issues/89639)

### A case study

For AI workloads such as semantic search or Retrieval Augmented Generation (RAG) which augment the natural language capabilities of Large Language Models like ChatGPT by introducing relevant data, operations on vectors like cosine similarity to find the most relevant data to answer a question are crucial. 

#### Before TensorPrimitives

Before `TensorPrimitives`, if you needed to apply any operations to your tensor-shaped data, you had two options:

1. Use external dependencies
2. Implement your own operations

##### Using heavy external dependencies

The easiest way for you to use any of these operations was to use existing libraries such as TorchSharp, TensorFlow.NET, Math.NET Numerics, ML.NET, or Semantic Kernel. If the application you were building heavily relied on the functionality provided by those libraries, it made sense to add them to your project. However, if all you needed was a handful of methods from those libraries, taking a dependency on those libraries produced introduced additional overhead. 

TODO: INSERT TORCHSHARP EXAMPLE (COSINE SIMILARITY)

##### Writing your own implementation

If you didn't want to take on another external dependency just to use a few operations in your application, the other alternative was to implement your own. This is what many of the libraries mentioned previously have done. While this is a viable path that offers you the most control over your code, this meant you were writing boilerplate code rather than focusing on the competitive advantages of your application or business. Since this was boilerplate code, most likely it also was a naive implementation of the operation which didn't take full advantage of the runtime's capabilities for hardware optimizations.  

TODO: INSERT NAIVE IMPL CODE SAMPLE (COSINE SIMILARITY)

#### After TensorPrimitives

`TensorPrimitives` simplifies these choices. If you just need a handful of operations, you don't need to take on a heavy external dependency into your project. 

TODO: INSERT TP IMPL EXAMPLE (COSINE SIMILARITY)

Similarly, for libraries who make use of these operations such as Semantic Kernel and ML.NET, they can replace many of their existing implementation with TensorPrimitives so they can focus on their competitive advantages and deliver features faster. 

### Current State

Currently, TensorPrimitives provides vectorized implementations for operations like:

- CosineSimilarity
- SoftMax
- Sigmoid
- Tanh
- Sinh
- Norm (L2)
- SumOfSquares
- ProductOfSums

For a complete list of operations, see [TensorPrimitives work items](https://bing.com)

### What's next?

Over the next few releases, we plan to:

- Provide more comprehensive coverage of tensor operations.
- Replace existing implementations of these operations in libraries like ML.NET and Semantic Kernel with the TensorPrimitives implementations.

### Get started with TensorPrimitives today

TODO: INSERT INSTALL / ONBOARDING INSTRUCTIONS

**Comment by lofcz** [comment]
@luisquintanilla shouldn't it be `System.Numerics.Tensors`? with `s`
