### ISSUE TITLE
Dotnet.exe  like jave.exe, is a freak. Can I compile executable files like a native executable file?

### ISSUE THREAD

**Issue by maikebing** [dotnet/core#850]
Dotnet.exe, like jave.exe, is a freak. Can I compile executable files like a native executable file?

 
Just like the original.Net compiled executable file, or as a native application compiled by VC？

**Comment by ThuCommix** [comment]
.exe does not have any meaning to other systems like MacOS or Linux, so why bother?

**Comment by Sebazzz** [comment]
If you want to distribute a direct executable binary to your end users, you may use [self-contained deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/#self-contained-deployments-scd).

**Comment by Petermarcu** [comment]
Yes, there are two options.

1) is self contained which gets you an experience much more like .NET Framework where you can have "Myapp.exe". 

2) There is really early work in the dotnet/corert repo to enable compiling into a single file native executable.

I'm going to close this issue for now because 1 is the current solution to not have to call dotnet.exe and 2 is the longer term work and doesn't need an issue tracking it.

**Comment by maikebing** [comment]
thinks! @Petermarcu
