### ISSUE TITLE
A princípio, instalado. Mas, consta erro. 

### ISSUE THREAD

**Issue by Will-Lopes-dev** [dotnet/core#8548]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

dotnet : O termo 'dotnet' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável.
Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.
No linha:1 caractere:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by adamsitnik** [comment]
Hi @Will-Lopes-dev 

On Windows, most of the installers add something to $PATH environment variable. The problem is that $PATH is not updated unless you start a brand new terminal window. So please start a new terminal window and let me know if it helps.

**Comment by Icegreeen** [comment]
It is always a good practice to check some information during installation, especially the PATH settings that are your problem.

The problem appears to be that the 'dotnet' executable was not being correctly recognized by PowerShell due to an inappropriate PATH configuration. 'dotnet' should be automatically added to the PATH during installation, but in some cases this configuration may not be effective.

The solution may be to correctly install dotnet or manually add the relevant 'dotnet' paths to the PATH in PowerShell to ensure the executable is recognized correctly.
