### ISSUE TITLE
Running Core 2.0 Self-Containing App on Linux fails

### ISSUE THREAD

**Issue by TimoBohl** [dotnet/core#857]
# Running a Net Core 2.0 Self-Containing App on Linux fails

Running a published self-containing app on linux results in an error regarding the assemblys manifest.
Worked well with Core 1.1.

# Investigations so far and how to reproduce

I recently converted a Net Core app 1.1 which worked fine to Net Core 2.0 and ran into an issue after publish and run at linux.
I am using Linux Pepermint8 and Ubuntu 16.04. Both showing the same errors.

"Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Console, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Aborted "

Then I decided to create a simple project on Visual Studio 2017.3 using the C# Net Core Console template with Net Core 2.0.

To make the sample self-containing, I've modified the Porject which now looks like:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifiers>win10-x64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
  </ItemGroup>
</Project>

```
The main moutine is the default hello world to console output.
Nothing else changed from the default template.

Called Publish form the Solution Explorer and selected "linux-x64" as target platform.
Copied the output to my linux machines and got the same error again.
"Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Console, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Aborted "

The deps file only references System.Console 4.3.0.

**Comment by onematchfox** [comment]
I have also run into a similar issue which may be related whilst building a self-contained app for target framework ubuntu.16.04-x64 which previously worked fine with 1.1.

`Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)` 

Through investigation I have found that a brand new console app works fine, but as soon as I reference something (in my case Newtonsoft.Json), the version of System.Runtime.Extensions in the published output becomes the signed v4.6.25519.3. Not sure where the dependency is coming from as everything seems to reference 4.3.0.

I suspect your issue is a result of dependencies introduced by the inclusion of Microsoft.AspNetCore.All.

P.S: I can get the app to work by overwriting all system dlls with those from the blank app.

**Comment by TimoBohl** [comment]
Removing the include of Microsoft.AspNetCore.All resolved it for me too.
Thank you!

Supposing that there is a reference issue in the metapackage since this was recommended in the migration description here [Migrating from ASP.NET Core 1.x to ASP.NET Core 2.0](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/).

**Comment by onematchfox** [comment]
@TimoBohl, FYI, after further investigation (i.e. discussion with far more knowledgeable folk), it seems that this issue actually lies with msbuild not correctly running the conflict resolution logic (see https://github.com/dotnet/corefx/issues/23436#issuecomment-324694287 and comments below it). IN case you do need to reference libraries like Microsoft.AspNetCore.All or any others that result in this issue then you can workaround the issue by using the native dotnet publish command instead of publishing from within VS.

**Comment by TimoBohl** [comment]
@onematchfox Thank you, I've reported this already in the [developer network - VS2017 15.3 Net Core 2.0 publish a self-contained app for Linux fails in VS](https://developercommunity.visualstudio.com/content/problem/101502/vs2017-153-net-core-20-publish-a-self-contained-ap.html).
Hope they can fix it.

**Comment by onematchfox** [comment]
👍  You can also follow https://github.com/dotnet/sdk/issues/1502 for progress on the issue.
