### ISSUE TITLE
Deadlock when reading from non existent `con` files

### ISSUE THREAD

**Issue by mrakgr** [dotnet/core#8726]
### Description

```fs
open System.IO
File.ReadAllLines("con")
```

Try this F# script anywhere, and you will see that it deadlocks.

https://superuser.com/questions/86999/why-cant-i-name-a-folder-or-file-con-in-windows

It turns out the `con` name is special and sets the file to read from the console. Typing the `con` as a module name into the Spiral language's project file was causing the language server to hang. I was relying on an exception being thrown to detect nonexistent files, but I've worked around it using `File.Exists` .

### Configuration

I am on .NET 8 preview 3 on Windows 10, but this error should be present in the old .NET versions as well.

**Comment by buyaa-n** [comment]
CC @KathleenDollard

**Comment by adamsitnik** [comment]
The behavior you have observed is correct. "con" is short for "console" and it's being mapped to "\\.\con" file path. The file is successfully opened (the file type is `FILE_TYPE_CHAR`) and the `File.ReadAllLines` waits for user input. When you type some text and press enter, it reads a line. The problem is that it needs and EOF to stop reading.

In the future we may add an API for getting file type: https://github.com/dotnet/runtime/issues/62868
