### ISSUE TITLE
Rsa ToXmlString is not supported on .NET Core 2.0

### ISSUE THREAD

**Issue by myloveCc** [dotnet/core#874]
# rsa.ToXmlString(true) is not supported on .NET Core 2.0

```csharp
 var rsa = RSA.Create(2048);
 var privateKey = rsa.ToXmlString(true);    // //not supported exception
```

**Comment by bartonjs** [comment]
Yep.  In .NET Framework networking, XML, and cryptography all live in one library (mscorlib).  In .NET Core they're in three separate libraries, and making this method work requires a circle:

* XML needs networking, because (even though we discourage it) DTDs can initiate downloads.
* Networking needs cryptography because TLS/https have X.509 certificates.
* Cryptography needs XML for ToXmlString/FromXmlString.

The easiest link to snip is the ToXmlString/FromXmlString methods.

Technically ToXmlString can be written without XML (like in [.NET Framework's implementation](http://referencesource.microsoft.com/#mscorlib/system/security/cryptography/rsa.cs,fd15a0bacd426550), but FromXmlString requires an XML parser.

My recommendation would be to make a `public static string ToXmlString(this RSAParameters rsaParameters)` method, and a `public static RSAParameters FromXmlString(string xml)` method; borrowing from NetFx and [CoreFx's SignedXml](https://github.com/dotnet/corefx/blob/c88064e2054fca0789511410260906ff5ff0468d/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/RSAKeyValue.cs); and to ultimately try moving off of the XML representations.

**Comment by myloveCc** [comment]
### This feature is not difficult, and I have been achieved in my project。

```csharp
using System;
using System.Security.Cryptography;
using System.Xml;
using Newtonsoft.Json;
using NETCore.Encrypt.Shared;
using NETCore.Encrypt.Internal;

namespace NETCore.Encrypt.Extensions.Internal
{

    internal static class RSAKeyExtensions
    {
        #region JSON
        internal static void FromJsonString(this RSA rsa, string jsonString)
        {
            Check.Argument.IsNotEmpty(jsonString, nameof(jsonString));
            try
            {
                var paramsJson = JsonConvert.DeserializeObject<RSAParametersJson>(jsonString);

                RSAParameters parameters = new RSAParameters();

                parameters.Modulus = paramsJson.Modulus != null ? Convert.FromBase64String(paramsJson.Modulus) : null;
                parameters.Exponent = paramsJson.Exponent != null ? Convert.FromBase64String(paramsJson.Exponent) : null;
                parameters.P = paramsJson.P != null ? Convert.FromBase64String(paramsJson.P) : null;
                parameters.Q = paramsJson.Q != null ? Convert.FromBase64String(paramsJson.Q) : null;
                parameters.DP = paramsJson.DP != null ? Convert.FromBase64String(paramsJson.DP) : null;
                parameters.DQ = paramsJson.DQ != null ? Convert.FromBase64String(paramsJson.DQ) : null;
                parameters.InverseQ = paramsJson.InverseQ != null ? Convert.FromBase64String(paramsJson.InverseQ) : null;
                parameters.D = paramsJson.D != null ? Convert.FromBase64String(paramsJson.D) : null;
                rsa.ImportParameters(parameters);
            }
            catch
            {
                throw new Exception("Invalid JSON RSA key.");
            }
        }

        internal static string ToJsonString(this RSA rsa, bool includePrivateParameters)
        {
            RSAParameters parameters = rsa.ExportParameters(includePrivateParameters);

            var parasJson = new RSAParametersJson()
            {
                Modulus = parameters.Modulus != null ? Convert.ToBase64String(parameters.Modulus) : null,
                Exponent = parameters.Exponent != null ? Convert.ToBase64String(parameters.Exponent) : null,
                P = parameters.P != null ? Convert.ToBase64String(parameters.P) : null,
                Q = parameters.Q != null ? Convert.ToBase64String(parameters.Q) : null,
                DP = parameters.DP != null ? Convert.ToBase64String(parameters.DP) : null,
                DQ = parameters.DQ != null ? Convert.ToBase64String(parameters.DQ) : null,
                InverseQ = parameters.InverseQ != null ? Convert.ToBase64String(parameters.InverseQ) : null,
                D = parameters.D != null ? Convert.ToBase64String(parameters.D) : null
            };

            return JsonConvert.SerializeObject(parasJson);
        }
        #endregion

        #region XML

        public static void FromLvccXmlString(this RSA rsa, string xmlString)
        {
            RSAParameters parameters = new RSAParameters();

            XmlDocument xmlDoc = new XmlDocument();
            xmlDoc.LoadXml(xmlString);

            if (xmlDoc.DocumentElement.Name.Equals("RSAKeyValue"))
            {
                foreach (XmlNode node in xmlDoc.DocumentElement.ChildNodes)
                {
                    switch (node.Name)
                    {
                        case "Modulus": parameters.Modulus = (string.IsNullOrEmpty(node.InnerText) ? null : Convert.FromBase64String(node.InnerText)); break;
                        case "Exponent": parameters.Exponent = (string.IsNullOrEmpty(node.InnerText) ? null : Convert.FromBase64String(node.InnerText)); break;
                        case "P": parameters.P = (string.IsNullOrEmpty(node.InnerText) ? null : Convert.FromBase64String(node.InnerText)); break;
                        case "Q": parameters.Q = (string.IsNullOrEmpty(node.InnerText) ? null : Convert.FromBase64String(node.InnerText)); break;
                        case "DP": parameters.DP = (string.IsNullOrEmpty(node.InnerText) ? null : Convert.FromBase64String(node.InnerText)); break;
                        case "DQ": parameters.DQ = (string.IsNullOrEmpty(node.InnerText) ? null : Convert.FromBase64String(node.InnerText)); break;
                        case "InverseQ": parameters.InverseQ = (string.IsNullOrEmpty(node.InnerText) ? null : Convert.FromBase64String(node.InnerText)); break;
                        case "D": parameters.D = (string.IsNullOrEmpty(node.InnerText) ? null : Convert.FromBase64String(node.InnerText)); break;
                    }
                }
            }
            else
            {
                throw new Exception("Invalid XML RSA key.");
            }

            rsa.ImportParameters(parameters);
        }

        public static string ToLvccXmlString(this RSA rsa, bool includePrivateParameters)
        {
            RSAParameters parameters = rsa.ExportParameters(includePrivateParameters);

            return string.Format("<RSAKeyValue><Modulus>{0}</Modulus><Exponent>{1}</Exponent><P>{2}</P><Q>{3}</Q><DP>{4}</DP><DQ>{5}</DQ><InverseQ>{6}</InverseQ><D>{7}</D></RSAKeyValue>",
                  parameters.Modulus != null ? Convert.ToBase64String(parameters.Modulus) : null,
                  parameters.Exponent != null ? Convert.ToBase64String(parameters.Exponent) : null,
                  parameters.P != null ? Convert.ToBase64String(parameters.P) : null,
                  parameters.Q != null ? Convert.ToBase64String(parameters.Q) : null,
                  parameters.DP != null ? Convert.ToBase64String(parameters.DP) : null,
                  parameters.DQ != null ? Convert.ToBase64String(parameters.DQ) : null,
                  parameters.InverseQ != null ? Convert.ToBase64String(parameters.InverseQ) : null,
                  parameters.D != null ? Convert.ToBase64String(parameters.D) : null);
        }

        #endregion
    }
}
```

**Comment by Petermarcu** [comment]
@danmosemsft can you get this moved over to dotnet/corefx to be tracked as an issue there?

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #23686](https://github.com/dotnet/corefx/issues/23686) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Korporal** [comment]
@myloveCc @bartonjs - Hi.

I'm seeing the same problem but I must say the "solution" here is rather unimpressive. If after all these years we've come back full circle and the much lauded "code reuse" is now nothing more than copying/pasting source code. then we're in trouble.

**Comment by Mitch-Wheat** [comment]
Totally agree with @Korporal: it is utterly astonishing and very disappointing that such a basic issue still exists a year later.

I made a design decision to go with Azure, and I'm totally regretting it. Azure Functions V1 are plagued with assembly version issues (most notably the reliance on Newtonsoft.JSON v9.0.1), Azure functions V2 seem to have been in preview mode for an embarassing amount of time. 

At this rate I'll be moving to AWS.

**Comment by MapleWithoutWords** [comment]
We hope to solve this problem as soon as possible.

**Comment by gsantopaolo** [comment]
Wondering why this issue is closed. The problem is still there, at least on UWP. 
@myloveCc 's solution seems pretty neat, why don't implement it?

**Comment by bartonjs** [comment]
> Wondering why this issue is closed. 

dotnet/core isn't the right place for issues like this.  This one belongs in dotnet/corefx.

https://github.com/dotnet/corefx/issues/23686 is open, and marked for .NET Core 3.0.

**Comment by Mani0811** [comment]
@myloveCc  How This will be solved with extension method .? RSA have an implementation for hiding that we need to derive the class. According to my understanding .

`public abstract partial class RSA : AsymmetricAlgorithm
    {
        public override void FromXmlString(string xmlString)
        {
            throw new PlatformNotSupportedException();
        }

        public override string ToXmlString(bool includePrivateParameters)
        {
            throw new PlatformNotSupportedException();
        }
    }`

**Comment by secwxx** [comment]
> ```cs
> RSAParametersJson
> ```

it works, thanks.
seems RSAParametersJson class is missing

**Comment by vms20591** [comment]
@Korporal, couldn't have said it any better.

This might be bit of rant, but I have to. We've been trying to migrate our code base from `.NET 4.5+` to `.NET Core 2.x` and we face issue after issue. When we use a .NET API that is no longer present/changed in .NET Core and we get a compile time error, I'm really glad, because now we know what to change.

But, it's issue like these, where the API still exists, but has different internal implementation. It's only during tests are we able to find out that there is an issue. Sadly, the issues are hidden inside other issue, that we have to look through all remotely similar issues. 

For example, casting `X509Certificate2.PrivateKey` to a `RSACryptoServiceProvider` service throws invalid cast error at runtime, because its actually `RSACng`. The docs doesn't clearly say this (sorry if I missed), and, when I try to search this issue, I almost end up in a third party library's GitHub issue, which is not exactly the same, but something similar.

Not saying every such change should documented in exquisite detail, but the most commonly used ones would help. I `really regret using .NET Core` and wonder if we could've rewrote the application from scratch or in a different language altogether.
