### ISSUE TITLE
RSAParameters not serializable in 2.0

### ISSUE THREAD

**Issue by stevewoj** [dotnet/core#889]
in netcore1.x when serializing the RSAParameters with private parameters to JSON it would serialize all fields after upgrade to netcore2 we only get the Exponent and Modulus serialized. Is this change intended?

```
using Newtonsoft.Json;
using System;
using System.Security.Cryptography;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var rsakey = RSA.Create();
            rsakey.KeySize = 2048;

            var rsaparameters = rsakey.ExportParameters(true);
            var rsaparametersString = JsonConvert.SerializeObject(rsaparameters, Formatting.Indented);

            Console.Write(rsaparametersString);

            Console.ReadKey();
        }
    }
}
```

Currently working around this passing the RSAParameters to a custom struct before serializing but would like to avoid doing that.

**Comment by ForkBug** [comment]
I encountered the same problem. 
After followed the Json.net code, I found that this problem was caused by RSAParameters.GetType();

RSAParameters.GetType(); return a type, which has a field DeclaredFields	{System.Reflection.FieldInfo[8]}.
FieldInfo has a field called Attributes	.
The Attributes for RSAParameters.D,DP,Q.. are  Public | NotSerialized.
Json.net will ignore NotSerialized fields.

It seems to be a enhancement for RSAParameters.  Someone do this without think all user scenarios carefully/

**Comment by ForkBug** [comment]
After a second thought, this should be a bug. I open a new one for corefx https://github.com/dotnet/corefx/issues/23847

**Comment by Petermarcu** [comment]
Closing this one because it looks like the bug was filed in corefx which is the right place.
