### ISSUE TITLE
The cached _graphClient instance in GraphSDKHelper is not used

### ISSUE THREAD

**Issue by dotnetgator** [dotnet/core#891]
# General
The _graphClient field in GraphSDK helper appears to be there in order to cache the reference between executions of the GetAuthenticatedClient method.  Except that the private field is *only* ever referenced from this function, and is generated new for every single function call.  Either the call needs to be changed to check it against null and *then* create the instance if null, or the variable can be moved from a field to a local function variable.

**Comment by Petermarcu** [comment]
Sounds like a bug in GraphSDKHelper. Is this what you are using?
https://developer.microsoft.com/en-us/graph/code-samples-and-sdks

If so, this issue is probably best opened here: https://github.com/microsoftgraph/msgraph-sdk-dotnet

Let me know if I'm missing something. I'm going to close this now as I don't see what the .NET Core platform can do to fix this.

**Comment by dotnetgator** [comment]
I don't know how these wires got crossed, but yes - this was supposed to be an issue logged against the ASP.NET Core Graph SDK Sample code in the collection you lined to above. Apologies for the confusion.

**Comment by Petermarcu** [comment]
Awesome, glad we uncrossed the wires :)
