### ISSUE TITLE
Can't install a Visual Studio 2022 error code 110

### ISSUE THREAD

**Issue by Yiotemeqriboetkhgiblouh** [dotnet/core#8936]
Operating System: Windows 11 Pro

Can't install .NET Multi-Platform AP UI for Visual Studio Community. Unknown error, journals shows code 110.

**Comment by mairaw** [comment]
It would be better to use the report a problem feature inside VS to report this:
https://developercommunity.visualstudio.com/VisualStudio/report#:~:text=How%20to%20report%20a%20problem%20for%20Visual%20Studio,email%20with%20a%20link%20for%20the%20submitted%20problem.

That way the issue is routed to the appropriate team.
