### ISSUE TITLE
There is no Counter Page from ASP.Net * sample page

### ISSUE THREAD

**Issue by youngky-h** [dotnet/core#8997]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/try
Operating System: windows

I following tutorial at dotnet.microsoft.com, I create project by selecting create Blazor Web App and select Asp.Net Core 8. I keep "include sample page" checked. After project generated, I could not find Counter.razor in pages folder 

![Screenshot 2023-12-12 185429](https://github.com/dotnet/core/assets/5582619/687bac8c-0ce2-4b1c-863a-a710e2f41db0)

**Comment by Jozkee** [comment]
@danroth27 @mairaw

**Comment by mairaw** [comment]
@danroth27 any ideas here? I followed the steps again on my VS and I get the Counter.razor page. Should @youngky-h try again and if it fails to create that page report an issue through VS?

![image](https://github.com/dotnet/core/assets/12971179/8f3eae75-623e-443b-9510-4dfe93a691d6)

**Comment by danroth27** [comment]
@youngky-h The absence of Counter.razor is most likely due to selecting "None" for the "Interactive render mode" option when creating the Blazor Web App project. Counter.razor requires interactivity, so the template doesn't include the file if no interactive render modes are enabled. If you select "Server" for the interactive render mode, then you should get the Counter.razor file. Let us know though if you're seeing otherwise!
