### ISSUE TITLE
the term "dotnet" is not recognized

### ISSUE THREAD

**Issue by raineraine01** [dotnet/core#9036]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![dotnet error](https://github.com/dotnet/core/assets/155475323/c954ec12-69af-420d-85f6-015e4d2d0890)

**Comment by claudiaregio** [comment]
Hi @raineraine01, is this your first time going through the tutorial/ installing dotnet? Does a restart of your machine fix the issue?

**Comment by Icegreeen** [comment]
@raineraine01 

The 'dotnet' command is not being recognized in PowerShell due to an inappropriate PATH configuration. It is always a good practice to check some information during installation, especially the PATH settings that are your problem. 

The 'dotnet' command should be automatically added to the PATH during installation, but in some cases this configuration may not be effective.

You can resolve your issue by manually adding the relevant 'dotnet' paths to the PATH in PowerShell to ensure the executable is recognized correctly.

**Comment by wfurt** [comment]
did the installer finished successfully ???
