### ISSUE TITLE
System.IO.Packaging 4.4.0 in .NET Framework depends on .NETStandard.Library

### ISSUE THREAD

**Issue by msmolka** [dotnet/core#919]
# System.IO.Packaging 4.4.0 in .NET Framework depends on .NETStandard.Library

I'm trying to upgrade System.IO.Packaging in my old project .NET Framework 4.6.2  from version 4.3. However it tries to install a lot of useless dependencies already available inside framework, because it depends on  .NETStandard.Library 1.6.1+

**Comment by svick** [comment]
Interesting. That package has two variants: one for .Net Standard 1.3 and one for .Net Framework 4.6. But both depend on `NETStandard.Library`. I don't think that's a common pattern and I don't know why does that dependency exist.

On the other hand, those "useless" packages should not cause any issues. And they're even less visible if you use the new `<PackageReference>` instead of `packages.config`.

**Comment by msmolka** [comment]
@svick `<PackageReference>` is not a option. I have old not Core project. I need this reference to use OpenXml nuget package which relies on Packaging one. Also it is problem because I have a lot duplicate dependency errors.

**Comment by msmolka** [comment]
@svick are you sure:
based on that: [Microsoft Docs](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)

> At present, package references are supported in Visual Studio 2017 only, for .NET Core projects, .NET Standard projects, and UWP projects targeting Windows 10 Build 15063 (Creators Update).

About the error I cannot reproduce it right now

**Comment by svick** [comment]
@msmolka Yes. If I set PackageReference as the "Default package management format", then I'm able to use `<PackageReference>` in a brand new .Net Framework project in VS 15.3.

I think the docs are out of date, so I opened https://github.com/NuGet/docs.microsoft.com-nuget/issues/443.

**Comment by Petermarcu** [comment]
@terrajobst

**Comment by Petermarcu** [comment]
I'm going to close this issue for now. Let us know if more follow up is needed.

**Comment by Sc0tTyXL** [comment]
We still have an issue where is tries to load .NET Standard in a .NET Framework application. We do not want to be dependent on Standard, could somebody please fix this error? There shouldn't be a dependency!

**Comment by JCPuerto** [comment]
Updating to 4.4.0 is causing errors in the Visual Studio Team Services Build:

`Error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\NETStandard.Library.2.0.1\build\NETStandard.Library.targets
`

Since it's adding some extra lines to the web.config:

```
  <Import Project="..\..\..\packages\NETStandard.Library.2.0.1\build\NETStandard.Library.targets" Condition="Exists('..\..\..\packages\NETStandard.Library.2.0.1\build\NETStandard.Library.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\..\..\packages\NETStandard.Library.2.0.1\build\NETStandard.Library.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\..\packages\NETStandard.Library.2.0.1\build\NETStandard.Library.targets'))" />
  </Target>
```

So please remove that dependency.

Thank you!

**Comment by msmolka** [comment]
@Petermarcu Could you reopen this issue? My project is using .NET Framework 4.7.1 which is compatible with .NETStandard 2.0, So there is no need to install tens of dependencies, but because of this bug it is painful with deployment. 
I'm considering this as bug, because no other package has such strange dependency.
Even in latest alfa version this dependency exists. And I cannot find reason for that.

**Comment by Petermarcu** [comment]
@weshaggard @terrajobst do you have any insight on why this package is "special"?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/corefx #26129](https://github.com/dotnet/corefx/issues/26129) via [**ZenHub**](https://www.zenhub.com/)
