### ISSUE TITLE
AAAAAAAAAAAAAAAA

### ISSUE THREAD

**Issue by AlexeyZBest** [dotnet/core#9304]
Note: the above code is also good because it clearly states *at the declaration* point that the return type of `Copy` depends on the containing type.  So if you call through a derived type, you get a derived type back from the `Copy` method in a *completely* typesafe fashion.  

If this was just looking up by name, the new method might return some other type entirely, which could break all successive code in the method.  For example;

```c#
    public void New_Copy(out int vertex_pro)
    {
        vertex_pro = 0;
    }
```

Uh oh!  Now instead of having a Vertex at the callside, you have an int, which will certainly break most code that follows that was trying to use that value.

_Originally posted by @CyrusNajmabadi in https://github.com/dotnet/csharplang/issues/8115#issuecomment-2106709408_

**Comment by AlexeyZBest** [comment]
This is caught at the compilation stage since the methodpublic void New_Copy(out int vertex_pro){vertex_pro = 0;} with an int parameter does not exist.

**Comment by CyrusNajmabadi** [comment]
@AlexeyZBest Stop spamming random repos.  Your post on csharplang was discussed and the reasoning was communicated to you as to the decision making here.  It was locked due to substantive progress being made on any points.  Leaking thing out to multiple different repos in response is not acceptable.
