### ISSUE TITLE
Microsoft.AspNetCore.Mvc.ViewFeatures: 2.2.0

### ISSUE THREAD

**Issue by Fn-M** [dotnet/core#9375]
### Package Id

Microsoft.AspNetCore.Mvc.ViewFeatures

### Package Version(s)

2.2.0

### Additional details

The package is being shown as deprecated without any other option. If such functionalities from the package are being deprecated, where are they being transferred to? To the actual framework? To another package?

I don't see how can a package be deprecated without any reason or option for the developers that have been consuming that package.. This action is lacking the support to guarantee the continuity on the work that people have been using with package.

**Comment by julealgon** [comment]
@Fn-M there are _many_ such packages. You don't see their "new" versions in NuGet anymore because they've been bundled together in the AspNetCore Ref package.
- https://www.nuget.org/packages/Microsoft.AspNetCore.App.Ref/8.0.6

If you download that package and check the dlls, you'll see that `ViewFeatures` in there:
![image](https://github.com/dotnet/core/assets/461579/10a86ba0-c881-40cd-b649-eec11db9c238)

To use these newer versions, you need to upgrade your project to newer framework targets and use the web SDK. There is no way to consume them directly in an older project (as far as I know).

**Comment by Fn-M** [comment]
Thanks! I eventually found them, but would be great if such info would be on the nuget page as well, so that people are "redirected" to the alternative version.

**Comment by julealgon** [comment]
@Fn-M 
> ...but would be great if such info would be on the nuget page as well, so that people are "redirected" to the alternative version.

Yep... I can agree with you there. This is definitely a bit on the cryptic side.
