### ISSUE TITLE
Serialization/Deserialization/untrusted data transforms and proactive mitigation measures against potential zero-days

### ISSUE THREAD

**Issue by githubgitgit** [dotnet/core#952]
In the news: Apache Struts2 malformed XML deserialization leads to RCE
https://arstechnica.com/information-technology/2017/09/exploit-goes-public-for-severe-bug-affecting-high-impact-sites/

Even though that's on the Java-side of the world. This is an industry-wide wake up call to strengthen security from the ground-up. .Net Core is relatively new and I think this is the right time to put a strong emphasis on security and put proper mitigations in place to prevent similar events. Security-first model.  

Could there potentially be serialization/deserialization bugs or similar defects when dealing with untrusted data transforms in .NET Core? And are there proper mitigations in place to prevent such attacks? Like Implementing (multiple layers of) sandboxing?

**Comment by benaadams** [comment]
Binary Serialization (using `BinaryFormatter`) is problematic and wasn't included in .NET Core originally. However, has come back with 2.0 as part of matching the .NET Standard 2.0 api set.

However all help pages about [Binary Serilization](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization) carry this warning

> Binary serialization can be dangerous. Never deserialize data from an untrusted source and never round-trip serialized data to systems not under your control.

And suggest always using a different type of serialization (e.g. JSON, protobuf, xml etc)

[Secure Coding Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/security/secure-coding-guidelines) has the following recommendation

> ### Securing Resource Access
> When designing and writing your code, you need to protect and limit the access that code has to resources, especially when using or invoking code of unknown origin. So, keep in mind the following techniques to ensure your code is secure:
>
> * Do not use Code Access Security (CAS).
> * Do not use partial trusted code.
> * Do not use .NET Remoting.
> * Do not use Distributed Component Object Model (DCOM).
> * Do not use binary formatters.
>
> Code Access Security and Security-Transparent Code will not be supported as a security boundary with partially trusted code. We advise against loading and executing code of unknown origins without putting alternative security measures in place. The alternative security measures are:
>
> * Virtualization
> * AppContainers
> * Operating system (OS) users and permissions
> * Hyper-V containers

WCF has a long section on [Security Considerations for Data](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/security-considerations-for-data) that's probably worth reading as its recommendations are applicable to more areas than just WCF.

/cc @blowdart

**Comment by blowdart** [comment]
In .NET Core 1 we dropped a lot of dangerous stuff, and, well, customers complained bitterly, so they all came back in 2.0 to enable people to migrate. It's more complicated by the fact that you can use these things securely. Take for example encryption. Encrypting without adding an HMAC is problematic, but we have to expose the crypto primitives because that's what people want, the low level primitives. While there's some scope for static analysis to fix the simple things (don't use MD5, don't use Binary Formatter), there are still legitimate reasons for using both and people then just ignore the false positives, or disable any such analysis.

We can do some things at a higher level, take data protection in asp.net, we force all sorts of opinions on you there and it's secure by default, but because the primitives must be present people are always going to roll their own, and we simply can't stop that. Even sandboxing isn't going to help, we tried that with Code Access Security - but you can't implement it properly within a framework, it needs to be provided by the OS, not something that runs in the same process as your own code.

**Comment by Petermarcu** [comment]
It goes without saying, we take security very seriously and have for decades in the .NET platform. Over the years we have taken many different strategies for helping people stay safe with respect to serialization. As mentioned above, that even included omitting certain parts of the stack in .NET Core. 
We plan to continue to find ways to make things safer and mitigate categories of problems. If you have specific ideas or want to engage on a pushing forward a potential way to mitigate a type of attack vector, let us know. We are continually hardening our stack to be more secure.

I'm going to close this now as we are already and always working on making these things more secure and don't need to keep this issue open to track it. :)
